### PR TITLE
Pt bug fix & json

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/120)

### CODE REVIEW

**Comment by gfr10598** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[bq/insert.go, line 92 at r1](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly3pxqdhEUNRmztP_D:-Kly3pxqdhEUNRmztP_E:b23mfvx) ([raw file](https://github.com/m-lab/etl/blob/c70fb86109bee05236d477a99ea7ac3bfa280dc6/bq/insert.go#L92)):*
> ```Go
> 		bqClient, err = bigquery.NewClient(ctx, os.Getenv("GCLOUD_PROJECT"))
>                 // Used for localhost debug
>                 //bqClient, err = bigquery.NewClient(ctx, "mlab-sandbox")
> ```

Should delete before merging.

---

*[bq/insert.go, line 147 at r1](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly44hknEnDIYdpqkMu:-Kly44hknEnDIYdpqkMv:ba3dfmt) ([raw file](https://github.com/m-lab/etl/blob/c70fb86109bee05236d477a99ea7ac3bfa280dc6/bq/insert.go#L147)):*
> ```Go
> 		if err != nil {
> 			// TODO - handle errors in middle better?
>                         log.Printf("%v\n", err)
> ```

Remove.

---

*[bq/insert.go, line 209 at r1](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly46TTXk0W2lQGkh_0:-Kly46TTXk0W2lQGkh_1:byp18fd) ([raw file](https://github.com/m-lab/etl/blob/c70fb86109bee05236d477a99ea7ac3bfa280dc6/bq/insert.go#L209)):*
> ```Go
> 	} else {
> 		// This adjusts the inserted count, failure count, and updates in.rows.
>                 log.Printf("%v\n", err)
> ```

Remove

---

*[parser/pt_test.go, line 47 at r2](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly4KAmm7VqQa1Hn5FJ:-Kly4KAnmDMCtcQkMnou:b-ww0tdr) ([raw file](https://github.com/m-lab/etl/blob/44c498e4af9885fb72803e6c467d3a9fcd6a113b/parser/pt_test.go#L47)):*
> ```Go
> 	// TODO(dev): reformat these individual values to be more readable.
> 	expected_hops := []schema.ParisTracerouteHop{
> 		schema.ParisTracerouteHop{Protocol: "tcp", Src_ip: "64.233.174.109", Src_af: 2, Dest_ip: "74.125.224.100", Dest_af: 2, Src_hostname: "sr05-te1-8.nuq04.net.google.com", Dest_hostname:: "74.125.224.100", Rtt: []float64{0.895}},
> ```

This seems like a bug.  Might be causing the travis failures.

---

*[schema/pt.json, line 1 at r1](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly4SdAQbAFRkDgpnEF:-Kly4SdAQbAFRkDgpnEG:b-cghjmj) ([raw file](https://github.com/m-lab/etl/blob/c70fb86109bee05236d477a99ea7ac3bfa280dc6/schema/pt.json#L1)):*
> ```JSON
> [
> ```

Please also add a paragraph to the schema/README.md

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/120)*

**Comment by gfr10598** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[parser/pt.go, line 191 at r1](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly4pQzMoreOaG1P8Gx:-Kly4pR-6Dm1FFwSNOTL:bkam7bp) ([raw file](https://github.com/m-lab/etl/blob/c70fb86109bee05236d477a99ea7ac3bfa280dc6/parser/pt.go#L191)):*
> ```Go
> 		err := pt.inserter.InsertRow(pt_test)
> 		if err != nil {
>                         log.Printf("herehere%v\n", err)
> ```

Remove or improve message.

---

*[parser/pt.go, line 309 at r1](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly4uoTQyYxzNAFMlNM:-Kly4uoTQyYxzNAFMlNN:b-6s9tqr) ([raw file](https://github.com/m-lab/etl/blob/c70fb86109bee05236d477a99ea7ac3bfa280dc6/parser/pt.go#L309)):*
> ```Go
> // TODO(dev): dedup the hops that are identical.
> func Parse(meta map[string]bigquery.Value, testName string, rawContent []byte) ([]schema.ParisTracerouteHop, int64, *schema.MLabConnectionSpecification, error) {
>         log.Printf("%s", testName)
> ```

Remove log??

---

*[parser/pt.go, line 357 at r1](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly5-Z_TtX8Eop2BOAA:-Kly5-Z_TtX8Eop2BOAB:bz262j6) ([raw file](https://github.com/m-lab/etl/blob/c70fb86109bee05236d477a99ea7ac3bfa280dc6/parser/pt.go#L357)):*
> ```Go
> 			for i := 3; i < len(parts); i += 4 {
> 				if len(parts) < i+4 {
> 					break
> ```

Add a comment.  Is this a data bug, or something else?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/120)*

**Comment by yachang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[bq/insert.go, line 92 at r1](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly3pxqdhEUNRmztP_D:-Kly5lDo1yhN0DUpqQF0:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/c70fb86109bee05236d477a99ea7ac3bfa280dc6/bq/insert.go#L92)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Should delete before merging.
</blockquote></details>

Done.

---

*[bq/insert.go, line 147 at r1](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly44hknEnDIYdpqkMu:-Kly5lhnu-x5alOUE9sH:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/c70fb86109bee05236d477a99ea7ac3bfa280dc6/bq/insert.go#L147)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.

---

*[bq/insert.go, line 209 at r1](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly46TTXk0W2lQGkh_0:-Kly5mOuSylT6DbLRrU0:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/c70fb86109bee05236d477a99ea7ac3bfa280dc6/bq/insert.go#L209)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/120)*

**Comment by gfr10598** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[parser/pt.go, line 332 at r4](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly6dYLi_tYDmEULpaR:-Kly6dYLi_tYDmEULpaS:bg1syks) ([raw file](https://github.com/m-lab/etl/blob/40520f556d72a47a15c29f1a629b96dda2448502/parser/pt.go#L332)):*
> ```Go
> 	var all_nodes []Node
> 
> 	for _, oneLine := range strings.Split(string(rawContent[:]), "\n") {
> ```

rawcontent is already a slice.  Is this slice copy necessary?

FYI, you could alternatively use a bytes.Buffer, and use ReadString('\n'), IIRC.  You'd have to strip
the \n from the resulting strings

---

*[schema/pt.json, line 1 at r1](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly4SdAQbAFRkDgpnEF:-Kly5M5cOpY0jEQ5vrRK:b-dk601z) ([raw file](https://github.com/m-lab/etl/blob/c70fb86109bee05236d477a99ea7ac3bfa280dc6/schema/pt.json#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please also add a paragraph to the schema/README.md
</blockquote></details>

Could you include either in the README if appropriate, or in the PR description if you think that is better, a description of how this schema differs from the legacy schema, and the motivation for the changes?

---

*[schema/pt.json, line 69 at r1](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly5diSLgo_TVhy7nq0:-Kly5diT-bFQCbcwOGdR:b-habwik) ([raw file](https://github.com/m-lab/etl/blob/c70fb86109bee05236d477a99ea7ac3bfa280dc6/schema/pt.json#L69)):*
> ```JSON
>                   { "name": "postal_code", "type": "STRING"},
>                   { "name": "region", "type": "STRING"}
>                 ], "name": "src_geolocation", "type": "RECORD"},
> ```

Is it useful to have the geolocation info for all the intermediate hops?  Do we do that in the legacy data?

---

*[bq/insert.go, line 136 at r3](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly63Zh9nvFKXe2q1eq:-Kly63Zh9nvFKXe2q1er:bbwz0mi) ([raw file](https://github.com/m-lab/etl/blob/58e0f834ae0bef0bdb52731ae5ebe8ea6f4aa5a3/bq/insert.go#L136)):*
> ```Go
> 	metrics.WorkerState.WithLabelValues("insert").Inc()
> 	defer metrics.WorkerState.WithLabelValues("insert").Dec()
> ```

Restore the blank line?  I think it is useful white space, and then I think this file won't be part of the PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/120)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[schema/pt.json, line 69 at r1](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly5diSLgo_TVhy7nq0:-Kly7MuDRUJIG-zCSr7b:b2nhswy) ([raw file](https://github.com/m-lab/etl/blob/c70fb86109bee05236d477a99ea7ac3bfa280dc6/schema/pt.json#L69)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Is it useful to have the geolocation info for all the intermediate hops?  Do we do that in the legacy data?
</blockquote></details>

Yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/120)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[bq/insert.go, line 136 at r3](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly63Zh9nvFKXe2q1eq:-Kly7QRiHw9ds_IP6olW:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/58e0f834ae0bef0bdb52731ae5ebe8ea6f4aa5a3/bq/insert.go#L136)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Restore the blank line?  I think it is useful white space, and then I think this file won't be part of the PR.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/120)*

**Comment by yachang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[schema/pt.json, line 1 at r1](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly4SdAQbAFRkDgpnEF:-Kly7upJ806l5T360WMx:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/c70fb86109bee05236d477a99ea7ac3bfa280dc6/schema/pt.json#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Could you include either in the README if appropriate, or in the PR description if you think that is better, a description of how this schema differs from the legacy schema, and the motivation for the changes?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/120)*

**Comment by yachang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[parser/pt.go, line 191 at r1](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly4pQzMoreOaG1P8Gx:-Klyj-E-UuRJNy24xv8G:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/c70fb86109bee05236d477a99ea7ac3bfa280dc6/parser/pt.go#L191)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Remove or improve message.
</blockquote></details>

Done.

---

*[parser/pt.go, line 309 at r1](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly4uoTQyYxzNAFMlNM:-Klyj6mEEsZuGXXC2Z_r:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/c70fb86109bee05236d477a99ea7ac3bfa280dc6/parser/pt.go#L309)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Remove log??
</blockquote></details>

Done.

---

*[parser/pt.go, line 357 at r1](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly5-Z_TtX8Eop2BOAA:-KlyjOdf1KRLChoKU3iJ:bt2vr1b) ([raw file](https://github.com/m-lab/etl/blob/c70fb86109bee05236d477a99ea7ac3bfa280dc6/parser/pt.go#L357)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add a comment.  Is this a data bug, or something else?
</blockquote></details>

Fixed.

---

*[parser/pt.go, line 332 at r4](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly6dYLi_tYDmEULpaR:-KlyjBDiirh7mwNd0U6R:b-o7gpr0) ([raw file](https://github.com/m-lab/etl/blob/40520f556d72a47a15c29f1a629b96dda2448502/parser/pt.go#L332)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

rawcontent is already a slice.  Is this slice copy necessary?

FYI, you could alternatively use a bytes.Buffer, and use ReadString('\n'), IIRC.  You'd have to strip
the \n from the resulting strings

</blockquote></details>

Yes. I tried, []byte cannot be used as input param for string.Split() directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/120)*

**Comment by yachang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[parser/pt_test.go, line 47 at r2](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly4KAmm7VqQa1Hn5FJ:-KlymkepQyt1HjZrBrpn:bt2vr1b) ([raw file](https://github.com/m-lab/etl/blob/44c498e4af9885fb72803e6c467d3a9fcd6a113b/parser/pt_test.go#L47)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This seems like a bug.  Might be causing the travis failures.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/120)*

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/pt.go, line 332 at r4](https://reviewable.io:443/reviews/m-lab/etl/120#-Kly6dYLi_tYDmEULpaR:-KlypERf5UyJBXIF161H:br8xt2c) ([raw file](https://github.com/m-lab/etl/blob/40520f556d72a47a15c29f1a629b96dda2448502/parser/pt.go#L332)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Yes. I tried, []byte cannot be used as input param for string.Split() directly.
</blockquote></details>

I think you misunderstood my comment.  There is a bytes.Buffer that can wrap a []byte.  It has a ReadString function.
Not important.

---

*[parser/pt.go, line 308 at r5](https://reviewable.io:443/reviews/m-lab/etl/120#-KlypT9IjcrOnI3EWUEe:-KlypT9IjcrOnI3EWUEf:b-hu9dle) ([raw file](https://github.com/m-lab/etl/blob/b6f203eca21f905318330b15a4305a240c2a10a7/parser/pt.go#L308)):*
> ```Go
> // TODO(dev): dedup the hops that are identical.
> func Parse(meta map[string]bigquery.Value, testName string, rawContent []byte) ([]schema.ParisTracerouteHop, int64, *schema.MLabConnectionSpecification, error) {
> 	// log.Printf("%s", testName)
> ```

Better to just delete for integration branch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/120#-:-KlyqH1fiqapB-S5fBF9:bnfp4nl)*

**Pull request merged**
