### PR TITLE
reduce to 4-6 instances, smaller memory

### PR DESCRIPTION
**Pull request by gfr10598**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/962)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
Should this also adjust the queueing rates? https://github.com/m-lab/etl/blob/master/appengine/queue.yaml

We'd effectively be increasing load by at least 4x -- with longer processing times -- how to best monitor the impact of this change?

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/962#-:-MRVzQ7S9yC18K5T7OgT:b-owm0l7)* status: 0 of 1 approvals obtained

**Review by stephen-soltesz — APPROVED** [review]
Oh, maybe that's addressed by https://github.com/m-lab/etl-gardener/pull/323#pullrequestreview-572519015

:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/962#-:-MRW531H2Qx29tQfGCfT:bxtenqx)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by stephen-soltesz — APPROVED** [review]
Looks like you're experimenting with even smaller instance counts. Please let me know what's going into your changes.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/962#-:-MR_eGl6DittTvG-nnLG:bhgc84n)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by gfr10598 — COMMENTED** [review]
I just observed that in practice it was only using 6 instances, but was somewhat unstable.  So I reduced it to a narrower range.  If you want to bump it back up to 8 or 10 feel free.

I'm only getting to commit on Sunday because there was a github change that prevented committing, and I didn't track it down until now.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/962#-:-MRrbfcu6Iz9XI8b0RXi:b-uw878d)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by gfr10598 — COMMENTED** [review]
Also reduced the memory footprint, based on observed memory use.  Should still be plenty of headroom.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/962#-:-MRrcXN89W57y4bcviwp:b-wjawtd)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
