### PR TITLE
Add parser for hopannotation1 datatype

### PR DESCRIPTION
**Pull request by cristinaleonr**
- Added new HopAnnotation1 datatype definition to [schema](https://github.com/m-lab/etl/tree/master/schema)
- Added HopAnnotation1 table creation to [update.go](https://github.com/m-lab/etl/blob/master/cmd/update-schema/update.go)
- Added parser for HopAnnotation1 datatype to [parser](https://github.com/m-lab/etl/tree/master/parser)
- Added HopAnnotation1 constants to [globals.go](https://github.com/m-lab/etl/blob/master/etl/globals.go)

Test data under gs://archive-mlab-testing/ndt/hopannotation1/2021/08/18/20210818T174432Z-hopannotation1-mlab1-arn03-ndt.tar

Sample output
```
{
  "ID":"20210818_1e0b318cf3c2_72.14.203.143",
  "Parser":  {
    "Version":"local development",
    "Time":"2021-08-19T01:04:37.447687391Z",
    "ArchiveURL":"gs://archive-mlab-testing/ndt/hopannotation1/2021/08/18/20210818T174432Z-hopannotation1-mlab1-arn03-ndt.tar",
    "Filename":"hopannotation1/2021/08/18/20210818T174429Z_1e0b318cf3c2_72.14.203.143.json",
    "Priority":0,
    "GitCommit":"uninitialized"
  },
  "Date":"2021-08-18",
  "Raw":  {
    "ID":"20210818_1e0b318cf3c2_72.14.203.143",
    "Timestamp":"2021-08-18T17:44:29Z",
    "Annotations":  {
      "Geo":  {
        "ContinentCode":"NA",
        "CountryCode":"US",
        "CountryName":"United States",
        "Latitude":37.751,
        "Longitude":-97.822,"AccuracyRadiusKm":1000
      },
      "Network":  {
        "CIDR":"72.14.192.0/18",
        "ASNumber":15169,
        "ASName":"Google LLC",
        "Systems": [{"ASNs":[15169]}]
      }
    }
  }
}

```

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/1015)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
I wanted to look at the generated schema in BQ and saw that the CB failed due to some "suite" value change.

e.g.
```
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
```

It may be possible to prevent this with the option (just found from searching):
```
apt-get update –allow-releaseinfo-change
```

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1015#-:-MhTl2ctBn48-ngToUtz:b-ns8nh9)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[schema/hopannotation1.go, line 14 at r1](https://reviewable.io/reviews/m-lab/etl/1015#-MhTjRs69QFgTIqVKi8k:-MhTjRs69QFgTIqVKi8l:b7vzjqk) ([raw file](https://github.com/m-lab/etl/blob/2e5ecd7b9b720b53775dcf7c3c81ee81b0d793fc/schema/hopannotation1.go#L14)):*
> ```Go
> 
> // Schema stub for HopAnnotation1.
> // Eventually this will be returned by traceroute-caller.
> ```

Please prefix this with `TODO` to flag this. We want to remove this definition as soon as the definition in traceroute-caller is available. ( @saiedkazemi  will know when it's merged ).

You may also see conventions like: `TODO(<username>):` and `TODO(<issue#>):` that links to a github issue. Both of these are better that a plain TODO. Since this is something we expect to change soon, I recommend `TODO(cristinaleon):`.
___
*[schema/descriptions/HopAnnotation1Row.yaml, line 0 at r1](https://reviewable.io/reviews/m-lab/etl/1015#-MhTlMU68GViXghOCHFm:-MhTlMU68GViXghOCHFn:b-vfmktc) ([raw file](https://github.com/m-lab/etl/blob/2e5ecd7b9b720b53775dcf7c3c81ee81b0d793fc/schema/descriptions/HopAnnotation1Row.yaml#L0)):*
Since this `ID` is different from most others (it's not a tcp connection UUID), we may want to override the description here. We can also document the origin of the Date ( @saiedkazemi ).

And, it would be worthwhile adding that the raw.Geo values are annotated using MaxMind which is known to be less accurate for infrastructure IPs in traceroute hops.

**Comment by cristinaleonr** [comment]
@SaiedKazemi, can you please take a look at the schema definitions https://github.com/m-lab/etl/pull/1015/files#diff-667275c909e96a34d4817e97f3b68c37fccc55da30ddd20f6bb229bafc0bc570R15? Thanks!

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1015)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[schema/hopannotation1.go, line 14 at r1](https://reviewable.io/reviews/m-lab/etl/1015#-MhTjRs69QFgTIqVKi8k:-MhVDmsEAcEELBa_BMWW:b-7yd1q4) ([raw file](https://github.com/m-lab/etl/blob/2e5ecd7b9b720b53775dcf7c3c81ee81b0d793fc/schema/hopannotation1.go#L14)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please prefix this with `TODO` to flag this. We want to remove this definition as soon as the definition in traceroute-caller is available. ( @saiedkazemi  will know when it's merged ).

You may also see conventions like: `TODO(<username>):` and `TODO(<issue#>):` that links to a github issue. Both of these are better that a plain TODO. Since this is something we expect to change soon, I recommend `TODO(cristinaleon):`.
</blockquote></details>

Added a TODO.
___
*[schema/descriptions/HopAnnotation1Row.yaml, line  at r1](https://reviewable.io/reviews/m-lab/etl/1015#-MhTlMU68GViXghOCHFm:-MhVDoxx2HRpIJJW1474:bboo4bv) ([raw file](https://github.com/m-lab/etl/blob/2e5ecd7b9b720b53775dcf7c3c81ee81b0d793fc/schema/descriptions/HopAnnotation1Row.yaml#L)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since this `ID` is different from most others (it's not a tcp connection UUID), we may want to override the description here. We can also document the origin of the Date ( @saiedkazemi ).

And, it would be worthwhile adding that the raw.Geo values are annotated using MaxMind which is known to be less accurate for infrastructure IPs in traceroute hops.
</blockquote></details>

Added descriptions for the fields.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> Reviewed 11 of 13 files at r1, 2 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1015)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[schema/descriptions/HopAnnotation1Row.yaml, line 2 at r5](https://reviewable.io/reviews/m-lab/etl/1015#-MhVFTxj4cU1dyF0axRY:-MhVFTxj4cU1dyF0axRZ:bka1dkr) ([raw file](https://github.com/m-lab/etl/blob/d98cec18f5a093f197f8405bd91b87dfe44e556f/schema/descriptions/HopAnnotation1Row.yaml#L2)):*
> ```YAML
> ID:
>   Description: Annotation ID is a daily unique identifier for Hop Annotations to join with traceroute datasets.
> ```

It looks like we may want to define both `id:` (to override the toplevel definition) and this `ID:`.

See the docs associated with the table in https://console.cloud.google.com/bigquery?project=measurement-lab&ws=!1m5!1m4!4m3!1smlab-sandbox!2stmp_ndt!3shopannotation1&page=table&d=tmp_ndt&p=mlab-sandbox&t=hopannotation1

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1015)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[schema/descriptions/HopAnnotation1Row.yaml, line 2 at r5](https://reviewable.io/reviews/m-lab/etl/1015#-MhVFTxj4cU1dyF0axRY:-MhVPTKiAu0A_MqNPolv:btjqrxv) ([raw file](https://github.com/m-lab/etl/blob/d98cec18f5a093f197f8405bd91b87dfe44e556f/schema/descriptions/HopAnnotation1Row.yaml#L2)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It looks like we may want to define both `id:` (to override the toplevel definition) and this `ID:`.

See the docs associated with the table in https://console.cloud.google.com/bigquery?project=measurement-lab&ws=!1m5!1m4!4m3!1smlab-sandbox!2stmp_ndt!3shopannotation1&page=table&d=tmp_ndt&p=mlab-sandbox&t=hopannotation1
</blockquote></details>

Added a definition for id.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: -- please confirm the descriptions look correct with @saiedkazemi .

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1015#-:-MhVbF2cD6Ran-2xXTRn:b-687i2r)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
