### PR TITLE
Add parser.GitCommit field into ParseInfo struct

### PR DESCRIPTION
**Pull request by cristinaleonr**
Summary:
Adding GitCommit field to ParseInfo struct

Description:
This struct is used by NDT7 and Annotation
NDT5 uses another version called ParseInfoV0, so it's not in scope for this change

Testing:
Change includes unit tests and will also be tested by checking the table schema

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/1005)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1005)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr and @gfr10598)

___
*[parser/annotation_test.go, line 53 at r2](https://reviewable.io/reviews/m-lab/etl/1005#-MefbMmd-6hHuWyO6qVX:-MefbMmd-6hHuWyO6qVY:b-xg3nwc) ([raw file](https://github.com/m-lab/etl/blob/569b575119762667e50b03ddcbde29e8bf9b28c1/parser/annotation_test.go#L53)):*
> ```Go
> 			}
> 
> 			if n.Accepted() == 1 {
> ```

Thank you for adding this.
___
*[parser/parser.go, line 49 at r2](https://reviewable.io/reviews/m-lab/etl/1005#-MefaiBj2I_5rsxn-z09:-MefaiBj2I_5rsxn-z0A:b-bsutvn) ([raw file](https://github.com/m-lab/etl/blob/569b575119762667e50b03ddcbde29e8bf9b28c1/parser/parser.go#L49)):*
> ```Go
> 	hash := etl.GitCommit
> 	if hash != "nocommit" && len(hash) >= 8 {
> 		gParserGitCommit = hash[0:8]
> ```

I know we touched on this conversationally. So, I'm sorry for the mixed message. I think we should include the complete hash here.

The NDT result schema includes a field named `GitShortCommit` https://github.com/m-lab/ndt-server/blob/master/data/result.go#L55 that is the short commit. To prevent having two names for the same things, I would suggest that we either use the complete commit hash here, or change the field name to GitShortCommit (and keep the short hash). I recommend the complete hash here.

**Comment by cristinaleonr** [comment]
___
*[parser/parser.go, line 49 at r2](https://reviewable.io/reviews/m-lab/etl/1005#-MefaiBj2I_5rsxn-z09:-MeffZO-EAb7nbKW8QR7:b-q0xzsy) ([raw file](https://github.com/m-lab/etl/blob/569b575119762667e50b03ddcbde29e8bf9b28c1/parser/parser.go#L49)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I know we touched on this conversationally. So, I'm sorry for the mixed message. I think we should include the complete hash here.

The NDT result schema includes a field named `GitShortCommit` https://github.com/m-lab/ndt-server/blob/master/data/result.go#L55 that is the short commit. To prevent having two names for the same things, I would suggest that we either use the complete commit hash here, or change the field name to GitShortCommit (and keep the short hash). I recommend the complete hash here.
</blockquote></details>

Apologies, I misunderstood our conversation. I changed it to use the complete hash now.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: -- @gfr10598 lgty? 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1005#-:-MefimlyAUSwFSvC1dmu:b-ovqf8w)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598)

___
*[parser/parser.go, line 49 at r2](https://reviewable.io/reviews/m-lab/etl/1005#-MefaiBj2I_5rsxn-z09:-MefigIY2EXCs70lxWOK:bt85kbu) ([raw file](https://github.com/m-lab/etl/blob/569b575119762667e50b03ddcbde29e8bf9b28c1/parser/parser.go#L49)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Apologies, I misunderstood our conversation. I changed it to use the complete hash now.
</blockquote></details>

Nothing to apologize for. Thank you for the update.

**Review by gfr10598 — COMMENTED** [review]
looking now

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1005#-:-MefrA_j39rOa3LKwYoR:b-r6olcc)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1005)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[parser/annotation_test.go, line 53 at r3](https://reviewable.io/reviews/m-lab/etl/1005#-MefrUWdAPAaiMkgdG95:-MefrUWdAPAaiMkgdG96:bzdsjsc) ([raw file](https://github.com/m-lab/etl/blob/77cb15a76c5703eb2763b7bfb9657549121b1670/parser/annotation_test.go#L53)):*
> ```Go
> 			}
> 
> 			if n.Accepted() == 1 {
> ```

Good addition.  Could you modify to test if != 1 and t.Fatal(), and then do the body outside the conditional?

**Review by gfr10598 — APPROVED** [review]
:lgtm: after one requested change in unit test

> Reviewed 1 of 8 files at r1, 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1005#-:-Mefs5S67kaXVe7Mfy2V:bmqllr8)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @cristinaleonr)

**Comment by cristinaleonr** [comment]
___
*[parser/annotation_test.go, line 53 at r3](https://reviewable.io/reviews/m-lab/etl/1005#-MefrUWdAPAaiMkgdG95:-MefsLkd-yeyylwEENf3:b-2i6h22) ([raw file](https://github.com/m-lab/etl/blob/77cb15a76c5703eb2763b7bfb9657549121b1670/parser/annotation_test.go#L53)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Good addition.  Could you modify to test if != 1 and t.Fatal(), and then do the body outside the conditional?
</blockquote></details>

Thanks for the suggestion.

The test cases also include a case for corrupt input (lines 27-29 of annotation_test.go), which fails that check. I could move that case out into a separate function?

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1005)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[parser/annotation_test.go, line 53 at r3](https://reviewable.io/reviews/m-lab/etl/1005#-MefrUWdAPAaiMkgdG95:-MefvK9QC1xZLE57Ky5Z:b-knvyg) ([raw file](https://github.com/m-lab/etl/blob/77cb15a76c5703eb2763b7bfb9657549121b1670/parser/annotation_test.go#L53)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Thanks for the suggestion.

The test cases also include a case for corrupt input (lines 27-29 of annotation_test.go), which fails that check. I could move that case out into a separate function?
</blockquote></details>

Ah I missed that.  I also missed that you don't want to use t.Fatal, as that would prevent the other test case from running.

So, I'm ok with leaving it as is.

**Review by gfr10598 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1005#-:-MefwXczAS_x5C7O91vb:bg7igkv)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @cristinaleonr)

**Pull request merged**
