### PR TITLE
Enable Geo with Sidestream

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/268)

### CODE REVIEW

**Comment by yachang** [comment]
working in sandbox:

#standardSQL
SELECT count(test_id) as cnt, web100_log_entry.connection_spec.local_geolocation.country_name
FROM `mlab-sandbox.mlab_sandbox.sidestream_20170401`
group by web100_log_entry.connection_spec.local_geolocation.country_name
order by cnt DESC

Output is 


1 | 855275 | United States |  
-- | -- | -- | --
2 | 62211 | Canada |  
3 | 50081 | Australia |  
4 | 44143 | United Kingdom |  
5 | 40200 |   |  
6 | 38129 | New Zealand |  
7 | 29691 | Romania |  
8 | 28383 | Cyprus |  
9 | 27093 | Italy |  
10 | 26072 | Serbia |  
11 | 25968 | Japan |  
12 | 25201 | Slovenia |  
13 | 24599 | Greece |  
14 | 23986 | Singapore

**Comment by yachang** [comment]
staging working:

#standardSQL
SELECT count(test_id) as cnt, web100_log_entry.connection_spec.local_geolocation.country_name
FROM `mlab-staging.staging.sidestream_20170401`
group by web100_log_entry.connection_spec.local_geolocation.country_name
order by cnt DESC

output:


1 | 458410 | United States |  
-- | -- | -- | --
2 | 37861 | Canada |  
3 | 31197 | United Kingdom |  
4 | 26731 | New Zealand |  
5 | 26676 | Australia |  
6 | 22886 | Cyprus |  
7 | 22435 |   |  
8 | 20849 | Norway |  
9 | 20500 | Singapore |  
10 | 17931 | Serbia |  
11 | 17281 | Italy |  
12 | 17088 | Austria |  
13 | 17086 | Philippines |  
14 | 16601 | Ghana

**Comment by gfr10598** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/268#-:-KwHoLlM-HKk5q6D_Epz:bnfp4nl)*

**Comment by yachang** [comment]
working in prod.

SELECT 
count(test_id) as cnt, web100_log_entry.connection_spec.local_geolocation.country_name
FROM [measurement-lab:public.sidestream_20170601]
group by web100_log_entry.connection_spec.local_geolocation.country_name
order by cnt DESC

Output:


1 | 1420519 | United States |  
-- | -- | -- | --
2 | 119152 | Canada |  
3 | 88194 | Australia |  
4 | 81801 | New Zealand |  
5 | 78245 | United Kingdom |  
6 | 66079 | Romania |  
7 | 66030 |   |  
8 | 50563 | Norway |  
9 | 49823 | South Africa |  
10 | 49400 | Taiwan |  
11 | 47527 | Philippines |  
12 | 47426 | Austria |  
13 | 44016 | Ireland |  
14 | 42846 | Slovenia

**Pull request merged**
