### PR TITLE
Migrate ndt5 to use standard columns

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change updates the ndt5 parser to support standard columns for the v2 gardener system.

Because the ndt5 result can include both S2C (download) and C2S (upload) but there is only a single summary record, this changes the parser to write one row per direction. The result of this decision is that the ndt5 rows will be organized more similarly to how ndt7 rows are collected and parsed, making down stream queries/filters and the unified tables easier to manage.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/1045)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1045)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[parser/ndt5_result.go, line 38 at r3](https://reviewable.io/reviews/m-lab/etl/1045#-MuMnE40AkxrBDlgEiF_:-MuMnE40AkxrBDlgEiFa:brmy0lf) ([raw file](https://github.com/m-lab/etl/blob/48066cb0631804e9b2a0ea85e40cc7e3ec608654/parser/ndt5_result.go#L38)):*
> ```Go
> 	bufSize := etl.NDT5.BQBufferSize()
> 	if ann == nil {
> 		ann = &nullAnnotator{}
> ```

What is the reason for this change? NDT uses `v2as.GetAnnotator(etl.BatchAnnotatorURL).
___
*[parser/ndt5_result.go, line 86 at r3](https://reviewable.io/reviews/m-lab/etl/1045#-MuMmdJX340cz9OHJXCm:-MuMmdJX340cz9OHJXCn:b-8d4zea) ([raw file](https://github.com/m-lab/etl/blob/48066cb0631804e9b2a0ea85e40cc7e3ec608654/parser/ndt5_result.go#L86)):*
> ```Go
> 	var re = regexp.MustCompile(`,"ClientMetadata":{[^}]+}`)
> 	test = []byte(re.ReplaceAllString(string(test), ``))
> 	if len(test) == 0 {
> ```

Do we want to know when this happens (maybe through some metric or logging)?
___
*[parser/ndt5_result.go, line 108 at r3](https://reviewable.io/reviews/m-lab/etl/1045#-MuMpt3q1syLa99UoeSX:-MuMpt3q1syLa99UoeSY:b-x4y7p0) ([raw file](https://github.com/m-lab/etl/blob/48066cb0631804e9b2a0ea85e40cc7e3ec608654/parser/ndt5_result.go#L108)):*
> ```Go
> 
> 	// S2C
> 	result, err := dp.newResult(test, parser, date)
> ```

Lines 108 through 112 repeat in 3 different places. Is it possible to refactor some of that logic so we don't repeat ourselves so much?
___
*[parser/ndt5_result.go, line 172 at r3](https://reviewable.io/reviews/m-lab/etl/1045#-MuMrQsRBur0vrUrjZpC:-MuMrQsRBur0vrUrjZpD:b-8vnzin) ([raw file](https://github.com/m-lab/etl/blob/48066cb0631804e9b2a0ea85e40cc7e3ec608654/parser/ndt5_result.go#L172)):*
> ```Go
> }
> 
> func (dp *NDT5ResultParser) prepareS2CRow(row *schema.NDT5ResultRowV2) error {
> ```

What is the point of this returning an `error` if we only return `nil`?
___
*[schema/descriptions/NDT5ResultRowV2.yaml, line 2 at r3](https://reviewable.io/reviews/m-lab/etl/1045#-MuMsVE-EhTBI3elxNx1:-MuMsVE-EhTBI3elxNx2:bi9estx) ([raw file](https://github.com/m-lab/etl/blob/48066cb0631804e9b2a0ea85e40cc7e3ec608654/schema/descriptions/NDT5ResultRowV2.yaml#L2)):*
> ```YAML
> id:
>   Description: A unique id for this test. For rows with an S2C (download) or C2S
> ```

:pray:

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1045)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[parser/ndt5_result.go, line 38 at r3](https://reviewable.io/reviews/m-lab/etl/1045#-MuMnE40AkxrBDlgEiF_:-MuMtyk51Hp5fXoLQs_o:b-84gies) ([raw file](https://github.com/m-lab/etl/blob/48066cb0631804e9b2a0ea85e40cc7e3ec608654/parser/ndt5_result.go#L38)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

What is the reason for this change? NDT uses `v2as.GetAnnotator(etl.BatchAnnotatorURL).
</blockquote></details>

NDT7*

**Review by stephen-soltesz — COMMENTED** [review]
Thank you, PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1045#-:-MuMzqbsE3qQDc-2rzbl:bxryuc8)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[parser/ndt5_result.go, line 38 at r3](https://reviewable.io/reviews/m-lab/etl/1045#-MuMnE40AkxrBDlgEiF_:-MuMugr52hZQ9CDlK2pS:b-wyych2) ([raw file](https://github.com/m-lab/etl/blob/48066cb0631804e9b2a0ea85e40cc7e3ec608654/parser/ndt5_result.go#L38)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

NDT7*
</blockquote></details>

The annotator is a legacy feature that makes calls out to the annotation-service. Because ndt5 (and other v2 types) use uuid-annotations now, this should be null to prevent the overhead of making calls to the annotation-service that are discarded. Ultimately, all of these can be replaced for v2 types.
___
*[parser/ndt5_result.go, line 86 at r3](https://reviewable.io/reviews/m-lab/etl/1045#-MuMmdJX340cz9OHJXCm:-MuMw3ql02JRHn5JJAbl:b-e5ort6) ([raw file](https://github.com/m-lab/etl/blob/48066cb0631804e9b2a0ea85e40cc7e3ec608654/parser/ndt5_result.go#L86)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Do we want to know when this happens (maybe through some metric or logging)?
</blockquote></details>

Good idea. Reusing the RowSize metric to record "zero" length files. This will populate the smallest bin.
___
*[parser/ndt5_result.go, line 108 at r3](https://reviewable.io/reviews/m-lab/etl/1045#-MuMpt3q1syLa99UoeSX:-MuMv71v27ttxKUvu7SC:b-igwy23) ([raw file](https://github.com/m-lab/etl/blob/48066cb0631804e9b2a0ea85e40cc7e3ec608654/parser/ndt5_result.go#L108)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Lines 108 through 112 repeat in 3 different places. Is it possible to refactor some of that logic so we don't repeat ourselves so much?
</blockquote></details>

I see a tradeoff here between clarity/simplicity of the logic and parsing the record once.

I parse the record multiple times b/c the pointer types within the result record need to be managed more carefully and reconstructed for the different direction cases (i.e. to mask S2C or C2S, etc) which risked corrupting them in subtle ways (now or in the future) -- simply reparsing guarantees the values are pristine and the logic is be easier to verify as correct by inspection.

What do you think?
___
*[parser/ndt5_result.go, line 172 at r3](https://reviewable.io/reviews/m-lab/etl/1045#-MuMrQsRBur0vrUrjZpC:-MuMvaAsARkLOhYhwJPi:bdgv1a) ([raw file](https://github.com/m-lab/etl/blob/48066cb0631804e9b2a0ea85e40cc7e3ec608654/parser/ndt5_result.go#L172)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

What is the point of this returning an `error` if we only return `nil`?
</blockquote></details>

No point - removed!
___
*[schema/descriptions/NDT5ResultRowV2.yaml, line 2 at r3](https://reviewable.io/reviews/m-lab/etl/1045#-MuMsVE-EhTBI3elxNx1:-MuMz67TBzyjWNfqXCAt:b-8fx2u7) ([raw file](https://github.com/m-lab/etl/blob/48066cb0631804e9b2a0ea85e40cc7e3ec608654/schema/descriptions/NDT5ResultRowV2.yaml#L2)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

:pray: 
</blockquote></details>

:+1:

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1045#-:-MuNJNmq0Z7-l4PB5ze_:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr and @stephen-soltesz)

___
*[parser/ndt5_result.go, line 108 at r3](https://reviewable.io/reviews/m-lab/etl/1045#-MuMpt3q1syLa99UoeSX:-MuNAurb-nIWDwViq1ha:bbxgr27) ([raw file](https://github.com/m-lab/etl/blob/48066cb0631804e9b2a0ea85e40cc7e3ec608654/parser/ndt5_result.go#L108)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I see a tradeoff here between clarity/simplicity of the logic and parsing the record once.

I parse the record multiple times b/c the pointer types within the result record need to be managed more carefully and reconstructed for the different direction cases (i.e. to mask S2C or C2S, etc) which risked corrupting them in subtle ways (now or in the future) -- simply reparsing guarantees the values are pristine and the logic is be easier to verify as correct by inspection.

What do you think?
</blockquote></details>

Hmm, you make a good point. SGTM as long as we're being repetitive for a specific reason.

**Comment by stephen-soltesz** [comment]
Part of https://github.com/m-lab/etl/issues/1046

**Pull request merged**
