### PR TITLE
Use standard columns for switch schema

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change is a companion to https://github.com/m-lab/etl-schema/pull/5

This change updates the disco switch schema to use standard columns for `test_id`, `task_filename` and `parse_time`.

As well, this change should resolve https://github.com/m-lab/etl/issues/462

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/530)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[parser/disco.go, line 74 at r1](https://reviewable.io/reviews/m-lab/etl/530#-LG27aM6AbJhHXobgXLU:-LG6EonA8ZFp3rp4Cmcu:b-4w4h5s) ([raw file](https://github.com/m-lab/etl/blob/79fc387dcc0779c4a5612e0abac69f625f8597fb/parser/disco.go#L74)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I've been using time.Now().  Let's discuss.
</blockquote></details>

Discussed. Done.

---

*[parser/disco.go, line 75 at r1](https://reviewable.io/reviews/m-lab/etl/530#-LG27e1H42qZLUR-9-Ql:-LG6EtDCCPm7iH275dzh:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/79fc387dcc0779c4a5612e0abac69f625f8597fb/parser/disco.go#L75)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please see https://reviewable.io/reviews/m-lab/etl/531, and consider adding ParserVersion here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/530)*

**Comment by gfr10598** [comment]
:lgtm:  after resolving one question

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[schema/switch_schema.go, line 13 at r2](https://reviewable.io/reviews/m-lab/etl/530#-LG6Fm8pE3s6v-dojaRJ:-LG6Fm922lBn3m_taTEu:b-fba416) ([raw file](https://github.com/m-lab/etl/blob/c8a5d263f916b540366fcd9719e4f1f633260653/schema/switch_schema.go#L13)):*
> ```Go
> 	TaskFilename  string   `json:"task_filename,string" bigquery:"task_filename"`
> 	TestID        string   `json:"test_id,string" bigquery:"test_id"`
> 	ParseTime     int64    `json:"parse_time,int64" bigquery:"parse_time"`
> ```

We want the BQ field to be a timestamp.  Does this result in a correct timestamp value?  I think SS uses struct with a time.Time field, and NDT uses a map with a timestamp marshalled to a string.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/530#-:-LG6M65q-YYwTv3uWGu8:b1equz0)*

**Comment by gfr10598** [comment]
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[schema/switch_schema.go, line 13 at r2](https://reviewable.io/reviews/m-lab/etl/530#-LG6Fm8pE3s6v-dojaRJ:-LG6rUZb4B2z35zuIbWq:b-qhqw3s) ([raw file](https://github.com/m-lab/etl/blob/c8a5d263f916b540366fcd9719e4f1f633260653/schema/switch_schema.go#L13)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

We want the BQ field to be a timestamp.  Does this result in a correct timestamp value?  I think SS uses struct with a time.Time field, and NDT uses a map with a timestamp marshalled to a string.
</blockquote></details>

Also ok to leave this to a followup PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/530)*

**Comment by stephen-soltesz** [comment]
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[schema/switch_schema.go, line 13 at r2](https://reviewable.io/reviews/m-lab/etl/530#-LG6Fm8pE3s6v-dojaRJ:-LG6sSLDCa4qz_oV1PGA:b-hnhs4u) ([raw file](https://github.com/m-lab/etl/blob/c8a5d263f916b540366fcd9719e4f1f633260653/schema/switch_schema.go#L13)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Also ok to leave this to a followup PR.
</blockquote></details>

Good question. It seems like there is some flexibility. But, I've changed ParseTime to `time.Time` for consistency.

The current switch schema depends on the bq type "TIMESTAMP" coming from a unix timestamp `int` for the disco sample timestamps -- and the BQ schema reports and renders correctly as a timestamp. So, I suspect that bq is doing the conversion independent of the Go or JSON types.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/530)*

**Comment by gfr10598** [comment]
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[schema/switch_schema.go, line 13 at r2](https://reviewable.io/reviews/m-lab/etl/530#-LG6Fm8pE3s6v-dojaRJ:-LGQcaSP3OQccj-EQs9W:b-lzdlvj) ([raw file](https://github.com/m-lab/etl/blob/c8a5d263f916b540366fcd9719e4f1f633260653/schema/switch_schema.go#L13)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Good question. It seems like there is some flexibility. But, I've changed ParseTime to `time.Time` for consistency.

The current switch schema depends on the bq type "TIMESTAMP" coming from a unix timestamp `int` for the disco sample timestamps -- and the BQ schema reports and renders correctly as a timestamp. So, I suspect that bq is doing the conversion independent of the Go or JSON types.
</blockquote></details>

Cool.  Didn't know it would do that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/530)*

**Pull request merged**
