### PR TITLE
Move sidestream to staging

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/246)

### CODE REVIEW

**Comment by gfr10598** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 155 at r2](https://reviewable.io:443/reviews/m-lab/etl/246#-KutS4Gy1hyr6xJbV4ib:-KutS4Gz0smg_PMrWzcH:b3341es) ([raw file](https://github.com/m-lab/etl/blob/825cdfc7702d98a1a4b7fce8622e55462ec3a947/.travis.yml#L155)):*
> ```YAML
>     all_branches: true
>     tag: true
>     condition: $TRAVIS_TAG == ss-staging*
> ```

ss-staging-*  (missing dash before *)

---

*[cmd/etl_worker/app-sidstream-staging.yaml, line 1 at r2](https://reviewable.io:443/reviews/m-lab/etl/246#-KutRdKNgaj9wv081A9l:-KutRdKNgaj9wv081A9m:bdx3s01) ([raw file](https://github.com/m-lab/etl/blob/825cdfc7702d98a1a4b7fce8622e55462ec3a947/cmd/etl_worker/app-sidstream-staging.yaml#L1)):*
> ```YAML
> runtime: custom
> ```

There is a typo in the file name.

---

*[cmd/etl_worker/app-sidstream-staging.yaml, line 25 at r2](https://reviewable.io:443/reviews/m-lab/etl/246#-KutRp_XlbQ50STDonSI:-KutRp_Y4C1_LKR6j-oy:bw9t6gi) ([raw file](https://github.com/m-lab/etl/blob/825cdfc7702d98a1a4b7fce8622e55462ec3a947/cmd/etl_worker/app-sidstream-staging.yaml#L25)):*
> ```YAML
>   # We don't care much about latency, so a high utilization is desireable.
>   cpu_utilization:
>     target_utilization: 0.95
> ```

Start with .90 and make sure that is stable first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/246)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/etl_worker/app-sidstream-staging.yaml, line 1 at r2](https://reviewable.io:443/reviews/m-lab/etl/246#-KutRdKNgaj9wv081A9l:-Kuu7BNpLHFRL_qenYqM:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/825cdfc7702d98a1a4b7fce8622e55462ec3a947/cmd/etl_worker/app-sidstream-staging.yaml#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

There is a typo in the file name.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/246)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/etl_worker/app-sidestream-staging.yaml, line 25 at r2](https://reviewable.io:443/reviews/m-lab/etl/246#-KutRp_XlbQ50STDonSI:-Kuu8B9rAk8f4cNILzgr:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/825cdfc7702d98a1a4b7fce8622e55462ec3a947/cmd/etl_worker/app-sidestream-staging.yaml#L25)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Start with .90 and make sure that is stable first.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/246)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 155 at r2](https://reviewable.io:443/reviews/m-lab/etl/246#-KutS4Gy1hyr6xJbV4ib:-Kuu9E2jQEp3LoT3oB0P:b-6clhy3) ([raw file](https://github.com/m-lab/etl/blob/825cdfc7702d98a1a4b7fce8622e55462ec3a947/.travis.yml#L155)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

ss-staging-*  (missing dash before *)
</blockquote></details>

discussed offline. comments above modified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/246)*

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/246#-:-KuuF86KoHa_aVwoIp6p:bnfp4nl)*

**Pull request merged**
