### PR TITLE
Created the first three common functions and their tests. Plus, added…

### PR DESCRIPTION
**Pull request by jlm123hi**
… metadata.
These are most of the shared functions that will be used for the metadata.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/221)

### CODE REVIEW

**Comment by yachang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[parser/metadata.go, line 15 at r1](https://reviewable.io:443/reviews/m-lab/etl/221#-KrXBNjrAXh9BpQdHaHA:-KrXBNjrAXh9BpQdHaHB:b-je0lfx) ([raw file](https://github.com/m-lab/etl/blob/aa8a421077be7fa43bc77534781a163333501c32/parser/metadata.go#L15)):*
> ```Go
> )
> 
> //GetMetaData combines the functionality of QueryAnnotationService and
> ```

Leave a space between // and documentation.

For all following comments as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/221)*

**Comment by yachang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[metrics/metrics.go, line 66 at r1](https://reviewable.io:443/reviews/m-lab/etl/221#-KrXCrizXrFlfImL-LxQ:-KrXCrizXrFlfImL-LxR:b-95azhj) ([raw file](https://github.com/m-lab/etl/blob/aa8a421077be7fa43bc77534781a163333501c32/metrics/metrics.go#L66)):*
> ```Go
> 	AnnotationErrorCount = prometheus.NewGaugeVec(prometheus.GaugeOpts{
> 		Name: "etl_annotator_Error_Count",
> 		Help: "The current number of unresolved errors encountered while attemting to add metadata.",
> ```

remove "unsolved"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/221)*

**Comment by yachang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[parser/metadata_test.go, line 114 at r1](https://reviewable.io:443/reviews/m-lab/etl/221#-KrXE3LhymOU6eJWLUJX:-KrXE3LhymOU6eJWLUJY:b-882qqz) ([raw file](https://github.com/m-lab/etl/blob/aa8a421077be7fa43bc77534781a163333501c32/parser/metadata_test.go#L114)):*
> ```Go
> 	for _, test := range tests {
> 		res, err := p.ParseJSONMetaDataResponse(test.testBuffer)
> 		if err == nil && test.resultError != nil ||
> ```

Add documentation for those logic combination.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/221)*

**Comment by jlm123hi** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[metrics/metrics.go, line 66 at r1](https://reviewable.io:443/reviews/m-lab/etl/221#-KrXCrizXrFlfImL-LxQ:-KrXGffOuJardWZha4WY:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/aa8a421077be7fa43bc77534781a163333501c32/metrics/metrics.go#L66)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

remove "unsolved"
</blockquote></details>

Done.

---

*[parser/metadata.go, line 15 at r1](https://reviewable.io:443/reviews/m-lab/etl/221#-KrXBNjrAXh9BpQdHaHA:-KrXGgdtUBWXq7UxCdlz:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/aa8a421077be7fa43bc77534781a163333501c32/parser/metadata.go#L15)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Leave a space between // and documentation.

For all following comments as well
</blockquote></details>

Done.

---

*[parser/metadata_test.go, line 114 at r1](https://reviewable.io:443/reviews/m-lab/etl/221#-KrXE3LhymOU6eJWLUJX:-KrXGhclwnCi2Hnv1NKU:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/aa8a421077be7fa43bc77534781a163333501c32/parser/metadata_test.go#L114)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Add documentation for those logic combination.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/221)*

**Comment by yachang** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/221#-:-KraH9ikTTatZ8QTbjVX:bnfp4nl)*

**Pull request merged**
