### PR TITLE
Added the batch request base code.

### PR DESCRIPTION
**Pull request by jlm123hi**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/233)

### CODE REVIEW

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[parser/metadata.go, line 273 at r1](https://reviewable.io:443/reviews/m-lab/etl/233#-KsdUDXBkM9qfn5hrnB6:-KsdUDXBkM9qfn5hrnB7:bb3fni6) ([raw file](https://github.com/m-lab/etl/blob/1b06f0d4a9f16d56168015f58674341d6d5b0f55/parser/metadata.go#L273)):*
> ```Go
> 		metrics.AnnotationErrorCount.
> 			With(prometheus.Labels{"source": "Error querying annotation service"}).Inc()
> 		log.Println(err)
> ```

return data and error as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/233)*

**Comment by jlm123hi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[parser/metadata.go, line 273 at r1](https://reviewable.io:443/reviews/m-lab/etl/233#-KsdUDXBkM9qfn5hrnB6:-KsdW-Fby1jU-Ap9jRlD:b-efn47l) ([raw file](https://github.com/m-lab/etl/blob/1b06f0d4a9f16d56168015f58674341d6d5b0f55/parser/metadata.go#L273)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

return data and error as well.
</blockquote></details>

What should I actually _do_ with the error in the calling function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/233)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/metadata_test.go, line 572 at r1](https://reviewable.io:443/reviews/m-lab/etl/233#-KsdeEzWACRgRgB5oQ-d:-KsdeEzWACRgRgB5oQ-e:bzgejaj) ([raw file](https://github.com/m-lab/etl/blob/1b06f0d4a9f16d56168015f58674341d6d5b0f55/parser/metadata_test.go#L572)):*
> ```Go
> 		{
> 			testBuffer:  []byte(`{"127.0.0.1xyz": {"Geo":null,"ASN":null}}`),
> 			resultData:  map[string]schema.MetaData{"127.0.0.1xyz": {Geo: nil, ASN: nil}},
> ```

Is this to test corrupted input (invalid IP address)?

If so, add documentation for this test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/233)*

**Comment by jlm123hi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/metadata.go, line 273 at r1](https://reviewable.io:443/reviews/m-lab/etl/233#-KsdUDXBkM9qfn5hrnB6:-Ksdg3acm67wwkWiaIn9:bjhfcvn) ([raw file](https://github.com/m-lab/etl/blob/1b06f0d4a9f16d56168015f58674341d6d5b0f55/parser/metadata.go#L273)):*
<details><summary><i>Previously, jlm123hi (Joseph Marques) wrote…</i></summary><blockquote>

What should I actually _do_ with the error in the calling function?
</blockquote></details>

Ignored, as per in-person discussion.

---

*[parser/metadata_test.go, line 572 at r1](https://reviewable.io:443/reviews/m-lab/etl/233#-KsdeEzWACRgRgB5oQ-d:-Ksdg2I4lwp-Oos_6Tby:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/1b06f0d4a9f16d56168015f58674341d6d5b0f55/parser/metadata_test.go#L572)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Is this to test corrupted input (invalid IP address)?

If so, add documentation for this test.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/233)*

**Comment by yachang** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/233#-:-KsdlYwY1QHWJMf6ZoGO:bnfp4nl)*

**Pull request merged**
