### PR TITLE
Move sidestream to prod

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/249)

### CODE REVIEW

**Comment by yachang** [comment]
Monitoring metrics are at:

http://status-mlab-oti.measurementlab.net:3000/dashboard/db/ss-pipeline?refresh=1m&orgId=1&from=now-30m&to=now

**Comment by yachang** [comment]
New BQ table has been created at:

https://bigquery.cloud.google.com/table/measurement-lab:public.traceroute?pli=1

**Comment by gfr10598** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis.yml, line 167 at r2](https://reviewable.io:443/reviews/m-lab/etl/249#-Kv3CSwcWB-w89eQfZV8:-Kv3CSwcWB-w89eQfZV9:b21zeoe) ([raw file](https://github.com/m-lab/etl/blob/61d4d916878deec6f7b75b433b6d366385340e16/.travis.yml#L167)):*
> ```YAML
>     all_branches: true
>     tag: true
>     condition: $TRAVIS_TAG == ss-prod*
> ```

Please change here and above to ss-prod-*.  Tags should always have additional info after the dash.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/249)*

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/249#-:-Kv3CmQeeIiBkkPGo7u7:bnfp4nl)*

**Comment by gfr10598** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/249)*

**Comment by yachang** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis.yml, line 167 at r2](https://reviewable.io:443/reviews/m-lab/etl/249#-Kv3CSwcWB-w89eQfZV8:-Kv3aXFlHIFT1-elh2cM:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/61d4d916878deec6f7b75b433b6d366385340e16/.travis.yml#L167)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please change here and above to ss-prod-*.  Tags should always have additional info after the dash.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/249)*

**Pull request merged**
