### PR TITLE
PT Specific Functions --- Attempt 2

### PR DESCRIPTION
**Pull request by jlm123hi**
2nd time submitting the PR because of Git mistakes

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/229)

### CODE REVIEW

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[parser/metadata.go, line 65 at r1](https://reviewable.io:443/reviews/m-lab/etl/229#-KrlbgKiPMEAZMeJhRbJ:-KrlbgKiPMEAZMeJhRbK:bmc8pnk) ([raw file](https://github.com/m-lab/etl/blob/1a474ccfbb884eaa48cdfc2aad91b88455ec2f51/parser/metadata.go#L65)):*
> ```Go
> 	if hop.Dest_ip != "" {
> 		GetAndInsertGeolocationIPStruct(&hop.Dest_geolocation, hop.Dest_ip, timestamp)
> 	}
> ```

src_ip and dest_ip should never be empty. create a metric for error count here if they are empty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/229)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/metadata.go, line 52 at r1](https://reviewable.io:443/reviews/m-lab/etl/229#-KrlcuNAS1D9r6uqw-Yh:-KrlcuNAS1D9r6uqw-Yi:bk7lnoq) ([raw file](https://github.com/m-lab/etl/blob/1a474ccfbb884eaa48cdfc2aad91b88455ec2f51/parser/metadata.go#L52)):*
> ```Go
> // timestamp. With these, it will fetch the appropriate metadata and
> // add it to the hop struct referenced by the pointer.
> func AddMetaDataPTHop(hop *schema.ParisTracerouteHop, timestamp time.Time) {
> ```

Check hop is not nil here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/229)*

**Comment by jlm123hi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/metadata.go, line 52 at r1](https://reviewable.io:443/reviews/m-lab/etl/229#-KrlcuNAS1D9r6uqw-Yh:-KrlhdZz3FBvWlKlGHNN:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/1a474ccfbb884eaa48cdfc2aad91b88455ec2f51/parser/metadata.go#L52)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Check hop is not nil here.
</blockquote></details>

Done.

---

*[parser/metadata.go, line 65 at r1](https://reviewable.io:443/reviews/m-lab/etl/229#-KrlbgKiPMEAZMeJhRbJ:-KrlheMhdJELF-KAcqnF:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/1a474ccfbb884eaa48cdfc2aad91b88455ec2f51/parser/metadata.go#L65)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

src_ip and dest_ip should never be empty. create a metric for error count here if they are empty.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/229)*

**Comment by yachang** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/229#-:-Krlpe-wEXOH_DBUBRx6:bnfp4nl)*

**Pull request merged**
