### PR TITLE
Meta file processing additions

### PR DESCRIPTION
**Pull request by gfr10598**
Adds actually writing the results to the web100 BQ records.
Adds IP parsing.
Adds log_time and test_id

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/81)

### CODE REVIEW

**Comment by pboothe** [comment]
*[parser/ndt.go, line 83 at r2](https://reviewable.io:443/reviews/m-lab/etl/81#-KkWYTy20zsj-tWgVwqD:-KkWYTy20zsj-tWgVwqE:b-938jzj) ([raw file](https://github.com/m-lab/etl/blob/90aa5ca6452d80897ffc0e657dc05d1fb1d935fb/parser/ndt.go#L83)):*
> ```Go
> 		return nil, errors.New("Invalid test path: " + path)
> 	}
> 	timestamp, err := time.Parse("20060102T15:04:05.999999999Z_", fields[2]+"T"+fields[3]+"Z_")
> ```

? This looks like a debug line that snuck in...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/81)*

**Comment by pboothe** [comment]
Things look good except for a debug line that looks like it snuck in

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/81#-:-KkWZ6CFS2j__V5UkOfC:bwgp516)*

**Comment by pboothe** [comment]
LGTM, after go date parsing was explained to me.

**Comment by gfr10598** [comment]
*[parser/ndt.go, line 83 at r2](https://reviewable.io:443/reviews/m-lab/etl/81#-KkWYTy20zsj-tWgVwqD:-KkWz3tLmQy7dbaY5WEs:bid11v4) ([raw file](https://github.com/m-lab/etl/blob/90aa5ca6452d80897ffc0e657dc05d1fb1d935fb/parser/ndt.go#L83)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

? This looks like a debug line that snuck in...
</blockquote></details>

Nope.  This is how golang time.Parse expresses a format string.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/81)*

**Pull request merged**
