### PR TITLE
add IP validation util for parsers

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/242)

### CODE REVIEW

**Comment by gfr10598** [comment]
Review status: 0 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[parser/util.go, line 20 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLkEFIiq8QgSmBZdSq:-KuLkEFIiq8QgSmBZdSr:b779mkv) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util.go#L20)):*
> ```Go
> }
> 
> // Return nil if it is a valid IP v4 or IPv6 address.
> ```

Take a look at net.IsGlobalUnicast(), which tests for many of the conditions you need to test.

---

*[parser/util.go, line 23 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLfNPF5w0UGYfWGTlH:-KuLfNPGqX0YRiKiMg9r:bnemh3o) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util.go#L23)):*
> ```Go
> func ValidateIP(ipStr string) error {
> 	ip := net.ParseIP(ipStr)
> 	if ip == nil || ip.To4() == nil && ip.To16() == nil {
> ```

I would suggest using:
if ip == nil {
  return ...
if ip.To4() {
   // IPv4 CIDR conversions
   // private network tests
   // nonroutable tests
} else {
   // IPv6 CIDR conversions
   // private network tests
   // nonroutable tests
}

---

*[parser/util.go, line 28 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLiWUzikOQPcsrZXxn:-KuLiWUzikOQPcsrZXxo:b-tgrow1) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util.go#L28)):*
> ```Go
> 	if ip.Equal(net.IPv4allrouter) || ip.Equal(net.IPv6linklocalallrouters) ||
> 		ip.Equal(net.IPv6zero) || ip.Equal(net.IPv4zero) {
> 		return errors.New("zero IP is invalid.")
> ```

Error message is misleading.

---

*[parser/util.go, line 50 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLhrC7sXp8JoDenOSa:-KuLhrC7sXp8JoDenOSb:b-1a4ef) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util.go#L50)):*
> ```Go
> 	if ip.To4() != nil {
> 		_, nonroutable1, _ := net.ParseCIDR("0.0.0.0/8")
> 		_, nonroutable2, _ := net.ParseCIDR("127.0.0.0/8")
> ```

See net.IsLoopback()

---

*[parser/util.go, line 53 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLi8_QrWhlu_UMHTBw:-KuLi8_QrWhlu_UMHTBx:b-ruvues) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util.go#L53)):*
> ```Go
> 		_, nonroutable3, _ := net.ParseCIDR("192.0.2.0/24")
> 		_, nonroutable4, _ := net.ParseCIDR("240.0.0.0/4")
> 		_, nonroutable5, _ := net.ParseCIDR("169.254.0.0/16")
> ```

See net.IsLinkLocalUnicast()

---

*[parser/util.go, line 65 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLj-bSuxEUZn4k0Tks:-KuLj-bTroKhGwC1A1LQ:b-ruvues) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util.go#L65)):*
> ```Go
> 		_, nonroutable3, _ := net.ParseCIDR("2001:db8::/32")
> 		_, nonroutable4, _ := net.ParseCIDR("fec0::/10")
> 		_, nonroutable5, _ := net.ParseCIDR("fe80::/10")
> ```

See net.IsLinkLocalUnicast()

---

*[parser/util.go, line 66 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLjedTgC34wAaibY6D:-KuLjedTgC34wAaibY6E:b-nzilrb) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util.go#L66)):*
> ```Go
> 		_, nonroutable4, _ := net.ParseCIDR("fec0::/10")
> 		_, nonroutable5, _ := net.ParseCIDR("fe80::/10")
> 		_, nonroutable6, _ := net.ParseCIDR("ff00::/8")
> ```

net.IsMulticast()

---

*[parser/util_test.go, line 9 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLfTyojJjwUOWUO45K:-KuLfTyojJjwUOWUO45L:b-osl0hh) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util_test.go#L9)):*
> ```Go
> 	"github.com/m-lab/etl/parser"
> )
> ```

Please add a simple benchmark for ValidateIP.  If it takes more than single digit microseconds we may need to improve it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/242)*

**Comment by yachang** [comment]
Review status: 0 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[parser/util.go, line 20 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLkEFIiq8QgSmBZdSq:-KuQbwKxAUN561M9ucSn:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util.go#L20)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Take a look at net.IsGlobalUnicast(), which tests for many of the conditions you need to test.
</blockquote></details>

Done.

---

*[parser/util.go, line 23 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLfNPF5w0UGYfWGTlH:-KuQJy97_D3AnoLLK0VA:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util.go#L23)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I would suggest using:
if ip == nil {
  return ...
if ip.To4() {
   // IPv4 CIDR conversions
   // private network tests
   // nonroutable tests
} else {
   // IPv6 CIDR conversions
   // private network tests
   // nonroutable tests
}

</blockquote></details>

Done.

---

*[parser/util.go, line 28 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLiWUzikOQPcsrZXxn:-KuQJvRa04EoqnzY_BYL:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util.go#L28)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Error message is misleading.
</blockquote></details>

Done.

---

*[parser/util.go, line 50 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLhrC7sXp8JoDenOSa:-KuQbxXoqu5VKLkG_obA:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util.go#L50)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

See net.IsLoopback()
</blockquote></details>

Done.

---

*[parser/util.go, line 53 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLi8_QrWhlu_UMHTBw:-KuQbyK8nqfG-eX5K4Y-:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util.go#L53)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

See net.IsLinkLocalUnicast()
</blockquote></details>

Done.

---

*[parser/util.go, line 65 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLj-bSuxEUZn4k0Tks:-KuQbzSQ40LTl0-DtXFY:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util.go#L65)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

See net.IsLinkLocalUnicast()
</blockquote></details>

Done.

---

*[parser/util.go, line 66 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLjedTgC34wAaibY6D:-KuQc-21v9q4twRPgyrP:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util.go#L66)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

net.IsMulticast()
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/242)*

**Comment by yachang** [comment]
Review status: 0 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[parser/util_test.go, line 9 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLfTyojJjwUOWUO45K:-KuQdMQHlFnNG1zuRC_W:b-28kcb9) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util_test.go#L9)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please add a simple benchmark for ValidateIP.  If it takes more than single digit microseconds we may need to improve it.
</blockquote></details>

Here is the benchmark results:

1000000	      3676 ns/op

3.676 microseconds / op

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/242)*

**Comment by gfr10598** [comment]
:lgtm: After resolving comments.

---

Reviewed 2 of 6 files at r1.
Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[parser/util.go, line 26 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuVFYaNV4v5LVzI-dQC:-KuVFYaNV4v5LVzI-dQD:b1jvr2g) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util.go#L26)):*
> IPv4allrouter
Do you still want to check for routers somewhere?

---

*[parser/util.go, line 45 at r2](https://reviewable.io:443/reviews/m-lab/etl/242#-KuVEWjyST2_iPLXQULS:-KuVEWjyST2_iPLXQULT:bybr5c) ([raw file](https://github.com/m-lab/etl/blob/9432c0faeef61d7201a38dcc0e405cff18846122/parser/util.go#L45)):*
> ip.IsLoopback() || ip.IsMulticast() || ip.IsLinkLocalUnicast() {

FYI, these could be tested outside of the ip4/ip6 blocks, since they don't care about 4 vs 6.

---

*[parser/util_test.go, line 9 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLfTyojJjwUOWUO45K:-KuVElf6wCRxkq3S4jXT:b-qn5lbb) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util_test.go#L9)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Here is the benchmark results:

1000000	      3676 ns/op

3.676 microseconds / op
</blockquote></details>

Perfect!

---

*[parser/util_test.go, line 40 at r2](https://reviewable.io:443/reviews/m-lab/etl/242#-KuVEvJAdoPrhUV8tCLP:-KuVEvJAdoPrhUV8tCLQ:b-yp2k4k) ([raw file](https://github.com/m-lab/etl/blob/9432c0faeef61d7201a38dcc0e405cff18846122/parser/util_test.go#L40)):*
> ```Go
> }
> 
> func BenchmarkFunction(b *testing.B) {
> ```

please rename BenchmarkValidateIPv4(...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/242#-:-KuVFilfgQ6HCRfdsiyb:bg7591s)*

**Comment by gfr10598** [comment]
Reviewed 1 of 6 files at r1, 1 of 2 files at r2.
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/242)*

**Comment by gfr10598** [comment]
Reviewed 1 of 6 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/242)*

**Comment by yachang** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/util.go, line 26 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuVFYaNV4v5LVzI-dQC:-KuVIha1_LoV0ZNdSZ-0:bs1vrko) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util.go#L26)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

> IPv4allrouter
Do you still want to check for routers somewhere?
</blockquote></details>

I tried to match the ValidateIP function in legacy pipeline. IPv4allrouter was not checked either in internal google3 functions.

---

*[parser/util_test.go, line 9 at r1](https://reviewable.io:443/reviews/m-lab/etl/242#-KuLfTyojJjwUOWUO45K:-KuVH_T8yV8K0PnX3zVF:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/fc0dec1aecf6db5fc643d99a9f12365cd705e7f8/parser/util_test.go#L9)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Perfect!
</blockquote></details>

Done.

---

*[parser/util_test.go, line 40 at r2](https://reviewable.io:443/reviews/m-lab/etl/242#-KuVEvJAdoPrhUV8tCLP:-KuVHZUHdBGyvIvmIWRW:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/9432c0faeef61d7201a38dcc0e405cff18846122/parser/util_test.go#L40)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

please rename BenchmarkValidateIPv4(...)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/242)*

**Comment by yachang** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[parser/util.go, line 45 at r2](https://reviewable.io:443/reviews/m-lab/etl/242#-KuVEWjyST2_iPLXQULS:-KuVN99VJmNOSm_xg9F5:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/9432c0faeef61d7201a38dcc0e405cff18846122/parser/util.go#L45)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

> ip.IsLoopback() || ip.IsMulticast() || ip.IsLinkLocalUnicast() {

FYI, these could be tested outside of the ip4/ip6 blocks, since they don't care about 4 vs 6.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/242)*

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/242#-:-KuVPK2rFnR1GMqlaz7g:bnfp4nl)*

**Comment by gfr10598** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/242)*

**Pull request merged**
