### PR TITLE
Remove v1 parser/base.go interface, migrate v1 types to row.Base

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change eliminates the `row.Annotatable` interface and the dependency on `row.NullAnnotator` for all schemas.

This change also eliminates the v1 parser/base.go interfaces in favor of migrating the v1 types (ndt, pt, and sidestream) to the `row.Base` interface. While these v1 types and schemas are not yet supported by the parsers, this is an incremental step toward making that possible. The only thing preventing it now is an update to the schema itself to use standard columns and supporting parser changes to use the updated schema.

Part of:
* https://github.com/m-lab/etl/issues/1084

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/1088)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1088#-:-N3tSUwWBo4kcWN0nHLj:b90ldqe)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`parser/ndt.go` line 158 at r2](https://reviewable.io/reviews/m-lab/etl/1088#-N3tb3oF1u4PyyjpoRr_:-N3tb3oF1u4PyyjpoRra:b3dfsyj) ([raw file](https://github.com/m-lab/etl/blob/726fa1eb66024daf41f831aff0a92fc0117b3a31/parser/ndt.go#L158)):*
> ```Go
> 	s := n.GetStats()
> 	if s.Committed < 10*s.Failed {
> 		log.Printf("Warning: high row commit errors: %d / %d\n",
> ```

Better :thumbsup:.
___
*[`parser/pt_test.go` line 278 at r2](https://reviewable.io/reviews/m-lab/etl/1088#-N3t_o4X8-Wdfsi7Xevt:-N3t_o4X8-Wdfsi7Xevu:b-iqr0du) ([raw file](https://github.com/m-lab/etl/blob/726fa1eb66024daf41f831aff0a92fc0117b3a31/parser/pt_test.go#L278)):*
> ```Go
> 	s := pt.GetStats()
> 	if s.Total() != 1 {
> 		fmt.Println(s.Total())
> ```

I know this is mirroring what was already there, but is this a debug line? Same question for lines 371, 402, and 409.
___
*[`parser/ss.go` line 31 at r2](https://reviewable.io/reviews/m-lab/etl/1088#-N3tZttmBQOnPyKh_5oA:-N3tZttmBQOnPyKh_5oB:bcsodny) ([raw file](https://github.com/m-lab/etl/blob/726fa1eb66024daf41f831aff0a92fc0117b3a31/parser/ss.go#L31)):*
> ```Go
> 
> // NewSSParser creates a new sidestream parser.
> func NewSSParser(sink row.Sink, table, suffix string) *SSParser {
> ```

Should this return `etl.Parser`? Or will that be in the future?
___
*[`row/row.go` line 206 at r2](https://reviewable.io/reviews/m-lab/etl/1088#-N3tXHA-EIyEVvtD7I04:-N3tXHA0B0NKoF3Rd-xJ:bjgqbdu) ([raw file](https://github.com/m-lab/etl/blob/726fa1eb66024daf41f831aff0a92fc0117b3a31/row/row.go#L206)):*
> ```Go
> }
> 
> // Put adds a row to the buffer. Iff the buffer is already full, then prior
> ```

Is this a typo or an "if and only if"?
___
*[`schema/pt_schema_test.go` line 2 at r2](https://reviewable.io/reviews/m-lab/etl/1088#-N3tWQBZBIEe7ohyjdr2:-N3tWQBZBIEe7ohyjdr3:b-ifr5o4) ([raw file](https://github.com/m-lab/etl/blob/3b809cfb5eb8f42a8c84755402a45fa7086c8f23/schema/pt_schema_test.go#L2)):*
> ```Go
> package schema_test
> ```

I think we should either:
* Delete this file.
* Add a TODO to add some tests for the schema.
* Add some tests for the schema.

**Review by stephen-soltesz — COMMENTED** [review]
Thank you - Love the meme!

PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1088#-:-N3uJQYm-NW52-YuTzBR:b-13bkxf)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`parser/pt_test.go` line 278 at r2](https://reviewable.io/reviews/m-lab/etl/1088#-N3t_o4X8-Wdfsi7Xevt:-N3ttm5_CYGjplXPeh-M:b-k12xl1) ([raw file](https://github.com/m-lab/etl/blob/726fa1eb66024daf41f831aff0a92fc0117b3a31/parser/pt_test.go#L278)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

I know this is mirroring what was already there, but is this a debug line? Same question for lines 371, 402, and 409.
</blockquote></details>

Yeah, good call. I've updated all references to `fmt` and used better idiomatic messages.
___
*[`parser/ss.go` line 31 at r2](https://reviewable.io/reviews/m-lab/etl/1088#-N3tZttmBQOnPyKh_5oA:-N3ttz1M2Ocgrq-G4qWE:bwlmt6a) ([raw file](https://github.com/m-lab/etl/blob/726fa1eb66024daf41f831aff0a92fc0117b3a31/parser/ss.go#L31)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Should this return `etl.Parser`? Or will that be in the future?
</blockquote></details>

I don't think we ever want to return interfaces. https://github.com/golang/go/wiki/CodeReviewComments#interfaces

I know that is common within the ETL code bases. That is an anti-pattern as I understand it today.
___
*[`row/row.go` line 206 at r2](https://reviewable.io/reviews/m-lab/etl/1088#-N3tXHA-EIyEVvtD7I04:-N3tugR0A5tMtxaY6anY:b-7f7y7a) ([raw file](https://github.com/m-lab/etl/blob/726fa1eb66024daf41f831aff0a92fc0117b3a31/row/row.go#L206)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Is this a typo or an "if and only if"?
</blockquote></details>

I wondered the same. I took it for "if and only if" but I'm not sure that specificity is called for here. Updated to `If`.
___
*[`schema/pt_schema_test.go` line 2 at r2](https://reviewable.io/reviews/m-lab/etl/1088#-N3tWQBZBIEe7ohyjdr2:-N3uIW1576XnCuheGEf4:bx57h38) ([raw file](https://github.com/m-lab/etl/blob/3b809cfb5eb8f42a8c84755402a45fa7086c8f23/schema/pt_schema_test.go#L2)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

I think we should either:
* Delete this file.
* Add a TODO to add some tests for the schema.
* Add some tests for the schema.
</blockquote></details>

I agree that we should prefer unit tests for schema types.

Since this is a v1 type, that is no longer usable without additional refactoring to plug into the v2 pipeline, I don't see the value of unit tests for the current schema.

I've added an explicit TODO to this file for the criteria to add unit tests in the future.

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1088#-:-N3uU8vV228jSmsguK7P:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by stephen-soltesz** [comment]
Thank you!

**Pull request merged**
