### PR TITLE
End to end demo #1

### PR DESCRIPTION
**Pull request by gfr10598**
This is the first end to end demo.  Pushing a gs:// file name to the task queue results in worker loading that file, and for each file in the tar file, inserting a row into the "test3" table.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/20)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Reviewed 3 of 7 files at r1.
Review status: 3 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[cmd/etl_worker/etl_worker.go, line 55 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwPKJ4KNec7RYkYy1x:-KhwPKJ4KNec7RYkYy1y:bnlln3g) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/cmd/etl_worker/etl_worker.go#L55)):*
> ```Go
> 	if err != nil {
> 		fmt.Fprintf(w, `{"message": "Could not create client."}`)
> 		w.WriteHeader(503) // Service Unavailable
> ```

Please use the named status from the `http` package. i.e. `http.StatusServiceUnavailable`.

---

*[cmd/etl_worker/etl_worker.go, line 63 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwPtLo6oN7SzZurI5o:-KhwPtLo6oN7SzZurI5p:bmjbvut) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/cmd/etl_worker/etl_worker.go#L63)):*
> log.Printf("Bailing out")

Do we need this?

---

*[cmd/etl_worker/etl_worker.go, line 65 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwQ9sR4CukmsjC-R8T:-KhwQ9sR4CukmsjC-R8U:b5d93gw) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/cmd/etl_worker/etl_worker.go#L65)):*
> w.WriteHeader

Please set a non-OK status code before returning (and below).

---

*[cmd/etl_worker/etl_worker.go, line 69 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwQlIz6OR21UfPtAtW:-KhwQlIz6OR21UfPtAtX:bkjcezh) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/cmd/etl_worker/etl_worker.go#L69)):*
> ```Go
> 	}
> 	parser := new(parser.TestParser)
> 	ins, err := bq.NewInserter("mlab-sandbox", "mlab_sandbox", "test3")
> ```

just an fyi: ultimately the project id can come from the environment. `GCLOUD_PROJECT`. I'm imagining the other fields will be determined based on the file type?

---

*[cmd/etl_worker/etl_worker.go, line 80 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwS4tuluoTvfy1InWn:-KhwS4tvBG_RvNBXE6fv:b8dr512) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/cmd/etl_worker/etl_worker.go#L80)):*
> ```Go
> 
> 	tsk.ProcessAllTests()
> 	tr.Close()
> ```

This could be a `defer tr.Close()` after the successful creation above.

---

*[parser/parser.go, line 51 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwTIVTfzIXvnvXh9ZU:-KhwTIVU-U6kZDPdzKQ6:bvqqsgg) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/parser/parser.go#L51)):*
> ```Go
> 
> func (np *TestParser) Parse(fn string, table string, test []byte) (interface{}, error) {
> 	test_count.With(prometheus.Labels{"table": table}).Inc()
> ```

Please update the variable names `test_count` and `failure_count` to use mixed caps form.

---

*[storage/storage_test.go, line 27 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwW06a2JBhNg3wUNJj:-KhwW06bE09-vudbI4Bo:bqi023r) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/storage/storage_test.go#L27)):*
> ```Go
> // Next reads the next test object from the tar file.
> // Returns io.EOF when there are no more tests.
> func next(tt TarReader) (string, []byte, error) {
> ```

What is different about this implementation from the one in task.go? Would it be worthwhile making a generic `Next` iterator that could be reused in both places to reduce the code repetition?

---

*[storage/storage_test.go, line 54 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwWTfttg3IL788RGsG:-KhwWTfttg3IL788RGsH:b-jjn8ph) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/storage/storage_test.go#L54)):*
> ```Go
> 
> func TestNewTarReader(t *testing.T) {
> 	reader, err := NewGCSTarReader(client, "gs://m-lab-sandbox/test.tar")
> ```

Is this the same bucket name we'll use for future tests?

---

*[storage/storage_test.go, line 63 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwWwFgrr1JKvXdZtV-:-KhwWwFgrr1JKvXdZtV0:b8xb8m5) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/storage/storage_test.go#L63)):*
> ```Go
> 		if err != nil {
> 			t.Fatal(err)
> 			return
> ```

Returns are unnecessary after `t.Fatal`.

An alternative option is to use `t.Error` and break to allow the checking to continue and fall through.

---

*[task/task.go, line 85 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwYzjKtN4Q_3P5qjyQ:-KhwYzjKtN4Q_3P5qjyR:bb0w8kd) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/task/task.go#L85)):*
> ```Go
> 		}
> 
> 		test, err := tt.Parser.Parse(fn, tt.table, data)
> ```

Rather than `test`, can we call this `rows`?

I have a mental model of inserting a single row. What is the underlying data type when the return value from `Parse` represents multiple rows?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/20)*

**Comment by gfr10598** [comment]
Review status: 3 of 7 files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[cmd/etl_worker/etl_worker.go, line 55 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwPKJ4KNec7RYkYy1x:-KhweXOAMSRYr-YMXGR8:bs5fh2y) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/cmd/etl_worker/etl_worker.go#L55)):*
> http.StatusServiceUnavailable
d'oh

---

*[cmd/etl_worker/etl_worker.go, line 63 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwPtLo6oN7SzZurI5o:-KhwfRMi20U2QZU62Kyl:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/cmd/etl_worker/etl_worker.go#L63)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

> log.Printf("Bailing out")

Do we need this?
</blockquote></details>

Done.

---

*[cmd/etl_worker/etl_worker.go, line 65 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwQ9sR4CukmsjC-R8T:-KhwfRuA98zx4aNE2Euc:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/cmd/etl_worker/etl_worker.go#L65)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

> w.WriteHeader

Please set a non-OK status code before returning (and below).
</blockquote></details>

Done.

---

*[cmd/etl_worker/etl_worker.go, line 69 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwQlIz6OR21UfPtAtW:-Khwg69_52kctadz7tRy:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/cmd/etl_worker/etl_worker.go#L69)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

just an fyi: ultimately the project id can come from the environment. `GCLOUD_PROJECT`. I'm imagining the other fields will be determined based on the file type?
</blockquote></details>

Done.

---

*[cmd/etl_worker/etl_worker.go, line 80 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwS4tuluoTvfy1InWn:-KhwgEtg7sYyIYzuLh5z:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/cmd/etl_worker/etl_worker.go#L80)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This could be a `defer tr.Close()` after the successful creation above.
</blockquote></details>

Done.

---

*[parser/parser.go, line 51 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwTIVTfzIXvnvXh9ZU:-KhwgkWhpUj2HIvCpngl:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/parser/parser.go#L51)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please update the variable names `test_count` and `failure_count` to use mixed caps form.
</blockquote></details>

Done.

---

*[storage/storage_test.go, line 27 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwW06a2JBhNg3wUNJj:-KhwgyGiTWUeNBE2dVpK:b-upse7p) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/storage/storage_test.go#L27)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What is different about this implementation from the one in task.go? Would it be worthwhile making a generic `Next` iterator that could be reused in both places to reduce the code repetition?
</blockquote></details>

No difference.  I'm intending to move the NextTest function into storage instead.  There is a comment there.

---

*[storage/storage_test.go, line 54 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwWTfttg3IL788RGsG:-KhwgtE1Qri9ILRPgPoR:bjjk1qr) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/storage/storage_test.go#L54)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this the same bucket name we'll use for future tests?
</blockquote></details>

You mean test.tar?  Don't know - haven't put any thought into it.

---

*[storage/storage_test.go, line 63 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwWwFgrr1JKvXdZtV-:-KhwhVHZ4gmaP_9QYJLa:b-cj45p7) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/storage/storage_test.go#L63)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Returns are unnecessary after `t.Fatal`.

An alternative option is to use `t.Error` and break to allow the checking to continue and fall through.
</blockquote></details>

Done.  Leaving as is, since I don't know the behavior after an error.

---

*[task/task.go, line 85 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwYzjKtN4Q_3P5qjyQ:-Khwi3PxUkdyTWKDHm0c:b-wsyygg) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/task/task.go#L85)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Rather than `test`, can we call this `rows`?

I have a mental model of inserting a single row. What is the underlying data type when the return value from `Parse` represents multiple rows?
</blockquote></details>

Done.
When that happens, I intend to inject the inserter into the parser, or possibly use a channel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/20)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[storage/storage_test.go, line 54 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwWTfttg3IL788RGsG:-Khx2TvjRberx6PY1hk6:b-t55nzu) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/storage/storage_test.go#L54)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

You mean test.tar?  Don't know - haven't put any thought into it.
</blockquote></details>

I meant `m-lab-sandbox`. Does there need to be a TODO to normalize the live buckets used by tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/20#-:-Khx3OsWv3xaW4k2OiEk:bnfp4nl)*

**Comment by gfr10598** [comment]
*[storage/storage_test.go, line 54 at r1](https://reviewable.io:443/reviews/m-lab/etl/20#-KhwWTfttg3IL788RGsG:-Khx5reo4mJyeoOl46HC:bntuir2) ([raw file](https://github.com/m-lab/etl/blob/6e112c67446acac37478357457a34d168bc1b673/storage/storage_test.go#L54)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I meant `m-lab-sandbox`. Does there need to be a TODO to normalize the live buckets used by tests?
</blockquote></details>

After offline discussion - yes, I think we can use sandbox for integration testing, and should generally avoid using GCS for automated unit testing.
I'll add a section to the design doc discussing conventions for unit and integration tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/20)*

**Pull request merged**
