### PR TITLE
Update NDT parser to use new Go web100 parser.

### PR DESCRIPTION
**Pull request by gfr10598**
Some changes to log messages and counters, tests.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/118)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Unless I've missed something, I think that `suffix` is used incorrectly. And, just asking for a little clarification on some comments.

---

Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[parser/ndt.go, line 287 at r1](https://reviewable.io:443/reviews/m-lab/etl/118#-Klewv5cChkhvqiyhGMG:-Klewv5cChkhvqiyhGMH:b-uz4txk) ([raw file](https://github.com/m-lab/etl/blob/f9f897d01e480ab8c773a85669032177400b6e45/parser/ndt.go#L287)):*
> ```Go
> 	snaplog, err := web100.NewSnapLog(test.data)
> 	if err != nil {
> 		// TODO - Use separate counter, since this is not unique across
> ```

I'm not sure what this comment is referring to here or below.

---

*[parser/ndt.go, line 290 at r1](https://reviewable.io:443/reviews/m-lab/etl/118#-Klevcrk-DDvXeJaXHEA:-Klevcrk-DDvXeJaXHEB:b-6ng6sw) ([raw file](https://github.com/m-lab/etl/blob/f9f897d01e480ab8c773a85669032177400b6e45/parser/ndt.go#L290)):*
> ```Go
> 		// the test.
> 		metrics.TestCount.WithLabelValues(
> 			n.TableName(), suffix, testType, "snaplog").Inc()
> ```

Is `suffix` used correctly here? It looks like a const regex string declared at the top of the file.

---

*[parser/ndt.go, line 349 at r1](https://reviewable.io:443/reviews/m-lab/etl/118#-Klez7ga2UQiV06kUd76:-Klez7ga2UQiV06kUd77:b-8ayrb5) ([raw file](https://github.com/m-lab/etl/blob/f9f897d01e480ab8c773a85669032177400b6e45/parser/ndt.go#L349)):*
> ```Go
> 
> 	// TODO(prod) Write a row with this data, even if the snapshot parsing fails?
> 	// TODO URGENT
> ```

What is urgent?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/118#-:-KlezDlnNv6BX3v7OKsq:b2jlmhy)*

**Comment by stephen-soltesz** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[parser/ndt.go, line 325 at r1](https://reviewable.io:443/reviews/m-lab/etl/118#-Klf-3OOGH1OyXVncMJS:-Klf-3OP9Kky3fbzSZX2:b-ncqtod) ([raw file](https://github.com/m-lab/etl/blob/f9f897d01e480ab8c773a85669032177400b6e45/parser/ndt.go#L325)):*
> ```Go
> 
> 	last := snaplog.SnapCount() - 1
> 	if last > 2100 {
> ```

Oh, and I'd like to talk with you in person about this constant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/118)*

**Comment by gfr10598** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[parser/ndt.go, line 287 at r1](https://reviewable.io:443/reviews/m-lab/etl/118#-Klewv5cChkhvqiyhGMG:-KltHpsYI1-7j1NnFRPe:b-lgt0wz) ([raw file](https://github.com/m-lab/etl/blob/f9f897d01e480ab8c773a85669032177400b6e45/parser/ndt.go#L287)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'm not sure what this comment is referring to here or below.
</blockquote></details>

Refers to desire to have multiple counts for a single test.  I've updated to use TestCount, ErrorCount, WarningCount more consistently.  There are probably still a few inconsistencies though.

---

*[parser/ndt.go, line 290 at r1](https://reviewable.io:443/reviews/m-lab/etl/118#-Klevcrk-DDvXeJaXHEA:-Klt62xGY1DvJlXfiIyw:b-n352tf) ([raw file](https://github.com/m-lab/etl/blob/f9f897d01e480ab8c773a85669032177400b6e45/parser/ndt.go#L290)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is `suffix` used correctly here? It looks like a const regex string declared at the top of the file.
</blockquote></details>

Oh - good catch.  I'm retiring suffix now - I don't think we are actually getting any value out of it.

---

*[parser/ndt.go, line 325 at r1](https://reviewable.io:443/reviews/m-lab/etl/118#-Klf-3OOGH1OyXVncMJS:-Klt6AP5vVDpnix9dwlW:b7fv6xa) ([raw file](https://github.com/m-lab/etl/blob/f9f897d01e480ab8c773a85669032177400b6e45/parser/ndt.go#L325)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Oh, and I'd like to talk with you in person about this constant.
</blockquote></details>

Yeah its a bit arbitrary.

---

*[parser/ndt.go, line 349 at r1](https://reviewable.io:443/reviews/m-lab/etl/118#-Klez7ga2UQiV06kUd76:-Klt6WdBSNe_JCuulIWM:bfqw9l4) ([raw file](https://github.com/m-lab/etl/blob/f9f897d01e480ab8c773a85669032177400b6e45/parser/ndt.go#L349)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What is urgent?
</blockquote></details>

Hmm - probably was thinking it was time to write a record even when snapshot parsing fails.  But now I don't think so, so I'm deleting comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/118)*

**Comment by stephen-soltesz** [comment]
:lgtm: -- added more thoughts on the "2100" constant. That issue doesn't need to block this PR, but I would like to follow the question through.

---

Reviewed 6 of 7 files at r2.
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[metrics/metrics.go, line 100 at r2](https://reviewable.io:443/reviews/m-lab/etl/118#-Klu0hiRsFaQxHevsA5Q:-KltOi0Tp0up8L7Fe55I:b-s0e3rc) ([raw file](https://github.com/m-lab/etl/blob/8ceb78aaf7fcaf01505be175a4dea81564c1233d/metrics/metrics.go#L100)):*
>  etl_warning_count{table, kind}

{table, filetype, kind}?

---

*[metrics/metrics.go, line 115 at r2](https://reviewable.io:443/reviews/m-lab/etl/118#-Klu0lM1kxkKXxPZ_trU:-Klu0lM1kxkKXxPZ_trV:bmxmvik) ([raw file](https://github.com/m-lab/etl/blob/8ceb78aaf7fcaf01505be175a4dea81564c1233d/metrics/metrics.go#L115)):*
> ```Go
> 	//
> 	// Provides metrics:
> 	//   etl_error_count{table, kind}
> ```

{table, filetype, kind}?

---

*[parser/ndt.go, line 325 at r1](https://reviewable.io:443/reviews/m-lab/etl/118#-Klf-3OOGH1OyXVncMJS:-Klu2iRXLhQlPqIYaWZ7:bmfornn) ([raw file](https://github.com/m-lab/etl/blob/f9f897d01e480ab8c773a85669032177400b6e45/parser/ndt.go#L325)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Yeah its a bit arbitrary.
</blockquote></details>

From conversations we've had with Matt, it sounds like there are points in the snaplog that are identifiable as the beginning and ending of a test that would make the duration and calculation of throughput more accurate.

Until we make this easy to do, I'm wondering: what is the advantage is of setting a static threshold when it will change behavior wrt the legacy tables for ambiguous benefit to analysis?

A plan that "preserves legacy behavior" (i.e. actual last snapshot) and then "improves accuracy for analysis" seems easily publicly defensible. What is the rationale for the static threshold (and it's consequential changes to the bq data)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/118#-:-Klu5z-uBLpvaudSPX0_:b-4i4g1)*

**Comment by gfr10598** [comment]
FYI also discovered a bug and more info related to name collisions.
PTAL in case I introduces some new bugs or issues.

---

Review status: 7 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[metrics/metrics.go, line 100 at r2](https://reviewable.io:443/reviews/m-lab/etl/118#-Klu0hiRsFaQxHevsA5Q:-Klz0hp2Ac_jCD2mDakx:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/8ceb78aaf7fcaf01505be175a4dea81564c1233d/metrics/metrics.go#L100)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

>  etl_warning_count{table, kind}

{table, filetype, kind}?
</blockquote></details>

Done.

---

*[metrics/metrics.go, line 115 at r2](https://reviewable.io:443/reviews/m-lab/etl/118#-Klu0lM1kxkKXxPZ_trU:-Klz0iRK4DLt7EsXgUVy:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/8ceb78aaf7fcaf01505be175a4dea81564c1233d/metrics/metrics.go#L115)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

{table, filetype, kind}?
</blockquote></details>

Done.

---

*[parser/ndt.go, line 325 at r1](https://reviewable.io:443/reviews/m-lab/etl/118#-Klf-3OOGH1OyXVncMJS:-Klz8z6kX54BEnLdNPgx:b5eipml) ([raw file](https://github.com/m-lab/etl/blob/f9f897d01e480ab8c773a85669032177400b6e45/parser/ndt.go#L325)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

From conversations we've had with Matt, it sounds like there are points in the snaplog that are identifiable as the beginning and ending of a test that would make the duration and calculation of throughput more accurate.

Until we make this easy to do, I'm wondering: what is the advantage is of setting a static threshold when it will change behavior wrt the legacy tables for ambiguous benefit to analysis?

A plan that "preserves legacy behavior" (i.e. actual last snapshot) and then "improves accuracy for analysis" seems easily publicly defensible. What is the rationale for the static threshold (and it's consequential changes to the bq data)?
</blockquote></details>

Changing this to 2800 which I can justify better, and adding some comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/118#-:-Klz9X2p08I_LgVRHXsl:b-7b5i62)*

**Comment by stephen-soltesz** [comment]
Depending on several factors (enumerated below) the .gz and un-gz'd files may present a new issue.

---

Reviewed 2 of 3 files at r3.
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[parser/ndt.go, line 325 at r1](https://reviewable.io:443/reviews/m-lab/etl/118#-Klf-3OOGH1OyXVncMJS:-KlzO1pe4EbjNzO1qEEp:bo84yoo) ([raw file](https://github.com/m-lab/etl/blob/f9f897d01e480ab8c773a85669032177400b6e45/parser/ndt.go#L325)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Changing this to 2800 which I can justify better, and adding some comments.
</blockquote></details>

Thanks, lgtm.

---

*[parser/ndt.go, line 164 at r3](https://reviewable.io:443/reviews/m-lab/etl/118#-KlzNb5iUpwJ3_W4RZfj:-KlzNb5iUpwJ3_W4RZfk:b-qutn1r) ([raw file](https://github.com/m-lab/etl/blob/62bbb7dfac6760c31ab45ac39c7b0f7170ad4f6c/parser/ndt.go#L164)):*
> ```Go
> 			}
> 		} else {
> 			// We only take action on the first file, to avoid dups.
> ```

I'm slightly worried about this.

My understanding is that the .gz file represents a file that ndt confirms is complete. An unzipped file is to some indeterminate degree incomplete.

The scenario I'm worried about is:
 * scraper collects a partial unzipped file.
 * an hour later, the test of course complete, and is gzipped on the node disk.
 * scraper collects the complete zipped file.
 * scraper does not delete previously synced files so both the partial-unzipped and complete-zipped file are both present.
 * the etl_worker sees the partial-unzipped file first and ignores the complete file.

Is this scenario possible?

I think we should always prefer the .gz file.

---

*[parser/ndt_test.go, line 65 at r1](https://reviewable.io:443/reviews/m-lab/etl/118#-KlzKjTYRzluCmWSf2NU:-KlzKjTZ-PJgOeKN4hvY:boqdse7) ([raw file](https://github.com/m-lab/etl/blob/f9f897d01e480ab8c773a85669032177400b6e45/parser/ndt_test.go#L65)):*
> ```Go
> 	// Load test data.
> 	ins := &inMemoryInserter{}
> 	parser.TmpDir = "./"
> ```

We can also remove the `tmpfs` mount configuration in our app engine yaml files: https://github.com/m-lab/etl/blob/integration/cmd/etl_worker/app-ndt.yaml#L22

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/118#-:-KlzOdgPpv5bizCZVj2U:bhs98zy)*

**Pull request merged**
