### PR TITLE
Ndt annotation refactoring

### PR DESCRIPTION
**Pull request by gfr10598**
Adds environment flag to enable annotation.
Pulls metadata handling into package geo.
Decouples geo from schema package by:
  * Pulling NDT specific code into ndt_annotation.go (and ..._test.go)
  * Commenting out PT and SS specific code that are not yet enabled.

Improves test coverage
Removes some dead code.
  * NullInserter, PrintingInserter
  * Some Geo annotator code that was never used.

Adds a netClient with a 1 second timeout for annotation requests, to avoid blocking the pipeline if annotator is slow.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/250)

### CODE REVIEW

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[bq/insert.go, line 260 at r10](https://reviewable.io:443/reviews/m-lab/etl/250#-KvCvko-_u2s7z4tpCDY:-KvCvko-_u2s7z4tpCDZ:b-w8zuig) ([raw file](https://github.com/m-lab/etl/blob/9746023c0f67990b17f1b4a8066fae2d6ea16b16/bq/insert.go#L260)):*
> ```Go
> //----------------------------------------------------------------------------
> 
> type NullInserter struct {
> ```

Add documentation for why you add this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/250)*

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[geo/metadata.go, line 214 at r10](https://reviewable.io:443/reviews/m-lab/etl/250#-KvCwe_QZM_LUsxmu8Sb:-KvCwe_QZM_LUsxmu8Sc:b2s2ria) ([raw file](https://github.com/m-lab/etl/blob/c1401ab48fee48b2c8d2adecbea8dd3e1dfd9eb4/geo/metadata.go#L214)):*
> ```Go
> 	}
> }
> */
> ```

What is this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/250)*

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[geo/metadata.go, line 64 at r10](https://reviewable.io:443/reviews/m-lab/etl/250#-KvCx4YJ3MJV1ovlCo9U:-KvCx4YJ3MJV1ovlCo9V:b76hgkq) ([raw file](https://github.com/m-lab/etl/blob/c1401ab48fee48b2c8d2adecbea8dd3e1dfd9eb4/geo/metadata.go#L64)):*
> ```Go
> // Web100ConnectionSpecification struct and a timestamp. With these,
> // it will fetch the appropriate metadata and add it to the hop struct
> // referenced by the pointer.
> ```

If this code will be used by multiple parsers, maybe util.go is a good place for it? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/250)*

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[geo/metadata.go, line 214 at r10](https://reviewable.io:443/reviews/m-lab/etl/250#-KvCwe_QZM_LUsxmu8Sb:-KvCxFfOHm523_LPZDZP:bds9hgt) ([raw file](https://github.com/m-lab/etl/blob/c1401ab48fee48b2c8d2adecbea8dd3e1dfd9eb4/geo/metadata.go#L214)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

What is this?
</blockquote></details>

Ignore this one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/250)*

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[parser/disco_test.go, line 23 at r10](https://reviewable.io:443/reviews/m-lab/etl/250#-KvCynkxFiXLN0m0udZ0:-KvCynkxFiXLN0m0udZ1:b-fezvu4) ([raw file](https://github.com/m-lab/etl/blob/9746023c0f67990b17f1b4a8066fae2d6ea16b16/parser/disco_test.go#L23)):*
> ```Go
> // PrintingInserter prints out the items passed in.
> // Inject into Parser for testing.
> type PrintingInserter struct {
> ```

NullInserter is not related to geo location at all, right?

If so, you can make a new&smaller PR, just with NullInserter, and I can stamp it quickly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/250)*

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[parser/ndt_annotation.go, line 41 at r10](https://reviewable.io:443/reviews/m-lab/etl/250#-KvD0ioAMBYvzlIr2Zyp:-KvD0ioAMBYvzlIr2Zyq:b-7fulcq) ([raw file](https://github.com/m-lab/etl/blob/c1401ab48fee48b2c8d2adecbea8dd3e1dfd9eb4/parser/ndt_annotation.go#L41)):*
> ```Go
> // annotates the connection spec with metadata associated with each IP
> // Address. It will either sucessfully add the metadata or fail
> // silently and make no changes.
> ```

Better remove NDT from the func name, because sidestream has the same connection spec and can reuse this code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/250)*

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[parser/ndt_test.go, line 299 at r10](https://reviewable.io:443/reviews/m-lab/etl/250#-KvD3EPW9LpyvLViP2Pa:-KvD3EPW9LpyvLViP2Pb:b-jgps11) ([raw file](https://github.com/m-lab/etl/blob/c1401ab48fee48b2c8d2adecbea8dd3e1dfd9eb4/parser/ndt_test.go#L299)):*
> ```Go
> 			if !reflect.DeepEqual(*got, tt.want) {
> 				t.Errorf("ParseNDTFileName() = %v, want %v", got, &tt.want)
> 				fmt.Printf("%+v\n", tt.want)
> ```

Remove those debug code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/250)*

**Comment by gfr10598** [comment]
*[parser/ndt_test.go, line 299 at r10](https://reviewable.io:443/reviews/m-lab/etl/250#-KvD3EPW9LpyvLViP2Pa:-KvDQoARZ_w66N9YFQJ6:bw1obeq) ([raw file](https://github.com/m-lab/etl/blob/c1401ab48fee48b2c8d2adecbea8dd3e1dfd9eb4/parser/ndt_test.go#L299)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Remove those debug code?
</blockquote></details>

They only trigger if the test fails, and are helpful in debugging.  I'd prefer to leave them for use in future test development.  (These tests are not complete yet).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/250)*

**Comment by gfr10598** [comment]
*[bq/insert.go, line 260 at r10](https://reviewable.io:443/reviews/m-lab/etl/250#-KvCvko-_u2s7z4tpCDY:-KvDR-m1leMsyHOcl3ih:bio85y8) ([raw file](https://github.com/m-lab/etl/blob/9746023c0f67990b17f1b4a8066fae2d6ea16b16/bq/insert.go#L260)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Add documentation for why you add this?
</blockquote></details>

It was previously used for some unit tests that no longer exist (I think).  It is used now only by PrintingInserter, which is also unused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/250)*

**Comment by gfr10598** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r8.
Review status: 2 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[geo/metadata.go, line 64 at r10](https://reviewable.io:443/reviews/m-lab/etl/250#-KvCx4YJ3MJV1ovlCo9U:-KvDQ4J1kmFO4H_TDgp1:b-g8mzkt) ([raw file](https://github.com/m-lab/etl/blob/c1401ab48fee48b2c8d2adecbea8dd3e1dfd9eb4/geo/metadata.go#L64)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

If this code will be used by multiple parsers, maybe util.go is a good place for it? 
</blockquote></details>

Agree.  Let's figure out how to do that later.  I've added a TODO.

---

*[geo/metadata.go, line 214 at r10](https://reviewable.io:443/reviews/m-lab/etl/250#-KvCwe_QZM_LUsxmu8Sb:-KvDRDzpRK77WMXLsMI4:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/c1401ab48fee48b2c8d2adecbea8dd3e1dfd9eb4/geo/metadata.go#L214)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Ignore this one
</blockquote></details>

Done.

---

*[parser/disco_test.go, line 23 at r10](https://reviewable.io:443/reviews/m-lab/etl/250#-KvCynkxFiXLN0m0udZ0:-KvDQZ_SmPbAvquFDGC5:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/9746023c0f67990b17f1b4a8066fae2d6ea16b16/parser/disco_test.go#L23)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

NullInserter is not related to geo location at all, right?

If so, you can make a new&smaller PR, just with NullInserter, and I can stamp it quickly.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/250)*

**Pull request closed without merging**
