### PR TITLE
Add parser for scamper1 datatype

### PR DESCRIPTION
**Pull request by cristinaleonr**
Scamper1 parsing output
```json
{
  "ID": "ndt-vfhzg_1630559948_0000000000024BD6",
  "Parser": {
    "Version": "local development",
    "Time": "2021-09-15T02:02:53.944790299Z",
    "ArchiveURL": "gs://archive-mlab-staging/ndt/scamper1/2021/09/06/20210906T003000.489493Z-scamper1-mlab4-bru01-ndt.tgz",
    "Filename": "2021/09/06/20210906T000000Z_ndt-vfhzg_1630559948_0000000000024BD6.jsonl",
    "Priority": 0,
    "GitCommit": "uninitialized"
  },
  "Date": "2021-09-06",
  "Raw": {
    "Metadata": {
      "UUID": "ndt-vfhzg_1630559948_0000000000024BD6",
      "TracerouteCallerVersion": "d84ea3d",
      "CachedResult": true,
      "CachedUUID": "ndt-vfhzg_1630559948_0000000000024B27"
    },
    "CycleStart": {
      "type": "cycle-start",
      "list_name": "default",
      "id": 0,
      "hostname": "ndt-vfhzg",
      "start_time": 1630885980
    },
    "Tracelb": {
      "Type": "tracelb",
      "Version": "0.1",
      "Userid": 0,
      "Method": "icmp-echo",
      "Src": "195.89.146.178",
      "Dst": "34.139.254.27",
      "Start": {
        "sec": 1630885980,
        "usec": 569320
      },
      "probe_size": 44,
      "Firsthop": 1,
      "Attempts": 3,
      "Confidence": 95,
      "Tos": 0,
      "Gaplimit": 0,
      "wait_timeout": 5,
      "wait_probe": 150,
      "Probec": 133,
      "probec_max": 3000,
      "Nodec": 11,
      "Linkc": 11,
      "Nodes": [
        {
          "hop_id": "20210905_ndt-vfhzg_195.89.146.129",
          "Addr": "195.89.146.129",
          "Name": "xe-11-0-1-xcr1.brx.cw.net",
          "q_ttl": 1,
          "Linkc": 1,
          "Links": [
            {
              "Links": [
                {
                  "addr": "195.2.16.254",
                  "probes": [
                    {
                      "tx": {
                        "sec": 1630885980,
                        "usec": 719881
                      },
                      "replyc": 1,
                      "ttl": 2,
                      "attempt": 0,
                      "flowid": 1,
                      "replies": [
                        {
                          "rx": {
                            "sec": 1630885980,
                            "usec": 723936
                          },
                          "ttl": 253,
                          "rtt": 4.055,
                          "icmp_type": 11,
                          "icmp_code": 0,
                          "icmp_q_tos": 0,
                          "icmp_q_ttl": 1
                        }
                      ]
                    },
                  ]
                }
              ]
            }
          ]
        },
      ]
    },
    "CycleStop": {
      "type": "cycle-stop",
      "list_name": "default",
      "id": 0,
      "hostname": "ndt-vfhzg",
      "stop_time": 1630886350
    }
  }
}

```

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/1021)

### CODE REVIEW

**Comment by SaiedKazemi** [comment]
___
*[parser/scamper1.go, line 1 at r2](https://reviewable.io/reviews/m-lab/etl/1021#-MknHBVY25AFXXmQ4L1m:-MknHBVY25AFXXmQ4L1n:b-1xxnlw) ([raw file](https://github.com/m-lab/etl/blob/146eb4994c750a408f7ca80593fb86cdfa653a88/parser/scamper1.go#L1)):*
> ```Go
> package parser
> ```

Although this is not directly related to this PR, I noticed that package comment lines in `{disco,parser,pt}.go` files need rewording.  Specifically, they still refer to `Paris Traceroute` but not to `scamper`.

**Comment by SaiedKazemi** [comment]
___
*[parser/scamper1.go, line 19 at r2](https://reviewable.io/reviews/m-lab/etl/1021#-MknKCV-7YmUgPPbLmoD:-MknKCV-7YmUgPPbLmoE:b8qtmyq) ([raw file](https://github.com/m-lab/etl/blob/146eb4994c750a408f7ca80593fb86cdfa653a88/parser/scamper1.go#L19)):*
> ```Go
> 
> //=====================================================================================
> //                       Scamper1 Parser
> ```

Should this be scamper1 (i.e., lower-case s)?

**Comment by SaiedKazemi** [comment]
___
*[parser/scamper1.go, line 106 at r2](https://reviewable.io/reviews/m-lab/etl/1021#-MknKN_-8jK3Ea3-kKsm:-MknKN_-8jK3Ea3-kKsn:bfsn25o) ([raw file](https://github.com/m-lab/etl/blob/146eb4994c750a408f7ca80593fb86cdfa653a88/parser/scamper1.go#L106)):*
> ```Go
> }
> 
> // ParseAndInsert decodes the Scamper1 data and inserts it into BQ.
> ```

Should this be scamper1?

**Comment by SaiedKazemi** [comment]
___
*[parser/scamper1.go, line 150 at r2](https://reviewable.io/reviews/m-lab/etl/1021#-MknKT8GCbsFOODbynXF:-MknKT8GCbsFOODbynXG:bfsn25o) ([raw file](https://github.com/m-lab/etl/blob/146eb4994c750a408f7ca80593fb86cdfa653a88/parser/scamper1.go#L150)):*
> ```Go
> 
> // NB: These functions are also required to complete the etl.Parser interface
> // For Scamper1, we just forward the calls to the Inserter.
> ```

Should this be scamper1?

**Comment by SaiedKazemi** [comment]
___
*[parser/scamper1.go, line 113 at r2](https://reviewable.io/reviews/m-lab/etl/1021#-MknL07U2tRFbpSH_FpI:-MknL07U2tRFbpSH_FpJ:b-7yhpnz) ([raw file](https://github.com/m-lab/etl/blob/146eb4994c750a408f7ca80593fb86cdfa653a88/parser/scamper1.go#L113)):*
> ```Go
> 	scamperOutput, err := parser.ParseTraceroute(rawContent)
> 	if err != nil {
> 		return fmt.Errorf("corrupted scamper1 file: %s", err)
> ```

I suggest that error messages here and elsewhere follow a consistent pattern of "failed to ..." so that they are a lot easier to be parsed in the logs.  This one, for example, could say "failed to parse scamper1 file: %v".  (You can look at traceroute-caller error messages to see other examples.)

**Comment by SaiedKazemi** [comment]
___
*[parser/scamper1.go, line 152 at r2](https://reviewable.io/reviews/m-lab/etl/1021#-MknNxMd-R39uWbiqjmf:-MknNxMd-R39uWbiqjmg:bpcqtiq) ([raw file](https://github.com/m-lab/etl/blob/146eb4994c750a408f7ca80593fb86cdfa653a88/parser/scamper1.go#L152)):*
> ```Go
> // For Scamper1, we just forward the calls to the Inserter.
> 
> func (p *Scamper1Parser) Flush() error {
> ```

Exported method Scamper1Parser.Flush should have comment or be unexported.

**Comment by SaiedKazemi** [comment]
___
*[parser/scamper1.go, line 156 at r2](https://reviewable.io/reviews/m-lab/etl/1021#-MknO6o4BLs4QX0rjHl3:-MknO6o4BLs4QX0rjHl4:b2nreh6) ([raw file](https://github.com/m-lab/etl/blob/146eb4994c750a408f7ca80593fb86cdfa653a88/parser/scamper1.go#L156)):*
> ```Go
> }
> 
> func (p *Scamper1Parser) TableName() string {
> ```

Same as above.

**Comment by SaiedKazemi** [comment]
___
*[parser/scamper1.go, line 160 at r2](https://reviewable.io/reviews/m-lab/etl/1021#-MknO9VbEBMU8YZwWwnT:-MknO9Vc3wWYkGAAljO2:b2nreh6) ([raw file](https://github.com/m-lab/etl/blob/146eb4994c750a408f7ca80593fb86cdfa653a88/parser/scamper1.go#L160)):*
> ```Go
> }
> 
> func (p *Scamper1Parser) FullTableName() string {
> ```

Same as above.

**Comment by SaiedKazemi** [comment]
Package testing fails for me:

(sandbox-cristinaleon-scamper1-parser)$ go test ./parser
2021/09/29 14:12:30 Prometheus metrics in tcp-info.metrics are registered.
2021/09/29 14:12:30 WARNING: failed to read toplevel.yaml
2021/09/29 14:12:30 WARNING: no file for schema field description: TCPRow.yaml
2021/09/29 14:12:30 pipe.go:715: # Script: unpacking testdata files
2021/09/29 14:12:30 pipe.go:522:     tar -C testdata -xvf testdata/pt-files.tar.gz
2021/09/29 14:12:30 pipe.go:522:     tar -C testdata -xvf testdata/web100-files.tar.gz
2021/09/29 14:12:30 pipe.go:522:     tar -C testdata -xvf testdata/sidestream-files.tar.gz
2021/09/29 14:12:30 row.go:247: empty client annotation response
2021/09/29 14:12:30 row.go:325: annotation:  Annotation error
2021/09/29 14:12:30 annotation.go:94: invalid character '/' after object key:value pair
2021/09/29 14:12:30 base.go:41: *parser_test.BadRow not Annotatable
2021/09/29 14:12:31 ndt.go:167: Warning: high row commit errors: 0 / 2
2021/09/29 14:12:31 globals.go:194: Unable to extract IATA code from 
2021/09/29 14:12:31 globals.go:194: Unable to extract IATA code from 
2021/09/29 14:12:31 globals.go:194: Unable to extract IATA code from testdata/PT/20171208T00:00:04Z-35.188.101.1-40784-173.205.3.38-9090.paris
2021/09/29 14:12:31 globals.go:194: Unable to extract IATA code from testdata/PT/20171208T00:00:04Z-37.220.21.130-5667-173.205.3.43-42487.paris
2021/09/29 14:12:31 globals.go:194: Unable to extract IATA code from testdata/PT/20171208T00:00:14Z-139.60.160.135-2023-173.205.3.44-1101.paris
2021/09/29 14:12:31 globals.go:194: Unable to extract IATA code from testdata/PT/20171208T00:00:14Z-76.227.226.149-37156-173.205.3.37-52156.paris
2021/09/29 14:12:31 globals.go:194: Unable to extract IATA code from testdata/PT/20171208T22:03:54Z-104.198.139.160-60574-163.22.28.37-7999.paris
2021/09/29 14:12:31 globals.go:194: Unable to extract IATA code from testdata/PT/20171208T22:03:59Z-139.60.160.135-1519-163.22.28.44-1101.paris
cannot load test data
--- FAIL: TestScamper1Parser_ParseAndInsert (0.00s)
    scamper1_test.go:48: Scamper1Parser.ParseAndInsert(): different rows - Raw.Tracelb.Nodes.slice[0].HopID: 20190824_ndt-plh7v_2001:550:1b01:1::1 != 20190825_ndt-plh7v_2001:550:1b01:1::1
        Raw.Tracelb.Nodes.slice[1].HopID: 20190824_ndt-plh7v_2001:4888:3f:6092:3a2:26:0:1 != 20190825_ndt-plh7v_2001:4888:3f:6092:3a2:26:0:1
2021/09/29 14:12:31 task.go:143: WARNING empty test test:test 
2021/09/29 14:12:31 task.go:179: Processed 364 files, 0 nil data, 362 rows committed, 0 failed, from gs://fake-archive/ndt/tcpinfo/2019/05/16/20190516T013026.744845Z-tcpinfo-mlab4-arn02-ndt.tgz into test_suffix
2021/09/29 14:12:31 task.go:179: Processed 364 files, 0 nil data, 362 rows committed, 0 failed, from gs://fake-archive/ndt/tcpinfo/2019/05/16/20190516T013026.744845Z-tcpinfo-mlab4-arn02-ndt.tgz into test_suffix
2021/09/29 14:12:31 task.go:179: Processed 364 files, 0 nil data, 362 rows committed, 0 failed, from gs://fake-archive/ndt/tcpinfo/2019/05/16/20190516T013026.744845Z-tcpinfo-mlab4-arn02-ndt.tgz into test_suffix
FAIL
FAIL	github.com/m-lab/etl/parser	0.629s
FAIL

**Review by SaiedKazemi — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1021)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

**Review by cristinaleonr — COMMENTED** [review]
Thanks for pointing this out!

As the error log shows, the test was failing because of incorrect timestamps in the HopID.
scamper1_test.go:48: Scamper1Parser.ParseAndInsert(): different rows - Raw.Tracelb.Nodes.slice[0].HopID: **20190824**_ndt-plh7v_2001:550:1b01:1::1 != **20190825**_ndt-plh7v_2001:550:1b01:1::1
Raw.Tracelb.Nodes.slice[1].HopID: **20190824**_ndt-plh7v_2001:4888:3f:6092:3a2:26:0:1 != **20190825**_ndt-plh7v_2001:4888:3f:6092:3a2:26:0:1

The reason why it was failing in some timezones (e.g., PST) and not others (e.g., EST and where the Cloud Build was run) is because the code uses the [time.Unix()](https://pkg.go.dev/time#Unix) function to generate the timestamp, which returns the local Time corresponding to the given Unix time.

I have fixed this issue by always converting the time to UTC, so the timestamp (and the test) is consistent across timezones.

A related matter is that the original timestamp logic was modeled after TRC's code for generating [timestamps](https://github.com/m-lab/traceroute-caller/blob/14d5a2d8612f60ebf2580a2c69d538e8e6ef3ca0/connectionlistener/connectionlistener.go#L101) for hop annotations. That is, as of now, the timestamp generated by TRC for the `ID` field of the `hopannotation1` data is dependent on the local machine timezone and it doesn't carry any timezone information to discern where it's coming from. One possible way to address this would be to always use UTC, like I have done. That said, I'm happy to discuss this further.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1021#-:-Mksl6uw1gO266Wqd1i7:b40j6j0)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[parser/scamper1.go, line 1 at r2](https://reviewable.io/reviews/m-lab/etl/1021#-MknHBVY25AFXXmQ4L1m:-MkscB6P4lJ67n0CQb_v:b-5l22ga) ([raw file](https://github.com/m-lab/etl/blob/146eb4994c750a408f7ca80593fb86cdfa653a88/parser/scamper1.go#L1)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Although this is not directly related to this PR, I noticed that package comment lines in `{disco,parser,pt}.go` files need rewording.  Specifically, they still refer to `Paris Traceroute` but not to `scamper`.
</blockquote></details>

I've updated the package comments in `disco.go` and `parser.go`—they were missing a lot of the newer types, not just `scamper1`.

I'm less familiar with the multiple comments regarding `Paris Traceroute` in `pt.go` so I'd prefer not to change them at this time.
___
*[parser/scamper1.go, line 19 at r2](https://reviewable.io/reviews/m-lab/etl/1021#-MknKCV-7YmUgPPbLmoD:-MkscuQdDcOJYF7R2nuY:b-655rh5) ([raw file](https://github.com/m-lab/etl/blob/146eb4994c750a408f7ca80593fb86cdfa653a88/parser/scamper1.go#L19)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Should this be scamper1 (i.e., lower-case s)?
</blockquote></details>

Sure, changed. 

The type name in the header for the other parsers is capitalized (e.g., see `annotation.go`), so I was trying to follow that convention. That said, it makes sense to use lower-case since we're trying to have more uniformity in our naming.
___
*[parser/scamper1.go, line 106 at r2](https://reviewable.io/reviews/m-lab/etl/1021#-MknKN_-8jK3Ea3-kKsm:-Mksku56CE66m3DjzQlu:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/146eb4994c750a408f7ca80593fb86cdfa653a88/parser/scamper1.go#L106)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Should this be scamper1?
</blockquote></details>

Done.
___
*[parser/scamper1.go, line 113 at r2](https://reviewable.io/reviews/m-lab/etl/1021#-MknL07U2tRFbpSH_FpI:-MkskvVbCS96bp-QDHIp:b86suyk) ([raw file](https://github.com/m-lab/etl/blob/146eb4994c750a408f7ca80593fb86cdfa653a88/parser/scamper1.go#L113)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

I suggest that error messages here and elsewhere follow a consistent pattern of "failed to ..." so that they are a lot easier to be parsed in the logs.  This one, for example, could say "failed to parse scamper1 file: %v".  (You can look at traceroute-caller error messages to see other examples.)
</blockquote></details>

Makes sense, changed.
___
*[parser/scamper1.go, line 150 at r2](https://reviewable.io/reviews/m-lab/etl/1021#-MknKT8GCbsFOODbynXF:-MkskyzT5CqVKi4NrQlR:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/146eb4994c750a408f7ca80593fb86cdfa653a88/parser/scamper1.go#L150)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Should this be scamper1?
</blockquote></details>

Done.
___
*[parser/scamper1.go, line 152 at r2](https://reviewable.io/reviews/m-lab/etl/1021#-MknNxMd-R39uWbiqjmf:-Mksl-Zt0z0BFsuHGSaR:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/146eb4994c750a408f7ca80593fb86cdfa653a88/parser/scamper1.go#L152)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Exported method Scamper1Parser.Flush should have comment or be unexported.
</blockquote></details>

Done.
___
*[parser/scamper1.go, line 156 at r2](https://reviewable.io/reviews/m-lab/etl/1021#-MknO6o4BLs4QX0rjHl3:-Mksl0N59dzKgH3KoOKu:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/146eb4994c750a408f7ca80593fb86cdfa653a88/parser/scamper1.go#L156)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[parser/scamper1.go, line 160 at r2](https://reviewable.io/reviews/m-lab/etl/1021#-MknO9VbEBMU8YZwWwnT:-Mksl1YaBfrfR-qQd8Ig:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/146eb4994c750a408f7ca80593fb86cdfa653a88/parser/scamper1.go#L160)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
Thanks for the suggestion, but let me look into this issue today and share my thoughts with you.  We need a robust solution that won't have to change going forward.

**Review by SaiedKazemi — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1021)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
