### PR TITLE
Add NDT5ResultRowStandardColumns

### PR DESCRIPTION
**Pull request by gfr10598**
We want to make NDT5 conform to standard columns, but doing so directly would break the legacy parser pipeline.

This adds a V1 version that implements standard columns.

The intent is then to use the original for legacy parsing, and the new one for Gardener 2.0 parsing.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/956)

### CODE REVIEW

**Review by yachang — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/956)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @yachang)

___
*[schema/ndt5_result.go, line 52 at r1](https://reviewable.io/reviews/m-lab/etl/956#-MHDMXjy9VIF5Icz-Psk:-MHDMXjy9VIF5Icz-Psl:buc890a) ([raw file](https://github.com/m-lab/etl/blob/876fa257c2965c2209a1bc34b363a2eeaeac5bf6/schema/ndt5_result.go#L52)):*
> ```Go
> 	Raw    data.NDT5Result `bigquery:"raw"`
> 
> 	// These will be populated by the join with tthe annoator data.
> ```

typo "tthe"

**Review by yachang — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/956#-:-MHDMbhv0x8gsL6Cvf2E:bg7igkv)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @yachang)

**Review by yachang — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/956#-:-MHDMdpd7MN3EA85oD4I:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598 and @yachang)

**Review by yachang — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/956#-:-MHIRE70BLPrAeoy1gJV:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598)

**Review by yachang — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/956#-:-MHIRGK7AFxe-I2kw8XA:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598)

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/956)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @yachang)

___
*[schema/ndt5_result.go, line 52 at r1](https://reviewable.io/reviews/m-lab/etl/956#-MHDMXjy9VIF5Icz-Psk:-MHDkM5T2ylnWPXbROeU:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/876fa257c2965c2209a1bc34b363a2eeaeac5bf6/schema/ndt5_result.go#L52)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

typo "tthe"
</blockquote></details>

Done.

**Review by gfr10598 — COMMENTED** [review]
It is necessary to manually delete the tmp_ndt.ndt5 and raw_ndt.ndt5 tables prior to deployment.  I have done this for mlab-sandbox, and will do it shortly for mlab-staging.  It is not necessary for mlab-oti, as those tables do not exist yet.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/956#-:-MHMpgQu6Szg9k4cofI7:b-rpmdfh)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @yachang)

**Pull request merged**
