### PR TITLE
Add changes for scamper1 schema definition

### PR DESCRIPTION
**Pull request by cristinaleonr**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/1020)

### CODE REVIEW

**Review by gfr10598 — CHANGES_REQUESTED** [review]
:lgtm: after resolving a few suggestions.

> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1020#-:-Mk7InVEDgNl9PUl-9QZ:btb00g)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[cmd/generate_schema_docs/generate_schema_docs, line 0 at r1](https://reviewable.io/reviews/m-lab/etl/1020#-Mk7I_JkCVrtW6zWcZvL:-Mk7I_JlEB7PcdVJeWEg:bcwwej1) ([raw file](https://github.com/m-lab/etl/blob/8f194cb488fa5661bf74a19ae3f46661d55951be/cmd/generate_schema_docs/generate_schema_docs#L0)):*
Same comment about binary in git.
If these need to be in git, then should probably add an explanation in a README.md file.
___
*[cmd/generate_schema_docs/main_test.go, line 37 at r1](https://reviewable.io/reviews/m-lab/etl/1020#-Mk7HhMT-vuriRgrALOj:-Mk7HhMT-vuriRgrALOk:bb6wk0y) ([raw file](https://github.com/m-lab/etl/blob/8f194cb488fa5661bf74a19ae3f46661d55951be/cmd/generate_schema_docs/main_test.go#L37)):*
> ```Go
> 	main() // no crash == working
> 
> 	files := [4]string{
> ```

Good
___
*[cmd/update-schema/update-schema, line 0 at r1](https://reviewable.io/reviews/m-lab/etl/1020#-Mk7HLOp2sfhMmidXzlJ:-Mk7HLOp2sfhMmidXzlK:b-3igdzx) ([raw file](https://github.com/m-lab/etl/blob/8f194cb488fa5661bf74a19ae3f46661d55951be/cmd/update-schema/update-schema#L0)):*
Doesn't seem like this binary should be here.  Check with Stephen, but IMO it should be removed from git.
___
*[schema/scamper1.go, line 1 at r1](https://reviewable.io/reviews/m-lab/etl/1020#-Mk7GpszAud7NwUuQs83:-Mk7GpszAud7NwUuQs84:b-mhtjvt) ([raw file](https://github.com/m-lab/etl/blob/8f194cb488fa5661bf74a19ae3f46661d55951be/schema/scamper1.go#L1)):*
> ```Go
> package schema
> ```

Very nice.
nit: Please add a header describing the reason for mixing structs from trc and new BQ structs.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1020)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598)

___
*[schema/scamper1.go, line 1 at r1](https://reviewable.io/reviews/m-lab/etl/1020#-Mk7GpszAud7NwUuQs83:-Mk7_EmJ5LONRRoqKVBP:b627mkz) ([raw file](https://github.com/m-lab/etl/blob/8f194cb488fa5661bf74a19ae3f46661d55951be/schema/scamper1.go#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Very nice.
nit: Please add a header describing the reason for mixing structs from trc and new BQ structs.
</blockquote></details>

Thanks, added a comment at the top.
___
*[cmd/generate_schema_docs/generate_schema_docs, line  at r1](https://reviewable.io/reviews/m-lab/etl/1020#-Mk7I_JkCVrtW6zWcZvL:-Mk7_7efE7CZAxy2-FZ_:bss4a2b) ([raw file](https://github.com/m-lab/etl/blob/8f194cb488fa5661bf74a19ae3f46661d55951be/cmd/generate_schema_docs/generate_schema_docs#L)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Same comment about binary in git.
If these need to be in git, then should probably add an explanation in a README.md file.
</blockquote></details>

Removed.
___
*[cmd/update-schema/update-schema, line  at r1](https://reviewable.io/reviews/m-lab/etl/1020#-Mk7HLOp2sfhMmidXzlJ:-Mk7_9zp10JjsDbRSwSP:bss4a2b) ([raw file](https://github.com/m-lab/etl/blob/8f194cb488fa5661bf74a19ae3f46661d55951be/cmd/update-schema/update-schema#L)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Doesn't seem like this binary should be here.  Check with Stephen, but IMO it should be removed from git.
</blockquote></details>

Removed.

**Review by stephen-soltesz — COMMENTED** [review]
one small drive-by comment.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1020#-:-MkHNihk8AEieGaQQOaC:b-cxglr7)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr and @gfr10598)

___
*[schema/descriptions/Scamper1Row.yaml, line 1 at r2](https://reviewable.io/reviews/m-lab/etl/1020#-MkHN_RWAt3ISrj4e2_j:-MkHN_RWAt3ISrj4e2_k:b-rx2f1f) ([raw file](https://github.com/m-lab/etl/blob/6c3eb0fc72478c10b84c689f01bcff09fac1079c/schema/descriptions/Scamper1Row.yaml#L1)):*
> ```YAML
> raw.Tracelb.Nodes.UUID:
> ```

Is this field what we describe in the design doc as "hop id"? If so, would it be possible to name this `HopID` or similar to prevent confusion with tcp connection UUIDs?

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1020)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @stephen-soltesz)

___
*[schema/descriptions/Scamper1Row.yaml, line 1 at r2](https://reviewable.io/reviews/m-lab/etl/1020#-MkHN_RWAt3ISrj4e2_j:-MkHghlN4kiIxAFNXibo:bf86zf5) ([raw file](https://github.com/m-lab/etl/blob/6c3eb0fc72478c10b84c689f01bcff09fac1079c/schema/descriptions/Scamper1Row.yaml#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this field what we describe in the design doc as "hop id"? If so, would it be possible to name this `HopID` or similar to prevent confusion with tcp connection UUIDs?
</blockquote></details>

Yes, it is. Done.

**Review by gfr10598 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1020)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

**Pull request merged**
