### PR TITLE
Add field descriptions for scamper1 datatype

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/1057)

### CODE REVIEW

**Comment by SaiedKazemi** [comment]
@cristinaleonr I forgot to mention in the pull request that the file isn't fully complete yet because I couldn't find descriptions for everything in samper header files.  Therefore, please consider this as the first step toward providing descriptions for all fields as we learn more ourselves.
@stephen-soltesz Just FYI...

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1057)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[schema/descriptions/Scamper1Row.yaml, line 48 at r1](https://reviewable.io/reviews/m-lab/etl/1057#-MwlSVoPCnVUDD3AYCCr:-MwlSVoPCnVUDD3AYCCs:b-7zrk6w) ([raw file](https://github.com/m-lab/etl/blob/a4419e8eb8ef249d89da6152bd840806a283060f/schema/descriptions/Scamper1Row.yaml#L48)):*
> ```YAML
>   Description:
> raw.Tracelb.method:
>   Description: The trace method use by tracelb (icmp-echo).
> ```

Used*
___
*[schema/descriptions/Scamper1Row.yaml, line 70 at r1](https://reviewable.io/reviews/m-lab/etl/1057#-MwlSb4F4p4CFdnA4H9v:-MwlSb4F4p4CFdnA4H9w:b-1h8lr5) ([raw file](https://github.com/m-lab/etl/blob/a4419e8eb8ef249d89da6152bd840806a283060f/schema/descriptions/Scamper1Row.yaml#L70)):*
> ```YAML
>   Description: Type-of-service byte to use.
> raw.Tracelb.gaplimit:
>   Description: Max consecutive unresp. hops.
> ```

What is "unresp."?
___
*[schema/descriptions/Scamper1Row.yaml, line 74 at r1](https://reviewable.io/reviews/m-lab/etl/1057#-MwlSjM93nAKLuRxutji:-MwlSjM93nAKLuRxutjj:bnl5nz) ([raw file](https://github.com/m-lab/etl/blob/a4419e8eb8ef249d89da6152bd840806a283060f/schema/descriptions/Scamper1Row.yaml#L74)):*
> ```YAML
>   Description: Seconds to wait before timeout.
> raw.Tracelb.wait_probe:
>   Description: min. inter-probe time per TTL.
> ```

Should this be capitalized like the others?
___
*[schema/descriptions/Scamper1Row.yaml, line 132 at r1](https://reviewable.io/reviews/m-lab/etl/1057#-MwlSvAVED17fKm5TXC-:-MwlSvAVED17fKm5TXC0:b-k7mm7q) ([raw file](https://github.com/m-lab/etl/blob/a4419e8eb8ef249d89da6152bd840806a283060f/schema/descriptions/Scamper1Row.yaml#L132)):*
> ```YAML
>   Description: ICMP type of the reply.
> raw.Tracelb.nodes.links.Links.Probes.Replies.icmp_code:
>   Description: ICMP code the reply.
> ```

Should this be "ICMP code **of** the reply."?

**Comment by SaiedKazemi** [comment]
___
*[schema/descriptions/Scamper1Row.yaml, line 70 at r1](https://reviewable.io/reviews/m-lab/etl/1057#-MwlSb4F4p4CFdnA4H9v:-Mx1Cmht0CorkDn7fco7:b9kse1y) ([raw file](https://github.com/m-lab/etl/blob/a4419e8eb8ef249d89da6152bd840806a283060f/schema/descriptions/Scamper1Row.yaml#L70)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

What is "unresp."?
</blockquote></details>

I think it is short for unresponsive, which I changed to.

**Comment by SaiedKazemi** [comment]
___
*[schema/descriptions/Scamper1Row.yaml, line 74 at r1](https://reviewable.io/reviews/m-lab/etl/1057#-MwlSjM93nAKLuRxutji:-Mx1Cz1Z6HIXBQSLHmn1:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a4419e8eb8ef249d89da6152bd840806a283060f/schema/descriptions/Scamper1Row.yaml#L74)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Should this be capitalized like the others?
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
___
*[schema/descriptions/Scamper1Row.yaml, line 48 at r1](https://reviewable.io/reviews/m-lab/etl/1057#-MwlSVoPCnVUDD3AYCCr:-Mx1Cloy2Bh-8k62mGr7:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a4419e8eb8ef249d89da6152bd840806a283060f/schema/descriptions/Scamper1Row.yaml#L48)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Used*
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
___
*[schema/descriptions/Scamper1Row.yaml, line 132 at r1](https://reviewable.io/reviews/m-lab/etl/1057#-MwlSvAVED17fKm5TXC-:-Mx1D0pk--CDm5w0IJEa:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a4419e8eb8ef249d89da6152bd840806a283060f/schema/descriptions/Scamper1Row.yaml#L132)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Should this be "ICMP code **of** the reply."?
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
Thank you @cristinaleonr for your careful review.  I fixed the typos.  PTAL.

**Review by cristinaleonr — APPROVED** [review]
Thanks! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1057#-:-Mx1EKIu38ZPzIWATkuM:b6duv8n)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
