### PR TITLE
Add schema for pcap index

### PR DESCRIPTION
**Pull request by cristinaleonr**
- Added new pcap datatype definition to [m-lab/etl/schema](https://github.com/m-lab/etl/tree/master/schema)
- Added pcap table creation to [update-schema](https://github.com/m-lab/etl/tree/master/cmd/update-schema)
- Added descriptions for PCAPRow schema

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/1009)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1009)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[schema/pcap.go, line 9 at r1](https://reviewable.io/reviews/m-lab/etl/1009#-Mf4kBSx58_Wz9Et-SpM:-Mf4kBSx58_Wz9Et-SpN:b-44sk4q) ([raw file](https://github.com/m-lab/etl/blob/2ad44774022c1c7bd6053bfe2a5c794726305280/schema/pcap.go#L9)):*
> ```Go
> )
> 
> type PCAPRow struct {
> ```

Please add a simple docstring for this type.  Does VS Code report "golint" warning? (In my interface it's a yellow curvy line under the type name).
___
*[schema/descriptions/PCAPRow.yaml, line 1 at r1](https://reviewable.io/reviews/m-lab/etl/1009#-Mf4kh1kE-mV1Qj8yPzE:-Mf4kh1kE-mV1Qj8yPzF:b-9xe659) ([raw file](https://github.com/m-lab/etl/blob/2ad44774022c1c7bd6053bfe2a5c794726305280/schema/descriptions/PCAPRow.yaml#L1)):*
> ```YAML
> ID:
> ```

Hmm. It looks like all the fields used in the PCAPRow struct are defined now in the toplevel.yaml ... I think we can keep this file as a reminder, but I think it can be empty without losing any behavior we need.
___
*[schema/descriptions/toplevel.yaml, line 11 at r1](https://reviewable.io/reviews/m-lab/etl/1009#-Mf4kvRr2AXwYW1zWzNc:-Mf4kvRr2AXwYW1zWzNd:b-9755fn) ([raw file](https://github.com/m-lab/etl/blob/2ad44774022c1c7bd6053bfe2a5c794726305280/schema/descriptions/toplevel.yaml#L11)):*
> ```YAML
>   Description: Version of the parser that processed this row.
> 
> id:
> ```

Thank you!

**Review by stephen-soltesz — COMMENTED** [review]
also, FYI: @gfr10598 .

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1009#-:-Mf4lDxd04pxjUgavR3R:b-xir90s)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

**Comment by cristinaleonr** [comment]
___
*[schema/pcap.go, line 9 at r1](https://reviewable.io/reviews/m-lab/etl/1009#-Mf4kBSx58_Wz9Et-SpM:-Mf4qWXu1C1BPdubkuKW:bjw278n) ([raw file](https://github.com/m-lab/etl/blob/2ad44774022c1c7bd6053bfe2a5c794726305280/schema/pcap.go#L9)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a simple docstring for this type.  Does VS Code report "golint" warning? (In my interface it's a yellow curvy line under the type name).
</blockquote></details>

Added, thanks!

I don't see a warning. I will look into why that is.

**Comment by cristinaleonr** [comment]
___
*[schema/descriptions/PCAPRow.yaml, line 1 at r1](https://reviewable.io/reviews/m-lab/etl/1009#-Mf4kh1kE-mV1Qj8yPzE:-Mf4qyo37SLd2U5uYbR6:bp890pp) ([raw file](https://github.com/m-lab/etl/blob/2ad44774022c1c7bd6053bfe2a5c794726305280/schema/descriptions/PCAPRow.yaml#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hmm. It looks like all the fields used in the PCAPRow struct are defined now in the toplevel.yaml ... I think we can keep this file as a reminder, but I think it can be empty without losing any behavior we need.
</blockquote></details>

Makes sense. I deleted the file contents.

**Review by stephen-soltesz — APPROVED** [review]
Two small Go style nits. After that, :lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1009#-:-Mf4sTX3E1UeZkqPlGUc:bd8guzw)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[schema/pcap.go, line 9 at r3](https://reviewable.io/reviews/m-lab/etl/1009#-Mf4s0zC7Fhx-KCyoUvy:-Mf4s0zC7Fhx-KCyoUvz:b-3c6tjq) ([raw file](https://github.com/m-lab/etl/blob/d6bc94fc744a9cee3e74447a191e727c98c28b3b/schema/pcap.go#L9)):*
nit: please end Go comments with a period. 

Paraphrasing from Effective Go,

> Doc comments work best as complete sentences, ...
___
*[schema/pcap.go, line 16 at r3](https://reviewable.io/reviews/m-lab/etl/1009#-Mf4sP1O34iLf_eAwTn5:-Mf4sP1O34iLf_eAwTn6:bi4nwvw) ([raw file](https://github.com/m-lab/etl/blob/d6bc94fc744a9cee3e74447a191e727c98c28b3b/schema/pcap.go#L16)):*
> ```Go
> }
> 
> // Schema returns the Bigquery schema for Pcap
> ```

nit: please add a period here also.

**Comment by cristinaleonr** [comment]
___
*[schema/pcap.go, line 9 at r3](https://reviewable.io/reviews/m-lab/etl/1009#-Mf4s0zC7Fhx-KCyoUvy:-Mf4t7z8ChzkBfxnP2Ob:b-dtkds3) ([raw file](https://github.com/m-lab/etl/blob/d6bc94fc744a9cee3e74447a191e727c98c28b3b/schema/pcap.go#L9)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: please end Go comments with a period. 

Paraphrasing from Effective Go,

> Doc comments work best as complete sentences, ...
</blockquote></details>

Done, thanks!

**Pull request merged**
