### PR TITLE
Add "table" label to all common etl metrics

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds a new "table" label to all common ETL parser metrics.

As well, the file `etl_test.go` is renamed to `globals_test.go` to match the location of function definitions tested in `globals_test.go`. There are new tests to improve the code coverage of globals.go.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/415)

### CODE REVIEW

**Comment by yachang** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[etl/globals_test.go, line 1 at r2](https://reviewable.io:443/reviews/m-lab/etl/415#-L4gqtQpo04IZXFsoGut:-L4gqtQpo04IZXFsoGuu:b-22wzl9) ([raw file](https://github.com/m-lab/etl/blob/d01b82813bd327b0df671e5ae3f28b4f86aa98f0/etl/globals_test.go#L1)):*
> ```Go
> package etl_test
> ```

rename the package name to globals_test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/415)*

**Comment by stephen-soltesz** [comment]
PTAL?

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[etl/globals_test.go, line 1 at r2](https://reviewable.io:443/reviews/m-lab/etl/415#-L4gqtQpo04IZXFsoGut:-L4grHmuOGBr6Io5RvxT:b-hfkmoh) ([raw file](https://github.com/m-lab/etl/blob/d01b82813bd327b0df671e5ae3f28b4f86aa98f0/etl/globals_test.go#L1)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

rename the package name to globals_test
</blockquote></details>

Thank you for the note. This package name comes from the package directory `etl`. See other go files whose test package name comes from the package directory name and not the file, e.g. `parser_test` in `etl/parser/*_test.go`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/415#-:-L4grloAguve2_le4Xfm:b-833305)*

**Comment by yachang** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[etl/globals_test.go, line 97 at r2](https://reviewable.io:443/reviews/m-lab/etl/415#-L4guyQQtWZZazZnwwoh:-L4guyQQtWZZazZnwwoi:bndmyfx) ([raw file](https://github.com/m-lab/etl/blob/d01b82813bd327b0df671e5ae3f28b4f86aa98f0/etl/globals_test.go#L97)):*
> ```Go
> }
> 
> func TestDataPath_GetDataType(t *testing.T) {
> ```

Move this func to above  TestGetMetroName()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/415)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[etl/globals_test.go, line 97 at r2](https://reviewable.io:443/reviews/m-lab/etl/415#-L4guyQQtWZZazZnwwoh:-L4gwEU6IHimH2605Xg-:bwhglds) ([raw file](https://github.com/m-lab/etl/blob/d01b82813bd327b0df671e5ae3f28b4f86aa98f0/etl/globals_test.go#L97)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Move this func to above  TestGetMetroName()
</blockquote></details>

Moved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/415)*

**Comment by yachang** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[etl/globals.go, line 43 at r3](https://reviewable.io:443/reviews/m-lab/etl/415#-L4gx_vV-A8rKsUV_2_h:-L4gx_vV-A8rKsUV_2_i:bcdu7mf) ([raw file](https://github.com/m-lab/etl/blob/8e5e7c00517ea42018d77fa6730b88be87b5d228/etl/globals.go#L43)):*
> ```Go
> 	// TODO(dev) Delete unused fields.
> 	// They are comprehensive now in anticipation of using them to populate
> 	// new fields in the BQ tables.
> ```

Documentation for all these fields

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/415)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[etl/globals.go, line 43 at r3](https://reviewable.io:443/reviews/m-lab/etl/415#-L4gx_vV-A8rKsUV_2_h:-L4h0NMO1IqC0tHj9UQp:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/8e5e7c00517ea42018d77fa6730b88be87b5d228/etl/globals.go#L43)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Documentation for all these fields
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/415)*

**Comment by yachang** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 231 at r4](https://reviewable.io:443/reviews/m-lab/etl/415#-L4i5Lv3jcp3Xh1S-7hK:-L4i5Lv3jcp3Xh1S-7hL:b-9axukp) ([raw file](https://github.com/m-lab/etl/blob/27ca67d3615e89b351053429e5181381a03ce779/.travis.yml#L231)):*
> ```YAML
> # SANDBOX: before code review for development code in a specific branch.
> - provider: script
>   script: $TRAVIS_BUILD_DIR/.personalize_deploy.sh
> ```

What did personalized_deploy.sh used to do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/415)*

**Comment by yachang** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[parser/ss.go, line 193 at r4](https://reviewable.io:443/reviews/m-lab/etl/415#-L4i86c2rUhYaOopTWyr:-L4i86c2rUhYaOopTWys:bw1qs1x) ([raw file](https://github.com/m-lab/etl/blob/99746a0de5786a3969d3d4ffdb1fe5d84ae6e9f4/parser/ss.go#L193)):*
> ```Go
> func (ss *SSParser) ParseAndInsert(meta map[string]bigquery.Value, testName string, rawContent []byte) error {
> 	metrics.WorkerState.WithLabelValues(ss.TableName(), "ss").Inc()
> 	defer metrics.WorkerState.WithLabelValues(ss.TableName(), "ss").Dec()
> ```

use the const defined in globals instead of "ss" here. (and all other places)

const (
	NDT             = DataType("ndt")
	NDT_OMIT_DELTAS = DataType("ndt_nodelta") // to support larger buffer size.
	SS              = DataType("sidestream")
	PT              = DataType("traceroute")
	SW              = DataType("disco")
	INVALID         = DataType("invalid")
)

DataTypeToTable = map[DataType]string{
		NDT:     "ndt",
		SS:      "sidestream",
		PT:      "traceroute",
		SW:      "disco_test",
		INVALID: "invalid",
	}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/415)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 231 at r4](https://reviewable.io:443/reviews/m-lab/etl/415#-L4i5Lv3jcp3Xh1S-7hK:-L4ibLrHXm22aUd9PuaE:b7gxxbo) ([raw file](https://github.com/m-lab/etl/blob/27ca67d3615e89b351053429e5181381a03ce779/.travis.yml#L231)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

What did personalized_deploy.sh used to do?
</blockquote></details>

The personalize script appended the sandbox branch suffix to the appengine service name (e.g. etl-sidestream-parser from the sandbox-soltesz branch would be deployed to appengine as "etl-sidestream-parser-soltesz".)

Since TaskQueue configs must match the service name to work correctly, we never used this. So, this is not removing any functionality that we used.

---

*[parser/ss.go, line 193 at r4](https://reviewable.io:443/reviews/m-lab/etl/415#-L4i86c2rUhYaOopTWyr:-L4ienEUT2S8Oh6Lv6KJ:bgbc17c) ([raw file](https://github.com/m-lab/etl/blob/99746a0de5786a3969d3d4ffdb1fe5d84ae6e9f4/parser/ss.go#L193)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

use the const defined in globals instead of "ss" here. (and all other places)

const (
	NDT             = DataType("ndt")
	NDT_OMIT_DELTAS = DataType("ndt_nodelta") // to support larger buffer size.
	SS              = DataType("sidestream")
	PT              = DataType("traceroute")
	SW              = DataType("disco")
	INVALID         = DataType("invalid")
)

DataTypeToTable = map[DataType]string{
		NDT:     "ndt",
		SS:      "sidestream",
		PT:      "traceroute",
		SW:      "disco_test",
		INVALID: "invalid",
	}
</blockquote></details>

The goal of this PR is to enable us to monitor separate parser activity in a parser that is processing multiple data types.

Additionally, we would like to reduce our maintenance of the Grafana dashboards. There are about 8 common metrics across the three pipeline dashboards. These can be consolidated into a single "common" dashboard and switched between one another by selecting on the distinct label. The current change standardizes on the "table" label because four metric already had a table label. Using constants instead of looking up the table name at run time would mean that some metrics would have one value for the table name (maybe disco_test), and other metrics would use some other value (e.g. etl.SW). This would make query maintenance unnecessarily complex. As well, if we wanted to setup a special table for testing, this approach would make the common dashboard work just as it works for all the others.

If the advantages of this approach are unclear, let's talk after the stand-up today.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/415)*

**Comment by yachang** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 231 at r4](https://reviewable.io:443/reviews/m-lab/etl/415#-L4i5Lv3jcp3Xh1S-7hK:-L4ktz9kkNADaostXezc:b-wsvas3) ([raw file](https://github.com/m-lab/etl/blob/27ca67d3615e89b351053429e5181381a03ce779/.travis.yml#L231)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The personalize script appended the sandbox branch suffix to the appengine service name (e.g. etl-sidestream-parser from the sandbox-soltesz branch would be deployed to appengine as "etl-sidestream-parser-soltesz".)

Since TaskQueue configs must match the service name to work correctly, we never used this. So, this is not removing any functionality that we used.
</blockquote></details>

Thanks for the explanation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/415)*

**Comment by yachang** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[parser/ss.go, line 193 at r4](https://reviewable.io:443/reviews/m-lab/etl/415#-L4i86c2rUhYaOopTWyr:-L4kuescXjuZl-3DvliC:b-o2euqu) ([raw file](https://github.com/m-lab/etl/blob/99746a0de5786a3969d3d4ffdb1fe5d84ae6e9f4/parser/ss.go#L193)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The goal of this PR is to enable us to monitor separate parser activity in a parser that is processing multiple data types.

Additionally, we would like to reduce our maintenance of the Grafana dashboards. There are about 8 common metrics across the three pipeline dashboards. These can be consolidated into a single "common" dashboard and switched between one another by selecting on the distinct label. The current change standardizes on the "table" label because four metric already had a table label. Using constants instead of looking up the table name at run time would mean that some metrics would have one value for the table name (maybe disco_test), and other metrics would use some other value (e.g. etl.SW). This would make query maintenance unnecessarily complex. As well, if we wanted to setup a special table for testing, this approach would make the common dashboard work just as it works for all the others.

If the advantages of this approach are unclear, let's talk after the stand-up today.
</blockquote></details>

Please add documentation to explain why you do not use predefined const in this case, instead using hard code string like "ss" here.  

At lease define a const string with value "ss" in this file, because it appears twice, and code maintenance is going to be painful to keep them always the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/415)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[parser/ss.go, line 193 at r4](https://reviewable.io:443/reviews/m-lab/etl/415#-L4i86c2rUhYaOopTWyr:-L4l-EvlEEwhtk_rfyrV:bpli8b4) ([raw file](https://github.com/m-lab/etl/blob/99746a0de5786a3969d3d4ffdb1fe5d84ae6e9f4/parser/ss.go#L193)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Please add documentation to explain why you do not use predefined const in this case, instead using hard code string like "ss" here.  

At lease define a const string with value "ss" in this file, because it appears twice, and code maintenance is going to be painful to keep them always the same.
</blockquote></details>

Hmm, this is not as easy as we'd like:

```
../../parser/ss.go:192:50: cannot use etl.SS (type etl.DataType) as type string in argument to metrics.WorkerState.WithLabelValues
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/415)*

**Comment by yachang** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[parser/ss.go, line 193 at r4](https://beta.reviewable.io/reviews/m-lab/etl/415#-L4i86c2rUhYaOopTWyr:-L4l2Fx9B9izh7AdFjS4:bqzzse6) ([raw file](https://github.com/m-lab/etl/blob/99746a0de5786a3969d3d4ffdb1fe5d84ae6e9f4/parser/ss.go#L193)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hmm, this is not as easy as we'd like:

```
../../parser/ss.go:192:50: cannot use etl.SS (type etl.DataType) as type string in argument to metrics.WorkerState.WithLabelValues
```
</blockquote></details>

Discussed offline. Agree to a TODO to get rid of hard coded "ss"

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/etl/415)*

**Comment by yachang** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/etl/415#-:-L4l2PGn05zB0EOOQzVm:bnfp4nl)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[parser/ss.go, line 193 at r4](https://reviewable.io:443/reviews/m-lab/etl/415#-L4i86c2rUhYaOopTWyr:-L4l2bMitK5yV9FOTHum:b-hukn99) ([raw file](https://github.com/m-lab/etl/blob/99746a0de5786a3969d3d4ffdb1fe5d84ae6e9f4/parser/ss.go#L193)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Discussed offline. Agree to a TODO to get rid of hard coded "ss"
</blockquote></details>

Added TODO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/415)*

**Pull request merged**
