### PR TITLE
Add anomolies fields and fix bug.

### PR DESCRIPTION
**Pull request by gfr10598**
Fix bug in "no meta" metrics.
Add some "anomalies" fields.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/134)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/ndt.go, line 347 at r1](https://reviewable.io:443/reviews/m-lab/etl/134#-KmhahfkqbyuCdONlw2j:-KmhahfkqbyuCdONlw2k:b-so0nl9) ([raw file](https://github.com/m-lab/etl/blob/f6a254a4f4d603054412c18958c2ef4bf0ae2076/parser/ndt.go#L347)):*
> ```Go
> 	deltaFieldCount := 0
> 	snapshotCount := 0
> 	for count := 0; count < snaplog.SnapCount() && count < MAX_NUM_SNAPSHOTS; count++ {
> ```

If `valid` is false for a snaplog, does this loop apply?

---

*[parser/ndt.go, line 393 at r1](https://reviewable.io:443/reviews/m-lab/etl/134#-Kmh_FnOGzeQ3VS6VD51:-Kmh_FnOGzeQ3VS6VD52:b-2p3pfn) ([raw file](https://github.com/m-lab/etl/blob/f6a254a4f4d603054412c18958c2ef4bf0ae2076/parser/ndt.go#L393)):*
> ```Go
> 
> 	if len(deltas) > 0 {
> 		deltas[len(deltas)-1]["is_last"] = true
> ```

How is "is_last" field used? Is the final delta special in any other way?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/134)*

**Comment by stephen-soltesz** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/134)*

**Comment by gfr10598** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/ndt.go, line 347 at r1](https://reviewable.io:443/reviews/m-lab/etl/134#-KmhahfkqbyuCdONlw2j:-KmhbIIFe6xO_Xtpwnut:b32xtgn) ([raw file](https://github.com/m-lab/etl/blob/f6a254a4f4d603054412c18958c2ef4bf0ae2076/parser/ndt.go#L347)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If `valid` is false for a snaplog, does this loop apply?
</blockquote></details>

Yes.  Updating comment up above.

---

*[parser/ndt.go, line 393 at r1](https://reviewable.io:443/reviews/m-lab/etl/134#-Kmh_FnOGzeQ3VS6VD51:-Kmhc9_Sn6RZkJ41VQqY:b-ehhl7q) ([raw file](https://github.com/m-lab/etl/blob/f6a254a4f4d603054412c18958c2ef4bf0ae2076/parser/ndt.go#L393)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

How is "is_last" field used? Is the final delta special in any other way?
</blockquote></details>

Adding comment.  Not really special in any other way at the moment, but may have more semantic meaning in future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/134)*

**Comment by gfr10598** [comment]
PTAL.

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/134#-:-KmhcZHdjs46ESGRl1Ou:b-83330m)*

**Comment by stephen-soltesz** [comment]
Thank you for the extra comments. :lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/134#-:-Kmhd6P1LR6QARlMilkh:b25cmdg)*

**Pull request merged**
