### PR TITLE
Site annotator for synthetic UUID

### PR DESCRIPTION
**Pull request by gfr10598**
This adds a site annotator, using code from uuid-annotator to minimize new code.

It will be used to create synthetic uuid-annotations for legacy data.

It may also replace the server annotations currently obtained from annotation-service, but that would not have long term value.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/958)

### CODE REVIEW

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/958)* status: 0 of 1 approvals obtained

___
*[site/site.go, line 26 at r1](https://reviewable.io/reviews/m-lab/etl/958#-MHSMoJx8hZyMeDekEhT:-MHSMoJx8hZyMeDekEhU:b-xbki25) ([raw file](https://github.com/m-lab/etl/blob/f991179dc44f28c0fea50aaf2d3a96a109eac99d/site/site.go#L26)):*
> ```Go
> }
> 
> // Annotate adds site annotation for a site/machine
> ```

Global is a shortcut.  We could alternatively create the annotator and inject it explicitly.

**Review by yachang — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/958)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598)

___
*[site/site.go, line 23 at r2](https://reviewable.io/reviews/m-lab/etl/958#-MHSTp_s9zkwYwzWXSFu:-MHSTp_s9zkwYwzWXSFv:b-rrkipn) ([raw file](https://github.com/m-lab/etl/blob/f7626bb0ff0b3f3f685055d8c1b642fdf82e4ed4/site/site.go#L23)):*
> ```Go
> 
> func init() {
> 	flag.Var(&siteinfo, "siteinfo.url", "The URL for the Siteinfo JSON file containing server location and ASN metadata. gs:// and file:// schemes accepted.")
> ```

Might add a doc for valid URL samples.

**Review by yachang — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/958)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598)

___
*[site/site.go, line 110 at r2](https://reviewable.io/reviews/m-lab/etl/958#-MHSUfTk7qBxuOwfutD3:-MHSUfTk7qBxuOwfutD4:b345a9n) ([raw file](https://github.com/m-lab/etl/blob/f7626bb0ff0b3f3f685055d8c1b642fdf82e4ed4/site/site.go#L110)):*
> ```Go
> func (sa *annotator) load(ctx context.Context) error {
> 	// siteinfoAnnotation struct is used for parsing the json annotation source.
> 	type siteinfoAnnotation struct {
> ```

Move this struct out of function? Is the json Marshal/UnMarshall only happen inside this func?

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/958)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[site/site.go, line 23 at r2](https://reviewable.io/reviews/m-lab/etl/958#-MHSTp_s9zkwYwzWXSFu:-MHSV7k040tZ9zMpF9vl:b-nun43m) ([raw file](https://github.com/m-lab/etl/blob/f7626bb0ff0b3f3f685055d8c1b642fdf82e4ed4/site/site.go#L23)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Might add a doc for valid URL samples.
</blockquote></details>

Well, the doc string indicates that any file:// or gs:// are accepted.  I also want to change as little as needed from uuid-annotator/main.go, which this is derived from.
___
*[site/site.go, line 110 at r2](https://reviewable.io/reviews/m-lab/etl/958#-MHSUfTk7qBxuOwfutD3:-MHSUwfF6Zvx9xDqnAg_:b-ilmyn6) ([raw file](https://github.com/m-lab/etl/blob/f7626bb0ff0b3f3f685055d8c1b642fdf82e4ed4/site/site.go#L110)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Move this struct out of function? Is the json Marshal/UnMarshall only happen inside this func?
</blockquote></details>

It is only needed in this function.  Placing it here makes it clear that it isn't needed anywhere else.

**Review by yachang — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/958)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @yachang)

___
*[site/site.go, line 119 at r2](https://reviewable.io/reviews/m-lab/etl/958#-MHS_KQrDFKsImIRL2kV:-MHS_KQrDFKsImIRL2kW:b-7v6vot) ([raw file](https://github.com/m-lab/etl/blob/f7626bb0ff0b3f3f685055d8c1b642fdf82e4ed4/site/site.go#L119)):*
> ```Go
> 	}
> 
> 	js, err := sa.siteinfoSource.Get(ctx)
> ```

This func was defined at https://github.com/m-lab/go/blob/master/content/provider.go#L43 , right?

So it try to load a json file coded using the struct siteinfoAnnotation defined above?

Then who is the owner of this file? I mean how to make sure the owner of that file keeps using the struct siteinfoAnnotation defined here to generate new file?

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/958)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[site/site.go, line 119 at r2](https://reviewable.io/reviews/m-lab/etl/958#-MHS_KQrDFKsImIRL2kV:-MHTTLof6IKhAlDn-XYN:b-nn2ua3) ([raw file](https://github.com/m-lab/etl/blob/f7626bb0ff0b3f3f685055d8c1b642fdf82e4ed4/site/site.go#L119)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

This func was defined at https://github.com/m-lab/go/blob/master/content/provider.go#L43 , right?

So it try to load a json file coded using the struct siteinfoAnnotation defined above?

Then who is the owner of this file? I mean how to make sure the owner of that file keeps using the struct siteinfoAnnotation defined here to generate new file?
</blockquote></details>

content.Provider does not define the struct - it is determined by the file content of the siteinfo file specified by the provided URL.  I'm continuing the same pattern that Peter established in uuid-annotator, which isn't ideal, but is good enough.  If the file format changes, the parser will crash loop, which is a bit harsh, but will certainly not go unnotiiced.

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/958)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[site/site.go, line 119 at r2](https://reviewable.io/reviews/m-lab/etl/958#-MHS_KQrDFKsImIRL2kV:-MHTUUVf7dGOSLgW4owB:bsfk9kb) ([raw file](https://github.com/m-lab/etl/blob/f7626bb0ff0b3f3f685055d8c1b642fdf82e4ed4/site/site.go#L119)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

content.Provider does not define the struct - it is determined by the file content of the siteinfo file specified by the provided URL.  I'm continuing the same pattern that Peter established in uuid-annotator, which isn't ideal, but is good enough.  If the file format changes, the parser will crash loop, which is a bit harsh, but will certainly not go unnotiiced.
</blockquote></details>

Ah - I answered the wrong question.  "js" is just a byte array.  Its contents depends on the URL provided, not on content.Provider.  In this case, the URL should point to a file containing json that matches this struct.  

In uuid-annotator on our servers, this is set up in the k8s-support repo, in the k8s/daemonsets/templates.jsonnet.  That defines the uuid-annotator deployment, which includes   '-siteinfo.url=https://siteinfo.' + PROJECT_ID + '.measurementlab.net/v1/sites/annotations.json',

So, those files are published on measurement-lab.ndt, and I intend to use the same files for the parser.  That will be in a future PR.

**Review by yachang — CHANGES_REQUESTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/958#-:-MHl9YbTEMS6qEF-41vf:bg7igkv)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @yachang)

___
*[site/site.go, line 119 at r2](https://reviewable.io/reviews/m-lab/etl/958#-MHS_KQrDFKsImIRL2kV:-MHl9HTV2cabHQ-QLHAP:bsrqngd) ([raw file](https://github.com/m-lab/etl/blob/f7626bb0ff0b3f3f685055d8c1b642fdf82e4ed4/site/site.go#L119)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Ah - I answered the wrong question.  "js" is just a byte array.  Its contents depends on the URL provided, not on content.Provider.  In this case, the URL should point to a file containing json that matches this struct.  

In uuid-annotator on our servers, this is set up in the k8s-support repo, in the k8s/daemonsets/templates.jsonnet.  That defines the uuid-annotator deployment, which includes   '-siteinfo.url=https://siteinfo.' + PROJECT_ID + '.measurementlab.net/v1/sites/annotations.json',

So, those files are published on measurement-lab.ndt, and I intend to use the same files for the parser.  That will be in a future PR.

</blockquote></details>

Thanks for the clarification. Maybe add the info above as a doc here? so we can sync the proto more easily.

**Review by yachang — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/958#-:-MHl9_ky3QEoZG8iYmJm:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598 and @yachang)

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/958)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @yachang)

___
*[site/site.go, line 119 at r2](https://reviewable.io/reviews/m-lab/etl/958#-MHS_KQrDFKsImIRL2kV:-MHvXU7k-ZvM5VbsfkUo:b-970q9f) ([raw file](https://github.com/m-lab/etl/blob/f7626bb0ff0b3f3f685055d8c1b642fdf82e4ed4/site/site.go#L119)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Thanks for the clarification. Maybe add the info above as a doc here? so we can sync the proto more easily.
</blockquote></details>

I already added a comment on the siteinfo flag in response to the question.

**Pull request merged**
