### PR TITLE
Sandbox gfr new jitter

### PR DESCRIPTION
**Pull request by gfr10598**
This draft includes a lot of optimized packet decoding logic.  Explicit overlay of the raw packet data, and explicit byte swapping of multi-byte fields improves performance by approximate 2X overall.  Since a large part of processing is the simple decompression of the pcap data, this 2X improvement represents a much larger improvement in efficiency in the interpretation of the data.

This branch is roughly at parity with the previous work based on the standard gopacket decoders, with maps for sequence numbers, and processing of the TSVal and TSEcn values.

It still needs work on Sack interpretation, inflight computation, better detection of lost packets (lost to PCAP), and general validation.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/1033)

### CODE REVIEW

**Comment by gfr10598** [comment]
newJitterNov28

**Comment by gfr10598** [comment]
Currently seeing about 440 Mb/sec per instance in sandbox!!  This is about 41% of the index only throughput.

**Comment by stephen-soltesz** [comment]
Closing old PR - and referencing the notes from this change in https://github.com/m-lab/etl/issues/1085

**Comment by gfr10598** [comment]
Heh - nice cleanup.
Sorry I've lost touch.  Would enjoy talking sometime if you like.

**Comment by stephen-soltesz** [comment]
@gfr10598 then don't be a stranger!

**Pull request closed without merging**
