### PR TITLE
Embargo deploy

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/219)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[functions/embargo/README.md, line 5 at r2](https://reviewable.io:443/reviews/m-lab/etl/219#-KrHHX0yjkZpXv_UjXct:-KrHHX0zvu6lObNvOYCw:b37701i) ([raw file](https://github.com/m-lab/etl/blob/7a67af6aea266aacc8037faf35b9f62c6fdf24d7/functions/embargo/README.md#L5)):*
> ```Markdown
>  gcloud beta functions deploy embargoOnFileNotificationSandbox \
>      --stage-bucket=functions-mlab-sandbox \
>      --trigger-bucket=m-lab-sandbox \
> ```

Which bucket name will be used in mlab-staging and mlab-oti? Can we use a trigger bucket that has the same form?

---

*[functions/embargo/transfer.js, line 202 at r2](https://reviewable.io:443/reviews/m-lab/etl/219#-KrHHngz9A0GkVM8IY5l:-KrHHngz9A0GkVM8IY5m:bownuts) ([raw file](https://github.com/m-lab/etl/blob/7a67af6aea266aacc8037faf35b9f62c6fdf24d7/functions/embargo/transfer.js#L202)):*
> ```JavaScript
>  *
>  * @param {string} project The cloud project ID
>  * @param {string} destBucket The Cloud Storage bucket to move files to.
> ```

The docstring is missing the new parameters.

---

*[functions/embargo/transfer.js, line 208 at r2](https://reviewable.io:443/reviews/m-lab/etl/219#-KrHHw6RuQtxKCCQyde7:-KrHHw6SOj0V_oFlCUQf:b-izr1x5) ([raw file](https://github.com/m-lab/etl/blob/7a67af6aea266aacc8037faf35b9f62c6fdf24d7/functions/embargo/transfer.js#L208)):*
> ```JavaScript
> exports.triggerEmbargoHandler = function (project, publicBucket, privateBucket, filename, callback) {
>     var gsFilename, safeFilename;
>     gsFilename = "gs://m-lab-sandbox/" + filename;
> ```

Should this be hard-coded?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/219)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[functions/embargo/README.md, line 5 at r2](https://reviewable.io:443/reviews/m-lab/etl/219#-KrHHX0yjkZpXv_UjXct:-KrHQR0apJwcsLecuxJI:b-ojwp4u) ([raw file](https://github.com/m-lab/etl/blob/7a67af6aea266aacc8037faf35b9f62c6fdf24d7/functions/embargo/README.md#L5)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Which bucket name will be used in mlab-staging and mlab-oti? Can we use a trigger bucket that has the same form?
</blockquote></details>

By design doc, triggering bucket should be scraper-project-name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/219)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[functions/embargo/transfer.js, line 202 at r2](https://reviewable.io:443/reviews/m-lab/etl/219#-KrHHngz9A0GkVM8IY5l:-KrHba56ornJhReiLHg2:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/7a67af6aea266aacc8037faf35b9f62c6fdf24d7/functions/embargo/transfer.js#L202)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The docstring is missing the new parameters.
</blockquote></details>

Done.

---

*[functions/embargo/transfer.js, line 208 at r2](https://reviewable.io:443/reviews/m-lab/etl/219#-KrHHw6RuQtxKCCQyde7:-KrHeSGxDYjdy643oudi:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/7a67af6aea266aacc8037faf35b9f62c6fdf24d7/functions/embargo/transfer.js#L208)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Should this be hard-coded?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/219)*

**Comment by stephen-soltesz** [comment]
:lgtm: with the docstring update.

---

Reviewed 1 of 2 files at r2.
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[functions/embargo/README.md, line 5 at r2](https://reviewable.io:443/reviews/m-lab/etl/219#-KrHHX0yjkZpXv_UjXct:-KrHcSC4ngfsDNCkGUTh:b-jc6x3y) ([raw file](https://github.com/m-lab/etl/blob/7a67af6aea266aacc8037faf35b9f62c6fdf24d7/functions/embargo/README.md#L5)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

By design doc, triggering bucket should be scraper-project-name.
</blockquote></details>

:+1: great.

---

*[functions/embargo/transfer.js, line 202 at r3](https://reviewable.io:443/reviews/m-lab/etl/219#-KrHg4hfRKjl96S7zVei:-KrHg4hgcbbamiAErbVV:b-to1awu) ([raw file](https://github.com/m-lab/etl/blob/b95de3172e07a3f05ea4351b73657f8984f71c9e/functions/embargo/transfer.js#L202)):*
> ```JavaScript
>  *
>  * @param {string} project The cloud project ID
>  * @param {string} publicBucket The Cloud Storage bucket to move the public files to.
> ```

Now `sourceBucket` is not documented! :-) And, please check the order.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/219#-:-KrHgrawA-3TVMNowOMf:bdue55g)*

**Comment by stephen-soltesz** [comment]
Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/219)*

**Comment by yachang** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[functions/embargo/transfer.js, line 202 at r3](https://reviewable.io:443/reviews/m-lab/etl/219#-KrHg4hfRKjl96S7zVei:-KrHiyN96TeRuOuwqRWI:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b95de3172e07a3f05ea4351b73657f8984f71c9e/functions/embargo/transfer.js#L202)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Now `sourceBucket` is not documented! :-) And, please check the order.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/219)*

**Pull request merged**
