### PR TITLE
enable geolocation annotation on PT.

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/259)

### CODE REVIEW

**Comment by gfr10598** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[parser/geo_annotation.go, line 230 at r1](https://reviewable.io:443/reviews/m-lab/etl/259#-KviOanXjOua_CjTtyeL:-KviOanXjOua_CjTtyeM:bt8jqkf) ([raw file](https://github.com/m-lab/etl/blob/07a73b7848972d0b1a1f48ec1a9bbc3891ca570c/parser/geo_annotation.go#L230)):*
> ```Go
> 	if cok {
> 		reqData = append(reqData, annotation.RequestData{IP: cip, Timestamp: timestamp})
> 	} else {
> ```

Please replace these with a new AnnotationWarningCount metric.

---

*[parser/pt.go, line 435 at r1](https://reviewable.io:443/reviews/m-lab/etl/259#-KviOgxQrs1xJMKwlFLh:-KviOgxQrs1xJMKwlFLi:b6jtaai) ([raw file](https://github.com/m-lab/etl/blob/c34d4f7152a494f3a713aaea6187a6fa7f919aa4/parser/pt.go#L435)):*
> ```Go
> 		Data_direction: 0,
> 	}
> 	AddGeoDataPTConnSpec(conn_spec, t)
> ```

Please add the flag protection in AddGeo... in annotation.go, as in NDT.
See https://github.com/m-lab/etl/blob/07a73b7848972d0b1a1f48ec1a9bbc3891ca570c/parser/geo_annotation.go#L176

Then to enable, you add an environment variable, as in app-ndt-prod.yml
See https://github.com/m-lab/etl/blob/07a73b7848972d0b1a1f48ec1a9bbc3891ca570c/cmd/etl_worker/app-ndt.yaml#L42

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/259)*

**Comment by yachang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/pt.go, line 435 at r1](https://reviewable.io:443/reviews/m-lab/etl/259#-KviOgxQrs1xJMKwlFLh:-KvmD86IZANWirCOeZjO:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/c34d4f7152a494f3a713aaea6187a6fa7f919aa4/parser/pt.go#L435)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please add the flag protection in AddGeo... in annotation.go, as in NDT.
See https://github.com/m-lab/etl/blob/07a73b7848972d0b1a1f48ec1a9bbc3891ca570c/parser/geo_annotation.go#L176

Then to enable, you add an environment variable, as in app-ndt-prod.yml
See https://github.com/m-lab/etl/blob/07a73b7848972d0b1a1f48ec1a9bbc3891ca570c/cmd/etl_worker/app-ndt.yaml#L42
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/259)*

**Comment by yachang** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/geo_annotation.go, line 230 at r1](https://reviewable.io:443/reviews/m-lab/etl/259#-KviOanXjOua_CjTtyeL:-KvmGEjNFbb0aASwKiNf:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/07a73b7848972d0b1a1f48ec1a9bbc3891ca570c/parser/geo_annotation.go#L230)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please replace these with a new AnnotationWarningCount metric.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/259)*

**Comment by yachang** [comment]
This PR enable the GeoLocation in mlab-sandbox.

**Comment by gfr10598** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[metrics/metrics.go, line 86 at r4](https://reviewable.io:443/reviews/m-lab/etl/259#-KvmGy0WobZpMm51hqFK:-KvmGy0WobZpMm51hqFL:bd5qis4) ([raw file](https://github.com/m-lab/etl/blob/bdd0111cc67a9dd2dd8dd718de6ec298b960d173/metrics/metrics.go#L86)):*
> ```Go
> 	// Example usage:
> 	//    metrics.AnnotationWarningCount.Inc()
> 	AnnotationWarningCount = prometheus.NewGaugeVec(prometheus.GaugeOpts{
> ```

This should be a Counter, not a Gauge.  The ErrorCount should also be, if you want to change that too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/259)*

**Comment by gfr10598** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r4.
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[parser/geo_annotation.go, line 144 at r4](https://reviewable.io:443/reviews/m-lab/etl/259#-KvmJLV8i08Lhu0Wj7d1:-KvmJLV8i08Lhu0Wj7d2:b-a685kw) ([raw file](https://github.com/m-lab/etl/blob/bdd0111cc67a9dd2dd8dd718de6ec298b960d173/parser/geo_annotation.go#L144)):*
> ```Go
> // timestamp. With these, it will fetch the appropriate geo data and
> // add it to the hop struct referenced by the pointer.
> func AddGeoDataPTHop(hop *schema.ParisTracerouteHop, timestamp time.Time) {
> ```

flag protection before any call to code that tries to contact the annotator, like the GetAndInsert calls below.

Even better, add it to GetAndInsertGeolocationIPStruct.

---

*[parser/pt.go, line 435 at r1](https://reviewable.io:443/reviews/m-lab/etl/259#-KviOgxQrs1xJMKwlFLh:-KvmHxbT--Se5iDZrIUW:b-w4fg0x) ([raw file](https://github.com/m-lab/etl/blob/c34d4f7152a494f3a713aaea6187a6fa7f919aa4/parser/pt.go#L435)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the flag protection in the code in annotation.go.  I've added a comment there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/259)*

**Comment by gfr10598** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/259)*

**Comment by gfr10598** [comment]
*[parser/geo_annotation.go, line 144 at r4](https://reviewable.io:443/reviews/m-lab/etl/259#-KvmJLV8i08Lhu0Wj7d1:-KvmKARrN3qefsPPhdx_:b-tatwal) ([raw file](https://github.com/m-lab/etl/blob/bdd0111cc67a9dd2dd8dd718de6ec298b960d173/parser/geo_annotation.go#L144)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

flag protection before any call to code that tries to contact the annotator, like the GetAndInsert calls below.

Even better, add it to GetAndInsertGeolocationIPStruct.
</blockquote></details>

Never mind.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/259)*

**Comment by gfr10598** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[parser/pt.go, line 435 at r1](https://reviewable.io:443/reviews/m-lab/etl/259#-KviOgxQrs1xJMKwlFLh:-KvmJo_6_G2AT-KniYhr:b-hyx0a3) ([raw file](https://github.com/m-lab/etl/blob/c34d4f7152a494f3a713aaea6187a6fa7f919aa4/parser/pt.go#L435)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I don't see the flag protection in the code in annotation.go.  I've added a comment there.
</blockquote></details>

Ah I see now.  Sorry for delay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/259)*

**Comment by yachang** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[parser/pt.go, line 435 at r1](https://reviewable.io:443/reviews/m-lab/etl/259#-KviOgxQrs1xJMKwlFLh:-KvmrXO3pvpFQrOErbq_:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/c34d4f7152a494f3a713aaea6187a6fa7f919aa4/parser/pt.go#L435)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Ah I see now.  Sorry for delay.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/259)*

**Comment by yachang** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[metrics/metrics.go, line 86 at r4](https://reviewable.io:443/reviews/m-lab/etl/259#-KvmGy0WobZpMm51hqFK:-Kw0eFiM2T007RtBwQT6:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/bdd0111cc67a9dd2dd8dd718de6ec298b960d173/metrics/metrics.go#L86)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This should be a Counter, not a Gauge.  The ErrorCount should also be, if you want to change that too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/259)*

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/259#-:-Kw0oNgl-ztNtIi0eJ_e:bnfp4nl)*

**Comment by gfr10598** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/259)*

**Comment by yachang** [comment]
Data verified in BE table:

https://bigquery.cloud.google.com/table/mlab-sandbox:mlab_sandbox.traceroute_20170603?pli=1&tab=preview

**Pull request merged**
