### PR TITLE
Batch inserter

### PR DESCRIPTION
**Pull request by gfr10598**
Add NewBQInserter check whether service is batch.  If it is then force all inserts to go to template table instead of partition, since target won't be the public table and we don't care about latency.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/399)

### CODE REVIEW

**Comment by yachang** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis.yml, line 181 at r3](https://reviewable.io:443/reviews/m-lab/etl/399#-L3nLw99w2mjcZf2DDYp:-L3nLw99w2mjcZf2DDYq:b-is47we) ([raw file](https://github.com/m-lab/etl/blob/07c9d73152026170a80513aff800d6479b1d0ba6/.travis.yml#L181)):*
> ```YAML
>     branch: integration
> 
> ######################################################################
> ```

Complete dup of previous code block?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/399)*

**Comment by gfr10598** [comment]
PTAL.  I accidentally branched off the wrong branch.
Please compare against original.  r1,r2,r3 are all gunk.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/399#-:-L3ndpvYUDtu_BUT3kZt:bkhbcb1)*

**Comment by gfr10598** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis.yml, line 181 at r3](https://reviewable.io:443/reviews/m-lab/etl/399#-L3nLw99w2mjcZf2DDYp:-L3nzlOHtxUjQ8sJQInC:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/07c9d73152026170a80513aff800d6479b1d0ba6/.travis.yml#L181)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Complete dup of previous code block?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/399)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[etl/globals.go, line 84 at r4](https://reviewable.io:443/reviews/m-lab/etl/399#-L3o06BU13tF-nBH85u5:-L3o06BU13tF-nBH85u6:bqhqti3) ([raw file](https://github.com/m-lab/etl/blob/b57205c0204529d57b2da410843322e9912dccbc/etl/globals.go#L84)):*
> ```Go
> }
> 
> // IsBatchService return true if this is a NDT batch service.
> ```

Add TODO for PT and SS batch processing here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/399)*

**Comment by yachang** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/399#-:-L3o0HMhIiztfYTAzCMT:bnfp4nl)*

**Comment by gfr10598** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[etl/globals.go, line 84 at r4](https://reviewable.io:443/reviews/m-lab/etl/399#-L3o06BU13tF-nBH85u5:-L3o21XaLYUyBo3fgH4s:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b57205c0204529d57b2da410843322e9912dccbc/etl/globals.go#L84)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Add TODO for PT and SS batch processing here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/399)*

**Pull request merged**
