### PR TITLE
Inject

### PR DESCRIPTION
**Pull request by gfr10598**
Pull Inserter interface out into intf package.
Inject Inserter into Parser, so that Parser can push rows directly to inserter.
Tiny change to unit test, using injection.

Merge AFTER PR#25

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/26)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Added some initial comments. The full review will be pending merge of PR#25.

---

Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[intf/intf.go, line 1 at r1](https://reviewable.io:443/reviews/m-lab/etl/26#-KiCZwGZXktkB_9Pr9SU:-KiCZwG_U1NT-5v6otjR:b-y4ljzg) ([raw file](https://github.com/m-lab/etl/blob/2c2e9350df634a6da1f40d26969a8c5c89bbb2c8/intf/intf.go#L1)):*
> ```Go
> package intf
> ```

This package name is not immediately meaningful. What does it stand for? Is there an alternative pronounceable name?

---

*[parser/parser.go, line 66 at r1](https://reviewable.io:443/reviews/m-lab/etl/26#-KiCb-0zP98dQe4q18KS:-KiCb-0zP98dQe4q18KT:btz6o3o) ([raw file](https://github.com/m-lab/etl/blob/2c2e9350df634a6da1f40d26969a8c5c89bbb2c8/parser/parser.go#L66)):*
> ```Go
> 	}
> 	values["testname"] = testName
> 	np.inserter.InsertRows(FileNameSaver{values})
> ```

Cool. I can see how this will work nicely with NDT snapshots.

---

*[parser/parser_test.go, line 17 at r1](https://reviewable.io:443/reviews/m-lab/etl/26#-KiC_u6ilCvJ4OW2HL6F:-KiC_u6jZ-9tFbPJirNm:be88l1u) ([raw file](https://github.com/m-lab/etl/blob/2c2e9350df634a6da1f40d26969a8c5c89bbb2c8/parser/parser_test.go#L17)):*
> ```Go
> // CountingInserter counts the calls to InsertRows and Flush.
> // Inject into Parser for testing.
> type CountingInserter struct {
> ```

If this type is only for testing, it should not be exported with a capital. `type countingInserter struct {`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/26#-:-KiCbBDx_l5q64CarLOa:b-3vkt5o)*

**Comment by gfr10598** [comment]
Merge is done.  Hopefully didn't break anything.  8-)

---

Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[intf/intf.go, line 1 at r1](https://reviewable.io:443/reviews/m-lab/etl/26#-KiCZwGZXktkB_9Pr9SU:-KiDFg_DiAO1uM3H8iU0:bgpabpr) ([raw file](https://github.com/m-lab/etl/blob/2c2e9350df634a6da1f40d26969a8c5c89bbb2c8/intf/intf.go#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This package name is not immediately meaningful. What does it stand for? Is there an alternative pronounceable name?
</blockquote></details>

The intent is interface, but that is a reserved word.
intfc ?

---

*[parser/parser_test.go, line 17 at r1](https://reviewable.io:443/reviews/m-lab/etl/26#-KiC_u6ilCvJ4OW2HL6F:-KiDG5Uvy1wqKjHCoRCj:bgwvn8g) ([raw file](https://github.com/m-lab/etl/blob/2c2e9350df634a6da1f40d26969a8c5c89bbb2c8/parser/parser_test.go#L17)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If this type is only for testing, it should not be exported with a capital. `type countingInserter struct {`
</blockquote></details>

Done.  However, I also use parser_test package for this reason (and others).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/26#-:-KiDGDbTnGYhGLJPi3Pn:b4rt1a0)*

**Comment by pboothe** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[intf/intf.go, line 1 at r1](https://reviewable.io:443/reviews/m-lab/etl/26#-KiCZwGZXktkB_9Pr9SU:-KiGBLwjQRkzX8VFzaTN:bepnmlw) ([raw file](https://github.com/m-lab/etl/blob/2c2e9350df634a6da1f40d26969a8c5c89bbb2c8/intf/intf.go#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

The intent is interface, but that is a reserved word.
intfc ?
</blockquote></details>

`interfaces` or just `etl`

Interfaces are usually project-wide globals, so give the package a generic name to indicate that these are the interfaces for the project as a whole and/or just put it in the root of the project.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/26)*

**Comment by pboothe** [comment]
:lgtm: , pending package rename

---

Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/26#-:-KiGD6HlrvffnMriGxI7:bjfclic)*

**Comment by gfr10598** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[intf/intf.go, line 1 at r1](https://reviewable.io:443/reviews/m-lab/etl/26#-KiCZwGZXktkB_9Pr9SU:-KiGoeRpyVRzmPy-8348:b-3366p1) ([raw file](https://github.com/m-lab/etl/blob/2c2e9350df634a6da1f40d26969a8c5c89bbb2c8/intf/intf.go#L1)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

`interfaces` or just `etl`

Interfaces are usually project-wide globals, so give the package a generic name to indicate that these are the interfaces for the project as a whole and/or just put it in the root of the project.
</blockquote></details>

I'll fix this in a followup PR, to minimize rebase headaches.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/26)*

**Pull request merged**
