### PR TITLE
activate GeoLocation in staging and prod for PT 

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/263)

### CODE REVIEW

**Comment by gfr10598** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/m-lab/etl/263#-Kw1kIs8BlapWwRtz6Ji:-Kw1kIs8BlapWwRtz6Jj:bqhgmco) (no related file):*
FYI, for me, the annotator is not working in staging.  Don't know why.  Working fine in sandbox.

Let me know if it is working for you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/263)*

**Comment by gfr10598** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/263#-:-Kw1pX-daqXtX53tNVsb:bnfp4nl)*

**Comment by gfr10598** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/263)*

**Comment by yachang** [comment]
staging working now:

#standardSQL
SELECT count(test_id) as cnt, connection_spec.client_geolocation.country_name
FROM `mlab-staging.staging.traceroute_20170404`
group by connection_spec.client_geolocation.country_name
order by cnt DESC

Output as 


Row | cnt | country_name |  
-- | -- | -- | --
1 | 11756845 | United States |  
2 | 714660 | United Kingdom |  
3 | 478187 | Italy |  
4 | 293997 | Canada |  
5 | 247661 | Australia |  
6 | 198714 | Germany |  
7 | 145452 | Russia |  
8 | 134011 | Spain |  
9 | 131056 | Portugal |  
10 | 129201 | Republic of Korea |  
11 | 98475 | Belgium |  
12 | 87468 | Denmark |  
13 | 73416 | Sweden |  
14 | 67370 | China |  
15 | 60123 | Czechia |

**Comment by yachang** [comment]
Prod working now:

https://bigquery.cloud.google.com/table/measurement-lab:public.traceroute_20170401?pli=1&tab=preview

**Comment by yachang** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/m-lab/etl/263#-Kw1kIs8BlapWwRtz6Ji:-KwGrFHljbeFOk2F1hWw:bdpuvhw) (no related file):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

FYI, for me, the annotator is not working in staging.  Don't know why.  Working fine in sandbox.

Let me know if it is working for you.
</blockquote></details>

All working and verified now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/263)*

**Comment by yachang** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/m-lab/etl/263#-Kw1kIs8BlapWwRtz6Ji:-KwGrY__-4v6jmkRd8V1:bb6un1j) (no related file):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

All working and verified now.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/263)*

**Pull request merged**
