### PR TITLE
Added the last common function and the code for NDT parsing. Plus tests.

### PR DESCRIPTION
**Pull request by jlm123hi**
This is the last of the code needed to add metadata to NDT tests, aside from a single method call from the parsing function.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/222)

### CODE REVIEW

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[parser/metadata.go, line 49 at r1](https://reviewable.io:443/reviews/m-lab/etl/222#-KrfGAzm5GaBTKkaDtx9:-KrfGAzm5GaBTKkaDtxA:b-m2vv84) ([raw file](https://github.com/m-lab/etl/blob/22ab2c2c0e6cb682e537a362fcad84879ae538ec/parser/metadata.go#L49)):*
> ```Go
> // string indicating whether it should get the metadata for the client
> // end or the server end of the connection. It will either insert the
> // data into the connection spec or silently fail.
> ```

Func name can be more representative,

GetAndInsertMetaIntoNDT

or just 

GetAndInsertMeta

return error to indicate whether it fail silently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/222)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/metadata.go, line 58 at r1](https://reviewable.io:443/reviews/m-lab/etl/222#-KrfGqFgOtH2zP-XvPSL:-KrfGqFgOtH2zP-XvPSM:b3s2pxs) ([raw file](https://github.com/m-lab/etl/blob/22ab2c2c0e6cb682e537a362fcad84879ae538ec/parser/metadata.go#L58)):*
> ```Go
> 		if annotationData != nil {
> 			CopyStructToMap(annotationData.Geo, spec.Get(side+"_geolocation"))
> 		}
> ```

handle nil case here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/222)*

**Comment by jlm123hi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/metadata.go, line 49 at r1](https://reviewable.io:443/reviews/m-lab/etl/222#-KrfGAzm5GaBTKkaDtx9:-KrfXzn_0JtnLXwsnHKq:bugpczi) ([raw file](https://github.com/m-lab/etl/blob/22ab2c2c0e6cb682e537a362fcad84879ae538ec/parser/metadata.go#L49)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Func name can be more representative,

GetAndInsertMetaIntoNDT

or just 

GetAndInsertMeta

return error to indicate whether it fail silently.
</blockquote></details>

Done. The name has been changed, and I made the other change of where the error metric is reported as we discussed.

---

*[parser/metadata.go, line 58 at r1](https://reviewable.io:443/reviews/m-lab/etl/222#-KrfGqFgOtH2zP-XvPSL:-KrfXydE4VUzD8dZUm7G:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/22ab2c2c0e6cb682e537a362fcad84879ae538ec/parser/metadata.go#L58)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

handle nil case here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/222)*

**Comment by yachang** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/222#-:-KrfpxxAnRbnvPnO2L8A:bnfp4nl)*

**Pull request merged**
