### PR TITLE
Remove explicit dependencies on the decommissioned annotation-service

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change removes all explicit dependencies on the annotation-service. Though go.mod still reports an indirect dependency (likely) through `uuid-annotator`.

To eliminate this dependency for v1 datatypes, we replace references to `*api.GeolocationIP` and `*api.ASData` with local struct definitions for `LegacyGeolocationIP` and `LegacyASData`.

Part of:
* https://github.com/m-lab/etl/issues/1084

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/1091)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
@SaiedKazemi would you also take a look? In particular, regarding the handling of the `Legacy*` structs.

**Comment by SaiedKazemi** [comment]
If legacy structs are not used anymore and are also not to be used, can they be commented out?

:lgtm:

**Review by SaiedKazemi — APPROVED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1091)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

**Review by cristinaleonr — COMMENTED** [review]
Will migrating sidestream, web100, and paris1 to the v2 pipeline allow us to get rid of the references to `Legacy*` structs? If so, I think it makes more sense to do that before this step.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1091#-:-N4D1DyqBsZ30sQnzIS8:b-mpub1)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
Yes, migrating the v1 datatypes to the v2 pipeline will get rid of the references to the Legacy structs.. but that's significantly more work b/c it will require new schema definitions and then updates to the parsers to use the new structs. This would also be without the synthetic uuid annotations embedded in the v1 tables today. I think of all this as part of the "v1 datatype migration" work that we elected not to do last half, and I expect we will not prioritize this half either. Do you see another way forward? (open to alternatives)

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1091#-:-N4DG1Sv-NDmk03Co0Ob:bvx93vh)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by cristinaleonr — APPROVED** [review]
I see. I thought even though we postponed the migration of the v1 datatypes, we would get to it sooner rather than later. If it will not be prioritized anytime soon, then it does not need to block this.
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1091#-:-N4DrizT42b16VGknOkC:b79l2li)* status: :shipit: complete! 2 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
Thank you.

If we did pair programming during the fixit week, I'll bet we could get pretty close pretty quickly... I think it's still an option, but someone has to want it.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1091#-:-N4Dsl2k-YhZeldEw7QA:b-dy4ewy)* status: :shipit: complete! 2 of 1 approvals obtained

**Pull request merged**
