### PR TITLE
Use ndt5 TCPInfo.MinRTT when available for a.MinRTT summary

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change updates the ndt5 parser to use the S2C.TCPInfo.MinRTT value when TCPInfo is available rather than the lower-resolution S2C.MinRTT (which was calculated in user-space to mimmic earlier web100 behavior, possibly before TCPInfo.MinRTT was calculated in the Linux kernel). This change includes a new sample ndt result file that includes an TCPInfo record.

Note: this change will apply to all ndt5 measurements since 2020-06-18 to present. The pipeline cycle time is much longer now so this value will not be updated for all historical data for several months. However, daily data will use this update once this change is deployed to production.

Part of:
* https://github.com/m-lab/etl/issues/1094

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/1097)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
FYI: @mattmathis PTAL?

**Review by cristinaleonr — COMMENTED** [review]
Is there a test case in which we verify the `MinRTT` value when `expectTCPInfo = false`?

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1097#-:-N4nTLqQ3w4ZWQjZu2K6:b-v5cw5c)* status: 0 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
That's a good idea. Not all of the `expectTCPInfo = false` cases are safe but the `expectMetadata` case is.

It does feel like we've passed the limits of Go's table driven testing approach for variations of datatype variations.. I'm wondering if a per-example-file test that compares raw input to explicit output would be better over all.. 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1097#-:-N4nVA9v-tkAnLn_t-ST:bsnj13d)* status: 0 of 1 approvals obtained

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1097#-:-N4nYqa55OmfS7vuocyh:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by stephen-soltesz** [comment]
Thank you!

**Pull request merged**
