### PR TITLE
Update NDT7 and Annotation schemas to use Standard Columns

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change updates the NDT7 and Annotation schemas to use the (hopefully) final Standard Column update to these tables.

In particular there are two principle changes:

* `TestTime` -> `Date`
* `ParseInfo` -> `Parser` and remove field name "stuttering" similar to Go conventions.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/895)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/dev-tracker/issues/497

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/dev-tracker/issues/578

**Comment by critzo** [comment]
I spoke with @stephen-soltesz about this and the proposed changes LGTM!

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/dev-tracker/issues/578

**Pull request merged**
