### PR TITLE
S5 multiqueue

### PR DESCRIPTION
**Pull request by pboothe**
I said I'd have it done or throw it over the wall by the end of the day.

I am unsure which this is :)

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/34)

### CODE REVIEW

**Comment by gfr10598** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[appengine/queue.yaml, line 27 at r1](https://reviewable.io:443/reviews/m-lab/etl/34#-Ki_Avz1P2gQkxldDzFR:-Ki_Avz1P2gQkxldDzFS:b-unrs0f) ([raw file](https://github.com/m-lab/etl/blob/ca4b2de20a8082863a663e4933258974d1f153f6/appengine/queue.yaml#L27)):*
> ```YAML
>   # Maximum number of concurrent requests.  This is large now, until we address the
>   # latency associated with BQ inserts.
>   max_concurrent_requests: 500
> ```

It is time to start restricting this more.  Please change these to bucket size 10 (just to limit inrush if we get a burst of requests), and max concurrent = 50.  This will allow us to see where the bottlenecks actually are, and we can bump it up as needed for each of the 4 pipelines.

---

*[appengine/queue_pusher/queue_pusher.go, line 20 at r1](https://reviewable.io:443/reviews/m-lab/etl/34#-Ki_BUyY_g292huLlDBG:-Ki_BUyY_g292huLlDBH:b-kyixl1) ([raw file](https://github.com/m-lab/etl/blob/ca4b2de20a8082863a663e4933258974d1f153f6/appengine/queue_pusher/queue_pusher.go#L20)):*
> ```Go
> 
> // Requests can only add tasks to one of these whitelisted queue names.
> var queueWhitelist = map[string]*regexp.Regexp{
> ```

Could you move these into etl package (in globals.go), so that they can be kept in sync with the TaskPattern there more easily?

---

*[appengine/queue_pusher/queue_pusher.go, line 94 at r1](https://reviewable.io:443/reviews/m-lab/etl/34#-Ki_C7fH5DhfGxintMRt:-Ki_C7fH5DhfGxintMRu:bhgmrvn) ([raw file](https://github.com/m-lab/etl/blob/ca4b2de20a8082863a663e4933258974d1f153f6/appengine/queue_pusher/queue_pusher.go#L94)):*
> ```Go
> 	}
> 
> 	decoded_filename, err := base64.StdEncoding.DecodeString(filename)
> ```

Would it make sense to reuse the decoding code in etl_worker?

---

*[appengine/queue_pusher/queue_pusher.go, line 103 at r1](https://reviewable.io:443/reviews/m-lab/etl/34#-Ki_CRhy1c94yNJ2FDlC:-Ki_CRhy1c94yNJ2FDlD:b-n5qtkg) ([raw file](https://github.com/m-lab/etl/blob/ca4b2de20a8082863a663e4933258974d1f153f6/appengine/queue_pusher/queue_pusher.go#L103)):*
> ```Go
> 	queuename := queueForFile(decoded_filename)
> 
> 	// Lots of files will be archived that should not be enqueued. Pass
> ```

Add a TODO to add a prometheus counter for these.

---

*[cmd/etl_worker/app-disco.yaml, line 1 at r1](https://reviewable.io:443/reviews/m-lab/etl/34#-Ki_CqQZW-Ma4exdYkJA:-Ki_CqQZW-Ma4exdYkJB:bj1zzz9) ([raw file](https://github.com/m-lab/etl/blob/ca4b2de20a8082863a663e4933258974d1f153f6/cmd/etl_worker/app-disco.yaml#L1)):*
> ```YAML
> runtime: custom
> ```

Does .travis.yaml need to be updated to handle the deployment?

---

*[cmd/etl_worker/app-disco.yaml, line 3 at r1](https://reviewable.io:443/reviews/m-lab/etl/34#-Ki_C_-FkRMszC6Zw7Wf:-Ki_C_-FkRMszC6Zw7Wg:b2r19ar) ([raw file](https://github.com/m-lab/etl/blob/ca4b2de20a8082863a663e4933258974d1f153f6/cmd/etl_worker/app-disco.yaml#L3)):*
> ```YAML
> runtime: custom
> env: flex
> service: disco-parser
> ```

prefix with etl?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/34)*

**Comment by pboothe** [comment]
Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[appengine/queue.yaml, line 27 at r1](https://reviewable.io:443/reviews/m-lab/etl/34#-Ki_Avz1P2gQkxldDzFR:-Ki_i6kkxELDlUC0A9P3:bb6un1j) ([raw file](https://github.com/m-lab/etl/blob/ca4b2de20a8082863a663e4933258974d1f153f6/appengine/queue.yaml#L27)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

It is time to start restricting this more.  Please change these to bucket size 10 (just to limit inrush if we get a burst of requests), and max concurrent = 50.  This will allow us to see where the bottlenecks actually are, and we can bump it up as needed for each of the 4 pipelines.
</blockquote></details>

Done

---

*[appengine/queue_pusher/queue_pusher.go, line 20 at r1](https://reviewable.io:443/reviews/m-lab/etl/34#-Ki_BUyY_g292huLlDBG:-Ki_i8BJAwvwU39-1CoC:bb6un1j) ([raw file](https://github.com/m-lab/etl/blob/ca4b2de20a8082863a663e4933258974d1f153f6/appengine/queue_pusher/queue_pusher.go#L20)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Could you move these into etl package (in globals.go), so that they can be kept in sync with the TaskPattern there more easily?
</blockquote></details>

Done

---

*[appengine/queue_pusher/queue_pusher.go, line 94 at r1](https://reviewable.io:443/reviews/m-lab/etl/34#-Ki_C7fH5DhfGxintMRt:-Ki_i9zxx7Bnsglg0hvK:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/ca4b2de20a8082863a663e4933258974d1f153f6/appengine/queue_pusher/queue_pusher.go#L94)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Would it make sense to reuse the decoding code in etl_worker?
</blockquote></details>

Done.

---

*[appengine/queue_pusher/queue_pusher.go, line 103 at r1](https://reviewable.io:443/reviews/m-lab/etl/34#-Ki_CRhy1c94yNJ2FDlC:-Ki_iAmkny4i_YYr1AlT:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/ca4b2de20a8082863a663e4933258974d1f153f6/appengine/queue_pusher/queue_pusher.go#L103)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add a TODO to add a prometheus counter for these.
</blockquote></details>

Done.

---

*[cmd/etl_worker/app-disco.yaml, line 1 at r1](https://reviewable.io:443/reviews/m-lab/etl/34#-Ki_CqQZW-Ma4exdYkJA:-Ki_iBZZ2luepjmakN48:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/ca4b2de20a8082863a663e4933258974d1f153f6/cmd/etl_worker/app-disco.yaml#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Does .travis.yaml need to be updated to handle the deployment?
</blockquote></details>

Done.

---

*[cmd/etl_worker/app-disco.yaml, line 3 at r1](https://reviewable.io:443/reviews/m-lab/etl/34#-Ki_C_-FkRMszC6Zw7Wf:-Ki_iCKFgUfYSzzy6yEG:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/ca4b2de20a8082863a663e4933258974d1f153f6/cmd/etl_worker/app-disco.yaml#L3)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

prefix with etl?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/34)*

**Comment by pboothe** [comment]
PTAL

**Comment by gfr10598** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[appengine/queue.yaml, line 27 at r1](https://reviewable.io:443/reviews/m-lab/etl/34#-Ki_Avz1P2gQkxldDzFR:-Kj57_U9K34urKWOJD8u:bqzlbpq) ([raw file](https://github.com/m-lab/etl/blob/ca4b2de20a8082863a663e4933258974d1f153f6/appengine/queue.yaml#L27)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Hmm - not seeing the changes.

---

*[cmd/etl_worker/app-ndt.yaml, line 1 at r2](https://reviewable.io:443/reviews/m-lab/etl/34#-Kj57zrnHaCqUYJnf1JI:-Kj57zrnHaCqUYJnf1JJ:b-uvalvu) ([raw file](https://github.com/m-lab/etl/blob/389f5e164fb650590eff418aa4d8a42846477b28/cmd/etl_worker/app-ndt.yaml#L1)):*
> ```YAML
> runtime: custom
> ```

Please compare these to the current app.yaml, as it may have changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/34)*

**Comment by pboothe** [comment]
Dangit. I recall making the changes, but obviously they didn't get uploaded :(

I'll rebase this, modernize it, and get it back to you tomorrow (Tuesday)

**Pull request closed without merging**
