### PR TITLE
Fix PT crash over before Rollins data

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/186)

### CODE REVIEW

**Comment by yachang** [comment]
I accidentally push the integration branch with new test data directly. So the updated testdata file (some test content, different file name) is not in the PR. sorry!

**Comment by yachang** [comment]
Now renamed testfile is in PR :)

**Comment by gfr10598** [comment]
A few changes to make, then
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[parser/pt.go, line 368 at r2](https://reviewable.io:443/reviews/m-lab/etl/186#-Knu2nJnswIgeUk00NGc:-Knu2nJnswIgeUk00NGd:b-nbgv32) ([raw file](https://github.com/m-lab/etl/blob/9fce89ae5e51101e1bc35df5b6ad6ecb9f44dee1/parser/pt.go#L368)):*
> ```Go
> 		// This var keep all new leaves
> 		var new_leaves []Node
> 		if is_first_line {
> ```

Please add a TODO, to handle the first line explicitly before this for loop, then run the for loop on the remainder of the slice.  This will avoid the if is_first_line, and make the code more readable and easier to maintain.

---

*[parser/pt.go, line 371 at r2](https://reviewable.io:443/reviews/m-lab/etl/186#-Knu261XKwj3XnTHo5HE:-Knu261XKwj3XnTHo5HF:b-vaxtav) ([raw file](https://github.com/m-lab/etl/blob/9fce89ae5e51101e1bc35df5b6ad6ecb9f44dee1/parser/pt.go#L371)):*
> ```Go
> 			is_first_line = false
> 			protocol, dest_IP, server_IP = ParseFirstLine(oneLine)
> 			if protocol == "" {
> ```

Would prefer that ParseFirstLine return an error, and check that here.

---

*[parser/pt.go, line 372 at r2](https://reviewable.io:443/reviews/m-lab/etl/186#-Knu2B_mQsQDUYe35tuc:-Knu2B_mQsQDUYe35tud:b-bsp85x) ([raw file](https://github.com/m-lab/etl/blob/9fce89ae5e51101e1bc35df5b6ad6ecb9f44dee1/parser/pt.go#L372)):*
> ```Go
> 			protocol, dest_IP, server_IP = ParseFirstLine(oneLine)
> 			if protocol == "" {
> 				metrics.TestCount.WithLabelValues(tableName, "pt", "wrong protocol").Inc()
> ```

Also please increment the ErrorCount metric, and add a log message.  We will soon start triggering StackDriver log captures on some log messages, so anything unexpected should ideally be logged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/186#-:-Knu36mSGSwwqqyPuY05:bk7arkf)*

**Comment by yachang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[parser/pt.go, line 368 at r2](https://reviewable.io:443/reviews/m-lab/etl/186#-Knu2nJnswIgeUk00NGc:-KnuCvu-BT2SHoAIiIar:b-896fjx) ([raw file](https://github.com/m-lab/etl/blob/9fce89ae5e51101e1bc35df5b6ad6ecb9f44dee1/parser/pt.go#L368)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please add a TODO, to handle the first line explicitly before this for loop, then run the for loop on the remainder of the slice.  This will avoid the if is_first_line, and make the code more readable and easier to maintain.
</blockquote></details>

Done

---

*[parser/pt.go, line 371 at r2](https://reviewable.io:443/reviews/m-lab/etl/186#-Knu261XKwj3XnTHo5HE:-KnuDKQPMRWjh-3y2_n8:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/9fce89ae5e51101e1bc35df5b6ad6ecb9f44dee1/parser/pt.go#L371)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Would prefer that ParseFirstLine return an error, and check that here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/186)*

**Comment by yachang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[parser/pt.go, line 372 at r2](https://reviewable.io:443/reviews/m-lab/etl/186#-Knu2B_mQsQDUYe35tuc:-KnuDeqbpJZjnMGP4uRf:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/9fce89ae5e51101e1bc35df5b6ad6ecb9f44dee1/parser/pt.go#L372)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Also please increment the ErrorCount metric, and add a log message.  We will soon start triggering StackDriver log captures on some log messages, so anything unexpected should ideally be logged.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/186)*

**Pull request merged**
