### PR TITLE
Add cloud function deployment to .travis.yml

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/511)

### CODE REVIEW

**Comment by gfr10598** [comment]
Could you please also update the comments section in transfer.js?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[.travis.yml, line 172 at r2](https://reviewable.io/reviews/m-lab/etl/511#-LEUqH4o47HyR26pZr-Z:-LEUqH4o47HyR26pZr-_:b-y8c5te) ([raw file](https://github.com/m-lab/etl/blob/88c0755a7b52556d03f9757a254ab63a2354b13d/.travis.yml#L172)):*
> ```YAML
>     SERVICE_ACCOUNT_mlab_sandbox $TRAVIS_BUILD_DIR/cmd/etl_worker app-sidestream.yaml
>     && gcloud beta functions deploy createSandboxTaskOnFileNotification
>     --stage-bucket=functions-mlab-sandbox --trigger-resource=m-lab-sandbox --project=mlab-sandbox
> ```

Neither this bucket, nor scraper-mlab-sandbox, have any sidestream data in them for 2018.  I guess we just manually transferred data when we needed to test.

So, let's update this to use the scraper-mlab-sandbox source, instead of m-lab-sandbox, which predates our naming convention.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/511#-:-LEUp4k99uaAbYbo3Yet:b-43c0qj)*

**Comment by gfr10598** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 172 at r2](https://reviewable.io/reviews/m-lab/etl/511#-LEUqH4o47HyR26pZr-Z:-LEUqvsGCXKv6D2tU_gm:bwom1bu) ([raw file](https://github.com/m-lab/etl/blob/88c0755a7b52556d03f9757a254ab63a2354b13d/.travis.yml#L172)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Neither this bucket, nor scraper-mlab-sandbox, have any sidestream data in them for 2018.  I guess we just manually transferred data when we needed to test.

So, let's update this to use the scraper-mlab-sandbox source, instead of m-lab-sandbox, which predates our naming convention.

</blockquote></details>

Do you know if there is any other reference to m-lab-sandbox in any of our code?

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/511)*

**Comment by gfr10598** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[.travis.yml, line 279 at r2](https://reviewable.io/reviews/m-lab/etl/511#-LEV0p0E1Ot2ijQm45K3:-LEV0p0E1Ot2ijQm45K4:b-btysxw) ([raw file](https://github.com/m-lab/etl/blob/88c0755a7b52556d03f9757a254ab63a2354b13d/.travis.yml#L279)):*
> ```YAML
>     && $TRAVIS_BUILD_DIR/travis/deploy_app.sh mlab-oti
>     SERVICE_ACCOUNT_mlab_oti $TRAVIS_BUILD_DIR/appengine/queue_pusher
>     && gcloud beta functions deploy embargoOnFileNotificationOti --stage-bucket=functions-mlab-oti \
> ```

Since this impacts the main NDT production pipeline, it should be in the NDT deployment, below, not the small deployment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/511)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[.travis.yml, line 172 at r2](https://reviewable.io/reviews/m-lab/etl/511#-LEUqH4o47HyR26pZr-Z:-LEVdvez38ZytZCj25vB:b-nzn8c0) ([raw file](https://github.com/m-lab/etl/blob/88c0755a7b52556d03f9757a254ab63a2354b13d/.travis.yml#L172)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Do you know if there is any other reference to m-lab-sandbox in any of our code?
</blockquote></details>

Fix the  "m-lab-sandbox" in the README.

---

*[.travis.yml, line 279 at r2](https://reviewable.io/reviews/m-lab/etl/511#-LEV0p0E1Ot2ijQm45K3:-LEVk980CmltGB8X6twT:b-bo5szc) ([raw file](https://github.com/m-lab/etl/blob/88c0755a7b52556d03f9757a254ab63a2354b13d/.travis.yml#L279)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Since this impacts the main NDT production pipeline, it should be in the NDT deployment, below, not the small deployment.
</blockquote></details>

I put it at both places.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/511)*

**Comment by gfr10598** [comment]
There are also extensive notes in transfer.js file, but they don't seem to be self-consistent.  I'll start another PR (or maybe issue) to fix those comments.

---

Review status: 0 of 1 LGTMs obtained

---

*[.travis.yml, line 172 at r2](https://reviewable.io/reviews/m-lab/etl/511#-LEUqH4o47HyR26pZr-Z:-LEjTE0v3h9K1_ng5o97:b-7vexxw) ([raw file](https://github.com/m-lab/etl/blob/88c0755a7b52556d03f9757a254ab63a2354b13d/.travis.yml#L172)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Fix the  "m-lab-sandbox" in the README.
</blockquote></details>

Hmm.  If you are not going to add the task creation function deployment, could you make sure there is an issue to add that deployment rule later?  Probably either Peter or I will end up doing it.  Alternatively, feel free to implement that in this or a followup PR.

---

*[.travis.yml, line 279 at r2](https://reviewable.io/reviews/m-lab/etl/511#-LEV0p0E1Ot2ijQm45K3:-LEjRjuw8qy9fsIvqZpm:b-6u4995) ([raw file](https://github.com/m-lab/etl/blob/88c0755a7b52556d03f9757a254ab63a2354b13d/.travis.yml#L279)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

I put it at both places.
</blockquote></details>

It should specifically NOT be in the small deployment.  The small deployment should not impact the NDT pipeline.  When code changes that impacts the NDT pipeline, then the full NDT pipeline should be redeployed, rather than just one or two components.  This avoids our highest visibility pipeline accidentally running a mix of different component versions.  Since NDT depends on both the embargo function and the create notification function, they should both be deployed as part of the NDT target, and NOT the "small" target.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/511#-:-LEjV8-oC3JXR31RDhXK:br3hhpg)*

**Comment by yachang** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[.travis.yml, line 172 at r2](https://reviewable.io/reviews/m-lab/etl/511#-LEUqH4o47HyR26pZr-Z:-LEuLnHa9ye6lC-npohU:bvowirz) ([raw file](https://github.com/m-lab/etl/blob/88c0755a7b52556d03f9757a254ab63a2354b13d/.travis.yml#L172)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Hmm.  If you are not going to add the task creation function deployment, could you make sure there is an issue to add that deployment rule later?  Probably either Peter or I will end up doing it.  Alternatively, feel free to implement that in this or a followup PR.
</blockquote></details>

new issue 

https://github.com/m-lab/etl/issues/521

created. Thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/511)*

**Comment by yachang** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[.travis.yml, line 279 at r2](https://reviewable.io/reviews/m-lab/etl/511#-LEV0p0E1Ot2ijQm45K3:-LEuPBG_0m1bdlU4nM5W:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/88c0755a7b52556d03f9757a254ab63a2354b13d/.travis.yml#L279)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

It should specifically NOT be in the small deployment.  The small deployment should not impact the NDT pipeline.  When code changes that impacts the NDT pipeline, then the full NDT pipeline should be redeployed, rather than just one or two components.  This avoids our highest visibility pipeline accidentally running a mix of different component versions.  Since NDT depends on both the embargo function and the create notification function, they should both be deployed as part of the NDT target, and NOT the "small" target.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/511)*

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/511#-:-LEuYspJ9nxRFJK7RVpC:bnfp4nl)*

**Pull request closed without merging**
