### PR TITLE
Preliminary review for Reprocessor

### PR DESCRIPTION
**Pull request by gfr10598**
This code is working, and in reasonable shape, but missing a few features.  Probably worthwhile merging into integration branch soon.

I've added unit tests, but they rely on a test bucket in GCS.  It seems impossible to fake either buckets
or storage.ObjectIterator at this time.  We might consider creating a higher level abstraction for testing, as with ETLSource.

Would like feedback on the testing methodology.

Thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/298)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Some initial thoughts. I'll keep thinking about it. Sounds like you will too.

---

Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[cmd/reproc/README.md, line 2 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1eJP2rxe4qpFuwmDV:-Ky1eJP2rxe4qpFuwmDW:b7pc2dg) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L2)):*
> ```Markdown
> 
> This should be run from an environment logged into gcloud in the mlab-oti project.  mlab-oti is the default project, but can be
> ```

nit: wrap at 80 cols.

---

*[cmd/reproc/README.md, line 2 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1eVLapHBuzadfKlNL:-Ky1eVLapHBuzadfKlNM:b8crp7q) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L2)):*
> ```Markdown
> 
> This should be run from an environment logged into gcloud in the mlab-oti project.  mlab-oti is the default project, but can be
> ```

I suggest either not using a default project (so it's always set explicitly) or setting the default to non-prod. 

The principle here is to try to minimize unintended side-effects on production from a new user experimenting with a new tool.

---

*[cmd/reproc/README.md, line 16 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1eyPZfTByjx1e3kz_:-Ky1eyPZfTByjx1e3kza:bfd599a) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L16)):*
> ```Markdown
> The command line flags are:
> ```
> 	fProject   = flag.String("project", "mlab-oti", "Project containing queues.")
> ```

I suggest copying the output from `--help` or referring the user to run `--help` rather than duplicating this code in the README.

---

*[cmd/reproc/README.md, line 25 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1fC-rrel2HraxrW_V:-Ky1fC-rrel2HraxrW_W:b-br0o4r) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L25)):*
> ```Markdown
> ```
> 
> The default queues feed into etl-ndt-batch pipeline, which pushes rows to measurement-lab:batch.ndt.  This table is created by
> ```

I support your goal to use standard sql globally. Is there inconsistency from bq between table references in standard sql and the bq cli tool? Is there a way to use the standard sql table references here?

---

*[cmd/reproc/README.md, line 30 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1faNy3Pfxzv8YtT_b:-Ky1faNy3Pfxzv8YtT_c:b136oir) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L30)):*
> ```Markdown
> ```
> 
> The pipeline job runs in mlab-oti, so I've granted bigquery.dataeditor permissions 
> ```

Please create an issue for this rather than a note in the readme?

---

*[cmd/reproc/reproc.go, line 59 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky2AW7gDRi_FHfWhoax:-Ky2AW7gDRi_FHfWhoay:b64ylta) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/reproc.go#L59)):*
> ```Go
> 
> func postOne(queue string, bucket string, fn string) error {
> 	reqStr := fmt.Sprintf("http://queue-pusher-dot-%s.appspot.com/receiver?queue=%s&filename=gs://%s/%s", *fProject, queue, bucket, fn)
> ```

Since this is an appspot subdomain, the HTTPS address should also be available. Please prefer HTTPS where available.

---

*[cmd/reproc/reproc.go, line 79 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky2CXpD81v0_8PBB7ip:-Ky2CXpD81v0_8PBB7iq:b-x7l2d1) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/reproc.go#L79)):*
> ```Go
> 	for o, err := it.Next(); err != iterator.Done; o, err = it.Next() {
> 		if err != nil {
> 			log.Println(err)
> ```

Have you seen any errors since you've been testing?

I'm wondering about the panic below. I can see how there may be no benefit to continuing but I'm not sure how to reliably continue from the point of failure after restarting this job.

Could we retry?

Or, is this a use-case for a journal? get list of objects to queue, write list to journal, take action on list, write action to journal, etc so a restart can pick up where it left off?

---

*[cmd/reproc/reproc.go, line 89 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky2CxR1KrVLt12Ec-hE:-Ky2CxR1KrVLt12Ec-hF:b-uhelcy) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/reproc.go#L89)):*
> ```Go
> 		if err != nil {
> 			log.Println(err)
> 			ec := atomic.AddInt32(&errCount, 1)
> ```

I predict that the aeflex service will see more errors than gcs. Can we have two error counts to test this hypothesis?

---

*[cmd/reproc/reproc.go, line 97 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky2FwnS2DqIxyFdr0Ur:-Ky2FwnS2DqIxyFdr0Us:b-2bby1v) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/reproc.go#L97)):*
> ```Go
> }
> 
> func queueFor(prefix string) string {
> ```

A comment that queueFor operates on YYYY/MM/DD strings? Maybe name the function queueForDay? Do we want to sort on any other quantity?

---

*[cmd/reproc/reproc.go, line 143 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky2GwfSztVAPgOzNGHb:-Ky2GwfTdknjY0zsg-DP:b-yhcg7q) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/reproc.go#L143)):*
> ```Go
> 			queue := queueFor(o.Prefix)
> 			wg.Add(1)
> 			go postDay(&wg, queue, it)
> ```

How many posts can we practically handle at once? in theory this could create ~16k / day posts very quickly for a single month?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/298#-:-Ky2Ii-KpNY-fGbqU3G8:b40zdb6)*

**Comment by gfr10598** [comment]
Review status: 1 of 3 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[cmd/reproc/README.md, line 2 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1eJP2rxe4qpFuwmDV:-Ky2X5P3Hukj_Juf-bru:bi0v5m3) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L2)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: wrap at 80 cols.
</blockquote></details>

Done ( I think)

---

*[cmd/reproc/README.md, line 2 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1eVLapHBuzadfKlNL:-Ky2ZTlZLPnFZt_tJQGl:b-7rl0kd) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L2)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest either not using a default project (so it's always set explicitly) or setting the default to non-prod. 

The principle here is to try to minimize unintended side-effects on production from a new user experimenting with a new tool.
</blockquote></details>

done

---

*[cmd/reproc/README.md, line 16 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1eyPZfTByjx1e3kz_:-Ky2XdFrMWMm1tz63V7o:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L16)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest copying the output from `--help` or referring the user to run `--help` rather than duplicating this code in the README.
</blockquote></details>

Done.

---

*[cmd/reproc/README.md, line 25 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1fC-rrel2HraxrW_V:-Ky2YbMV7bq4bccM_qgf:bkr0gih) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L25)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I support your goal to use standard sql globally. Is there inconsistency from bq between table references in standard sql and the bq cli tool? Is there a way to use the standard sql table references here?
</blockquote></details>

looks like --nouse_legacy_sql works with queries, but not with mk.  It accepts it, but still requires the : as the project:dataset separator.  Not clear if it impacts the default query style for the table.

---

*[cmd/reproc/README.md, line 30 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1faNy3Pfxzv8YtT_b:-Ky2ZMsbKD6Kx38f5usp:b-53yqa) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L30)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please create an issue for this rather than a note in the readme?
</blockquote></details>

It is #296 

---

*[cmd/reproc/reproc.go, line 59 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky2AW7gDRi_FHfWhoax:-Ky2_r1C4Vz5vXu74hpy:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/reproc.go#L59)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since this is an appspot subdomain, the HTTPS address should also be available. Please prefer HTTPS where available.
</blockquote></details>

Done.

---

*[cmd/reproc/reproc.go, line 79 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky2CXpD81v0_8PBB7ip:-Ky2_sKsoZzjLYmBuWzG:b-86yglx) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/reproc.go#L79)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Have you seen any errors since you've been testing?

I'm wondering about the panic below. I can see how there may be no benefit to continuing but I'm not sure how to reliably continue from the point of failure after restarting this job.

Could we retry?

Or, is this a use-case for a journal? get list of objects to queue, write list to journal, take action on list, write action to journal, etc so a restart can pick up where it left off?
</blockquote></details>

Only when I deliberately use an invalid queue name.
I'll think about this.  Already added todo to consider retries of some kind.

---

*[cmd/reproc/reproc.go, line 89 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky2CxR1KrVLt12Ec-hE:-Ky2a-OokccQj-qX19Pj:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/reproc.go#L89)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I predict that the aeflex service will see more errors than gcs. Can we have two error counts to test this hypothesis?
</blockquote></details>

Done.

---

*[cmd/reproc/reproc.go, line 143 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky2GwfSztVAPgOzNGHb:-Ky2a1g2TwlNyGl-M551:b-35vwoz) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/reproc.go#L143)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

How many posts can we practically handle at once? in theory this could create ~16k / day posts very quickly for a single month?
</blockquote></details>

Lots.  The queue limit is I think 1 billion.  500K takes up about 300MB, and I have allocated 2GB.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/298)*

**Comment by gfr10598** [comment]
Review status: 1 of 3 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[cmd/reproc/README.md, line 2 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1eJP2rxe4qpFuwmDV:-Ky2X5P3Hukj_Juf-bru:bi0v5m3) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L2)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: wrap at 80 cols.
</blockquote></details>

Done ( I think)

---

*[cmd/reproc/README.md, line 2 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1eVLapHBuzadfKlNL:-Ky2ZTlZLPnFZt_tJQGl:b-7rl0kd) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L2)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest either not using a default project (so it's always set explicitly) or setting the default to non-prod. 

The principle here is to try to minimize unintended side-effects on production from a new user experimenting with a new tool.
</blockquote></details>

done

---

*[cmd/reproc/README.md, line 16 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1eyPZfTByjx1e3kz_:-Ky2XdFrMWMm1tz63V7o:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L16)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest copying the output from `--help` or referring the user to run `--help` rather than duplicating this code in the README.
</blockquote></details>

Done.

---

*[cmd/reproc/README.md, line 25 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1fC-rrel2HraxrW_V:-Ky2YbMV7bq4bccM_qgf:bkr0gih) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L25)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I support your goal to use standard sql globally. Is there inconsistency from bq between table references in standard sql and the bq cli tool? Is there a way to use the standard sql table references here?
</blockquote></details>

looks like --nouse_legacy_sql works with queries, but not with mk.  It accepts it, but still requires the : as the project:dataset separator.  Not clear if it impacts the default query style for the table.

---

*[cmd/reproc/README.md, line 30 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1faNy3Pfxzv8YtT_b:-Ky2ZMsbKD6Kx38f5usp:b-53yqa) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L30)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please create an issue for this rather than a note in the readme?
</blockquote></details>

It is #296 

---

*[cmd/reproc/reproc.go, line 59 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky2AW7gDRi_FHfWhoax:-Ky2_r1C4Vz5vXu74hpy:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/reproc.go#L59)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since this is an appspot subdomain, the HTTPS address should also be available. Please prefer HTTPS where available.
</blockquote></details>

Done.

---

*[cmd/reproc/reproc.go, line 79 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky2CXpD81v0_8PBB7ip:-Ky2_sKsoZzjLYmBuWzG:b-86yglx) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/reproc.go#L79)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Have you seen any errors since you've been testing?

I'm wondering about the panic below. I can see how there may be no benefit to continuing but I'm not sure how to reliably continue from the point of failure after restarting this job.

Could we retry?

Or, is this a use-case for a journal? get list of objects to queue, write list to journal, take action on list, write action to journal, etc so a restart can pick up where it left off?
</blockquote></details>

Only when I deliberately use an invalid queue name.
I'll think about this.  Already added todo to consider retries of some kind.

---

*[cmd/reproc/reproc.go, line 89 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky2CxR1KrVLt12Ec-hE:-Ky2a-OokccQj-qX19Pj:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/reproc.go#L89)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I predict that the aeflex service will see more errors than gcs. Can we have two error counts to test this hypothesis?
</blockquote></details>

Done.

---

*[cmd/reproc/reproc.go, line 143 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky2GwfSztVAPgOzNGHb:-Ky2a1g2TwlNyGl-M551:b-35vwoz) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/reproc.go#L143)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

How many posts can we practically handle at once? in theory this could create ~16k / day posts very quickly for a single month?
</blockquote></details>

Lots.  The queue limit is I think 1 billion.  500K takes up about 300MB, and I have allocated 2GB.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/298)*

**Comment by gfr10598** [comment]
PTAL

---

Review status: 0 of 4 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/298#-:-KyM7f7TOdJi-XOxxTOf:bb71pro)*

**Comment by stephen-soltesz** [comment]
From casual conversation, it sounds like we'll build upon the logic in `reproc` over time as we reprocess more historical archives and reprocess recent history as a matter of common course. Maybe we'll run the `reproc` command in batch environments that we'll want to monitor.

Since we expect to depend on this code more over time, my thought is that it would be worthwhile to invest the time to separate the logic from global flags into a separate module. For example, a separate module would not require the manipulations of command line arguments in tests.

Happy to discuss how to balance this with more expedient goals.

---

Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[cmd/reproc/README.md, line 2 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1eJP2rxe4qpFuwmDV:-KyM9voVCmlF0FLfiIdk:b-jftcti) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L2)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Done ( I think)
</blockquote></details>

Please wrap README text at 80 cols.

---

*[cmd/reproc/README.md, line 2 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1eVLapHBuzadfKlNL:-KyMA1L95Xa85nSjG7w-:b-1pdhk4) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L2)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

done
</blockquote></details>

You said "done" but the production project is still described as the default. 

---

*[cmd/reproc/reproc.go, line 40 at r9](https://reviewable.io:443/reviews/m-lab/etl/298#-KyMEbJOy3R6WIxpKGy3:-KyMEbJOy3R6WIxpKGy4:bhsa0yg) ([raw file](https://github.com/m-lab/etl/blob/1d9d647d2ae826b9f90fec4258eebcae863401f9/cmd/reproc/reproc.go#L40)):*
> ```Go
> 
> func (dr *dryRunHTTP) Get(url string) (resp *http.Response, err error) {
> 	resp = &http.Response{}
> ```

log URLs under some conditions? (I realize there will be many)

---

*[cmd/reproc/reproc.go, line 195 at r9](https://reviewable.io:443/reviews/m-lab/etl/298#-KyMCtI90Y0gaZbBFZPK:-KyMCtI90Y0gaZbBFZPL:bgjqclf) ([raw file](https://github.com/m-lab/etl/blob/1d9d647d2ae826b9f90fec4258eebcae863401f9/cmd/reproc/reproc.go#L195)):*
> ```Go
> 
> 	bucket = storageClient.Bucket(*fBucket)
> 	_, err = bucket.Attrs(context.Background())
> ```

This is just to verify the credentials are setup correctly? And, that the bucket exists?

---

*[cmd/reproc/reproc.go, line 212 at r9](https://reviewable.io:443/reviews/m-lab/etl/298#-KyMDps4G5O-l42LySF8:-KyMDps4G5O-l42LySF9:bistgc8) ([raw file](https://github.com/m-lab/etl/blob/1d9d647d2ae826b9f90fec4258eebcae863401f9/cmd/reproc/reproc.go#L212)):*
> ```Go
> func main() {
> 	flag.Parse()
> 	if *fProject == "" && !*fDryRun {
> ```

It looks like nothing would crash, but running with `fProject == ""` and `fDryRun == true` would use incomplete queue pusher urls.

---

*[cmd/reproc/reproc_test.go, line 16 at r8](https://reviewable.io:443/reviews/m-lab/etl/298#-KyMIUHyYaaFUiiSJTGE:-KyMIUHyYaaFUiiSJTGF:b-rsj6o6) ([raw file](https://github.com/m-lab/etl/blob/3b75752c9860c883979e2eb9a6a7763851395dd5/cmd/reproc/reproc_test.go#L16)):*
> ```Go
> // ResetFlags restores the command line flags to their default
> // values.  This does NOT reset the result of Parsed().
> func ResetFlags() {
> ```

Oh, neat. I didn't know this was possible.

---

*[cmd/reproc/reproc_test.go, line 50 at r8](https://reviewable.io:443/reviews/m-lab/etl/298#-KyMJVzMlM4ehyB4uCb_:-KyMJVzMlM4ehyB4uCba:be6royj) ([raw file](https://github.com/m-lab/etl/blob/3b75752c9860c883979e2eb9a6a7763851395dd5/cmd/reproc/reproc_test.go#L50)):*
> ```Go
> 
> // NOTE: This test depends on the contents of the test-archive-mlab-sandbox
> // bucket.  If it fails, check whether that bucket has been modified.
> ```

A README or WARNING file at the base of gs://test-archive-mlab-sandbox could help guard the contents of that bucket.

---

*[cmd/reproc/reproc_test.go, line 67 at r8](https://reviewable.io:443/reviews/m-lab/etl/298#-KyMKqN5KMEYrTpp2XLa:-KyMKqN5KMEYrTpp2XLb:b-llv0wj) ([raw file](https://github.com/m-lab/etl/blob/3b75752c9860c883979e2eb9a6a7763851395dd5/cmd/reproc/reproc_test.go#L67)):*
> ```Go
> // NOTE: This test depends on the contents of the test-archive-mlab-sandbox
> // bucket.  If it fails, check whether that bucket has been modified.
> func Example_month() {
> ```

Aaah, I've never used `Example` functions before. I like it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/298#-:-KyML51YS3xYl-uvydGw:bd2ui1v)*

**Comment by gfr10598** [comment]
PTAL.

Adding a TODO at the var declaration along these lines.

---

Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[cmd/reproc/README.md, line 2 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1eJP2rxe4qpFuwmDV:-KyMXpNWM3EBHA50v83E:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L2)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please wrap README text at 80 cols.
</blockquote></details>

Done.

---

*[cmd/reproc/README.md, line 2 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky1eVLapHBuzadfKlNL:-KyMXwSOn_CZZcEV7JLE:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/README.md#L2)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

You said "done" but the production project is still described as the default. 
</blockquote></details>

Done.

---

*[cmd/reproc/reproc.go, line 97 at r1](https://reviewable.io:443/reviews/m-lab/etl/298#-Ky2FwnS2DqIxyFdr0Ur:-KyMSjfvNe7Vk7GSGvVk:b-nb9xle) ([raw file](https://github.com/m-lab/etl/blob/6f34f0954e55b2941dde0a3f7160be08ae4daff9/cmd/reproc/reproc.go#L97)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

A comment that queueFor operates on YYYY/MM/DD strings? Maybe name the function queueForDay? Do we want to sort on any other quantity?
</blockquote></details>

It operates on timestamps.  Changed name to queueForDate, which is most accurate I think.

---

*[cmd/reproc/reproc.go, line 40 at r9](https://reviewable.io:443/reviews/m-lab/etl/298#-KyMEbJOy3R6WIxpKGy3:-KyMSHVBueYSorjh3E4m:b-u637ie) ([raw file](https://github.com/m-lab/etl/blob/1d9d647d2ae826b9f90fec4258eebcae863401f9/cmd/reproc/reproc.go#L40)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

log URLs under some conditions? (I realize there will be many)
</blockquote></details>

Not sure what you mean?  Generally, or for dry-run?  A typical day would generate 16K urls.

---

*[cmd/reproc/reproc.go, line 195 at r9](https://reviewable.io:443/reviews/m-lab/etl/298#-KyMCtI90Y0gaZbBFZPK:-KyMSyz1QOeEeR6lT8Xi:bcunndk) ([raw file](https://github.com/m-lab/etl/blob/1d9d647d2ae826b9f90fec4258eebcae863401f9/cmd/reproc/reproc.go#L195)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This is just to verify the credentials are setup correctly? And, that the bucket exists?
</blockquote></details>

Correct.  Added comment.

---

*[cmd/reproc/reproc.go, line 212 at r9](https://reviewable.io:443/reviews/m-lab/etl/298#-KyMDps4G5O-l42LySF8:-KyMTgSJLWikHuiSfg8M:b-bizqh8) ([raw file](https://github.com/m-lab/etl/blob/1d9d647d2ae826b9f90fec4258eebcae863401f9/cmd/reproc/reproc.go#L212)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It looks like nothing would crash, but running with `fProject == ""` and `fDryRun == true` would use incomplete queue pusher urls.
</blockquote></details>

Added comment.

---

*[cmd/reproc/reproc_test.go, line 16 at r8](https://reviewable.io:443/reviews/m-lab/etl/298#-KyMIUHyYaaFUiiSJTGE:-KyMTiJqFMy5NI6SGN2L:buz449v) ([raw file](https://github.com/m-lab/etl/blob/3b75752c9860c883979e2eb9a6a7763851395dd5/cmd/reproc/reproc_test.go#L16)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Oh, neat. I didn't know this was possible.
</blockquote></details>

::smile::

---

*[cmd/reproc/reproc_test.go, line 50 at r8](https://reviewable.io:443/reviews/m-lab/etl/298#-KyMJVzMlM4ehyB4uCb_:-KyMVMoPs4qATyLoPtUy:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/3b75752c9860c883979e2eb9a6a7763851395dd5/cmd/reproc/reproc_test.go#L50)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

A README or WARNING file at the base of gs://test-archive-mlab-sandbox could help guard the contents of that bucket.
</blockquote></details>

Done.

---

*[cmd/reproc/reproc_test.go, line 67 at r8](https://reviewable.io:443/reviews/m-lab/etl/298#-KyMKqN5KMEYrTpp2XLa:-KyMTu9zpIAEqjaO4f8R:b-izmygt) ([raw file](https://github.com/m-lab/etl/blob/3b75752c9860c883979e2eb9a6a7763851395dd5/cmd/reproc/reproc_test.go#L67)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Aaah, I've never used `Example` functions before. I like it.
</blockquote></details>

::big smile::

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/298#-:-KyMZ4n15_xgYuRjEMz0:b-2ivmcs)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r7, 1 of 1 files at r8, 2 of 2 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmd/reproc/reproc.go, line 40 at r9](https://reviewable.io:443/reviews/m-lab/etl/298#-KyMEbJOy3R6WIxpKGy3:-KyMcXcMkDvpEpOHp1_p:b-oezwq2) ([raw file](https://github.com/m-lab/etl/blob/1d9d647d2ae826b9f90fec4258eebcae863401f9/cmd/reproc/reproc.go#L40)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Not sure what you mean?  Generally, or for dry-run?  A typical day would generate 16K urls.
</blockquote></details>

I think of "dry run" as kind of like a "debug" mode, where printing the urls might be helpful. Maybe every %1000. Just as a hint. Just an idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/298#-:-KyMkXlqkhrt6ZY2W2Fb:bnfp4nl)*

**Pull request merged**
