### PR TITLE
Queue pusher

### PR DESCRIPTION
**Pull request by gfr10598**
Add a queue parameter to the queue pusher, to support batch queues.

Also adds some basic unit tests for the receiver function.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/295)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[appengine/queue_pusher/queue_pusher.go, line 56 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-Kxs5kssuEiwG2zJva5G:-Kxs5kssuEiwG2zJva5H:b-jnd48a) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher.go#L56)):*
> ```Go
> func queueStats(w http.ResponseWriter, r *http.Request) {
> 	queuename := r.FormValue("queuename")
> 	test := r.FormValue("test-bypass")
> ```

This feels a little funny to change the public interface but it may not be worse than the better.

---

*[appengine/queue_pusher/queue_pusher.go, line 98 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-KxrzryDWPTvBChmUYOg:-KxrzryDWPTvBChmUYOh:bncfr46) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher.go#L98)):*
> ```Go
> 
> // receiver accepts a GET request, and transforms the given parameters into a TaskQueue Task.
> // TODO - this should expect a POST, for consistency with REST api?
> ```

Can this TODO be combined with the one below?

---

*[appengine/queue_pusher/queue_pusher_test.go, line 22 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-Kxs1KryE9zzOy4HuksL:-Kxs1KryE9zzOy4HuksM:bl5cdig) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher_test.go#L22)):*
> ```Go
> 	if w.Result().StatusCode != http.StatusOK {
> 		b, _ := ioutil.ReadAll(w.Body)
> 		log.Println(string(b))
> ```

Should we favor `t.Log()` to report more information in tests. Or multiple `t.Error()`. This will keep the formatting consistent.

---

*[appengine/queue_pusher/queue_pusher_test.go, line 26 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-Kxs350gW9G0UvIYh057:-Kxs350gW9G0UvIYh058:b-d3mex6) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher_test.go#L26)):*
> ```Go
> 	}
> 
> 	// TODO - is this working as intended?
> ```

Based on defaultHandler, I expect this to fail, with a status code of`http.StatusMethodNotAllowed`. Why doesn't it?

---

*[appengine/queue_pusher/queue_pusher_test.go, line 54 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-Kxs4-3XEptgs-13uj8X:-Kxs4-3Yow48M-lnd64L:b-896fig) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher_test.go#L54)):*
> ```Go
> 		status   int
> 	}{
> 		// TODO: Add test cases.
> ```

Done?

---

*[appengine/queue_pusher/queue_pusher_test.go, line 91 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-Kxs4AE3Cmh35qzFNPzh:-Kxs4AE3Cmh35qzFNPzi:bwy3yd2) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher_test.go#L91)):*
> ```Go
> 		t.Run(tt.name, func(t *testing.T) {
> 			var reqStr string
> 			if tt.queue != "" {
> ```

None of the test cases above are non-empty. Is this intendend?

---

*[appengine/queue_pusher/queue_pusher_test.go, line 100 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-Kxs5UWA0gShaP7ofoo_:-Kxs5UWA0gShaP7ofooa:bmaadv0) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher_test.go#L100)):*
> ```Go
> 			receiver(w, r)
> 			b, _ := ioutil.ReadAll(w.Body)
> 			log.Println(string(b))
> ```

`t.Log()`? Or, only on error?

---

*[appengine/queue_pusher/queue_pusher_test.go, line 115 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-Kxs5JDpX_ojTUDKN1BW:-Kxs5JDpX_ojTUDKN1BX:b-896fig) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher_test.go#L115)):*
> ```Go
> 		status   int
> 	}{
> 		// TODO: Add test cases.
> ```

Done?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/295)*

**Comment by gfr10598** [comment]
PTAL.  The missing StatusMethodNotAllowed is really strange.

---

Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[appengine/queue_pusher/queue_pusher.go, line 56 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-Kxs5kssuEiwG2zJva5G:-KxsAdKxouY7t6Dvt4HX:b-c1wdr6) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher.go#L56)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This feels a little funny to change the public interface but it may not be worse than the better.
</blockquote></details>

I think it is the cleanest mechanism.

---

*[appengine/queue_pusher/queue_pusher.go, line 98 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-KxrzryDWPTvBChmUYOg:-KxsAoHD0cZ7z1Rjsl7F:b7zae6f) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher.go#L98)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Can this TODO be combined with the one below?
</blockquote></details>

d'oh
removed.  I think the other is adequate.

---

*[appengine/queue_pusher/queue_pusher_test.go, line 22 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-Kxs1KryE9zzOy4HuksL:-KxsCoLVBgbNa9KO5zbd:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher_test.go#L22)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Should we favor `t.Log()` to report more information in tests. Or multiple `t.Error()`. This will keep the formatting consistent.
</blockquote></details>

Done.

---

*[appengine/queue_pusher/queue_pusher_test.go, line 26 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-Kxs350gW9G0UvIYh057:-KxsCqsEIo6Z6yMl57Fw:b-bypzd4) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher_test.go#L26)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Based on defaultHandler, I expect this to fail, with a status code of`http.StatusMethodNotAllowed`. Why doesn't it?
</blockquote></details>

Don't know.  That is what the "working as intended" comment was intended to highlight.
I just checked and it is definitely getting the POST, and executing  the http.Error call.  But after the Error call, the status is actually 200.  Strange!

I verified that the same log statement shows the correct 400 code when the queue name is empty in queueStats.

---

*[appengine/queue_pusher/queue_pusher_test.go, line 54 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-Kxs4-3XEptgs-13uj8X:-KxsAzkL_SMiE-AUtB7a:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher_test.go#L54)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Done?
</blockquote></details>

Done.

---

*[appengine/queue_pusher/queue_pusher_test.go, line 91 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-Kxs4AE3Cmh35qzFNPzh:-KxsBlLv6KhO_n8QisWC:b-qjqe8y) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher_test.go#L91)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

None of the test cases above are non-empty. Is this intendend?
</blockquote></details>

Good point.  Deleted code.

---

*[appengine/queue_pusher/queue_pusher_test.go, line 100 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-Kxs5UWA0gShaP7ofoo_:-KxsCJvgBi3_3TStdgwC:b-qu7obs) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher_test.go#L100)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`t.Log()`? Or, only on error?
</blockquote></details>

Moved inside and changed to t.

---

*[appengine/queue_pusher/queue_pusher_test.go, line 115 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-Kxs5JDpX_ojTUDKN1BW:-KxsAL034xXFTxxdhlC_:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher_test.go#L115)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Done?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/295#-:-KxsGE7lfgeMflYkVzMB:b-n01voa)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[appengine/queue_pusher/queue_pusher_test.go, line 26 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-Kxs350gW9G0UvIYh057:-KxsHr1aRhyx6WZQr8dr:b-bkhshe) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher_test.go#L26)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Don't know.  That is what the "working as intended" comment was intended to highlight.
I just checked and it is definitely getting the POST, and executing  the http.Error call.  But after the Error call, the status is actually 200.  Strange!

I verified that the same log statement shows the correct 400 code when the queue name is empty in queueStats.


</blockquote></details>

O_o -- that is really strange.

Maybe update the above TODO question to a statement. This is not WAI.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/295#-:-KxsIlah4RYWf3d3ls6j:bnfp4nl)*

**Comment by gfr10598** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[appengine/queue_pusher/queue_pusher_test.go, line 26 at r2](https://reviewable.io:443/reviews/m-lab/etl/295#-Kxs350gW9G0UvIYh057:-KxsjugNJenChKtgpL54:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/cb5655c99897d5e5a688febf440b80fd0a696414/appengine/queue_pusher/queue_pusher_test.go#L26)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

O_o -- that is really strange.

Maybe update the above TODO question to a statement. This is not WAI.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/295)*

**Pull request merged**
