### PR TITLE
First step in expanding pcap parser

### PR DESCRIPTION
**Pull request by gfr10598**
This PR adds code to the pcap parser that uses gopacket to parse the top level packets from the pcap rawcontent.
It does not parse the IP or TCP headers, as the gopacket implementation is rather heavyweight. 
Two new histogram metrics are introduced, in the pcap.go file (which is debatable) to track the connection duration and packet counts.  These may not be important long term, but have been useful for development.

During development, I managed to cause some instance restarts with array index panics, so I added the panic handling to the active polling code.  I also fixed the very very noisy labelling for the FileCount metric.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/1031)

### CODE REVIEW

**Comment by gfr10598** [comment]
Prototype dashboard with the new metrics is here:
https://grafana.mlab-sandbox.measurementlab.net/goto/8Jd3j4pnk?orgId=1

**Comment by gfr10598** [comment]
The benchmark is fairly complex, and I think the stats are the average across the three files that it parses.
BenchmarkGetPackets-8   	    2156	    493474 ns/op	 1181692 B/op	    1892 allocs/op

The associated profile looks like this:
profile006

**Review by cristinaleonr — COMMENTED** [review]
Nice panels and profiling!

> Reviewed 2 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1031#-:-Mp7n5Jb5qTgIEQBVBed:bmi20d3)* status: 0 of 1 approvals obtained (waiting on @gfr10598)

___
*[go.mod, line 17 at r3](https://reviewable.io/reviews/m-lab/etl/1031#-Mp7k0Dg8jqHceAvbNWR:-Mp7k0Dh2Z010pdelft8:bdmi48e) ([raw file](https://github.com/m-lab/etl/blob/2557e800f7186066e79a261a13e50573c69d3351/go.mod#L17)):*
> ```XML
> 	github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da // indirect
> 	github.com/google/go-jsonnet v0.17.0
> 	github.com/google/gopacket v1.1.19 // indirect
> ```

I see the warning "github.com/google/gopacket should be direct go mod tidy" under this line when I check out the branch. Would you mind running `go mod tidy`?
___
*[active/poller.go, line 126 at r3](https://reviewable.io/reviews/m-lab/etl/1031#-Mp7exH12FOkp85zhX1O:-Mp7exH12FOkp85zhX1P:b6t1gf2) ([raw file](https://github.com/m-lab/etl/blob/2557e800f7186066e79a261a13e50573c69d3351/active/poller.go#L126)):*
> ```Go
> 
> 			// Capture any panic and convert it to an error.
> 			defer func(tag string) {
> ```

Are we using this `tag`?
___
*[active/poller.go, line 219 at r3](https://reviewable.io/reviews/m-lab/etl/1031#-Mp7dN388N3oYVxsHbWc:-Mp7dN388N3oYVxsHbWd:b-m146wi) ([raw file](https://github.com/m-lab/etl/blob/2557e800f7186066e79a261a13e50573c69d3351/active/poller.go#L219)):*
> ```Go
> 		err := eg.Wait()
> 		if err != nil {
> 			log.Println(err, "on wait for", job.Path())
> ```

Should we return here? We're printing out the error followed by "finished".
___
*[parser/pcap.go, line 35 at r3](https://reviewable.io/reviews/m-lab/etl/1031#-Mp7dia6DW3lctXHJkK4:-Mp7dia6DW3lctXHJkK5:b-cb49yj) ([raw file](https://github.com/m-lab/etl/blob/2557e800f7186066e79a261a13e50573c69d3351/parser/pcap.go#L35)):*
> ```Go
> 	ErrNoIPLayer = fmt.Errorf("no IP layer")
> 
> 	PcapPacketCount = promauto.NewHistogramVec(
> ```

Does it make sense to put these metrics under `metrics.go`? 
___
*[parser/pcap.go, line 113 at r3](https://reviewable.io/reviews/m-lab/etl/1031#-Mp7e1JL8GH5-N7vYtdW:-Mp7e1JL8GH5-N7vYtdX:btgpj88) ([raw file](https://github.com/m-lab/etl/blob/2557e800f7186066e79a261a13e50573c69d3351/parser/pcap.go#L113)):*
> ```Go
> // GetIP decodes the IP layers and returns some basic information.
> func (p *Packet) GetIP() (net.IP, net.IP, uint8, uint16, error) {
> 	// Decode a packet
> ```

Nitpick: missing period.
___
*[parser/pcap.go, line 148 at r3](https://reviewable.io/reviews/m-lab/etl/1031#-Mp7j6VN-IRSF0t1SSsi:-Mp7j6VN-IRSF0t1SSsj:b-u0zrmg) ([raw file](https://github.com/m-lab/etl/blob/2557e800f7186066e79a261a13e50573c69d3351/parser/pcap.go#L148)):*
> ```Go
> 	}
> 
> 	if err != nil {
> ```

Do we want to return the error here (otherwise we're returning a `nil` error)?
___
*[parser/pcap_test.go, line 148 at r3](https://reviewable.io/reviews/m-lab/etl/1031#-Mp7hF3jEsmcrULeuvxT:-Mp7hF3jEsmcrULeuvxU:b6y47hq) ([raw file](https://github.com/m-lab/etl/blob/2557e800f7186066e79a261a13e50573c69d3351/parser/pcap_test.go#L148)):*
> ```Go
> 	}
> 	tests := []test{
> 		{name: "retransmits", fn: "testfiles/ndt-nnwk2_1611335823_00000000000C2DFE.pcap.gz",
> ```

Minor: there is an existing `testdata/PCAP` path.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1031)* status: 0 of 1 approvals obtained (waiting on @gfr10598)

___
*[parser/pcap.go, line 142 at r3](https://reviewable.io/reviews/m-lab/etl/1031#-Mp7oL6F0F7Tzu9qn_tk:-Mp7oL6F0F7Tzu9qn_tl:bkd66f7) ([raw file](https://github.com/m-lab/etl/blob/2557e800f7186066e79a261a13e50573c69d3351/parser/pcap.go#L142)):*
> ```Go
> 
> 	// TODO - should we use MSS instead?
> 	packets := make([]Packet, 0, len(data)/18)
> ```

Out of curiosity, where did the 18 number come from?

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1031)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[go.mod, line 17 at r3](https://reviewable.io/reviews/m-lab/etl/1031#-Mp7k0Dg8jqHceAvbNWR:-Mp9PcSC20thXbUyDANV:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/2557e800f7186066e79a261a13e50573c69d3351/go.mod#L17)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

I see the warning "github.com/google/gopacket should be direct go mod tidy" under this line when I check out the branch. Would you mind running `go mod tidy`?
</blockquote></details>

Done.
___
*[active/poller.go, line 126 at r3](https://reviewable.io/reviews/m-lab/etl/1031#-Mp7exH12FOkp85zhX1O:-Mp7tuwr8-eJSGlYfA1x:bctv9fa) ([raw file](https://github.com/m-lab/etl/blob/2557e800f7186066e79a261a13e50573c69d3351/active/poller.go#L126)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Are we using this `tag`?
</blockquote></details>

Good point.  Fixed.
___
*[active/poller.go, line 219 at r3](https://reviewable.io/reviews/m-lab/etl/1031#-Mp7dN388N3oYVxsHbWc:-Mp7vQzzBpxp_CNc3cFr:b-9lslq0) ([raw file](https://github.com/m-lab/etl/blob/2557e800f7186066e79a261a13e50573c69d3351/active/poller.go#L219)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Should we return here? We're printing out the error followed by "finished".
</blockquote></details>

tweaked.
___
*[parser/pcap.go, line 35 at r3](https://reviewable.io/reviews/m-lab/etl/1031#-Mp7dia6DW3lctXHJkK4:-Mp7tFfS9Q9BnMn59TFI:bmadfns) ([raw file](https://github.com/m-lab/etl/blob/2557e800f7186066e79a261a13e50573c69d3351/parser/pcap.go#L35)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Does it make sense to put these metrics under `metrics.go`? 
</blockquote></details>

 Moved them.  Thinking about what is the best way to handle lots of metrics.  Maybe different files within a single package.  But for now, I've just continued the previous pattern.
___
*[parser/pcap.go, line 113 at r3](https://reviewable.io/reviews/m-lab/etl/1031#-Mp7e1JL8GH5-N7vYtdW:-Mp9QVDY-FfmlWJl1mId:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/2557e800f7186066e79a261a13e50573c69d3351/parser/pcap.go#L113)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Nitpick: missing period.
</blockquote></details>

Done.
___
*[parser/pcap.go, line 142 at r3](https://reviewable.io/reviews/m-lab/etl/1031#-Mp7oL6F0F7Tzu9qn_tk:-Mp7tWNM5iLxYPAms0TS:bsghwkk) ([raw file](https://github.com/m-lab/etl/blob/2557e800f7186066e79a261a13e50573c69d3351/parser/pcap.go#L142)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Out of curiosity, where did the 18 number come from?
</blockquote></details>

I'll add a comment.  It was measured by observing the ratio of source data size to number of packets for three files, and choosing the smallest one.

Unfortunately, this change seems to have caused the sandbox to start crashing, which makes no sense at all.  But I'm reverting it in any case.
___
*[parser/pcap.go, line 148 at r3](https://reviewable.io/reviews/m-lab/etl/1031#-Mp7j6VN-IRSF0t1SSsi:-Mp7vnWUE3P_P3rYggZN:bw0a2pt) ([raw file](https://github.com/m-lab/etl/blob/2557e800f7186066e79a261a13e50573c69d3351/parser/pcap.go#L148)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Do we want to return the error here (otherwise we're returning a `nil` error)?
</blockquote></details>

Yup - thanks.
___
*[parser/pcap_test.go, line 148 at r3](https://reviewable.io/reviews/m-lab/etl/1031#-Mp7hF3jEsmcrULeuvxT:-Mp9QYCG6eByRZz_g75j:bzewvk) ([raw file](https://github.com/m-lab/etl/blob/2557e800f7186066e79a261a13e50573c69d3351/parser/pcap_test.go#L148)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Minor: there is an existing `testdata/PCAP` path.
</blockquote></details>

Good point.  I'll move these there.

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1031#-:-MpCHhEK-nU-KqSHnaq9:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
