### PR TITLE
Add cloud function deploy for parser task queue triggering in .travis.yml

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/535)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[.travis.yml, line 159 at r1](https://reviewable.io/reviews/m-lab/etl/535#-LGBt1YD14MQM0LfJBv1:-LGBt1YD14MQM0LfJBv2:b-51sbj4) ([raw file](https://github.com/m-lab/etl/blob/383cc13740d3ef94bdddf091a031ab68df92b75f/.travis.yml#L159)):*
> ```YAML
>     repo: m-lab/etl
>     all_branches: true
>     condition: $TRAVIS_BRANCH == cf-sandbox-* || $TRAVIS_BRANCH == sandbox-*
> ```

This matches different patterns than you had in the earlier pr. Is that intentional?

---

*[.travis.yml, line 294 at r1](https://reviewable.io/reviews/m-lab/etl/535#-LGBt9hw5Y3-cvXZro9u:-LGBt9hw5Y3-cvXZro9v:bjm8lq) ([raw file](https://github.com/m-lab/etl/blob/383cc13740d3ef94bdddf091a031ab68df92b75f/.travis.yml#L294)):*
> ```YAML
>     SERVICE_ACCOUNT_mlab_oti $TRAVIS_BUILD_DIR/appengine/queue_pusher
>     && cd $TRAVIS_BUILD_DIR/functions
>     && gcloud beta functions deploy createProdTaskOnFileNotification --stage-bucket=functions-mlab-oti --trigger-resource=archive-mlab-oti --project=mlab-oti
> ```

Please use the same pattern for mlab-oti.

We only want three instances of `gcloud beta functions deploy` for the archive buckets, one for each project.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/535)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[.travis.yml, line 155 at r1](https://reviewable.io/reviews/m-lab/etl/535#-LGBtZpg0e_gMEpMJ3M1:-LGBtZpg0e_gMEpMJ3M2:b-c17zpu) ([raw file](https://github.com/m-lab/etl/blob/383cc13740d3ef94bdddf091a031ab68df92b75f/.travis.yml#L155)):*
> ```YAML
>     && cd $TRAVIS_BUILD_DIR/functions
>     && gcloud beta functions deploy createSandboxTaskOnFileNotification --stage-bucket=functions-mlab-sandbox --trigger-resource=archive-mlab-sandbox --project=mlab-sandbox
>   skip_cleanup: true  
> ```

nit: Looks like there is some eol whitespace here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/535)*

**Comment by yachang** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[.travis.yml, line 159 at r1](https://reviewable.io/reviews/m-lab/etl/535#-LGBt1YD14MQM0LfJBv1:-LGBvmVA-nzRjgI9L0pX:bb77ufg) ([raw file](https://github.com/m-lab/etl/blob/383cc13740d3ef94bdddf091a031ab68df92b75f/.travis.yml#L159)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This matches different patterns than you had in the earlier pr. Is that intentional?
</blockquote></details>

Yes.

---

*[.travis.yml, line 294 at r1](https://reviewable.io/reviews/m-lab/etl/535#-LGBt9hw5Y3-cvXZro9u:-LGBwuMoDJRaIXIQeWCG:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/383cc13740d3ef94bdddf091a031ab68df92b75f/.travis.yml#L294)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please use the same pattern for mlab-oti.

We only want three instances of `gcloud beta functions deploy` for the archive buckets, one for each project.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/535)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/535#-:-LGC0cJF06-wWBJCP7CD:bnfp4nl)*

**Pull request merged**
