### PR TITLE
Add method for GCS Path for DataPath type

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds a new helper method to recover the GCS "Path" portion of the URI. A common use case is extracting this path. As a result, this change reduces some ad-hoc parsing of the URI in favor of placing all URI parsing in the etl.DataPath type.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/993)

### CODE REVIEW

**Review by gfr10598 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/993)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[storage/rowwriter.go, line 184 at r1](https://reviewable.io/reviews/m-lab/etl/993#-McGf0O4BgSBNskoitHD:-McGf0O4BgSBNskoitHE:bsbetue) ([raw file](https://github.com/m-lab/etl/blob/724b1ee134eb86c82f9f9224e28cacf912c2729c/storage/rowwriter.go#L184)):*
> ```Go
> 	if fn == "" {
> 		return nil, factory.NewError(dp.DataType, "InvalidPath",
> 			http.StatusInternalServerError, errors.New("empty gcs path"))
> ```

"empty or invalid gcs path"

Also, I've been trying for some time to avoid inline errors.New, and instead create error vars at the top of files, instead of creating them on the fly, though I haven't been perfect about it and didn't do it in the early files in etl/.   Consider creating a file level error definition (either local or exported) at the top of the file.
___
*[storage/storage.go, line 246 at r1](https://reviewable.io/reviews/m-lab/etl/993#-McGg9cM5LWwlvRr09QV:-McGg9cM5LWwlvRr09QW:b-60wpm8) ([raw file](https://github.com/m-lab/etl/blob/724b1ee134eb86c82f9f9224e28cacf912c2729c/storage/storage.go#L246)):*
> ```Go
> 	}
> 	bucket := dp.Bucket
> 	fn := dp.Path()
> ```

check for empty fn?
___
*[storage/storage.go, line 247 at r1](https://reviewable.io/reviews/m-lab/etl/993#-McGgET44syRLg3QNUuN:-McGgET44syRLg3QNUuO:b-hkyegb) ([raw file](https://github.com/m-lab/etl/blob/b5ab8e874a3c07bbf22f98910b4f361e15cd999d/storage/storage.go#L247)):*
> ```Go
> 	parts := strings.SplitN(dp.URI, "/", 4)
> 	if len(parts) != 4 {
> 		return nil, errors.New("invalid file path: " + dp.URI)
> ```

Well - I see I didn't follow my own advice here.  8-(
___
*[storage/storage.go, line 254 at r1](https://reviewable.io/reviews/m-lab/etl/993#-McGgHgIBSdgweX2vdLr:-McGgHgIBSdgweX2vdLs:bpiog6e) ([raw file](https://github.com/m-lab/etl/blob/b5ab8e874a3c07bbf22f98910b4f361e15cd999d/storage/storage.go#L254)):*
> ```Go
> 	archiveDate, err := time.Parse("2006/01/02", dp.DatePath)
> 	if err != nil {
> 		return nil, fmt.Errorf("failed to parse archive date path: %w", err)
> ```

Or here.

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/993)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598 and @stephen-soltesz)

___
*[storage/rowwriter.go, line 184 at r1](https://reviewable.io/reviews/m-lab/etl/993#-McGf0O4BgSBNskoitHD:-McGomcW8LwFPpgRjXZA:b4r3fie) ([raw file](https://github.com/m-lab/etl/blob/724b1ee134eb86c82f9f9224e28cacf912c2729c/storage/rowwriter.go#L184)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

"empty or invalid gcs path"

Also, I've been trying for some time to avoid inline errors.New, and instead create error vars at the top of files, instead of creating them on the fly, though I haven't been perfect about it and didn't do it in the early files in etl/.   Consider creating a file level error definition (either local or exported) at the top of the file.
</blockquote></details>

Rather than worrying about return values for `Path()`, I think I'd like to update `etl.ValidateTestPath` to set a new field named `Path` so that this may be used unconditionally for validated paths. This also eliminates the redundant parsing of Path() in this implementation.

**Review by stephen-soltesz — COMMENTED** [review]
PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/993#-:-McL1waW4UIrMy9oX5YP:b-833305)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598)

___
*[storage/rowwriter.go, line 184 at r1](https://reviewable.io/reviews/m-lab/etl/993#-McGf0O4BgSBNskoitHD:-McL1W3KDlcnRTkQYU1s:b8v2m4x) ([raw file](https://github.com/m-lab/etl/blob/883da4f721a777225e5dab2c300b2285265a3d36/storage/rowwriter.go#L184)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Rather than worrying about return values for `Path()`, I think I'd like to update `etl.ValidateTestPath` to set a new field named `Path` so that this may be used unconditionally for validated paths. This also eliminates the redundant parsing of Path() in this implementation.
</blockquote></details>

I believe this implementation is better. We are now relying on `ValidateTestPath` to do the right thing.
___
*[storage/storage.go, line 246 at r1](https://reviewable.io/reviews/m-lab/etl/993#-McGg9cM5LWwlvRr09QV:-McL1MEd5SkIgVNA_9A7:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/883da4f721a777225e5dab2c300b2285265a3d36/storage/storage.go#L246)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

check for empty fn?
</blockquote></details>

Done.

**Review by gfr10598 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/993)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by gfr10598 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/993#-:-McLDrcqEZzPtdYY6KYX:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
