### PR TITLE
add legacy dataset views

### PR DESCRIPTION
**Pull request by gfr10598**
This completes the hierarchy of views under the public views we want people to use.
Without this, the staging deployment was failing, so etl integration deployment has been unhealthy for quite a while.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/481)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---

*[schema/views_legacysql/make_views.sh, line 100 at r1](https://beta.reviewable.io/reviews/m-lab/etl/481#-L8Yz8pYA_ItIa4Tczlq:-L8Yz8pYA_ItIa4Tczlr:b-i2zecm) ([raw file](https://github.com/m-lab/etl/blob/929e23a3959e90db3ef0e217e780c4754e47ab86/schema/views_legacysql/make_views.sh#L100)):*
> ```Shell
> if [[ -v TRAVIS ]];then set -x; fi
> 
> create_view ${LEGACY} ndt_with_partition_date \
> ```

Can the tables `ndt_with_partition_date` and `ndt_pre2015_with_partition_date` not be combined into a single query as `ndt_plx.sql` from the standardsql views? Perhaps using the "comma" form of legacySQL querying from multiple tables?

If not, please add a comment why, since this separation adds some extra complexity to the legacy configuration. If so, please combine these.

---

*[schema/views_standardsql/ndt_plx.sql, line 11 at r1](https://beta.reviewable.io/reviews/m-lab/etl/481#-L8YvTnq6H2jWW9qBaMn:-L8YvTnq6H2jWW9qBaMo:b-j215qt) ([raw file](https://github.com/m-lab/etl/blob/929e23a3959e90db3ef0e217e780c4754e47ab86/schema/views_standardsql/ndt_plx.sql#L11)):*
> ```SQLPL
>   connection_spec,
>   web100_log_entry
> FROM `mlab-sandbox.legacy.ndt`
> ```

Is this project / table correct? I expected `measurement-lab`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/etl/481)*

**Comment by gfr10598** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[schema/views_legacysql/make_views.sh, line 100 at r1](https://reviewable.io:443/reviews/m-lab/etl/481#-L8Yz8pYA_ItIa4Tczlq:-L8Z55fg2HHeGX2BPG_u:b2d5qtw) ([raw file](https://github.com/m-lab/etl/blob/929e23a3959e90db3ef0e217e780c4754e47ab86/schema/views_legacysql/make_views.sh#L100)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Can the tables `ndt_with_partition_date` and `ndt_pre2015_with_partition_date` not be combined into a single query as `ndt_plx.sql` from the standardsql views? Perhaps using the "comma" form of legacySQL querying from multiple tables?

If not, please add a comment why, since this separation adds some extra complexity to the legacy configuration. If so, please combine these.
</blockquote></details>

Good idea.  I hadn't figured out how to do this last year, but figured it out now, and it definitely makes things cleaner.

---

*[schema/views_standardsql/ndt_plx.sql, line 11 at r1](https://reviewable.io:443/reviews/m-lab/etl/481#-L8YvTnq6H2jWW9qBaMn:-L8Z5-vDL09WdviKMvNW:bwzo6j1) ([raw file](https://github.com/m-lab/etl/blob/929e23a3959e90db3ef0e217e780c4754e47ab86/schema/views_standardsql/ndt_plx.sql#L11)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this project / table correct? I expected `measurement-lab`.
</blockquote></details>

Thanks!  Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/481)*

**Comment by gfr10598** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[schema/views_standardsql/ndt_plx.sql, line 11 at r1](https://reviewable.io:443/reviews/m-lab/etl/481#-L8YvTnq6H2jWW9qBaMn:-L8ZCHXF_BLVZsUaKo0A:b-vhnpbt) ([raw file](https://github.com/m-lab/etl/blob/929e23a3959e90db3ef0e217e780c4754e47ab86/schema/views_standardsql/ndt_plx.sql#L11)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does a table name without the project prefix automatically look in the project from which the query is being run?

I have a funny feeling about this, because we often run jobs from the three primary projects on measurement-lab. Will we ever want a situation where the job runs from another project and wants to access the measurement-lab views / tables?
</blockquote></details>

Not sure, so playing it safe.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/481)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Reviewed 3 of 8 files at r1, 11 of 13 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[schema/views_legacysql/make_views.sh, line 100 at r1](https://beta.reviewable.io/reviews/m-lab/etl/481#-L8Yz8pYA_ItIa4Tczlq:-L8ZIWuYDDHUiSvKMA6U:b-ec019f) ([raw file](https://github.com/m-lab/etl/blob/929e23a3959e90db3ef0e217e780c4754e47ab86/schema/views_legacysql/make_views.sh#L100)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Good idea.  I hadn't figured out how to do this last year, but figured it out now, and it definitely makes things cleaner.
</blockquote></details>

Excellent.

---

*[schema/views_standardsql/ndt_plx.sql, line 11 at r1](https://beta.reviewable.io/reviews/m-lab/etl/481#-L8YvTnq6H2jWW9qBaMn:-L8ZIquj8n5GMt_TGOPk:bc9q60n) ([raw file](https://github.com/m-lab/etl/blob/929e23a3959e90db3ef0e217e780c4754e47ab86/schema/views_standardsql/ndt_plx.sql#L11)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Not sure, so playing it safe.
</blockquote></details>

I approve of playing it safe. :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/etl/481#-:-L8ZJCMO1sxFz8gp7rKo:bnfp4nl)*

**Pull request merged**
