### PR TITLE
BQ inserter for PT

### PR DESCRIPTION
**Pull request by yachang**
BQ inserter for PT

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/70)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Reviewed 1 of 5 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[schema/pt_schema.go, line 13 at r1](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjt0XItajgR53JPWFt2:-Kjt0XItajgR53JPWFt3:b-v46c) ([raw file](https://github.com/m-lab/etl/blob/65eab448890daa2269b33623e9b81d70460d3a1c/schema/pt_schema.go#L13)):*
> ```Go
> type PTValueMap map[string]bigquery.Value
> 
> type ParisTracerouteHop struct {
> ```

The bigquery `Uploader.Put` interface supports two conventions.

The first convention is the `StructSaver` interface. With this interface, we can provide a literal struct to `Put` and the bigquery library will automatically determine the field names. The Disco parser uses this convention. The Go struct field names are re-mapped to the JSON names that appear in BQ using the `json:` tags. See: https://github.com/m-lab/etl/blob/integration/parser/disco.go#L22 for an example.

The second convention is the `ValueSaver` interface. With this interface, any type can define a `Save` method and bigquery will call that function to get the values. The schema/web100.go (and the ndt.go parser) uses `map[string]bigquery.Value` objects to construct a record. Then ndt.go wraps the map value in a `MapSaver` to automatically satisfy the `ValueSaver` interface for BQ: https://github.com/m-lab/etl/blob/integration/parser/ndt.go#L234 and https://github.com/m-lab/etl/blob/integration/bq/insert.go#L78

The new structs added to `pt_schema.go` appear to use a mixture of both conventions.

Since you've taken the time to create the structs already, I suggest using these directly and annotating them with `json:` tags to name the BQ columns how you want.

---

*[schema/pt_schema.go, line 93 at r1](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjt4FjVL0lYv9kwA-K6:-Kjt4FjVL0lYv9kwA-K7:bkolfjf) ([raw file](https://github.com/m-lab/etl/blob/65eab448890daa2269b33623e9b81d70460d3a1c/schema/pt_schema.go#L93)):*
> ```Go
> 
> // SetInt64 saves an int64 in a field with the given name.
> func (s PTValueMap) SetInt64(name string, value int64) {
> ```

This interface is only helpful for reading values from web100 snaplogs. I don't think PT needs these. https://github.com/m-lab/etl/blob/integration/web100/web100.go#L40

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/70)*

**Comment by yachang** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[schema/pt_schema.go, line 13 at r1](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjt0XItajgR53JPWFt2:-KjxgnkL6TUMlAhtM_Wn:b7d3mu) ([raw file](https://github.com/m-lab/etl/blob/65eab448890daa2269b33623e9b81d70460d3a1c/schema/pt_schema.go#L13)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The bigquery `Uploader.Put` interface supports two conventions.

The first convention is the `StructSaver` interface. With this interface, we can provide a literal struct to `Put` and the bigquery library will automatically determine the field names. The Disco parser uses this convention. The Go struct field names are re-mapped to the JSON names that appear in BQ using the `json:` tags. See: https://github.com/m-lab/etl/blob/integration/parser/disco.go#L22 for an example.

The second convention is the `ValueSaver` interface. With this interface, any type can define a `Save` method and bigquery will call that function to get the values. The schema/web100.go (and the ndt.go parser) uses `map[string]bigquery.Value` objects to construct a record. Then ndt.go wraps the map value in a `MapSaver` to automatically satisfy the `ValueSaver` interface for BQ: https://github.com/m-lab/etl/blob/integration/parser/ndt.go#L234 and https://github.com/m-lab/etl/blob/integration/bq/insert.go#L78

The new structs added to `pt_schema.go` appear to use a mixture of both conventions.

Since you've taken the time to create the structs already, I suggest using these directly and annotating them with `json:` tags to name the BQ columns how you want.
</blockquote></details>

I prefer to use ValueSaver interface and there is no StructSaver in current code.

---

*[schema/pt_schema.go, line 93 at r1](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjt4FjVL0lYv9kwA-K6:-Kjxhg_HsEZLFdzLT6Bc:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/65eab448890daa2269b33623e9b81d70460d3a1c/schema/pt_schema.go#L93)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This interface is only helpful for reading values from web100 snaplogs. I don't think PT needs these. https://github.com/m-lab/etl/blob/integration/web100/web100.go#L40
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/70)*

**Comment by yachang** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[schema/pt_schema.go, line 13 at r1](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjt0XItajgR53JPWFt2:-KjxznAvNCo_8AaSmMk3:b-prikfc) ([raw file](https://github.com/m-lab/etl/blob/65eab448890daa2269b33623e9b81d70460d3a1c/schema/pt_schema.go#L13)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

I prefer to use ValueSaver interface and there is no StructSaver in current code.
</blockquote></details>

Discussed offline. comments addressed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/70)*

**Comment by stephen-soltesz** [comment]
Review status: 1 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[parser/pt.go, line 50 at r2](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjy22W6g_dxv6NJ0OXE:-Kjy22W6g_dxv6NJ0OXF:b-zd1ues) ([raw file](https://github.com/m-lab/etl/blob/b1bde7e7bcdce59931a1421e29411c1cdde31442/parser/pt.go#L50)):*
> ```Go
> type PTParser struct {
> 	inserter etl.Inserter
> 	tmpDir   string
> ```

I know this code was already present, but PTParser doesn't need the tmpDir field -- that is a special case for NDT. Please remove from pt parser and tests.

---

*[parser/pt.go, line 184 at r2](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjy-iy_EGN-6RziqJ8S:-Kjy-iy_EGN-6RziqJ8T:b-g4jfz1) ([raw file](https://github.com/m-lab/etl/blob/b1bde7e7bcdce59931a1421e29411c1cdde31442/parser/pt.go#L184)):*
> ```Go
> 	test_id := CreateTestId(testName)
> 	for _, hop := range hops {
> 		var pt_test schema.PT
> ```

I suggest using syntax like:
```
pt_test := schema.PT{
    Test_id: test_id,
    Log_time: logTime,
    Connection_spec: *conn_spec,
    Paris_traceroute_hop: hop,
    ...
}
```

---

*[parser/pt_test.go, line 34 at r2](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjy0z0Myi-rDHmUAY9O:-Kjy0z0N9L8ihv846Tqm:b-nvc9fw) ([raw file](https://github.com/m-lab/etl/blob/b1bde7e7bcdce59931a1421e29411c1cdde31442/parser/pt_test.go#L34)):*
> ```Go
> 	}
> 
> 	expected_cspec := schema.MLabConnectionSpecification{Server_ip: "64.86.132.75", Server_af: 2, Client_ip: "98.162.212.214", Client_af: 2, Data_direction: 0}
> ```

I suggest line wrapping this value with one field per line for easier readability.

---

*[parser/pt_test.go, line 40 at r2](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjy2uPGbPdiDLmSLIyh:-Kjy2uPGbPdiDLmSLIyi:b-5rkvol) ([raw file](https://github.com/m-lab/etl/blob/b1bde7e7bcdce59931a1421e29411c1cdde31442/parser/pt_test.go#L40)):*
> ```Go
> 
> 	expected_hops := []schema.ParisTracerouteHop{
> 		schema.ParisTracerouteHop{Protocol: "tcp", Src_ip: "64.233.174.109", Src_af: 2, Dest_ip: "74.125.224.100", Dest_af: 2, Src_hostname: "sr05-te1-8.nuq04.net.google.com", Des_hostname: "74.125.224.100", Rtt: []float64{0.895}},
> ```

Please add a TODO to reformat these individual values to be more readable.

---

*[parser/pt_test.go, line 128 at r2](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjy2cqs3DEOKTiF5w5c:-Kjy2cqs3DEOKTiF5w5d:b4b7e4z) ([raw file](https://github.com/m-lab/etl/blob/b1bde7e7bcdce59931a1421e29411c1cdde31442/parser/pt_test.go#L128)):*
> ```Go
> 			Rtt:          []float64{0.895},
> 		},
> 		Type: 2}
> ```

Please put the closing `}` on a new line.

---

*[schema/pt_schema.go, line 13 at r1](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjt0XItajgR53JPWFt2:-Kjy2kCpIW8rhLZgnPmd:b9bkkp1) ([raw file](https://github.com/m-lab/etl/blob/65eab448890daa2269b33623e9b81d70460d3a1c/schema/pt_schema.go#L13)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Discussed offline. comments addressed.
</blockquote></details>

Looks great!

---

*[schema/pt_schema.go, line 20 at r2](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjy38gOQZSsm4YlTMT1:-Kjy38gOQZSsm4YlTMT2:b-g05ai7) ([raw file](https://github.com/m-lab/etl/blob/b1bde7e7bcdce59931a1421e29411c1cdde31442/schema/pt_schema.go#L20)):*
> ```Go
> type ParisTracerouteHop struct {
>           Protocol     string  `json:"protocal, string"`
> 	  Src_ip       string  `json:"src_ip, string"`
> ```

Please add a TODO to use mixed case Go variable names throughout. https://golang.org/doc/effective_go.html#mixed-caps

---

*[schema/pt_schema.go, line 43 at r2](https://reviewable.io:443/reviews/m-lab/etl/70#-KjxzmboHPI8DN4UlX-F:-KjxzmboHPI8DN4UlX-G:b-v9m3uv) ([raw file](https://github.com/m-lab/etl/blob/b1bde7e7bcdce59931a1421e29411c1cdde31442/schema/pt_schema.go#L43)):*
> ```Go
> 	Connection_spec      MLabConnectionSpecification  `json:"connection_spec"`
> 	Paris_traceroute_hop  ParisTracerouteHop `json:"paris_traceroute_hop"`
>         Type int32  `json:"type, int32"`
> ```

Please run `gofmt`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/70)*

**Comment by yachang** [comment]
Review status: 1 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[parser/pt.go, line 50 at r2](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjy22W6g_dxv6NJ0OXE:-KjyGdx3joISGyrCGw-f:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b1bde7e7bcdce59931a1421e29411c1cdde31442/parser/pt.go#L50)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I know this code was already present, but PTParser doesn't need the tmpDir field -- that is a special case for NDT. Please remove from pt parser and tests.
</blockquote></details>

Done.

---

*[parser/pt.go, line 184 at r2](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjy-iy_EGN-6RziqJ8S:-KjyH7UaTjOo-GlapYjy:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b1bde7e7bcdce59931a1421e29411c1cdde31442/parser/pt.go#L184)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest using syntax like:
```
pt_test := schema.PT{
    Test_id: test_id,
    Log_time: logTime,
    Connection_spec: *conn_spec,
    Paris_traceroute_hop: hop,
    ...
}
```
</blockquote></details>

Done.

---

*[parser/pt_test.go, line 34 at r2](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjy0z0Myi-rDHmUAY9O:-KjyHR6yjIOGRA9n0bip:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b1bde7e7bcdce59931a1421e29411c1cdde31442/parser/pt_test.go#L34)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest line wrapping this value with one field per line for easier readability.
</blockquote></details>

Done.

---

*[parser/pt_test.go, line 40 at r2](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjy2uPGbPdiDLmSLIyh:-KjyHmlqS7UzOKuFYx2j:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b1bde7e7bcdce59931a1421e29411c1cdde31442/parser/pt_test.go#L40)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a TODO to reformat these individual values to be more readable.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/70)*

**Comment by yachang** [comment]
Review status: 1 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[parser/pt_test.go, line 128 at r2](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjy2cqs3DEOKTiF5w5c:-KjyHym068VsSaFKiJVg:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b1bde7e7bcdce59931a1421e29411c1cdde31442/parser/pt_test.go#L128)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please put the closing `}` on a new line.
</blockquote></details>

Done.

---

*[schema/pt_schema.go, line 13 at r1](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjt0XItajgR53JPWFt2:-KjyHzqHi5Kr6ZwPxpFK:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/65eab448890daa2269b33623e9b81d70460d3a1c/schema/pt_schema.go#L13)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Looks great!
</blockquote></details>

Done.

---

*[schema/pt_schema.go, line 20 at r2](https://reviewable.io:443/reviews/m-lab/etl/70#-Kjy38gOQZSsm4YlTMT1:-KjyIYQAzjEySxM-pUfP:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b1bde7e7bcdce59931a1421e29411c1cdde31442/schema/pt_schema.go#L20)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a TODO to use mixed case Go variable names throughout. https://golang.org/doc/effective_go.html#mixed-caps
</blockquote></details>

Done.

---

*[schema/pt_schema.go, line 43 at r2](https://reviewable.io:443/reviews/m-lab/etl/70#-KjxzmboHPI8DN4UlX-F:-KjyI3oWGsnd2EoJO10t:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b1bde7e7bcdce59931a1421e29411c1cdde31442/schema/pt_schema.go#L43)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please run `gofmt`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/70)*

**Comment by stephen-soltesz** [comment]
Huzzah! :lgtm:

---

Review status: 1 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/70#-:-KjyJNLBJPKKAd7-BAEV:b8g6h8k)*

**Pull request merged**
