### PR TITLE
PT perf tuning

### PR DESCRIPTION
**Pull request by yachang**
to reduce the BQ insertion time and possible insertion ParseAndInsertErrors.

https://github.com/m-lab/etl/issues/459

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/460)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[etl/globals.go, line 213 at r1](https://reviewable.io:443/reviews/m-lab/etl/460#-L5ol9RN3Sn9v9U4OXDP:-L5ol9RN3Sn9v9U4OXDQ:b-34yot8) ([raw file](https://github.com/m-lab/etl/blob/93d54139d7dbb611cdd21027ae11d37b525cbd0a/etl/globals.go#L213)):*
> ```Go
> 		NDT_OMIT_DELTAS: 50,
> 		SS:              100,
> 		PT:              100,
> ```

Please see my comment on https://github.com/m-lab/etl/issues/459#issuecomment-367096613

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/460)*

**Comment by yachang** [comment]
Deploy this change on staging, and process one day data:

The average BQ insertion time drop to 47ms. 

The duration of each worker drop to <1ms for 50%, <5m for 99%.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/460#-:-L5oryAuUocHsmCATOcD:b-y2fh2t)*

**Comment by stephen-soltesz** [comment]
The duration dashboard was providing misleading information. When we only look at the duration of request duration for workers that succeeded ( status "OK"), the delays appear to have increased.



I think it would be worth while testing with a BQ buffer larger than 300. Perhaps 600 or even 1000.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/460#-:-L5oz1_nlvUFodZuRW3I:b-99ml1k)*

**Comment by stephen-soltesz** [comment]
We discussed in person, and @yachang will run another test using the larger BQ buffer size.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/460#-:-L5yN7Zz5cJmeEi0BbXy:bxmb06a)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cmd/etl_worker/app-traceroute.yaml, line 13 at r2](https://reviewable.io:443/reviews/m-lab/etl/460#-L6bHJypUbwGNso4rYqF:-L6bHJyql01ggltHtzxE:b-p7hqot) ([raw file](https://github.com/m-lab/etl/blob/edaae0ef91fac3caf54cb1a9cc7e25658d3a882e/cmd/etl_worker/app-traceroute.yaml#L13)):*
> ```YAML
>   # Instances support between [(cpu * 0.9) - 0.4, (cpu * 6.5) - 0.4]
>   # Actual memory available is exposed via GAE_MEMORY_MB environment variable.
>   memory_gb: 1.5
> ```

Please add a comment like: "even though the parser has extremely limited RAM requirements, the minimum RAM assignable to 2 CPUs is around 1.5GB".

---

*[cmd/etl_worker/app-traceroute.yaml, line 16 at r2](https://reviewable.io:443/reviews/m-lab/etl/460#-L6bHfpwQnIuNvbBvRWK:-L6bHfpwQnIuNvbBvRWL:b-p48lsh) ([raw file](https://github.com/m-lab/etl/blob/edaae0ef91fac3caf54cb1a9cc7e25658d3a882e/cmd/etl_worker/app-traceroute.yaml#L16)):*
> ```YAML
> 
>   # TODO - Adjust once we understand requirements.
>   disk_size_gb: 10
> ```

This setting can be removed. This is a carry over from the ndt parser a long time ago.

---

*[cmd/etl_worker/app-traceroute.yaml, line 43 at r2](https://reviewable.io:443/reviews/m-lab/etl/460#-L6bK7OmfZ0TzvlkvrnB:-L6bK7OmfZ0TzvlkvrnC:b-3p0ziz) ([raw file](https://github.com/m-lab/etl/blob/edaae0ef91fac3caf54cb1a9cc7e25658d3a882e/cmd/etl_worker/app-traceroute.yaml#L43)):*
> ```YAML
>   COMMIT_HASH: ${TRAVIS_COMMIT}
> 
>   MAX_WORKERS: 10
> ```

We discussed in person, and yachang will try a lower value of MAX workers here. Because, from our discussion last Friday, I thought we expected that fewer than 10 (maybe 4 or 6) could provide the optimal balance of "Worker States". Originally the ratio was something like 6:1 and now it is 4:1. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/460)*

**Comment by yachang** [comment]
Drop MAX workers to 5:

average worker duration: 50%: < 2m, 99%: <  8m
CPU utilization around 60%
2 instance
peak time worker status: 9 workers, 6 parse, 3 flush
 

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/460#-:-L6s-5GhRunCshOpkVbA:b63lwj6)*

**Comment by yachang** [comment]
Modify CPU target utilization to 0.6

Feed one day data, the instance increased to 4 after a few minutes.

While the worker duration stay the same.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/460#-:-L6s-iSmI1vqxbW27L5z:b-5soxq)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cmd/etl_worker/app-traceroute.yaml, line 13 at r2](https://reviewable.io:443/reviews/m-lab/etl/460#-L6bHJypUbwGNso4rYqF:-L6vtaCuLXzFEEq2eIZG:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/edaae0ef91fac3caf54cb1a9cc7e25658d3a882e/cmd/etl_worker/app-traceroute.yaml#L13)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a comment like: "even though the parser has extremely limited RAM requirements, the minimum RAM assignable to 2 CPUs is around 1.5GB".
</blockquote></details>

Done.

---

*[cmd/etl_worker/app-traceroute.yaml, line 16 at r2](https://reviewable.io:443/reviews/m-lab/etl/460#-L6bHfpwQnIuNvbBvRWK:-L6vtalwZIHaitjPo5Bh:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/edaae0ef91fac3caf54cb1a9cc7e25658d3a882e/cmd/etl_worker/app-traceroute.yaml#L16)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This setting can be removed. This is a carry over from the ndt parser a long time ago.
</blockquote></details>

Done.

---

*[cmd/etl_worker/app-traceroute.yaml, line 43 at r2](https://reviewable.io:443/reviews/m-lab/etl/460#-L6bK7OmfZ0TzvlkvrnB:-L6vtcBdcAgbDEgofG0c:b-rkb4r7) ([raw file](https://github.com/m-lab/etl/blob/edaae0ef91fac3caf54cb1a9cc7e25658d3a882e/cmd/etl_worker/app-traceroute.yaml#L43)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

We discussed in person, and yachang will try a lower value of MAX workers here. Because, from our discussion last Friday, I thought we expected that fewer than 10 (maybe 4 or 6) could provide the optimal balance of "Worker States". Originally the ratio was something like 6:1 and now it is 4:1. 
</blockquote></details>

Done. See above updates.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/460)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[etl/globals.go, line 213 at r1](https://reviewable.io:443/reviews/m-lab/etl/460#-L5ol9RN3Sn9v9U4OXDP:-L6vto1djO6gX0Czu5ak:bdcun52) ([raw file](https://github.com/m-lab/etl/blob/93d54139d7dbb611cdd21027ae11d37b525cbd0a/etl/globals.go#L213)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please see my comment on https://github.com/m-lab/etl/issues/459#issuecomment-367096613
</blockquote></details>

Tried 1000 and 100. Both had little impact on worker duration.

Discussed offline, and agreed to keep the same as 300.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/460)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/460#-:-L6wahGIyl-lOcQQDZvG:bnfp4nl)*

**Pull request merged**
