### PR TITLE
Add inFlight, metrics, TableName, Dataset, ...

### PR DESCRIPTION
**Pull request by gfr10598**
Adds limiting to 25 active requests.
Additional TaskCount and insertion time metrics.
Added TableName and Dataset getters.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/38)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Reviewed 4 of 9 files at r1.
Review status: 4 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[appengine/queue.yaml, line 14 at r1](https://reviewable.io:443/reviews/m-lab/etl/38#-Kil1diCyYENp4pRp4Em:-Kil1diCyYENp4pRp4En:bgm49hg) ([raw file](https://github.com/m-lab/etl/blob/06cbd6ff401caa5b2eb4c73a010e79e6abf79683/appengine/queue.yaml#L14)):*
> ```YAML
>   # Maximum number of concurrent requests.  This is large now, until we address the
>   # latency associated with BQ inserts.
>   max_concurrent_requests: 100
> ```

Are there any insights worth noting along with these value changes?

---

*[bq/insert.go, line 134 at r1](https://reviewable.io:443/reviews/m-lab/etl/38#-Kil2Qyt-FvPNCUUmHI1:-Kil2Qyt-FvPNCUUmHI2:bazazv) ([raw file](https://github.com/m-lab/etl/blob/06cbd6ff401caa5b2eb4c73a010e79e6abf79683/bq/insert.go#L134)):*
> ```Go
> 		tag = "fail"
> 	}
> 	metrics.InsertionHistogram.WithLabelValues(
> ```

Just thinking out loud: We could also create an "instrumented Inserter" that wraps an implementation like `BQInserter` and increments this metric based on whether or not the underlying `Flush` returns `nil` or not.

This could separate the BQ logic from the metric tracking logic.

---

*[cmd/etl_worker/app.yaml, line 13 at r1](https://reviewable.io:443/reviews/m-lab/etl/38#-Kil2w0CWvJsKOHSbKLy:-Kil2w0DEBZKxM-3OewE:btafwa) ([raw file](https://github.com/m-lab/etl/blob/06cbd6ff401caa5b2eb4c73a010e79e6abf79683/cmd/etl_worker/app.yaml#L13)):*
> ```YAML
>   # Instances support between [(cpu * 0.9) - 0.4, (cpu * 6.5) - 0.4]
>   # Actual memory available is exposed via GAE_MEMORY_MB environment variable.
>   memory_gb: 12
> ```

Are there any insights worth noting along with this value change?

---

*[cmd/etl_worker/etl_worker.go, line 33 at r1](https://reviewable.io:443/reviews/m-lab/etl/38#-Kil314JQq9ZVFCmRNRW:-Kil314Klfb4TRkIXJuk:b-49f57s) ([raw file](https://github.com/m-lab/etl/blob/06cbd6ff401caa5b2eb4c73a010e79e6abf79683/cmd/etl_worker/etl_worker.go#L33)):*
> ```Go
> func init() {
> 	// Always prepend the filename and line number.
> 	log.SetFlags(log.LstdFlags | log.Lshortfile)
> ```

This is good.

---

*[cmd/etl_worker/etl_worker.go, line 159 at r1](https://reviewable.io:443/reviews/m-lab/etl/38#-Kil4_ciueDDKN1yOJxx:-Kil4_ciueDDKN1yOJxy:b-jzwyww) ([raw file](https://github.com/m-lab/etl/blob/06cbd6ff401caa5b2eb4c73a010e79e6abf79683/cmd/etl_worker/etl_worker.go#L159)):*
> ```Go
> 	fn, err := getFilename(r.FormValue("filename"))
> 	if err != nil {
> 		metrics.TaskCount.WithLabelValues("parserName", "BadRequest").Inc()
> ```

Is `parserName` just a stand-in for the actual parser used for the request? Should there be a TODO?

---

*[cmd/etl_worker/etl_worker.go, line 267 at r1](https://reviewable.io:443/reviews/m-lab/etl/38#-Kil5InzD0_Buu3sNt89:-Kil5InzD0_Buu3sNt8A:bcmviqu) ([raw file](https://github.com/m-lab/etl/blob/06cbd6ff401caa5b2eb4c73a010e79e6abf79683/cmd/etl_worker/etl_worker.go#L267)):*
> ```Go
> 
> 	// Enable block profiling
> 	runtime.SetBlockProfileRate(1000000) // One event per msec.
> ```

`ListenAndServe` above should block. Does `SetBlockProfileRate` need to be called first?

---

*[etl/etl.go, line 17 at r1](https://reviewable.io:443/reviews/m-lab/etl/38#-Kil74KTvklbJm8tFdsv:-Kil74KTvklbJm8tFdsw:b-zg2r) ([raw file](https://github.com/m-lab/etl/blob/06cbd6ff401caa5b2eb4c73a010e79e6abf79683/etl/etl.go#L17)):*
> ```Go
> //   Dataset - name of the BQ dataset containing the table.
> //   Count - returns the count of rows currently in the buffer.
> //   RowsInBuffer - returns the count of rows currently in the buffer.
> ```

"Effective Go" provides advice for formatting comments that work well with generated godocs.

https://golang.org/doc/effective_go.html#commentary

In this case, I think the comments will look closer to the way you intend if they are next to the fields within the interface below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/38)*

**Comment by gfr10598** [comment]
Review status: 4 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[cmd/etl_worker/app.yaml, line 13 at r1](https://reviewable.io:443/reviews/m-lab/etl/38#-Kil2w0CWvJsKOHSbKLy:-KilGQPcZmAxC4BaUPlH:bl2hgq4) ([raw file](https://github.com/m-lab/etl/blob/06cbd6ff401caa5b2eb4c73a010e79e6abf79683/cmd/etl_worker/app.yaml#L13)):*
> increments
See design doc.

---

*[cmd/etl_worker/etl_worker.go, line 159 at r1](https://reviewable.io:443/reviews/m-lab/etl/38#-Kil4_ciueDDKN1yOJxx:-KilGU44sfO5UAUnuPr_:b-vxqrzp) ([raw file](https://github.com/m-lab/etl/blob/06cbd6ff401caa5b2eb4c73a010e79e6abf79683/cmd/etl_worker/etl_worker.go#L159)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is `parserName` just a stand-in for the actual parser used for the request? Should there be a TODO?
</blockquote></details>

Yes.  Quotes are typo I will fix in next PR.

---

*[cmd/etl_worker/etl_worker.go, line 267 at r1](https://reviewable.io:443/reviews/m-lab/etl/38#-Kil5InzD0_Buu3sNt89:-KilGij96BDU4uLgwEme:bikbld8) ([raw file](https://github.com/m-lab/etl/blob/06cbd6ff401caa5b2eb4c73a010e79e6abf79683/cmd/etl_worker/etl_worker.go#L267)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`ListenAndServe` above should block. Does `SetBlockProfileRate` need to be called first?
</blockquote></details>

Fixed in followup PR

---

*[etl/etl.go, line 17 at r1](https://reviewable.io:443/reviews/m-lab/etl/38#-Kil74KTvklbJm8tFdsv:-KilGoOxG6-bJKZON2P5:b97gzza) ([raw file](https://github.com/m-lab/etl/blob/06cbd6ff401caa5b2eb4c73a010e79e6abf79683/etl/etl.go#L17)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

"Effective Go" provides advice for formatting comments that work well with generated godocs.

https://golang.org/doc/effective_go.html#commentary

In this case, I think the comments will look closer to the way you intend if they are next to the fields within the interface below.
</blockquote></details>

Will fix in next PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/38)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 4 of 9 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/38#-:-KilGRd9KJQbHYOl1Zzr:bnfp4nl)*

**Comment by gfr10598** [comment]
Review status: 4 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[appengine/queue.yaml, line 14 at r1](https://reviewable.io:443/reviews/m-lab/etl/38#-Kil1diCyYENp4pRp4Em:-KilGrp8pzhFNsotWvRC:b-m9znx6) ([raw file](https://github.com/m-lab/etl/blob/06cbd6ff401caa5b2eb4c73a010e79e6abf79683/appengine/queue.yaml#L14)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Are there any insights worth noting along with these value changes?
</blockquote></details>

see design doc.

---

*[bq/insert.go, line 134 at r1](https://reviewable.io:443/reviews/m-lab/etl/38#-Kil2Qyt-FvPNCUUmHI1:-KilGvADHjWlST9A_DaF:b-h2y03e) ([raw file](https://github.com/m-lab/etl/blob/06cbd6ff401caa5b2eb4c73a010e79e6abf79683/bq/insert.go#L134)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Just thinking out loud: We could also create an "instrumented Inserter" that wraps an implementation like `BQInserter` and increments this metric based on whether or not the underlying `Flush` returns `nil` or not.

This could separate the BQ logic from the metric tracking logic.
</blockquote></details>

Good idea.  Will do that next week.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/38)*

**Pull request merged**
