### PR TITLE
Start parsing ".json" files (#974)

### PR DESCRIPTION
**Pull request by SaiedKazemi**
Starting with this PR, ".json" files for the new "traceroute3"
datatype are no longer ignored.

This PR includes some improvements to the testing code of the
"parser" package.  Specifically, super long lines (some greater
than 6,000 characters!) that are used to initialize a string
variable are replaced by reading the contents of a file.  Also,
temporary files created during package testing are now deleted
when the test finishes.

The changes were tested as follows:
$ git status -s
$ go test ./...
$ git status -s

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/976)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
@SaiedKazemi I'm confused by this PR. How is this different from #974 ?

**Comment by SaiedKazemi** [comment]
> @SaiedKazemi I'm confused by this PR. How is this different from #974 ?

I noticed that #974 somehow did not have the line in parser/pt.go that would accept ".json" files (not sure at all how that happened).  This PR amends 974 to include that line.

**Comment by stephen-soltesz** [comment]
Something is still wrong. The build is failing, the branch is out of date, the diff looks the same as #974 somehow. Please fix these issues first. Thank you.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/976#-:-MWW-cE3EaSfrOb6GIvl:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
