### PR TITLE
Add or update field descriptions for scamper1 datatype

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This commit adds (or updates) descriptions for the fields that
were not covered in https://github.com/m-lab/etl/pull/1057.
Descriptions for raw.{CycleStart,Tracelb,CycleStop} fields are
provided by scamper's author Matthew Luckie.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/1064)

### CODE REVIEW

**Review by cristinaleonr — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1064)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[schema/descriptions/Scamper1Row.yaml, line 144 at r1](https://reviewable.io/reviews/m-lab/etl/1064#-MxbBBss2ekWZqLA6yaP:-MxbBBss2ekWZqLA6yaQ:be0f9a2) ([raw file](https://github.com/m-lab/etl/blob/96d4968bf8ae8c1b96dc3268342653a4f010791e/schema/descriptions/Scamper1Row.yaml#L144)):*
> ```YAML
>   Description:
> raw.CycleStop.ID:
>   Description: UUID of the connection under consideration.
> ```

Is this the same description as `raw.CycleStart.ID`? Should we add that one, too?

**Comment by SaiedKazemi** [comment]
___
*[schema/descriptions/Scamper1Row.yaml, line 144 at r1](https://reviewable.io/reviews/m-lab/etl/1064#-MxbBBss2ekWZqLA6yaP:-MxbVjlZ1e_Wb-aynEyT:b-dxbdrx) ([raw file](https://github.com/m-lab/etl/blob/96d4968bf8ae8c1b96dc3268342653a4f010791e/schema/descriptions/Scamper1Row.yaml#L144)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Is this the same description as `raw.CycleStart.ID`? Should we add that one, too?
</blockquote></details>

It should be the same.  But now that you are asking and I am looking at it in greater detail, I am seeing that it doesn't match scamper source code which describes id as "the cycle id".  I need to check this with Matthew.

Thank you for your detailed review.

**Comment by SaiedKazemi** [comment]
@cristinaleonr PTAL.

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1064#-:-MxpAi8e-qHOygruvGec:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

**Pull request merged**
