### PR TITLE
Sidestream parser and BigQuery inserter

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/205)

### CODE REVIEW

**Comment by gfr10598** [comment]
Reviewed 1 of 5 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[schema/ss_schema.go, line 1 at r1](https://reviewable.io:443/reviews/m-lab/etl/205#-KpGpoYjjZPLjktbn9Sp:-KpGpoYjjZPLjktbn9Sq:b-vk5d87) ([raw file](https://github.com/m-lab/etl/blob/73c0ac581310367ab7212679617306934fd20f47/schema/ss_schema.go#L1)):*
> ```Go
> // This files contains schema for SideStream tests.
> ```

Are these fields identical to the fields used by NDT?  If so, or if they COULD be identical, you should reuse the NDT map handling code in schema/web100.go

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by gfr10598** [comment]
One pretty high level comment about schema.go.  Have a look while I look at the rest of the code.

---

Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205#-:-KpGqPX08VFjLnTiYKKY:bwog4b2)*

**Comment by yachang** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[schema/ss_schema.go, line 1 at r1](https://reviewable.io:443/reviews/m-lab/etl/205#-KpGpoYjjZPLjktbn9Sp:-KpL6DODZ78r2BlmGlhh:bvjblkx) ([raw file](https://github.com/m-lab/etl/blob/73c0ac581310367ab7212679617306934fd20f47/schema/ss_schema.go#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Are these fields identical to the fields used by NDT?  If so, or if they COULD be identical, you should reuse the NDT map handling code in schema/web100.go
</blockquote></details>

No. They are not identical. Some fields, such as WAD_* are only available in ndt.json. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by gfr10598** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[schema/ss_schema.go, line 1 at r1](https://reviewable.io:443/reviews/m-lab/etl/205#-KpGpoYjjZPLjktbn9Sp:-KpLxjpmy7bxU2lT1g8q:b-wgl61l) ([raw file](https://github.com/m-lab/etl/blob/73c0ac581310367ab7212679617306934fd20f47/schema/ss_schema.go#L1)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

No. They are not identical. Some fields, such as WAD_* are only available in ndt.json. 
</blockquote></details>

On thinking further, you can probably still use the web100/schema.go, since it uses maps.  This would allow much more code reuse, and avoid having intermediate structs.  Please take a look, particularly at NewWeb100MinimalRecord

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by yachang** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[schema/ss_schema.go, line 1 at r1](https://reviewable.io:443/reviews/m-lab/etl/205#-KpGpoYjjZPLjktbn9Sp:-KpM2ILpvQhsG3XuKtMf:b8kokjs) ([raw file](https://github.com/m-lab/etl/blob/73c0ac581310367ab7212679617306934fd20f47/schema/ss_schema.go#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

On thinking further, you can probably still use the web100/schema.go, since it uses maps.  This would allow much more code reuse, and avoid having intermediate structs.  Please take a look, particularly at NewWeb100MinimalRecord
</blockquote></details>

There is no

web100/schema.go

Do you mean schema/web100.go?

I read the func NewWeb100MinimalRecord(). Which is actually the reason I do not reuse web100.go code, 

Sidestream does not have "anomalies" or "deltas". But it has "group_name", and many other extra fields inside SNAP. 

The schema defined in schema/ss_schema.go is clean and easy to maintain.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by gfr10598** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[schema/ss_schema.go, line 1 at r1](https://reviewable.io:443/reviews/m-lab/etl/205#-KpGpoYjjZPLjktbn9Sp:-KpMqzbTlXAQDkWQHRAr:b-6q31lc) ([raw file](https://github.com/m-lab/etl/blob/73c0ac581310367ab7212679617306934fd20f47/schema/ss_schema.go#L1)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

There is no

web100/schema.go

Do you mean schema/web100.go?

I read the func NewWeb100MinimalRecord(). Which is actually the reason I do not reuse web100.go code, 

Sidestream does not have "anomalies" or "deltas". But it has "group_name", and many other extra fields inside SNAP. 

The schema defined in schema/ss_schema.go is clean and easy to maintain.
</blockquote></details>

Ok.  group_name also exists in the legacy NDT schema, but always has the same value so I left it out of the new schema.

In general, the schema/web100.go doesn't need to know about individual fields, which avoids a lot of unnecessary code.  Let's look at this together tomorrow and figure out whether we could easily modify the existing code to work for SS too, or if that would be too messy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by gfr10598** [comment]
I've started using go lint, and trying to bring existing code into compliance with lint warnings.
Suggest you also run lint before merging this PR, and handle at least a subset of the warnings.

---

Reviewed 2 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[parser/ss.go, line 1 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVcpFDovnARTTff9FL:-KpVcpFET_wvdFcj9V2Q:b1oprn7) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L1)):*
> ```Go
> // Parse Sidestream filename like 20170516T22:00:00Z_163.7.129.73_0.web100
> ```

This comment seems to be out of date.  Or do you mean "Parse Sidestream files, like ..."?

---

*[parser/ss.go, line 38 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-Kpa8opAQkz44HtRYWDL:-Kpa8opAQkz44HtRYWDM:b-a0ksbc) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L38)):*
> ```Go
> 	testName := filepath.Base(fileName)
> 	if len(testName) < 19 || !strings.Contains(testName, ".web100") {
> 		return 0, errors.New("Wrong sidestream filename")
> ```

invalid sidestream filename

---

*[parser/ss.go, line 41 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-Kpa8yPgjnZZaO55UdT2:-Kpa8yPgjnZZaO55UdT3:bajza9m) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L41)):*
> ```Go
> 	}
> 
> 	date_str := testName[0:4] + "-" + testName[4:6] + "-" + testName[6:8] + testName[8:17] + ".000Z"
> ```

FYI, the time parser can handle this directly.  See
https://github.com/m-lab/etl/blob/integration/parser/ndt.go#L89

---

*[parser/ss.go, line 61 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVe8mo7KWfsl7QM1mt:-KpVe8mo7KWfsl7QM1mu:bmceruc) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L61)):*
> ```Go
> }
> 
> // the first line of SS test is in format "K: web100_variables_separated_by_space"
> ```

I would comment with the actual first few variable names like:
"K: cid PollTime LocalAddress LocalPort ..."

---

*[parser/ss.go, line 103 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVfwtYy2iTeTlnn1Au:-KpVfwtYy2iTeTlnn1Av:b-525k1n) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L103)):*
> ```Go
> }
> 
> func InsertIntoBQ(ss_inserter etl.Inserter, ss_value map[string]string, log_time int64, testName string) error {
> ```

This function name implies that it is doing little other than inserting.  See comment below...

---

*[parser/ss.go, line 107 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVgrO3xaOG0mk6ACM7:-KpVgrO3xaOG0mk6ACM8:bg37rh) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L107)):*
> ```Go
> 	local_port, err := strconv.Atoi(ss_value["LocalPort"])
> 	if err != nil {
> 		return err
> ```

Should add TestError metric for each of these errors.  (TODO if you prefer)

---

*[parser/ss.go, line 139 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVg4UtuteZC3h6CoLI:-KpVg4UtuteZC3h6CoLJ:bc8518g) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L139)):*
> ```Go
> 		Web100_log_entry: *web100_log,
> 		Is_last_entry:    true,
> 	}
> ```

How about renaming this function ParseTest, and returning the ss_test here.  Then just put the ss_inserter.InsertRow inline in the location that this func is called from.

---

*[parser/ss.go, line 158 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVgZ96Z4bu_a3RiMW0:-KpVgZ96Z4bu_a3RiMW1:bmszx8) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L158)):*
> ```Go
> 
> 	for index, val := range value {
> 		if index == 0 {
> ```

range value[1:] instead of checking for index == 0

---

*[parser/ss.go, line 181 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-Kpa6Bs7BpMNKar3InC5:-Kpa6Bs8nH47R3uYG2-F:bsdy5zz) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L181)):*
> ```Go
> 		fmt.Println(key)
> 		x := reflect.ValueOf(snap).Elem().FieldByName(key)
> 		t := x.Type().String()
> ```

Can you just use the type here instead of converting to string?

---

*[parser/ss.go, line 184 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-Kpa6kS4e3Ia3RG5gZmh:-Kpa6kS5D4bFCHkOiuqW:bag9r2w) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L184)):*
> ```Go
> 		log.Printf("Name: %s    Type: %s\n", key, t)
> 
> 		switch t {
> ```

I'd suggest just "switch x.Type() {" would be more readable.

---

*[parser/ss.go, line 216 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVewxer-Qr2UmNQGCk:-KpVewxer-Qr2UmNQGCl:bh9eosa) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L216)):*
> ```Go
> 		oneLine := strings.TrimSuffix(oneLine, "\n")
> 		// TODO: add metrics.
> 		if index == 0 {
> ```

It would be better to avoid this "if index == 0" pattern.  It is pretty bad for readability.  

---

*[parser/ss.go, line 232 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVh6EAi_s5cC8Cpfhl:-KpVh6EAi_s5cC8Cpfhm:bhhjfm1) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L232)):*
> ```Go
> 			if err != nil {
> 				metrics.ErrorCount.WithLabelValues(
> 					ss.TableName(), "ss", "insert-err").Inc()
> ```

As written, several error types that have nothing to do with insert will show up as "insert-err"

---

*[parser/ss_test.go, line 33 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-Kpa8BfY6arzIIaZz2g6:-Kpa8BfY6arzIIaZz2g7:b5x7afr) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss_test.go#L33)):*
> ```Go
> 	_, err := parser.PopulateSnap(ss_value)
> 	if err != nil {
> 		t.Fatalf("Do not populate snap fields correctly.")
> ```

Here and other places in tests...
Does not, or Did not ...
Or
"Snap fields not populated correctly."

---

*[schema/ss_schema.go, line 6 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVhXgCOsfMLYxbYyee:-KpVhXgCOsfMLYxbYyef:bbuglk4) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/schema/ss_schema.go#L6)):*
> ```Go
> type Web100ConnectionSpecification struct {
> 	Local_ip    string `json:"local_ip, string"`
> 	Local_af    int32  `json:"local_af, int32"`
> ```

Is the use of int32 doing anything useful?  Seems like the code would be simpler if everything that will be ultimately written to BQ is int64.

---

*[schema/ss_schema.go, line 12 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-Kpa7H6Bn66rO8I8_WNA:-Kpa7H6Bn66rO8I8_WNB:b-aukuhb) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/schema/ss_schema.go#L12)):*
> ```Go
> }
> 
> type Web100Snap struct {
> ```

Please add a comment indicating that any changes here should also be made in ss.json.

---

*[schema/ss_schema.go, line 13 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-Kpa7ptWmB2iPTu_HJRl:-Kpa7dbVFltTd6k52ev7:be3xult) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/schema/ss_schema.go#L13)):*
> ```Go
> 
> type Web100Snap struct {
> 	AbruptTimeouts       int64  `json:"AbruptTimeouts, int64"`
> ```

FYI, the json annotations are not needed for this struct, since the names and types are unchanged, but I guess you included them for consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205#-:-KpVdAzv4bQneM74EjcV:bnlxetr)*

**Comment by yachang** [comment]
Review status: 3 of 7 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[parser/ss.go, line 1 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVcpFDovnARTTff9FL:-KppRlHxKYca9frBeS5J:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This comment seems to be out of date.  Or do you mean "Parse Sidestream files, like ..."?
</blockquote></details>

Done.

---

*[parser/ss.go, line 38 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-Kpa8opAQkz44HtRYWDL:-KppRxVAYFD7yUScjzFj:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L38)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

invalid sidestream filename
</blockquote></details>

Done.

---

*[parser/ss.go, line 41 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-Kpa8yPgjnZZaO55UdT2:-KppXTGJfoLHpe91lN8O:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L41)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

FYI, the time parser can handle this directly.  See
https://github.com/m-lab/etl/blob/integration/parser/ndt.go#L89

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by yachang** [comment]
Review status: 3 of 7 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[parser/ss.go, line 61 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVe8mo7KWfsl7QM1mt:-KppXduVJKHQd6px6Ue-:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L61)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I would comment with the actual first few variable names like:
"K: cid PollTime LocalAddress LocalPort ..."

</blockquote></details>

Done.

---

*[parser/ss.go, line 103 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVfwtYy2iTeTlnn1Au:-KppXvSijxFHyaJxHhcj:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L103)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This function name implies that it is doing little other than inserting.  See comment below...
</blockquote></details>

Done.

---

*[parser/ss.go, line 107 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVgrO3xaOG0mk6ACM7:-KppXmJ5qBvpgkMkKvCb:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L107)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Should add TestError metric for each of these errors.  (TODO if you prefer)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by yachang** [comment]
Review status: 3 of 7 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[parser/ss.go, line 139 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVg4UtuteZC3h6CoLI:-Kpp_2cGMDlojLE8OToG:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L139)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

How about renaming this function ParseTest, and returning the ss_test here.  Then just put the ss_inserter.InsertRow inline in the location that this func is called from.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by yachang** [comment]
Review status: 3 of 7 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[parser/ss.go, line 158 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVgZ96Z4bu_a3RiMW0:-Kppb0R53CoEtX1OBL8P:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L158)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

range value[1:] instead of checking for index == 0
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by yachang** [comment]
Review status: 3 of 7 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[parser/ss.go, line 181 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-Kpa6Bs7BpMNKar3InC5:-KppbEGpB-9YKEien3zB:b-9c6ofv) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L181)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Can you just use the type here instead of converting to string?
</blockquote></details>

As I tried, it won't work

---

*[parser/ss.go, line 184 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-Kpa6kS4e3Ia3RG5gZmh:-KppbZfdYxADOad4oKHJ:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L184)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I'd suggest just "switch x.Type() {" would be more readable.
</blockquote></details>

Done.

---

*[parser/ss.go, line 216 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVewxer-Qr2UmNQGCk:-KppcBWCTArAhoyp6VeY:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L216)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

It would be better to avoid this "if index == 0" pattern.  It is pretty bad for readability.  
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by yachang** [comment]
Review status: 3 of 7 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[parser/ss.go, line 232 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVh6EAi_s5cC8Cpfhl:-KppcJmBRIF4hwLfCxOr:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L232)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

As written, several error types that have nothing to do with insert will show up as "insert-err"
</blockquote></details>

Done.

---

*[parser/ss_test.go, line 33 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-Kpa8BfY6arzIIaZz2g6:-Kppco5IuSV7lSA5u-N4:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss_test.go#L33)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Here and other places in tests...
Does not, or Did not ...
Or
"Snap fields not populated correctly."
</blockquote></details>

Done.

---

*[schema/ss_schema.go, line 1 at r1](https://reviewable.io:443/reviews/m-lab/etl/205#-KpGpoYjjZPLjktbn9Sp:-Kppcs86GmdXNQwdu_-y:b-m7emff) ([raw file](https://github.com/m-lab/etl/blob/73c0ac581310367ab7212679617306934fd20f47/schema/ss_schema.go#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Ok.  group_name also exists in the legacy NDT schema, but always has the same value so I left it out of the new schema.

In general, the schema/web100.go doesn't need to know about individual fields, which avoids a lot of unnecessary code.  Let's look at this together tomorrow and figure out whether we could easily modify the existing code to work for SS too, or if that would be too messy.
</blockquote></details>

Discussed offline already

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by gfr10598** [comment]
Review status: 2 of 7 files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[parser/ss.go, line 216 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVewxer-Qr2UmNQGCk:-KppcuMBJuvOyB-66hub:b-ucfknh) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L216)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!

---

*[parser/ss.go, line 202 at r3](https://reviewable.io:443/reviews/m-lab/etl/205#-KppczrhLuf0CdOmzspV:-KppczrivzqAyiqLcrBQ:b3l8cjv) ([raw file](https://github.com/m-lab/etl/blob/520a28102d76d9fc887174962aaec5213df779de/parser/ss.go#L202)):*
> ```Go
> 	}
> 	var var_names []string
> 	testContent := strings.Split(string(rawContent[:]), "\n")
> ```

Add a check for len(testContent) < 2 ??

---

*[task/task.go, line 107 at r3](https://reviewable.io:443/reviews/m-lab/etl/205#-KppdeJpYxI9JC75O4eY:-KppdeJpYxI9JC75O4eZ:b-r4fgco) ([raw file](https://github.com/m-lab/etl/blob/520a28102d76d9fc887174962aaec5213df779de/task/task.go#L107)):*
> ```Go
> 			continue
> 		}
> 		if strings.Contains(testname, ".tra") {
> ```

This should not be at the task level.  Please move this check into the parser.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by yachang** [comment]
Review status: 2 of 7 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[schema/ss_schema.go, line 6 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVhXgCOsfMLYxbYyee:-KppdeFRmE7adMQDzpGy:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/schema/ss_schema.go#L6)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Is the use of int32 doing anything useful?  Seems like the code would be simpler if everything that will be ultimately written to BQ is int64.
</blockquote></details>

Done.

---

*[schema/ss_schema.go, line 12 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-Kpa7H6Bn66rO8I8_WNA:-KppdCMMtzttXoaenSxA:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/schema/ss_schema.go#L12)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please add a comment indicating that any changes here should also be made in ss.json.
</blockquote></details>

Done.

---

*[schema/ss_schema.go, line 13 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-Kpa7ptWmB2iPTu_HJRl:-KppdH-86OtdRKgpv3Hb:b2nhswy) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/schema/ss_schema.go#L13)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

FYI, the json annotations are not needed for this struct, since the names and types are unchanged, but I guess you included them for consistency.
</blockquote></details>

Yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by gfr10598** [comment]
Reviewed 1 of 5 files at r3.
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[parser/ss.go, line 135 at r4](https://reviewable.io:443/reviews/m-lab/etl/205#-Kppg_kvBS9sdq65iNwW:-Kppg_kvBS9sdq65iNwX:b-cpvfbx) ([raw file](https://github.com/m-lab/etl/blob/18694465266f4318eaeadd457b64bc5be98f6b3b/parser/ss.go#L135)):*
> ```Go
> 		Test_id:          testName,
> 		Log_time:         log_time,
> 		Type:             int64(1),
> ```

I think some of these int64 conversions are no longer needed, here and above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by yachang** [comment]
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[task/task.go, line 107 at r3](https://reviewable.io:443/reviews/m-lab/etl/205#-KppdeJpYxI9JC75O4eY:-KppeOz9GHAEA_1JxuvG:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/520a28102d76d9fc887174962aaec5213df779de/task/task.go#L107)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This should not be at the task level.  Please move this check into the parser.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by yachang** [comment]
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[parser/ss.go, line 135 at r4](https://reviewable.io:443/reviews/m-lab/etl/205#-Kppg_kvBS9sdq65iNwW:-KppvRDwiYvBY8XtU1HQ:b-z1b0ku) ([raw file](https://github.com/m-lab/etl/blob/18694465266f4318eaeadd457b64bc5be98f6b3b/parser/ss.go#L135)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I think some of these int64 conversions are no longer needed, here and above.
</blockquote></details>

We do need those to build w/o errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by yachang** [comment]
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[parser/ss.go, line 202 at r3](https://reviewable.io:443/reviews/m-lab/etl/205#-KppczrhLuf0CdOmzspV:-Kppw-q58qBBbbn73OyE:bb6un1j) ([raw file](https://github.com/m-lab/etl/blob/520a28102d76d9fc887174962aaec5213df779de/parser/ss.go#L202)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add a check for len(testContent) < 2 ??
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by yachang** [comment]
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[parser/ss.go, line 216 at r2](https://reviewable.io:443/reviews/m-lab/etl/205#-KpVewxer-Qr2UmNQGCk:-KppwZIRMMNih7c4nJLX:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/e26feb827f584cc5c427bd6f06dfdef560ab075d/parser/ss.go#L216)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: 3 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205#-:-Kpq4Md7SRTiT00If2Sz:bnfp4nl)*

**Comment by gfr10598** [comment]
Reviewed 1 of 5 files at r3, 1 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/205)*

**Pull request merged**
