### PR TITLE
add metrics for PT

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/160)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/pt.go, line 203 at r1](https://reviewable.io:443/reviews/m-lab/etl/160#-KnLGUD6QfwrptlgovdD:-KnLGUD6QfwrptlgovdE:b-bihakq) ([raw file](https://github.com/m-lab/etl/blob/844cfa9ae9a773a301f6c7fa44efea2757d9327f/parser/pt.go#L203)):*
> ```Go
> 		err := pt.inserter.InsertRow(pt_test)
> 		if err != nil {
> 			metrics.ErrorCount.WithLabelValues(
> ```

The sum of all labels associated with a particular metric (e.g. `sum(etl_test_count)`) should total 100% of the thing.

Above TestCount is used to count "corrupted content". And, here it looks like TestCount will not record this test if an error occurs during InsertRow. So, `etl_test_count` won't count everything.

I suggest adding increments for both ErrorCount and TestCount here. Like in this block: https://github.com/m-lab/etl/blob/integration/parser/ndt.go#L428

---

*[parser/pt.go, line 328 at r1](https://reviewable.io:443/reviews/m-lab/etl/160#-KnLIMcLV4gcb0oFN8bF:-KnLIMcLV4gcb0oFN8bG:bimi0a) ([raw file](https://github.com/m-lab/etl/blob/844cfa9ae9a773a301f6c7fa44efea2757d9327f/parser/pt.go#L328)):*
> ```Go
> 	log.Printf("%s", testName)
> 
> 	metrics.WorkerState.WithLabelValues("pt").Inc()
> ```

This metric will be more helpful if there are many uses. For example in NDT, there are many worker states that show where most of the processing time is spent.

If you do not have access yet, just follow the "Sign up" steps and log in with that account.
http://status-mlab-sandbox.measurementlab.net:3000/dashboard/db/etl-pipeline?refresh=1m&panelId=1&fullscreen&edit&orgId=1&from=1498218317578&to=1498228456015

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/160)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/pt.go, line 328 at r1](https://reviewable.io:443/reviews/m-lab/etl/160#-KnLIMcLV4gcb0oFN8bF:-KnLMsSIXKqbF8wbBdQ1:b-1k8jxt) ([raw file](https://github.com/m-lab/etl/blob/844cfa9ae9a773a301f6c7fa44efea2757d9327f/parser/pt.go#L328)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This metric will be more helpful if there are many uses. For example in NDT, there are many worker states that show where most of the processing time is spent.

If you do not have access yet, just follow the "Sign up" steps and log in with that account.
http://status-mlab-sandbox.measurementlab.net:3000/dashboard/db/etl-pipeline?refresh=1m&panelId=1&fullscreen&edit&orgId=1&from=1498218317578&to=1498228456015
</blockquote></details>

This link may be better initially:

http://status-mlab-sandbox.measurementlab.net:3000/dashboard/db/etl-pipeline?refresh=1m&panelId=1&fullscreen&orgId=1&from=1498218196889&to=1498229156057

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/160)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/pt.go, line 203 at r1](https://reviewable.io:443/reviews/m-lab/etl/160#-KnLGUD6QfwrptlgovdD:-KnLOcogxE9mNfdU75DO:bwls28k) ([raw file](https://github.com/m-lab/etl/blob/844cfa9ae9a773a301f6c7fa44efea2757d9327f/parser/pt.go#L203)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The sum of all labels associated with a particular metric (e.g. `sum(etl_test_count)`) should total 100% of the thing.

Above TestCount is used to count "corrupted content". And, here it looks like TestCount will not record this test if an error occurs during InsertRow. So, `etl_test_count` won't count everything.

I suggest adding increments for both ErrorCount and TestCount here. Like in this block: https://github.com/m-lab/etl/blob/integration/parser/ndt.go#L428
</blockquote></details>

add counters for hops for PT.
keep the test counter as the total number of test in raw files.
The ErrorCount has two kinds of lables: pt-test, or pt-hop
So the error rate can be calculated both as test based and hop based.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/160)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[parser/pt.go, line 187 at r3](https://reviewable.io:443/reviews/m-lab/etl/160#-KnZgv11VyCTHG8DH1NA:-KnZgv11VyCTHG8DH1NB:bdyuv6l) ([raw file](https://github.com/m-lab/etl/blob/ca59369a0d603fd1a43afd1d55ec090e4a100afb/parser/pt.go#L187)):*
> ```Go
> 	if err != nil {
> 		metrics.ErrorCount.WithLabelValues(
> 			pt.TableName(), "pt-test", "insert-err").Inc()
> ```

Please keep the filetype consistent across a single metric since there is only one paris traceroute file type, right?. Here the filetype should remain "pt", not "pt-test".

Also, is this an "insert-error"? This looks like something failed in parsing the content.

---

*[parser/pt.go, line 208 at r3](https://reviewable.io:443/reviews/m-lab/etl/160#-KnZiLfDaKWeQECE9DmY:-KnZiLfDaKWeQECE9DmZ:bvrvvkx) ([raw file](https://github.com/m-lab/etl/blob/ca59369a0d603fd1a43afd1d55ec090e4a100afb/parser/pt.go#L208)):*
> ```Go
> 			metrics.ErrorCount.WithLabelValues(
> 				pt.TableName(), "pt-hop", "insert-err").Inc()
> 			metrics.PTHopCount.WithLabelValues(
> ```

I suggest moving `PTHopCount` to `Parse` to directly count the individual hops, with or without errors. e.g.
```
metrics.PTHopCount.WithLabels(pt.TableName(), "pt", "ok")
metrics.PTHopCount.WithLabels(pt.TableName(), "pt", "specific-error-string")
```

---

*[parser/pt.go, line 330 at r3](https://reviewable.io:443/reviews/m-lab/etl/160#-KnZiBD5VO4nhVFOTyUq:-KnZiBD5VO4nhVFOTyUr:b-wleijp) ([raw file](https://github.com/m-lab/etl/blob/ca59369a0d603fd1a43afd1d55ec090e4a100afb/parser/pt.go#L330)):*
> ```Go
> // Parse the raw test file into hops ParisTracerouteHop.
> // TODO(dev): dedup the hops that are identical.
> func Parse(meta map[string]bigquery.Value, testName string, rawContent []byte) ([]schema.ParisTracerouteHop, int64, *schema.MLabConnectionSpecification, error) {
> ```

As written, `Parse` never returns an error. Is this intended?

---

*[parser/pt.go, line 382 at r3](https://reviewable.io:443/reviews/m-lab/etl/160#-KnZhX5a9bRSvqGOvV7W:-KnZhX5bOVMljIoUivG4:b-6esp7q) ([raw file](https://github.com/m-lab/etl/blob/ca59369a0d603fd1a43afd1d55ec090e4a100afb/parser/pt.go#L382)):*
> ```Go
> 			for i := 3; i < len(parts); i += 4 {
> 				tuple_str := []string{parts[i], parts[i+1], parts[i+2], parts[i+3]}
> 				ProcessOneTuple(tuple_str, protocol, current_leaves, &all_nodes, &new_leaves)
> ```

It would be helpful to count the errors returned from `ProcessOneTuple`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/160)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[parser/pt.go, line 208 at r3](https://reviewable.io:443/reviews/m-lab/etl/160#-KnZiLfDaKWeQECE9DmY:-KnZwDabt3VF2eS3OTD8:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/ca59369a0d603fd1a43afd1d55ec090e4a100afb/parser/pt.go#L208)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest moving `PTHopCount` to `Parse` to directly count the individual hops, with or without errors. e.g.
```
metrics.PTHopCount.WithLabels(pt.TableName(), "pt", "ok")
metrics.PTHopCount.WithLabels(pt.TableName(), "pt", "specific-error-string")
```
</blockquote></details>

Done.

---

*[parser/pt.go, line 330 at r3](https://reviewable.io:443/reviews/m-lab/etl/160#-KnZiBD5VO4nhVFOTyUq:-Kn_-OMI8sRxKOPZursS:b-d5q2i1) ([raw file](https://github.com/m-lab/etl/blob/ca59369a0d603fd1a43afd1d55ec090e4a100afb/parser/pt.go#L330)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

As written, `Parse` never returns an error. Is this intended?
</blockquote></details>

Fixed. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/160)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[parser/pt.go, line 382 at r3](https://reviewable.io:443/reviews/m-lab/etl/160#-KnZhX5a9bRSvqGOvV7W:-Kn_1_lnb165uqbZ0DhL:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/ca59369a0d603fd1a43afd1d55ec090e4a100afb/parser/pt.go#L382)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It would be helpful to count the errors returned from `ProcessOneTuple`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/160)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[parser/pt.go, line 187 at r3](https://reviewable.io:443/reviews/m-lab/etl/160#-KnZgv11VyCTHG8DH1NA:-Kn_1iJxd7kJpHYwbyUA:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/ca59369a0d603fd1a43afd1d55ec090e4a100afb/parser/pt.go#L187)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please keep the filetype consistent across a single metric since there is only one paris traceroute file type, right?. Here the filetype should remain "pt", not "pt-test".

Also, is this an "insert-error"? This looks like something failed in parsing the content.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/160)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[parser/pt.go, line 328 at r1](https://reviewable.io:443/reviews/m-lab/etl/160#-KnLIMcLV4gcb0oFN8bF:-Kn_2tJ0h5oS8-AFJ44r:b-95txdl) ([raw file](https://github.com/m-lab/etl/blob/844cfa9ae9a773a301f6c7fa44efea2757d9327f/parser/pt.go#L328)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This link may be better initially:

http://status-mlab-sandbox.measurementlab.net:3000/dashboard/db/etl-pipeline?refresh=1m&panelId=1&fullscreen&orgId=1&from=1498218196889&to=1498229156057
</blockquote></details>


Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/160)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[parser/pt.go, line 93 at r4](https://reviewable.io:443/reviews/m-lab/etl/160#-Kn_87Xo5OghpkArdvKS:-Kn_87Xo5OghpkArdvKT:b-99e4wi) ([raw file](https://github.com/m-lab/etl/blob/69a976a297f89846b4e35f7ab65798a4a29824d8/parser/pt.go#L93)):*
> ```Go
> 			}
> 			results = append(results, *one_hop)
> 			metrics.PTHopCount.WithLabelValues(tableName, "pt", "ok")
> ```

Since these lines are identical, please place them outside the `if/else` branch.

---

*[parser/pt.go, line 199 at r5](https://reviewable.io:443/reviews/m-lab/etl/160#-Kn_eOGFcEUS4-5vXLiF:-Kn_eOGFcEUS4-5vXLiG:bati3il) ([raw file](https://github.com/m-lab/etl/blob/2e3a787acaa15481745891be65e763868f73939f/parser/pt.go#L199)):*
> ```Go
> 	}
> 	test_id := CreateTestId(testName)
> 	metrics.TestCount.WithLabelValues(pt.TableName(), "pt", "ok").Inc()
> ```

Place this line before the final `return nil` statement. This is counting successes, and it's possible for the function to return with an error after this line.

---

*[parser/pt.go, line 212 at r5](https://reviewable.io:443/reviews/m-lab/etl/160#-Kn_dGV5YlZy1gT827tr:-Kn_dGV5YlZy1gT827ts:beyy8iy) ([raw file](https://github.com/m-lab/etl/blob/2e3a787acaa15481745891be65e763868f73939f/parser/pt.go#L212)):*
> ```Go
> 		if err != nil {
> 			metrics.ErrorCount.WithLabelValues(
> 				pt.TableName(), "pt-hop", "insert-err").Inc()
> ```

I don't think we want "pt-hop" here. Again, this field is the "filetype". And, there is only one file type for the PT parser. Please change "pt-hop" to "pt".

---

*[parser/pt.go, line 213 at r5](https://reviewable.io:443/reviews/m-lab/etl/160#-Kn_eePdIrdW6mBbsq9p:-Kn_eePe2RjxH-ehkxxZ:b-v464ad) ([raw file](https://github.com/m-lab/etl/blob/2e3a787acaa15481745891be65e763868f73939f/parser/pt.go#L213)):*
> ```Go
> 			metrics.ErrorCount.WithLabelValues(
> 				pt.TableName(), "pt-hop", "insert-err").Inc()
> 			metrics.PTHopCount.WithLabelValues(
> ```

`metrics.PTHopCount` is counting things at the hop level. It looks like the counts in `ProcessAllNodes` and `Parse` count 100% of hops. Does that sound right to you?

Here, I suggest replacing with:
```
metrics.TestCount.WithLabelValues(pt.TableName(), "pt", "insert-err").Inc()
```

Is it clear why I am suggesting this?

---

*[parser/pt.go, line 387 at r5](https://reviewable.io:443/reviews/m-lab/etl/160#-Kn_bWcbEwGulDRMZLQr:-Kn_bWccCIhK9Zu2syiq:bmtyq5c) ([raw file](https://github.com/m-lab/etl/blob/2e3a787acaa15481745891be65e763868f73939f/parser/pt.go#L387)):*
> ```Go
> 				if err != nil {
> 					metrics.PTHopCount.WithLabelValues(
> 						tableName, "pt", "parse error").Inc()
> ```

`metrics.TestCount` counts success or error at the file level; either case adds one.

`metrics.PTHopCount` is counting individual hops in `ProcessAllNodes`. Rather than counting just one "parse error" here, please count all of the discarded hops. This way the `sum(etl_pthop_count)` will equal 100% of hops scanned. Some portion will be successfully parsed hops. And, the rest are those that were not parsed or were discarded due to a parse error.

Can this be done with?
```
metrics.PTHopCount.WithLabelValues(tableName, "pt", "discarded").Add(len(all_nodes))
```

Does `all_nodes` reflect the number of discarded hops when a parse error is encountered?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/160)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[parser/pt.go, line 93 at r4](https://reviewable.io:443/reviews/m-lab/etl/160#-Kn_87Xo5OghpkArdvKS:-Kn_tswiP1tRh4G54mUo:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/69a976a297f89846b4e35f7ab65798a4a29824d8/parser/pt.go#L93)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since these lines are identical, please place them outside the `if/else` branch.
</blockquote></details>

Done.

---

*[parser/pt.go, line 199 at r5](https://reviewable.io:443/reviews/m-lab/etl/160#-Kn_eOGFcEUS4-5vXLiF:-Kn_u5JSWqqaA30Pkzsr:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/2e3a787acaa15481745891be65e763868f73939f/parser/pt.go#L199)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Place this line before the final `return nil` statement. This is counting successes, and it's possible for the function to return with an error after this line.
</blockquote></details>

Done.

---

*[parser/pt.go, line 212 at r5](https://reviewable.io:443/reviews/m-lab/etl/160#-Kn_dGV5YlZy1gT827tr:-Kn_uHmo0IGsjPZnJ1aA:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/2e3a787acaa15481745891be65e763868f73939f/parser/pt.go#L212)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I don't think we want "pt-hop" here. Again, this field is the "filetype". And, there is only one file type for the PT parser. Please change "pt-hop" to "pt".
</blockquote></details>

Done.

---

*[parser/pt.go, line 213 at r5](https://reviewable.io:443/reviews/m-lab/etl/160#-Kn_eePdIrdW6mBbsq9p:-Kn_uUXgphfX1ruoUqFg:bs2tnzu) ([raw file](https://github.com/m-lab/etl/blob/2e3a787acaa15481745891be65e763868f73939f/parser/pt.go#L213)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`metrics.PTHopCount` is counting things at the hop level. It looks like the counts in `ProcessAllNodes` and `Parse` count 100% of hops. Does that sound right to you?

Here, I suggest replacing with:
```
metrics.TestCount.WithLabelValues(pt.TableName(), "pt", "insert-err").Inc()
```

Is it clear why I am suggesting this?
</blockquote></details>

so where to do ErrorCount?

---

*[parser/pt.go, line 387 at r5](https://reviewable.io:443/reviews/m-lab/etl/160#-Kn_bWcbEwGulDRMZLQr:-Kn_uvUYg4eyC0lpIWA8:b3o1dj7) ([raw file](https://github.com/m-lab/etl/blob/2e3a787acaa15481745891be65e763868f73939f/parser/pt.go#L387)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`metrics.TestCount` counts success or error at the file level; either case adds one.

`metrics.PTHopCount` is counting individual hops in `ProcessAllNodes`. Rather than counting just one "parse error" here, please count all of the discarded hops. This way the `sum(etl_pthop_count)` will equal 100% of hops scanned. Some portion will be successfully parsed hops. And, the rest are those that were not parsed or were discarded due to a parse error.

Can this be done with?
```
metrics.PTHopCount.WithLabelValues(tableName, "pt", "discarded").Add(len(all_nodes))
```

Does `all_nodes` reflect the number of discarded hops when a parse error is encountered?
</blockquote></details>

The number of hops got discarded here is really hard to calculate exactly, because it depends on the tree structure implied in the node queue.

I would not spend too much time here to get exact number, since len(all_nodes) is a close estimate anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/160)*

**Comment by stephen-soltesz** [comment]
Reviewed 1 of 2 files at r4, 1 of 2 files at r7.
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[parser/pt.go, line 213 at r5](https://reviewable.io:443/reviews/m-lab/etl/160#-Kn_eePdIrdW6mBbsq9p:-Kn_waujFImjh9NW_oiH:bpr193i) ([raw file](https://github.com/m-lab/etl/blob/2e3a787acaa15481745891be65e763868f73939f/parser/pt.go#L213)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

so where to do ErrorCount?
</blockquote></details>

We are not communicating effectively. If you can help suggest how we can communicate more clearly, please let me know.

My original comment was on and about the line `metrics.PTHopCount`.

My expectation was that ErrorCount would remain the same and `PTHopCount` would be replaced with `TestCount`.

Is it clear why I am suggesting this change?

---

*[parser/pt.go, line 387 at r5](https://reviewable.io:443/reviews/m-lab/etl/160#-Kn_bWcbEwGulDRMZLQr:-Kn_x9MUoNBcgPvytTvi:b-837i3v) ([raw file](https://github.com/m-lab/etl/blob/2e3a787acaa15481745891be65e763868f73939f/parser/pt.go#L387)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

The number of hops got discarded here is really hard to calculate exactly, because it depends on the tree structure implied in the node queue.

I would not spend too much time here to get exact number, since len(all_nodes) is a close estimate anyway.

</blockquote></details>

Okay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/160)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[parser/pt.go, line 205 at r8](https://reviewable.io:443/reviews/m-lab/etl/160#-Kna9vxqw0hbrfGAlmXZ:-Kna9vxqw0hbrfGAlmX_:b1n193l) ([raw file](https://github.com/m-lab/etl/blob/83efc9f1a550c290b929d08d03faca306763d735/parser/pt.go#L205)):*
> ```Go
> 		test_id = CreateTestId(meta["filename"].(string), filepath.Base(testName))
> 	}
> 	noErr := true
> ```

The double negative in the condition below is confusing. I suggest using `insertErr := false` and if an error occurs setting `insertErr = true`.

Then making the condition at the end `if insertErr ... else ...`

---

*[parser/pt.go, line 226 at r8](https://reviewable.io:443/reviews/m-lab/etl/160#-Kna6EmLkkVZsjpmjR6c:-Kna6EmLkkVZsjpmjR6d:b-h3adxu) ([raw file](https://github.com/m-lab/etl/blob/83efc9f1a550c290b929d08d03faca306763d735/parser/pt.go#L226)):*
> ```Go
> 		// Inc TestCount only once per test.
> 		metrics.TestCount.WithLabelValues(pt.TableName(), "pt", "insert-err").Inc()
> 	}
> ```

These two increments are mutually exclusive. Please use an else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/160)*

**Comment by yachang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[parser/pt.go, line 205 at r8](https://reviewable.io:443/reviews/m-lab/etl/160#-Kna9vxqw0hbrfGAlmXZ:-KnduyRk_j-q0mHGdBBL:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/83efc9f1a550c290b929d08d03faca306763d735/parser/pt.go#L205)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The double negative in the condition below is confusing. I suggest using `insertErr := false` and if an error occurs setting `insertErr = true`.

Then making the condition at the end `if insertErr ... else ...`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/160)*

**Comment by yachang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[parser/pt.go, line 213 at r5](https://reviewable.io:443/reviews/m-lab/etl/160#-Kn_eePdIrdW6mBbsq9p:-KndvkEEIggYMePrqzBX:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/2e3a787acaa15481745891be65e763868f73939f/parser/pt.go#L213)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

We are not communicating effectively. If you can help suggest how we can communicate more clearly, please let me know.

My original comment was on and about the line `metrics.PTHopCount`.

My expectation was that ErrorCount would remain the same and `PTHopCount` would be replaced with `TestCount`.

Is it clear why I am suggesting this change?
</blockquote></details>

Done.

---

*[parser/pt.go, line 226 at r8](https://reviewable.io:443/reviews/m-lab/etl/160#-Kna6EmLkkVZsjpmjR6c:-Kndvl_ItP-kKe1rm7xa:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/83efc9f1a550c290b929d08d03faca306763d735/parser/pt.go#L226)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

These two increments are mutually exclusive. Please use an else.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/160)*

**Comment by yachang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[parser/pt.go, line 387 at r5](https://reviewable.io:443/reviews/m-lab/etl/160#-Kn_bWcbEwGulDRMZLQr:-KndvnyQmEZswJWlMlIY:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/2e3a787acaa15481745891be65e763868f73939f/parser/pt.go#L387)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Okay.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/160)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/160#-:-Kne46Gjt-N2QA47KSii:bnfp4nl)*

**Pull request merged**
