### PR TITLE
Add meta data to the table rows

### PR DESCRIPTION
**Pull request by gfr10598**
Adds source file, test file, parse time, and attempt count (not yet implemented).
Also adds worker count prometheus gauge.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/21)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Great to see this coming together!

---

Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[appengine/queue.yaml, line 5 at r1](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki1sT81lY3De4WGz7Yo:-Ki1sT81lY3De4WGz7Yp:b-kw96sh) ([raw file](https://github.com/m-lab/etl/blob/ddcac64a6616b10cf89b09893927a0973bf36f3b/appengine/queue.yaml#L5)):*
> ```YAML
> - name: etl-parser-queue
>   target: etl-parser
>   rate: 5/s
> ```

Please add comments describing the significance of these changes.

---

*[cmd/etl_worker/app.yaml, line 4 at r1](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki1snoPxgWORw4FKo6o:-Ki1snoPxgWORw4FKo6p:br5qvvt) ([raw file](https://github.com/m-lab/etl/blob/ddcac64a6616b10cf89b09893927a0973bf36f3b/cmd/etl_worker/app.yaml#L4)):*
> ```YAML
> env: flex
> service: etl-parser
> resources:
> ```

You beat me to the review! Please include additional comments like my pending changes:
https://github.com/m-lab/etl/blob/sandbox-soltesz/cmd/etl_worker/app.yaml#L5

Please note where values differ from the defaults and add a comment for why we need the difference. "Whys" can get lost easily otherwise.

---

*[cmd/etl_worker/etl_worker.go, line 24 at r1](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki1tXlYxCP_c3PqEr8x:-Ki1tXlZkFKC72fw9D8O:b-83v4qp) ([raw file](https://github.com/m-lab/etl/blob/ddcac64a6616b10cf89b09893927a0973bf36f3b/cmd/etl_worker/etl_worker.go#L24)):*
> ```Go
> 	//   https://blog.golang.org/profiling-go-programs
> 	_ "net/http/pprof"
> 	// Enable exported debug vars.  See https://golang.org/pkg/expvar/
> ```

Neat.

---

*[cmd/etl_worker/etl_worker.go, line 94 at r1](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki1vJPLk3y7s-0R-GKj:-Ki1vJPLk3y7s-0R-GKk:b-rz783f) ([raw file](https://github.com/m-lab/etl/blob/ddcac64a6616b10cf89b09893927a0973bf36f3b/cmd/etl_worker/etl_worker.go#L94)):*
> ```Go
> 	}
> 
> 	// TODO - need to check for base64
> ```

Does this comment still apply? If so, please clarify.

---

*[cmd/etl_worker/etl_worker.go, line 143 at r1](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki1uejS6PMo6Iafogu6:-Ki1uejTFxt12wjwelNs:b-rjzfbh) ([raw file](https://github.com/m-lab/etl/blob/ddcac64a6616b10cf89b09893927a0973bf36f3b/cmd/etl_worker/etl_worker.go#L143)):*
> ```Go
> 
> var (
> 	workerCount = prometheus.NewGauge(prometheus.GaugeOpts{
> ```

Would you be willing to put these into etl/metrics/metrics.go? And, make them part of `DurationHandler`?

---

*[parser/parser_test.go, line 19 at r1](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki1wy_z0J6VrDFfKgag:-Ki1wy_z0J6VrDFfKgah:b-hu83hm) ([raw file](https://github.com/m-lab/etl/blob/ddcac64a6616b10cf89b09893927a0973bf36f3b/parser/parser_test.go#L19)):*
> ```Go
> 	p := parser.NullParser{}
> 	var meta map[string]bigquery.Value
> 	_, err := p.Parse(meta, "foo", "table", foo[:])
> ```

Since this is a `NullParser` why not just pass `nil` here?

---

*[task/task.go, line 112 at r2](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki2-PkkAq7FQB0FsOgI:-Ki2-PkkAq7FQB0FsOgJ:b-1l9m86) ([raw file](https://github.com/m-lab/etl/blob/246235d21653a68f913ed82dbec5042aa18c3fa4/task/task.go#L112)):*
> ```Go
> 	}
> 	// TODO - make this debug or remove
> 	log.Printf("%d files, %d nil data, %d inserts", files, nilData, inserts)
> ```

General comment, not necessarily for this PR, I would like to see nilData split into two parts: directories, and everything else. We expect most of `nilData` as it's currently counted to be directories. We will want to know and worry a little about any non-file, non-directory records in our tar files.

---

*[task/task_test.go, line 24 at r2](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki1yRqej6fzL24251-K:-Ki1yRqej6fzL24251-L:bpj1z9s) ([raw file](https://github.com/m-lab/etl/blob/246235d21653a68f913ed82dbec5042aa18c3fa4/task/task_test.go#L24)):*
> ```Go
> 	foo := [10]byte{1, 2, 3, 4, 5, 1, 2, 3, 4, 5}
> 	p := parser.NullParser{}
> 	var meta map[string]bigquery.Value
> ```

Here too. I expect `meta` to be used, but iiuc, it's just a `nil` placeholder. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/21#-:-Ki20Spv8q9CWdryY1rm:b-lm75e8)*

**Comment by gfr10598** [comment]
Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[appengine/queue.yaml, line 5 at r1](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki1sT81lY3De4WGz7Yo:-Ki28RVN9JgIiCYvKbfv:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/ddcac64a6616b10cf89b09893927a0973bf36f3b/appengine/queue.yaml#L5)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add comments describing the significance of these changes.
</blockquote></details>

Done.

---

*[cmd/etl_worker/app.yaml, line 4 at r1](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki1snoPxgWORw4FKo6o:-Ki2A7o0j3a8qZRm0icl:b-v6cx5s) ([raw file](https://github.com/m-lab/etl/blob/ddcac64a6616b10cf89b09893927a0973bf36f3b/cmd/etl_worker/app.yaml#L4)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

You beat me to the review! Please include additional comments like my pending changes:
https://github.com/m-lab/etl/blob/sandbox-soltesz/cmd/etl_worker/app.yaml#L5

Please note where values differ from the defaults and add a comment for why we need the difference. "Whys" can get lost easily otherwise.
</blockquote></details>

Ok.  Also added your changes, for efficiency.  Did not mention defaults everywhere.  Why do you care?

---

*[cmd/etl_worker/etl_worker.go, line 94 at r1](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki1vJPLk3y7s-0R-GKj:-Ki2AZ-aKBUPtVMhHLEO:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/ddcac64a6616b10cf89b09893927a0973bf36f3b/cmd/etl_worker/etl_worker.go#L94)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does this comment still apply? If so, please clarify.
</blockquote></details>

Done.

---

*[cmd/etl_worker/etl_worker.go, line 143 at r1](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki1uejS6PMo6Iafogu6:-Ki2AdqP_B5oBgf6D03A:bd0emji) ([raw file](https://github.com/m-lab/etl/blob/ddcac64a6616b10cf89b09893927a0973bf36f3b/cmd/etl_worker/etl_worker.go#L143)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Would you be willing to put these into etl/metrics/metrics.go? And, make them part of `DurationHandler`?
</blockquote></details>

I've made it a TODO, but will try to do that in my next PR.

---

*[parser/parser_test.go, line 19 at r1](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki1wy_z0J6VrDFfKgag:-Ki2AyEG0UE2j8rSqT2u:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/ddcac64a6616b10cf89b09893927a0973bf36f3b/parser/parser_test.go#L19)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since this is a `NullParser` why not just pass `nil` here?
</blockquote></details>

Done.

---

*[task/task.go, line 112 at r2](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki2-PkkAq7FQB0FsOgI:-Ki2CD5NUz7TlqrrXHvg:b-iw1i2d) ([raw file](https://github.com/m-lab/etl/blob/246235d21653a68f913ed82dbec5042aa18c3fa4/task/task.go#L112)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

General comment, not necessarily for this PR, I would like to see nilData split into two parts: directories, and everything else. We expect most of `nilData` as it's currently counted to be directories. We will want to know and worry a little about any non-file, non-directory records in our tar files.
</blockquote></details>

Added todo

---

*[task/task_test.go, line 24 at r2](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki1yRqej6fzL24251-K:-Ki2BOtBEypbF78rSQvZ:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/246235d21653a68f913ed82dbec5042aa18c3fa4/task/task_test.go#L24)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Here too. I expect `meta` to be used, but iiuc, it's just a `nil` placeholder. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/21)*

**Comment by gfr10598** [comment]
PTAL.

---

Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/21#-:-Ki2CJ4QR-HcBid6jg9A:b-83330m)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Reviewed 1 of 7 files at r1, 4 of 6 files at r3.
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/etl_worker/app.yaml, line 4 at r1](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki1snoPxgWORw4FKo6o:-Ki2F04rYs_Zss_t8acS:b-qw9l64) ([raw file](https://github.com/m-lab/etl/blob/ddcac64a6616b10cf89b09893927a0973bf36f3b/cmd/etl_worker/app.yaml#L4)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Ok.  Also added your changes, for efficiency.  Did not mention defaults everywhere.  Why do you care?
</blockquote></details>

Oh, I don't care about default values especially, but anywhere we need to specify a non-default value we probably have a good reason. It's that reason I'm looking for.

---

*[cmd/etl_worker/app.yaml, line 13 at r3](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki2FDi8FogTSpm1dJEM:-Ki2FDi9PmiyifRCPDOy:bc5qkal) ([raw file](https://github.com/m-lab/etl/blob/75d1a9e34a05148757cd38156da54ec3285f5dc6/cmd/etl_worker/app.yaml#L13)):*
> ```YAML
>   # Instances support between [(cpu * 0.9) - 0.4, (cpu * 6.5) - 0.4]
>   # Actual memory available is exposed via GAE_MEMORY_MB environment variable.
>   memory_gb: 2.5
> ```

Will this number be adequate when we start unpacking NDT archives?

---

*[cmd/etl_worker/app.yaml, line 27 at r3](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki2Eyyh1HPrpnDNPFZe:-Ki2Eyyh1HPrpnDNPFZf:bdtoi3i) ([raw file](https://github.com/m-lab/etl/blob/75d1a9e34a05148757cd38156da54ec3285f5dc6/cmd/etl_worker/app.yaml#L27)):*
> ```YAML
> 
> automatic_scaling:
>         # We expect fairly steady load, so a modest minimum will rarely cost us anything.
> ```

Please use consistent indent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/21#-:-Ki2GrY1W8G4vnIG_Thh:bnfp4nl)*

**Comment by gfr10598** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/etl_worker/app.yaml, line 13 at r3](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki2FDi8FogTSpm1dJEM:-Ki2Hqd_SZw0SMOLOSFy:b-pn1w11) ([raw file](https://github.com/m-lab/etl/blob/75d1a9e34a05148757cd38156da54ec3285f5dc6/cmd/etl_worker/app.yaml#L13)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Will this number be adequate when we start unpacking NDT archives?
</blockquote></details>

Not clear.  I think we will want to limit the number of active workers with a semaphore, and keep a fairly small memory footprint.  Might want to bump it up slightly then.

---

*[cmd/etl_worker/app.yaml, line 27 at r3](https://reviewable.io:443/reviews/m-lab/etl/21#-Ki2Eyyh1HPrpnDNPFZe:-Ki2IEjTJTGt9Ufme5hd:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/75d1a9e34a05148757cd38156da54ec3285f5dc6/cmd/etl_worker/app.yaml#L27)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please use consistent indent.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/21)*

**Pull request merged**
