### PR TITLE
Utility functions for gcs tar file

### PR DESCRIPTION
**Pull request by gfr10598**
Not ready for review, but if  you have any helpful suggestions they would be welcome

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/17)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Some initial thoughts.

I'm still wondering how we can define a better interface around the tar reader / gzip reader / body closer.

---

Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions.

---

*[storage/storage.go, line 22 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-Khd-sySxdafVOexnTY4:-Khd-sySxdafVOexnTY5:b7jw5ik) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L22)):*
> ```Go
> )
> 
> type TarReaderCloser struct {
> ```

I'm wondering if we could define our own interface around an implementation using the tar.Reader. e.g. Something like:

```
type GCSTarReaderCloser interface {
    func (tr *Reader) Next() (*Header, error)
    func (tr *Reader) Read(b []byte) (int, error)
    io.Closer
}
```

And writing tiny wrapper functions for calling the underlying `tar` object.

---

*[storage/storage.go, line 25 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-KhcyG6es91aOkBXa1D_:-KhcyG6es91aOkBXa1Da:b-ihpp1d) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L25)):*
> ```Go
> 	*tar.Reader
> 	// Should this be a slice?
> 	closer func() error
> ```

What do you think of using a standard `Closer` interface? https://golang.org/pkg/io/#Closer

---

*[storage/storage.go, line 39 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-KhcquAUgS9NFm8ikq8J:-KhcquAUgS9NFm8ikq8K:b30j2bq) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L39)):*
> ```Go
> func NewGCSTarReader(client *http.Client, uri string) (*TarReaderCloser, error) {
> 	// For now only handle gcs paths.
> 	if !strings.HasPrefix(uri, "gs://") {
> ```

It's too bad the storage API does not provide a mechanism for parsing these URIs.

The golang `net/url` package can parse generic URL schemes. https://golang.org/pkg/net/url/#URL

The simpler parsing might be worth tolerating calling the bucketname "Host" briefly.

---

*[storage/storage.go, line 49 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-KhcoXy7YAuIQ0qsaGcn:-KhcoXy8Y1_JjKodOobM:b-ah89fp) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L49)):*
> ```Go
> 	fn := parts[3]
> 
> 	if !(strings.HasSuffix(fn, ".tgz") || strings.HasSuffix(fn, ".tar")) {
> ```

Just a clarifying question, we have no ".tar.gz" files?

---

*[storage/storage.go, line 58 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-Khcx87E8PSH9Pnk5eS-:-Khcx87E8PSH9Pnk5eS0:b-6paiat) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L58)):*
> ```Go
> 	}
> 
> 	// Wrap with a tar.Reader that also has a response closer.
> ```

I don't have a counter example, but some part of me feels like the "Closer" setup below could be simpler somehow.

---

*[storage/storage.go, line 67 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-KhctxCyH9EXoq-8tH9e:-KhctxCyH9EXoq-8tH9f:b-e7vstq) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L67)):*
> ```Go
> 		rdr, err := gzip.NewReader(obj.Body)
> 		if err != nil {
> 			closer()
> ```

Can we use `obj.Body.Close` directly here?

---

*[storage/storage.go, line 73 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-Khcto4z3NL3YE_NvZ-E:-Khcto4z3NL3YE_NvZ-F:b-5inc2) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L73)):*
> ```Go
> 		c := func() error {
> 			rdr.Close()
> 			tmp()
> ```

Do we need `tmp`? Could we use `obj.Body.Close` directly here?

---

*[storage/storage.go, line 90 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-KhcusuRq2w0oL5ZPjak:-KhcusuRq2w0oL5ZPjal:b-usvy5i) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L90)):*
> ```Go
> 
> // Create a storage reader client.
> func getStorageClient(write_access bool) (*http.Client, error) {
> ```

style: go discourages snake-case variables names in favor of camel-case. Here `writeAccess` or `withWrite` (or similar) would be preferable.  https://golang.org/doc/effective_go.html#mixed-caps

---

*[storage/storage.go, line 93 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-Khcw8sdnhTnsXjCHvHv:-Khcw8sdnhTnsXjCHvHw:bvwcesd) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L93)):*
> ```Go
> 	// TODO - is this the scope we want?
> 	var scope string
> 	if scope = storage.DevstorageReadOnlyScope; write_access {
> ```

The logic implies to my mind that `scope = storage.DevstorageReadOnlyScope` is something that could fail, but of course it can't.

I think it would be preferable to separate these two statements.
```
var scope string
scope = storage.DevstorageReadOnlyScope
if write_access {
    scope = storage.DevstorageReadWriteScope
}
```

Or highlight that they're mutually exclusive:
```
var scope string
if write_access {
    scope = storage.DevstorageReadWriteScope
} else {
    scope = storage.DevstorageReadOnlyScope
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/17#-:-Khd2oLwHSgm7ejwEjz7:b-x6ayin)*

**Comment by gfr10598** [comment]
Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[storage/storage.go, line 22 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-Khd-sySxdafVOexnTY4:-KhdE8u62rCCSoutIGuE:b-k0gefk) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L22)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'm wondering if we could define our own interface around an implementation using the tar.Reader. e.g. Something like:

```
type GCSTarReaderCloser interface {
    func (tr *Reader) Next() (*Header, error)
    func (tr *Reader) Read(b []byte) (int, error)
    io.Closer
}
```

And writing tiny wrapper functions for calling the underlying `tar` object.
</blockquote></details>

I was starting to do just that. 

---

*[storage/storage.go, line 25 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-KhcyG6es91aOkBXa1D_:-KhdGlmG7BYpqBYbYla6:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L25)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What do you think of using a standard `Closer` interface? https://golang.org/pkg/io/#Closer
</blockquote></details>

Done.

---

*[storage/storage.go, line 39 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-KhcquAUgS9NFm8ikq8J:-KhdHxZpvAb3e0YS3aYN:bvv3a9m) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L39)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It's too bad the storage API does not provide a mechanism for parsing these URIs.

The golang `net/url` package can parse generic URL schemes. https://golang.org/pkg/net/url/#URL

The simpler parsing might be worth tolerating calling the bucketname "Host" briefly.
</blockquote></details>

Prefer to leave as is for now.

---

*[storage/storage.go, line 49 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-KhcoXy7YAuIQ0qsaGcn:-KhdGr_JDj59s8DB8yCX:bt2vr1b) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L49)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Just a clarifying question, we have no ".tar.gz" files?
</blockquote></details>

Fixed.

---

*[storage/storage.go, line 58 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-Khcx87E8PSH9Pnk5eS-:-KhdI1S5HgikgVHn-4Kj:b2nhysk) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L58)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I don't have a counter example, but some part of me feels like the "Closer" setup below could be simpler somehow.
</blockquote></details>

ack

---

*[storage/storage.go, line 67 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-KhctxCyH9EXoq-8tH9e:-KhdGxMi0iTU3AG9265V:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L67)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Can we use `obj.Body.Close` directly here?
</blockquote></details>

Done.

---

*[storage/storage.go, line 73 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-Khcto4z3NL3YE_NvZ-E:-KhdGy4f6W1GD5WnRynA:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L73)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Do we need `tmp`? Could we use `obj.Body.Close` directly here?
</blockquote></details>

Done.

---

*[storage/storage.go, line 90 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-KhcusuRq2w0oL5ZPjak:-KhdHpipYPFcq7_2R5e0:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L90)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

style: go discourages snake-case variables names in favor of camel-case. Here `writeAccess` or `withWrite` (or similar) would be preferable.  https://golang.org/doc/effective_go.html#mixed-caps
</blockquote></details>

Done.

---

*[storage/storage.go, line 93 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-Khcw8sdnhTnsXjCHvHv:-KhdHr8sTzkUvwzxsJ5h:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L93)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The logic implies to my mind that `scope = storage.DevstorageReadOnlyScope` is something that could fail, but of course it can't.

I think it would be preferable to separate these two statements.
```
var scope string
scope = storage.DevstorageReadOnlyScope
if write_access {
    scope = storage.DevstorageReadWriteScope
}
```

Or highlight that they're mutually exclusive:
```
var scope string
if write_access {
    scope = storage.DevstorageReadWriteScope
} else {
    scope = storage.DevstorageReadOnlyScope
}
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/17)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/storage.go, line 58 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-Khcx87E8PSH9Pnk5eS-:-KhdcRR7IjPtxaO8DlNc:b-8pyzxp) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L58)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

ack
</blockquote></details>

This is closer to what I'm thinking: https://play.golang.org/p/Reuxq1-x0S

Since we need to close the original `obj.Body` as well as the `gzip.Reader` if we use it, we need references to both objects for Close. In this example, we simply keep references to the underlying types and conditionally close them in the receiver's `Close` implementation.

---

*[storage/storage.go, line 44 at r2](https://reviewable.io:443/reviews/m-lab/etl/17#-Khdn7nFcEWlLaym3-LU:-Khdn7nFcEWlLaym3-LV:b46nknz) ([raw file](https://github.com/m-lab/etl/blob/acb032a27c0957032fae971fb046797729c85ab2/storage/storage.go#L44)):*
> ```Go
> //
> // uri should be of form gs://bucket/filename.tar or gs://bucket/filename.tgz
> // FYI Using a persistent client saves about 80 msec, and 220 allocs, totalling 70kB.
> ```

Based on the benchmark, which approach do you recommend?

My bias is towards always using injection and not defining special cases to auto-allocate objects. Convenience methods that bundle up sequences of necessary calls make sense to me too. But, I imagine those being in a separate package that calls `storage`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/17)*

**Comment by gfr10598** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/storage.go, line 58 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-Khcx87E8PSH9Pnk5eS-:-Khht75hem38FAK8Fmvc:b-otsl3u) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L58)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This is closer to what I'm thinking: https://play.golang.org/p/Reuxq1-x0S

Since we need to close the original `obj.Body` as well as the `gzip.Reader` if we use it, we need references to both objects for Close. In this example, we simply keep references to the underlying types and conditionally close them in the receiver's `Close` implementation.
</blockquote></details>

Ok - did something similar, see what you think.

---

*[storage/storage.go, line 44 at r2](https://reviewable.io:443/reviews/m-lab/etl/17#-Khdn7nFcEWlLaym3-LU:-Khdrf1wfGmmd7Yekb1Z:b-yka53b) ([raw file](https://github.com/m-lab/etl/blob/acb032a27c0957032fae971fb046797729c85ab2/storage/storage.go#L44)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Based on the benchmark, which approach do you recommend?

My bias is towards always using injection and not defining special cases to auto-allocate objects. Convenience methods that bundle up sequences of necessary calls make sense to me too. But, I imagine those being in a separate package that calls `storage`.
</blockquote></details>

Passing the client in, or having a preallocated client in a wrapping object!  Saves a round trip to the server.  We may need to check for disconnections or some other rare conditions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/17)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/storage.go, line 58 at r1](https://reviewable.io:443/reviews/m-lab/etl/17#-Khcx87E8PSH9Pnk5eS-:-Khi0Ah_R1G9ifz9oilB:b8eau4p) ([raw file](https://github.com/m-lab/etl/blob/8dd6478a8088d5045a806f365f5c17662da63bdd/storage/storage.go#L58)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Ok - did something similar, see what you think.
</blockquote></details>

I like it!

---

*[storage/storage.go, line 44 at r2](https://reviewable.io:443/reviews/m-lab/etl/17#-Khdn7nFcEWlLaym3-LU:-Khi-UPmKU8uzTYsyVcC:bb6mt9b) ([raw file](https://github.com/m-lab/etl/blob/acb032a27c0957032fae971fb046797729c85ab2/storage/storage.go#L44)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Passing the client in, or having a preallocated client in a wrapping object!  Saves a round trip to the server.  We may need to check for disconnections or some other rare conditions.
</blockquote></details>

:+1:

---

*[storage/storage.go, line 86 at r3](https://reviewable.io:443/reviews/m-lab/etl/17#-Khi-p1bRacSmFkxM9uT:-Khi-p1bRacSmFkxM9uU:b1qexi5) ([raw file](https://github.com/m-lab/etl/blob/6556af792b90cd3f95b6460866a4051efd0f1022/storage/storage.go#L86)):*
> ```Go
> 	if strings.HasSuffix(strings.ToLower(fn), "gz") {
> 		// TODO add unit test
> 		var err error
> ```

Do we need this `err`? There is one define in the outer scope, so the assignment below should be valid.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/17#-:-Khi0XiN-8WZTpB70gj6:bnfp4nl)*

**Comment by gfr10598** [comment]
*[storage/storage.go, line 86 at r3](https://reviewable.io:443/reviews/m-lab/etl/17#-Khi-p1bRacSmFkxM9uT:-Khi15_c6QgQFxBNLLdj:bd30ifx) ([raw file](https://github.com/m-lab/etl/blob/6556af792b90cd3f95b6460866a4051efd0f1022/storage/storage.go#L86)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Do we need this `err`? There is one define in the outer scope, so the assignment below should be valid.
</blockquote></details>

good catch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/17)*

**Pull request merged**
