### PR TITLE
Move reproc stuff to new batch package

### PR DESCRIPTION
**Pull request by gfr10598**
Move reproc related functions from cmd/reproc to batch.

Collecting these here, as I don't want them under cmd in main packages, which is where they will be used, but also don't want them in subdirs with the same name, to avoid name confusion.

This should be a simpler sxs comparison, but for some reason github and reviewable stopped considering batch.go a move after I modified the files.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/388)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
I don't think the batch test needs flags, and my preference remains to avoid special handling of specific parameter values rather than asking the caller to provide a specific instance.

:lgtm:

---

Reviewed 3 of 4 files at r1, 2 of 2 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[batch/batch.go, line 50 at r2](https://reviewable.io:443/reviews/m-lab/etl/388#-L35KH-1_I0Mj9rUIBXd:-L35KH-1_I0Mj9rUIBXe:b-swnecn) ([raw file](https://github.com/m-lab/etl/blob/9313fb275a9e490713bbe90cfd75c32b79d9eae6/batch/batch.go#L50)):*
> ```Go
> func NewQueuer(altHTTP HTTPClientIntf, queueBase string, numQueues int, project, bucketName string, dryRun bool) (Queuer, error) {
> 	var httpClient HTTPClientIntf
> 	if altHTTP != nil {
> ```

I see that something like this special handling was in the old `setup` and I'm not sure how I missed it during the first review. But, my preference remains for avoiding special cases whenever possible and simply requiring the caller to provide the http client instance.

---

*[batch/batch_test.go, line 39 at r2](https://reviewable.io:443/reviews/m-lab/etl/388#-L35JzizxoEZgF8Z10x_:-L35JzizxoEZgF8Z10xa:bpqv5bn) ([raw file](https://github.com/m-lab/etl/blob/9313fb275a9e490713bbe90cfd75c32b79d9eae6/batch/batch_test.go#L39)):*
> ```Go
> 
> var (
> 	fProject = flag.String("project", "", "Project containing queues.")
> ```

I'm confused -- does the test need flags?

---

*[batch/batch_test.go, line 43 at r2](https://reviewable.io:443/reviews/m-lab/etl/388#-L35OQEewAGim8Oeguf5:-L35OQEewAGim8Oeguf6:b-1oiqko) ([raw file](https://github.com/m-lab/etl/blob/9313fb275a9e490713bbe90cfd75c32b79d9eae6/batch/batch_test.go#L43)):*
> ```Go
> 	// TODO implement listing queues to determine number of queue, and change this to 0
> 	fNumQueues = flag.Int("num_queues", 8, "Number of queues.  Normally determined by listing queues.")
> 	fBucket    = flag.String("bucket", "archive-mlab-oti", "Source bucket.")
> ```

If it does need flags, definitely never use prod targets for testing, right?

---

*[cmd/reproc/reproc.go, line 38 at r2](https://reviewable.io:443/reviews/m-lab/etl/388#-L35Md5MwrSV4Fu5kjv8:-L35Md5MwrSV4Fu5kjv9:bpypqtk) ([raw file](https://github.com/m-lab/etl/blob/9313fb275a9e490713bbe90cfd75c32b79d9eae6/cmd/reproc/reproc.go#L38)):*
> ```Go
> 	// TODO implement listing queues to determine number of queue, and change this to 0
> 	fNumQueues = flag.Int("num_queues", 8, "Number of queues.  Normally determined by listing queues.")
> 	fBucket    = flag.String("bucket", "archive-mlab-oti", "Source bucket.")
> ```

I still discourage using production targets as default parameters. This invites unintended side effects from innocent errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/388#-:-L35OdjzEFSFlHwb74uj:b-ipp4xi)*

**Comment by stephen-soltesz** [comment]
Please also fix the build before merging.

---

Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/388#-:-L35QYKbqqGHe6jOmj4R:b-eiz4fu)*

**Comment by gfr10598** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[batch/batch.go, line 50 at r2](https://reviewable.io:443/reviews/m-lab/etl/388#-L35KH-1_I0Mj9rUIBXd:-L3E8vUN-wZxj2XWKtuB:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/9313fb275a9e490713bbe90cfd75c32b79d9eae6/batch/batch.go#L50)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I see that something like this special handling was in the old `setup` and I'm not sure how I missed it during the first review. But, my preference remains for avoiding special cases whenever possible and simply requiring the caller to provide the http client instance.
</blockquote></details>

Done.

---

*[batch/batch_test.go, line 39 at r2](https://reviewable.io:443/reviews/m-lab/etl/388#-L35JzizxoEZgF8Z10x_:-L3EBjMXftTSBt1qRnUK:brpmqb3) ([raw file](https://github.com/m-lab/etl/blob/9313fb275a9e490713bbe90cfd75c32b79d9eae6/batch/batch_test.go#L39)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'm confused -- does the test need flags?
</blockquote></details>

removed

---

*[cmd/reproc/reproc.go, line 38 at r2](https://reviewable.io:443/reviews/m-lab/etl/388#-L35Md5MwrSV4Fu5kjv8:-L3EBnEJYK9XwzppKFpU:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/9313fb275a9e490713bbe90cfd75c32b79d9eae6/cmd/reproc/reproc.go#L38)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I still discourage using production targets as default parameters. This invites unintended side effects from innocent errors.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/388)*

**Comment by gfr10598** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[batch/batch_test.go, line 43 at r2](https://reviewable.io:443/reviews/m-lab/etl/388#-L35OQEewAGim8Oeguf5:-L3EC8uMRuNirtkuFjlr:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/9313fb275a9e490713bbe90cfd75c32b79d9eae6/batch/batch_test.go#L43)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If it does need flags, definitely never use prod targets for testing, right?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/388)*

**Comment by stephen-soltesz** [comment]
Reviewed 1 of 4 files at r1, 1 of 4 files at r4.
Review status: 2 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[batch/batch.go, line 82 at r4](https://reviewable.io:443/reviews/m-lab/etl/388#-L3EF-4UJeH1Rnx9KUgb:-L3EF-4UJeH1Rnx9KUgc:bo6vqks) ([raw file](https://github.com/m-lab/etl/blob/de7a2f45b6871fe9673dc803e5e92c40aa1c58fc/batch/batch.go#L82)):*
> ```Go
> 
> // NewQueuer creates a Queuer struct from provided parameters.
> //   altHTTP - allows injection of an http client to be used for queue_pusher calls.
> ```

Does the `altHTTP` comment still apply?

---

*[batch/batch.go, line 98 at r4](https://reviewable.io:443/reviews/m-lab/etl/388#-L3EHvBWaaykAumx6Y1Q:-L3EHvBWaaykAumx6Y1R:b-sd05xm) ([raw file](https://github.com/m-lab/etl/blob/de7a2f45b6871fe9673dc803e5e92c40aa1c58fc/batch/batch.go#L98)):*
> ```Go
> 	// Check that the bucket is valid, by fetching it's attributes.
> 	// Bypass check if we are running travis tests.
> 	if !dryRun {
> ```

Not blocking, just want to open discussion on this.

During my python days I internalized a principle that a class's init method should not have external side effects, such as network calls. That makes writing unit tests more difficult b/c in python one couldn't even make the object to mock without first preventing the side effects.

I see that running the attribute check is conditional. Still, I'm wondering out loud whether the principle holds for other languages.

---

*[batch/batch.go, line 134 at r4](https://reviewable.io:443/reviews/m-lab/etl/388#-L3EHioyMu_vnJlItDpA:-L3EHioyMu_vnJlItDpB:bs2af3b) ([raw file](https://github.com/m-lab/etl/blob/de7a2f45b6871fe9673dc803e5e92c40aa1c58fc/batch/batch.go#L134)):*
> ```Go
> 		buf, _ := ioutil.ReadAll(resp.Body)
> 		message := string(buf)
> 		if strings.Contains(message, "UNKNOWN_QUEUE") {
> ```

The other day you described an issue where queue pusher service ignore unknown queues -- is that sorted out now?

---

*[batch/batch.go, line 239 at r4](https://reviewable.io:443/reviews/m-lab/etl/388#-L3ELSrWcp5TGP47bytV:-L3ELSrWcp5TGP47bytW:bcv3ott) ([raw file](https://github.com/m-lab/etl/blob/de7a2f45b6871fe9673dc803e5e92c40aa1c58fc/batch/batch.go#L239)):*
> ```Go
> 		if err != nil {
> 			log.Println(err)
> 			if strings.Contains(err.Error(),
> ```

For any non-Done and non-`storage.objects.list access` error this loop would continue until Next returned Done. Perhaps add a comment that we're intentionally ignoring all other errors?

---

*[cmd/reproc/reproc.go, line 61 at r4](https://reviewable.io:443/reviews/m-lab/etl/388#-L3EH_LmQAQ5fuQkliux:-L3EH_LmQAQ5fuQkliuy:b-56gmjz) ([raw file](https://github.com/m-lab/etl/blob/de7a2f45b6871fe9673dc803e5e92c40aa1c58fc/cmd/reproc/reproc.go#L61)):*
> ```Go
> 	}
> 
> 	q, err := batch.NewQueuer(nil, nil, *fQueue, *fNumQueues, *fProject, *fBucket, *fDryRun)
> ```

This will fail with the new implementation of NewQueuer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/388)*

**Comment by gfr10598** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[batch/batch.go, line 82 at r4](https://reviewable.io:443/reviews/m-lab/etl/388#-L3EF-4UJeH1Rnx9KUgb:-L3EQSpT9M6p32N1X4F3:b-g7tuu) ([raw file](https://github.com/m-lab/etl/blob/de7a2f45b6871fe9673dc803e5e92c40aa1c58fc/batch/batch.go#L82)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does the `altHTTP` comment still apply?
</blockquote></details>

Thanks.  Fixed.

---

*[batch/batch.go, line 98 at r4](https://reviewable.io:443/reviews/m-lab/etl/388#-L3EHvBWaaykAumx6Y1Q:-L3EQh2g82WaJI5jVFkC:b7dcy7l) ([raw file](https://github.com/m-lab/etl/blob/de7a2f45b6871fe9673dc803e5e92c40aa1c58fc/batch/batch.go#L98)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Not blocking, just want to open discussion on this.

During my python days I internalized a principle that a class's init method should not have external side effects, such as network calls. That makes writing unit tests more difficult b/c in python one couldn't even make the object to mock without first preventing the side effects.

I see that running the attribute check is conditional. Still, I'm wondering out loud whether the principle holds for other languages.
</blockquote></details>

Hmm.  Probably a good principle that I have ignored here. 
I'll change name to CreateQueuer, which perhaps helps a bit.  But the point here is to do
some of the init that involves network overhead to get it out of the way.

---

*[batch/batch.go, line 134 at r4](https://reviewable.io:443/reviews/m-lab/etl/388#-L3EHioyMu_vnJlItDpA:-L3EQsdyaBKpbp2mf90M:b-l886nn) ([raw file](https://github.com/m-lab/etl/blob/de7a2f45b6871fe9673dc803e5e92c40aa1c58fc/batch/batch.go#L134)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The other day you described an issue where queue pusher service ignore unknown queues -- is that sorted out now?
</blockquote></details>

Yes that is sorted.  Not sure what I was seeing before.  I restarted the sandbox queue_pusher.  Perhaps it was a bug in the much older version that was running (from 6/2017 I think.)

---

*[batch/batch.go, line 239 at r4](https://reviewable.io:443/reviews/m-lab/etl/388#-L3ELSrWcp5TGP47bytV:-L3ETm3MA6AK-mHFIuK1:b-f3bojr) ([raw file](https://github.com/m-lab/etl/blob/de7a2f45b6871fe9673dc803e5e92c40aa1c58fc/batch/batch.go#L239)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

For any non-Done and non-`storage.objects.list access` error this loop would continue until Next returned Done. Perhaps add a comment that we're intentionally ignoring all other errors?
</blockquote></details>

Improved a bit and added comment.

---

*[cmd/reproc/reproc.go, line 61 at r4](https://reviewable.io:443/reviews/m-lab/etl/388#-L3EH_LmQAQ5fuQkliux:-L3EPtpegh0aFXi-vPfw:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/de7a2f45b6871fe9673dc803e5e92c40aa1c58fc/cmd/reproc/reproc.go#L61)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This will fail with the new implementation of NewQueuer?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/388)*

**Pull request merged**
