### PR TITLE
Pt parser

### PR DESCRIPTION
**Pull request by yachang**
PT parser: filename, logtime, protocal, etc

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/28)

### CODE REVIEW

**Comment by gfr10598** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/m-lab/etl/28#-KiHpdvac7PmgWXHy1Fu:-KiHpdvbeciEuOJ14OWI:bdc6bi7) (no related file):*
Please take a look at my comments on PR #19.

---

*[parser/pt.go, line 54 at r3](https://reviewable.io:443/reviews/m-lab/etl/28#-KiHps1oQiMwT4xTv6ed:-KiHps1pYis5FcNPqF8Q:b71ldfz) ([raw file](https://github.com/m-lab/etl/blob/569d270df8799d8d7b2dac0db5a47f5c72135b9f/parser/pt.go#L54)):*
> ```Go
> 	client_ip      string
> 	client_af      int
> 	data_direction int // 0 for SERVER_TO_CLIENT
> ```

Please use an enum, or a bool, maybe isUpload.

---

*[parser/pt.go, line 71 at r3](https://reviewable.io:443/reviews/m-lab/etl/28#-KiHq-fxKr2r23KaR-1t:-KiHq-fywLBzMznQErmY:bof1w65) ([raw file](https://github.com/m-lab/etl/blob/569d270df8799d8d7b2dac0db5a47f5c72135b9f/parser/pt.go#L71)):*
> ```Go
> }
> 
> func (pt *PTParser) Parse(meta map[string]bigquery.Value, fileName string, tableID string, rawContent []byte) (interface{}, error) {
> ```

Please rebase on integration branch, which has some interface changes.

---

*[parser/pt.go, line 143 at r3](https://reviewable.io:443/reviews/m-lab/etl/28#-KiHqCsps0tv4HBoMfLX:-KiHqCsq9roS1I65uuXj:b-cwqghw) ([raw file](https://github.com/m-lab/etl/blob/569d270df8799d8d7b2dac0db5a47f5c72135b9f/parser/pt.go#L143)):*
> ```Go
> 	}
> 
> 	one_row := &PT{
> ```

This looks like test code.  Please break it out into a TestPTParser, or something like that.

---

*[parser/pt_test.go, line 1 at r3](https://reviewable.io:443/reviews/m-lab/etl/28#-KiHqKkjOGFSJct20z0N:-KiHqKkkgDJOA75whJvj:b1kg9wr) ([raw file](https://github.com/m-lab/etl/blob/569d270df8799d8d7b2dac0db5a47f5c72135b9f/parser/pt_test.go#L1)):*
> ```Go
> package parser
> ```

Use parser_test, and import parser.
This will ensure that you are doing blackbox testing, and actually verifying the API that other packages have access to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/28)*

**Comment by gfr10598** [comment]
If you like, you can make these comments TODO(dev) and do them in a later PR.  However, I expect that doing the function extraction refactoring now will actually help get you to fully functional code quicker.

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/m-lab/etl/28#-KiHpdvac7PmgWXHy1Fu:-KiQVuNXPRxzZfvEzBpE:bj567wn) (no related file):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please take a look at my comments on PR #19.
</blockquote></details>

With regard to the regexp comment, you can defer that with a TODO(dev) if you prefer.

---

*[parser/pt.go, line 95 at r3](https://reviewable.io:443/reviews/m-lab/etl/28#-KiQV1-88NmAlbd_uJ7e:-KiQV1-88NmAlbd_uJ7f:bgos2jp) ([raw file](https://github.com/m-lab/etl/blob/569d270df8799d8d7b2dac0db5a47f5c72135b9f/parser/pt.go#L95)):*
> ```Go
> 	// The filename contains 5-tuple like 20170320T23:53:10Z-98.162.212.214-53849-64.86.132.75-42677.paris
> 	// We can get the logtime, local IP, local port, server IP, server port from fileName directly
> 	scanner := bufio.NewScanner(file)
> ```

We don't need buffered I/O, and it looks like you can get what you need from Reader.Readln().  Since that is a lower level and more universal library, I think it would be better to use that instead of Scanner.

---

*[parser/pt.go, line 105 at r3](https://reviewable.io:443/reviews/m-lab/etl/28#-KiQTsWa4Z2kykFUsmMP:-KiQTsWa4Z2kykFUsmMQ:b-jemlvt) ([raw file](https://github.com/m-lab/etl/blob/569d270df8799d8d7b2dac0db5a47f5c72135b9f/parser/pt.go#L105)):*
> ```Go
> 			continue
> 		}
> 		if is_first_line {
> ```

This is an excellent place to pull out functions for first line and other lines.
Also, instead of using is_first_line, invoke the first line function before the loop, then the other line function inside the loop.  This will improve readability significantly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/28#-:-KiQV_4pB2wd1YP_x5ND:b-a1yao8)*

**Comment by gfr10598** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[parser/pt.go, line 33 at r4](https://reviewable.io:443/reviews/m-lab/etl/28#-Ki_hMRUG3dYRKSR6z-0:-Ki_hMRVx3TxG38pkyHL:b-g2gfsf) ([raw file](https://github.com/m-lab/etl/blob/4025b7d81f8b6c24fb5d6fe771531dc054533952/parser/pt.go#L33)):*
> ```Go
> }
> 
> func (f *PTFileName) GetDate() (string, bool) {
> ```

Add todo to split this into a Validate method, (or perhaps a NewPTFileName method) that validates that the filename is consistent with all parsing we need to do on it.  Then GetDate (and all other field calls) will always return valid results, because the validation was done on initialization.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/28)*

**Comment by yachang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[parser/pt.go, line 54 at r3](https://reviewable.io:443/reviews/m-lab/etl/28#-KiHps1oQiMwT4xTv6ed:-KipNoh5i3gToFPqtSl3:b-7wg8n4) ([raw file](https://github.com/m-lab/etl/blob/569d270df8799d8d7b2dac0db5a47f5c72135b9f/parser/pt.go#L54)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please use an enum, or a bool, maybe isUpload.
</blockquote></details>

These fields match the schema of BQ tables, so I cannot change their name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/28)*

**Comment by yachang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[parser/pt.go, line 105 at r3](https://reviewable.io:443/reviews/m-lab/etl/28#-KiQTsWa4Z2kykFUsmMP:-KipO4pySZgZaLPxbmRk:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/569d270df8799d8d7b2dac0db5a47f5c72135b9f/parser/pt.go#L105)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This is an excellent place to pull out functions for first line and other lines.
Also, instead of using is_first_line, invoke the first line function before the loop, then the other line function inside the loop.  This will improve readability significantly.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/28)*

**Comment by yachang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[parser/pt.go, line 143 at r3](https://reviewable.io:443/reviews/m-lab/etl/28#-KiHqCsps0tv4HBoMfLX:-KipO8OsNyUuii09plqc:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/569d270df8799d8d7b2dac0db5a47f5c72135b9f/parser/pt.go#L143)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This looks like test code.  Please break it out into a TestPTParser, or something like that.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/28)*

**Comment by gfr10598** [comment]
Review status: 0 of 3 files reviewed at latest revision, 15 unresolved discussions, some commit checks broke.

---

*[parser/pt.go, line 173 at r5](https://reviewable.io:443/reviews/m-lab/etl/28#-Kj4QKyA630cpLqcEHvB:-Kj4QKyA630cpLqcEHvC:buwbs9y) ([raw file](https://github.com/m-lab/etl/blob/b92b339935beb4066c96e164c6bf444c6d624d5b/parser/pt.go#L173)):*
> ```Go
> 			if mm[0] == "algo" {
> 				if mm[1] != "exhaustive" {
> 					log.Fatal("Unexpected algorithm")
> ```

No log.Fatal allowed.

---

*[parser/pt.go, line 204 at r5](https://reviewable.io:443/reviews/m-lab/etl/28#-Kj4SaHP4JbAOfH_Iint:-Kj4SaHP4JbAOfH_Iinu:b-oxujrl) ([raw file](https://github.com/m-lab/etl/blob/b92b339935beb4066c96e164c6bf444c6d624d5b/parser/pt.go#L204)):*
> ```Go
> 
> func (pt *PTParser) Parse(meta map[string]bigquery.Value, fileName string, tableID string, rawContent []byte) (interface{}, error) {
> 	file, err := os.Open(fileName)
> ```

fileName is not intended for openning a file - only for use in log messages.
You want to use the contents from rawContent.

Also, this interface is out of date.  You will need to 
  git checkout integration
  git pull
  git checkout pt-parser
  git rebase -i integration

Take a look at disco.go or ndt.go for examples of implementing the top of this function.

---

*[parser/pt.go, line 249 at r5](https://reviewable.io:443/reviews/m-lab/etl/28#-Kj4MJNKsVDjyaoN82hR:-Kj4MJNKsVDjyaoN82hS:btgrp4b) ([raw file](https://github.com/m-lab/etl/blob/b92b339935beb4066c96e164c6bf444c6d624d5b/parser/pt.go#L249)):*
> ```Go
> 
> 			// Drop the first 3 parts, like "1  P(6, 6)" because they are useless.
> 			// The following pars are grouped into 4 tuples, for each 4 tuples, it is like:
> ```

s/pars/parts/  ??

---

*[parser/pt.go, line 253 at r5](https://reviewable.io:443/reviews/m-lab/etl/28#-Kj4MTZtt4lRink0scGv:-Kj4MTZtt4lRink0scGw:b-ivmf08) ([raw file](https://github.com/m-lab/etl/blob/b92b339935beb4066c96e164c6bf444c6d624d5b/parser/pt.go#L253)):*
> ```Go
> 			// parts[4] is IP address like "(66.110.57.41)" or "(72.14.218.190):0,2,3,4,6,8,10"
> 			// parts[5] are rtt in numbers like "0.298/0.318/0.340/0.016"
> 			// parts[6] should walys be "ms"
> ```

walys?

---

*[parser/pt.go, line 257 at r5](https://reviewable.io:443/reviews/m-lab/etl/28#-Kj4QUhr6I-wFgzx9X7X:-Kj4QUhr6I-wFgzx9X7Y:bafgp2q) ([raw file](https://github.com/m-lab/etl/blob/b92b339935beb4066c96e164c6bf444c6d624d5b/parser/pt.go#L257)):*
> ```Go
> 			for i := 3; i < len(parts); i += 4 {
> 				if parts[i+3] != "ms" {
> 					log.Fatal("Malformed line. Expected 'ms'")
> ```

A lot of this error checking goes away if you use a regex to parse the entire line, so I think now is a good time to do that.  Then once you have run the regex parser, you can either throw an error immediately, or you should be able to complete the parsing.

You might want several parsers, one for each variation, like multi

---

*[parser/pt.go, line 286 at r5](https://reviewable.io:443/reviews/m-lab/etl/28#-Kj4OZQ7yMGmio5Vrol1:-Kj4OZQ8Kue6iEm1ZJ1p:b-p6agv3) ([raw file](https://github.com/m-lab/etl/blob/b92b339935beb4066c96e164c6bf444c6d624d5b/parser/pt.go#L286)):*
> ```Go
> 				}
> 				// check whether it is single flow or mulitple flows
> 				// sample of miltiple flows: (72.14.218.190):0,2,3,4,6,8,10
> ```

miltiple

---

*[parser/pt.go, line 305 at r5](https://reviewable.io:443/reviews/m-lab/etl/28#-Kj4S7XrHSz6ifQ_XLjJ:-Kj4S7XrHSz6ifQ_XLjK:b-a3umhl) ([raw file](https://github.com/m-lab/etl/blob/b92b339935beb4066c96e164c6bf444c6d624d5b/parser/pt.go#L305)):*
> ```Go
> 				}
> 				if len(ips) == 1 {
> 					// Single flow will be son of all current leaves
> ```

Not sure what "son of all..." means.

---

*[parser/pt.go, line 354 at r5](https://reviewable.io:443/reviews/m-lab/etl/28#-Kj4Q9sxhnQC2aT85MsU:-Kj4Q9sxhnQC2aT85MsV:bo399ni) ([raw file](https://github.com/m-lab/etl/blob/b92b339935beb4066c96e164c6bf444c6d624d5b/parser/pt.go#L354)):*
> ```Go
> 
> 	if err := scanner.Err(); err != nil {
> 		log.Fatal(err)
> ```

Can't use log.Fatal anywhere.  Propogate the error up the stack.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/28)*

**Comment by yachang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 15 unresolved discussions, some commit checks broke.

---

*[parser/pt.go, line 33 at r4](https://reviewable.io:443/reviews/m-lab/etl/28#-Ki_hMRUG3dYRKSR6z-0:-Kj9WhfGnFdU3m6pMZ2E:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/4025b7d81f8b6c24fb5d6fe771531dc054533952/parser/pt.go#L33)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add todo to split this into a Validate method, (or perhaps a NewPTFileName method) that validates that the filename is consistent with all parsing we need to do on it.  Then GetDate (and all other field calls) will always return valid results, because the validation was done on initialization.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/28)*

**Comment by yachang** [comment]
Review status: 0 of 30 files reviewed at latest revision, 15 unresolved discussions.

---

*[parser/pt.go, line 71 at r3](https://reviewable.io:443/reviews/m-lab/etl/28#-KiHq-fxKr2r23KaR-1t:-Kj9XyMkTGdQGsoNBlBD:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/569d270df8799d8d7b2dac0db5a47f5c72135b9f/parser/pt.go#L71)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please rebase on integration branch, which has some interface changes.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/28)*

**Comment by yachang** [comment]
Review status: 0 of 30 files reviewed at latest revision, 15 unresolved discussions.

---

*[parser/pt.go, line 173 at r5](https://reviewable.io:443/reviews/m-lab/etl/28#-Kj4QKyA630cpLqcEHvB:-Kj9_qNOdYpOaGmGqRVd:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b92b339935beb4066c96e164c6bf444c6d624d5b/parser/pt.go#L173)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

No log.Fatal allowed.
</blockquote></details>

Done.

---

*[parser/pt.go, line 204 at r5](https://reviewable.io:443/reviews/m-lab/etl/28#-Kj4SaHP4JbAOfH_Iint:-Kj9_urp7Tex5No-VIB0:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b92b339935beb4066c96e164c6bf444c6d624d5b/parser/pt.go#L204)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

fileName is not intended for openning a file - only for use in log messages.
You want to use the contents from rawContent.

Also, this interface is out of date.  You will need to 
  git checkout integration
  git pull
  git checkout pt-parser
  git rebase -i integration

Take a look at disco.go or ndt.go for examples of implementing the top of this function.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/28)*

**Comment by yachang** [comment]
Review status: 0 of 30 files reviewed at latest revision, 15 unresolved discussions.

---

*[parser/pt.go, line 95 at r3](https://reviewable.io:443/reviews/m-lab/etl/28#-KiQV1-88NmAlbd_uJ7e:-Kj9dmretrTns9w0l4sx:b-yt5che) ([raw file](https://github.com/m-lab/etl/blob/569d270df8799d8d7b2dac0db5a47f5c72135b9f/parser/pt.go#L95)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

We don't need buffered I/O, and it looks like you can get what you need from Reader.Readln().  Since that is a lower level and more universal library, I think it would be better to use that instead of Scanner.
</blockquote></details>


https://stackoverflow.com/questions/8757389/reading-file-line-by-line-in-go/16615559

scanner is a better way to read line by line. I see codes using scanner in google3 as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/28)*

**Comment by yachang** [comment]
Review status: 0 of 30 files reviewed at latest revision, 15 unresolved discussions.

---

*[parser/pt.go, line 249 at r5](https://reviewable.io:443/reviews/m-lab/etl/28#-Kj4MJNKsVDjyaoN82hR:-Kj9evwaYEpBdv_EQS15:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b92b339935beb4066c96e164c6bf444c6d624d5b/parser/pt.go#L249)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

s/pars/parts/  ??
</blockquote></details>

Done.

---

*[parser/pt.go, line 253 at r5](https://reviewable.io:443/reviews/m-lab/etl/28#-Kj4MTZtt4lRink0scGv:-Kj9f09uqqDtICh1aKUz:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b92b339935beb4066c96e164c6bf444c6d624d5b/parser/pt.go#L253)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

walys?
</blockquote></details>

Done.

---

*[parser/pt.go, line 257 at r5](https://reviewable.io:443/reviews/m-lab/etl/28#-Kj4QUhr6I-wFgzx9X7X:-Kj9h5111DIF02abNVgE:bnysxdx) ([raw file](https://github.com/m-lab/etl/blob/b92b339935beb4066c96e164c6bf444c6d624d5b/parser/pt.go#L257)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

A lot of this error checking goes away if you use a regex to parse the entire line, so I think now is a good time to do that.  Then once you have run the regex parser, you can either throw an error immediately, or you should be able to complete the parsing.

You might want several parsers, one for each variation, like multi
</blockquote></details>

The number of segments of one line is not always the same, so it is very hard to have a regex for all kinds of conditions.

---

*[parser/pt.go, line 286 at r5](https://reviewable.io:443/reviews/m-lab/etl/28#-Kj4OZQ7yMGmio5Vrol1:-Kj9hMIkRm5UOjDJ-SwI:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b92b339935beb4066c96e164c6bf444c6d624d5b/parser/pt.go#L286)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

miltiple
</blockquote></details>

Done.

---

*[parser/pt.go, line 305 at r5](https://reviewable.io:443/reviews/m-lab/etl/28#-Kj4S7XrHSz6ifQ_XLjJ:-Kj9hj7kOb6KmJJdKskp:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b92b339935beb4066c96e164c6bf444c6d624d5b/parser/pt.go#L305)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Not sure what "son of all..." means.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/28)*

**Comment by yachang** [comment]
Review status: 0 of 30 files reviewed at latest revision, 15 unresolved discussions.

---

*[parser/pt.go, line 354 at r5](https://reviewable.io:443/reviews/m-lab/etl/28#-Kj4Q9sxhnQC2aT85MsU:-Kj9htRnoFlQaA4HH9q4:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b92b339935beb4066c96e164c6bf444c6d624d5b/parser/pt.go#L354)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Can't use log.Fatal anywhere.  Propogate the error up the stack.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/28)*

**Comment by gfr10598** [comment]
Review status: 0 of 30 files reviewed at latest revision, 15 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/m-lab/etl/28#-KiHpdvac7PmgWXHy1Fu:-KjE19jSiLevWiKJ0gse:baf67i8) (no related file):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

With regard to the regexp comment, you can defer that with a TODO(dev) if you prefer.
</blockquote></details>

Looks like this branch got really messed up when you rebased with integration.  Same thing happened to Peter, and we think it happens when you do a pull instead of a push -f after rebasing.

I've created a new branch called pt-parser-repair.  Please clone that, and create a new PR to merge that into integration and send to me for review.  Close the current PR.  I can still find it to review the comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/28)*

**Pull request closed without merging**
