### PR TITLE
Add NDT support for full schema

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds support for a schema that more closely matches the current production web100 schema for NDT.

TODO:
 * Update the table name for testing.
 * implement the fixValues function to support IPv6 and other record fields.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/61)

### CODE REVIEW

**Comment by gfr10598** [comment]
Please change web100.go to ndt.go, since sidestream also uses web100.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/61#-:-KjE8eaHsNli2OvCKiOL:baqn1j2)*

**Comment by stephen-soltesz** [comment]
We discussed in person that the schema in `schema/web100.go` is meant to reproduce the schema used in the public bq tables today. In the current public schema, ndt, sidestream, and npad all use the same schema.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/61#-:-KjENf-qgEi1qbbyqUyD:b-rd5rb7)*

**Comment by gfr10598** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[parser/ndt_test.go, line 3 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEOn-Dt6wHEENOLR_-:-KjEOn-EeE9PYO7DxFbK:barxnud) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/parser/ndt_test.go#L3)):*
> ```Go
> package parser
> 
> // TODO - use parser_test, to force proper package isolation.
> ```

Would you rename the package parser_test, and do the appropriate imports, to ensure that this is blackbox testing, and that everything works from outside the package?  Then you can delete this comment.  Apologies for not having fixed this in the parser_test.go file.  8-(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/61)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[parser/ndt_test.go, line 3 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEOn-Dt6wHEENOLR_-:-KjEQJDZxc0BRVvW3_Ah:b-k5ta7d) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/parser/ndt_test.go#L3)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Would you rename the package parser_test, and do the appropriate imports, to ensure that this is blackbox testing, and that everything works from outside the package?  Then you can delete this comment.  Apologies for not having fixed this in the parser_test.go file.  8-(
</blockquote></details>

Done. We need to reset the tmpdir through the `parser` package public interface in this case, which I've done with a variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/61)*

**Comment by gfr10598** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[schema/web100.go, line 9 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjE_NqdSfOpQcDto5Ns:-KjE_NqdSfOpQcDto5Nt:b-jjxnf9) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/schema/web100.go#L9)):*
> ```Go
> )
> 
> // Map performs a type conversion on the given value.
> ```

Not clear what this function should be used for.  Can you improve the name or comment?

---

*[schema/web100.go, line 19 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEZLflqyJFx1ihlIGV:-KjEZLflqyJFx1ihlIGW:b-co5mii) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/schema/web100.go#L19)):*
> ```Go
> }
> 
> // NewRecord creates an empty full schema record with nested records already in place.
> ```

Seems like this should only be used for dumping the schema for table creation.  For normal insertions, I think you just want a minimal skeleton, perhaps with nothing but (almost) empty maps, so that any omitted fields don't show up in the JSON.

---

*[schema/web100.go, line 56 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEPKaVSTjrHbhC77wA:-KjEPKaWFzu_FZo_02PJ:b-svwbfc) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/schema/web100.go#L56)):*
> ```Go
> 			"snap": map[string]bigquery.Value{},
> 		},
> 		// TODO(dev): add paris_traceroute_hop records here or separately?
> ```

Let's discuss further before adding any records that aren't needed for NDT.

---

*[web100/web100.go, line 47 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEPYk0x16zDNvwkovy:-KjEPYk0x16zDNvwkovz:bqmp7gt) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/web100/web100.go#L47)):*
> ```Go
> 	legacyNames map[string]string
> 
> 	// Do not export unsafe pointers.
> ```

Could you add some more notes about unsafe pointer use?  They are still a mystery to me.

---

*[web100/web100.go, line 99 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEQOzRFuDTzQd9glFq:-KjEQOzRFuDTzQd9glFr:b-3izcm7) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/web100/web100.go#L99)):*
> ```Go
> 	w := &Web100{
> 		legacyNames: legacyNames,
> 		snaplog:     unsafe.Pointer(snaplog),
> ```

Is this a pointer to itself?  Having trouble finding useful documentation about use of unsafe.Pointer that lines up with what I see in the code.

---

*[web100/web100.go, line 152 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjE_dwOQS7v-io4i20X:-KjE_dwOQS7v-io4i20Y:b-x6zmha) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/web100/web100.go#L152)):*
> ```Go
> 	record := schema.Map(r)
> 	if record == nil {
> 		return fmt.Errorf("Can only fix types of map[string]bigquery.Value")
> ```

Maybe just pass in map instead of Value?

---

*[web100/web100.go, line 199 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEbinleQ6tCmfrTeJs:-KjEbinleQ6tCmfrTeJt:b-qv4hni) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/web100/web100.go#L199)):*
> ```Go
> }
> 
> // snapValues converts all variables in the latest snap record into a results map.
> ```

Thanks for writing this code.  The functionality is pretty messy, so I'm glad I didn't end up doing it myself.  8)

---

*[web100/web100.go, line 200 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEa2fRsbPdZ5zXWprA:-KjEa2fRsbPdZ5zXWprB:b-b1bl1x) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/web100/web100.go#L200)):*
> ```Go
> 
> // snapValues converts all variables in the latest snap record into a results map.
> func (w *Web100) snapValues(logValues map[string]bigquery.Value) error {
> ```

snapshotValues() ?

---

*[web100/web100.go, line 204 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEaokEPZd3jM9aW1TT:-KjEaokEPZd3jM9aW1TU:b-iu7kjk) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/web100/web100.go#L204)):*
> ```Go
> 	snap := (*C.web100_snapshot)(w.snap)
> 
> 	web100snap := schema.Map(logValues["snap"])
> ```

Need a good comment here.  What is web100snap?

---

*[web100/web100.go, line 209 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEbwW_i9ONw8lLkPth:-KjEbwWa8MSjt80Xr_5t:bozze2h) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/web100/web100.go#L209)):*
> ```Go
> 	var w_errno C.int = C.WEB100_ERR_SUCCESS
> 	group := C.web100_get_log_group(snaplog)
> 	for v := C.web100_var_head(group, &w_errno); v != nil; v = C.web100_var_next(v, &w_errno) {
> ```

I think this is a good time to start adding more comments.  The code is quite hard to understand without digging into the guts of web100, and I think it is worthwhile adding enough comments so that anyone can read this code in the future and understand what is going on (in broad strokes) under the hood.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/61)*

**Comment by stephen-soltesz** [comment]
I've tried something differently with web100.go in order to separate the wrapper of our C library from the schema definitions we'll want to use now or in the future.

The main idea is to use a "Saver" interface for `SnapshotValues` and `ConnectionSpec` so that the web100 functions can save values to a provided object rather than creating and returning one.

The interface is general enough that we should be able to use maps now and structs in the future if we want without needing to change web100.go for anything other than cleanups or other local improvements.

What do you think?

---

Review status: 0 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[schema/web100.go, line 9 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjE_NqdSfOpQcDto5Ns:-KjFvSTd2wCAGp02y7qW:b9eiqhe) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/schema/web100.go#L9)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Not clear what this function should be used for.  Can you improve the name or comment?
</blockquote></details>

`schema.Map` has been removed.

---

*[schema/web100.go, line 19 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEZLflqyJFx1ihlIGV:-KjFvZaqoK0cRXngpBuQ:b-vr1ika) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/schema/web100.go#L19)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Seems like this should only be used for dumping the schema for table creation.  For normal insertions, I think you just want a minimal skeleton, perhaps with nothing but (almost) empty maps, so that any omitted fields don't show up in the JSON.
</blockquote></details>

I've created two functions for the "Full" and "Minimal" records for the different cases.

---

*[web100/web100.go, line 47 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEPYk0x16zDNvwkovy:-KjFwD5qFvhJp2PE6bGo:b-q9f3c5) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/web100/web100.go#L47)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Could you add some more notes about unsafe pointer use?  They are still a mystery to me.
</blockquote></details>

I have added a clarifying comment. Let me know what you think.

---

*[web100/web100.go, line 99 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEQOzRFuDTzQd9glFq:-KjFwJQy02aigZi0YhSQ:bhxfwn9) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/web100/web100.go#L99)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Is this a pointer to itself?  Having trouble finding useful documentation about use of unsafe.Pointer that lines up with what I see in the code.
</blockquote></details>

My understanding is that `unsafe.Pointer` is kind of like `void *` in Go. I'm using it here rather than the underlying C types to emphasize that we should use these values carefully and as little as possible.

---

*[web100/web100.go, line 152 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjE_dwOQS7v-io4i20X:-KjFwilftI59tqF6Cwzk:bg85m7a) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/web100/web100.go#L152)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Maybe just pass in map instead of Value?
</blockquote></details>

Yes. I wasn't entirely sure what to do with this function before. I knew it would be necessary but not where it should live. I wasn't really happy with it in web100.go. Now, I've moved this function to `parser/ndt.go` because the schema should be fully separate from `web100/web100.go` now.

---

*[web100/web100.go, line 199 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEbinleQ6tCmfrTeJs:-KjFx4P3X61CPaiydnrf:b-8fx2u7) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/web100/web100.go#L199)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Thanks for writing this code.  The functionality is pretty messy, so I'm glad I didn't end up doing it myself.  8)
</blockquote></details>

:+1: 

---

*[web100/web100.go, line 200 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEa2fRsbPdZ5zXWprA:-KjFxjjF-ds8WVyjSlrV:b5kj8cd) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/web100/web100.go#L200)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

snapshotValues() ?
</blockquote></details>

How about `SnapshotValues`?

---

*[web100/web100.go, line 204 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEaokEPZd3jM9aW1TT:-KjFxoOj_6m7bf3_WuaB:biebauu) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/web100/web100.go#L204)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Need a good comment here.  What is web100snap?
</blockquote></details>

The object we'll save values in is now given as an argument to `SnapshotValues`.

---

*[web100/web100.go, line 209 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEbwW_i9ONw8lLkPth:-KjG-QYL4Bob4mjazaiV:bz9bsu7) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/web100/web100.go#L209)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I think this is a good time to start adding more comments.  The code is quite hard to understand without digging into the guts of web100, and I think it is worthwhile adding enough comments so that anyone can read this code in the future and understand what is going on (in broad strokes) under the hood.
</blockquote></details>

That's a good idea. I've added more clarifying comments that try to help. How does it look?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/61#-:-KjG0AMr0jj3RE0amMqR:bj8mbqt)*

**Comment by gfr10598** [comment]
*[web100/web100.go, line 209 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEbwW_i9ONw8lLkPth:-KjJZzNBuogAHPUCzhh_:btojbfd) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/web100/web100.go#L209)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

That's a good idea. I've added more clarifying comments that try to help. How does it look?
</blockquote></details>

Great!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/61)*

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[web100/web100.go, line 61 at r2](https://reviewable.io:443/reviews/m-lab/etl/61#-KjJAHbNcLHoxVN_h-wT:-KjJAHbNcLHoxVN_h-wU:bc7emf) ([raw file](https://github.com/m-lab/etl/blob/abd7b3291bb5630b5d87f498e13af901bf50c993/web100/web100.go#L61)):*
> ```Go
> 	snap unsafe.Pointer
> 
> 	// text and data are temporary space for converting web100 variables to strings.
> ```

// Pointers to C buffers for use in calls to web100 functions.

---

*[web100/web100.go, line 172 at r2](https://reviewable.io:443/reviews/m-lab/etl/61#-KjJZdtBCMxa6NjpS9DH:-KjJZdtBCMxa6NjpS9DI:b-8wu7zo) ([raw file](https://github.com/m-lab/etl/blob/abd7b3291bb5630b5d87f498e13af901bf50c993/web100/web100.go#L172)):*
> ```Go
> 	dstIp := net.IP(C.GoBytes(unsafe.Pointer(&spec.dst_addr), 4))
> 
> 	connSpec.SetString("local_ip", srcIp.String())
> ```

Does source always correspond to local, and destination to remote?

---

*[web100/web100.go, line 227 at r2](https://reviewable.io:443/reviews/m-lab/etl/61#-KjJUo0HmXQ5HJnNn5Sn:-KjJUo0HmXQ5HJnNn5So:blfgtnw) ([raw file](https://github.com/m-lab/etl/blob/abd7b3291bb5630b5d87f498e13af901bf50c993/web100/web100.go#L227)):*
> ```Go
> 		// tcp-kis.txt).
> 		canonicalName := C.GoString(name)
> 		if _, ok := w.legacyNames[canonicalName]; ok {
> ```

Why are you using _ here?  Seems like it would read better to use a temp.  Or is this a go idiom?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/61#-:-KjJ_7zguFrnVqid0U9X:bnfp4nl)*

**Comment by gfr10598** [comment]
Reviewed 1 of 4 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/61)*

**Comment by stephen-soltesz** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[web100/web100.go, line 209 at r1](https://reviewable.io:443/reviews/m-lab/etl/61#-KjEbwW_i9ONw8lLkPth:-KjJpDbCttwWNLHzNS_0:bb6mt9b) ([raw file](https://github.com/m-lab/etl/blob/058992e0d9cb20feb048b587c830222571b348cf/web100/web100.go#L209)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Great!
</blockquote></details>

:+1:

---

*[web100/web100.go, line 61 at r2](https://reviewable.io:443/reviews/m-lab/etl/61#-KjJAHbNcLHoxVN_h-wT:-KjJjhkxwktNTkO9Rq9q:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/abd7b3291bb5630b5d87f498e13af901bf50c993/web100/web100.go#L61)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

// Pointers to C buffers for use in calls to web100 functions.
</blockquote></details>

Done.

---

*[web100/web100.go, line 172 at r2](https://reviewable.io:443/reviews/m-lab/etl/61#-KjJZdtBCMxa6NjpS9DH:-KjJk2XLCD97-vaHBP0R:b-3btbzk) ([raw file](https://github.com/m-lab/etl/blob/abd7b3291bb5630b5d87f498e13af901bf50c993/web100/web100.go#L172)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Does source always correspond to local, and destination to remote?
</blockquote></details>

Yes, I believe so. Our legacy pipeline uses this mapping.

---

*[web100/web100.go, line 227 at r2](https://reviewable.io:443/reviews/m-lab/etl/61#-KjJUo0HmXQ5HJnNn5Sn:-KjK6T8DlVnjeqJ9eoN6:b-2paoft) ([raw file](https://github.com/m-lab/etl/blob/abd7b3291bb5630b5d87f498e13af901bf50c993/web100/web100.go#L227)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Why are you using _ here?  Seems like it would read better to use a temp.  Or is this a go idiom?
</blockquote></details>

I believe this is considered idiomatic in Go to check for the presence of a key in the map.

https://golang.org/doc/effective_go.html#maps

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/61)*

**Pull request merged**
