### PR TITLE
Add unit test and fix bugs

### PR DESCRIPTION
**Pull request by gfr10598**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/173)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/ndt_meta.go, line 53 at r1](https://reviewable.io:443/reviews/m-lab/etl/173#-Knpm8eMSKa_Q2m6N4dJ:-Knpm8eN0rkgrU6C_4RJ:b-ihs4pa) ([raw file](https://github.com/m-lab/etl/blob/ecd84d870247b1a764285a214ff5b1f62ebb9b3b/parser/ndt_meta.go#L53)):*
> ```Go
> 		log.Printf("Failed parsing connSpec IP: %s\n", ipString)
> 		metrics.WarningCount.WithLabelValues(
> 			"table", "unknown", "failed parsing connSpec IP").Inc()
> ```

Do you mean to leave the "table" & "unknown" fields unspecified?

---

*[parser/ndt_meta_test.go, line 53 at r1](https://reviewable.io:443/reviews/m-lab/etl/173#-KnpmoniMUBtISGJyWPf:-KnpmoniMUBtISGJyWPg:be5uyd4) ([raw file](https://github.com/m-lab/etl/blob/ecd84d870247b1a764285a214ff5b1f62ebb9b3b/parser/ndt_meta_test.go#L53)):*
> ```Go
> 		log.Println("missing client ip address")
> 		for k, v := range meta.Fields {
> 			log.Printf("%s : %s\n", k, v)
> ```

I suggest `t.Logf` rather than `log.Printf` in tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/173)*

**Comment by gfr10598** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/ndt_meta.go, line 53 at r1](https://reviewable.io:443/reviews/m-lab/etl/173#-Knpm8eMSKa_Q2m6N4dJ:-KnpoFkKwtfdyXZxCUzP:b-tpqex2) ([raw file](https://github.com/m-lab/etl/blob/ecd84d870247b1a764285a214ff5b1f62ebb9b3b/parser/ndt_meta.go#L53)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Do you mean to leave the "table" & "unknown" fields unspecified?
</blockquote></details>

The info in not available.  I'll change table to "ndt" for now, though.

---

*[parser/ndt_meta_test.go, line 53 at r1](https://reviewable.io:443/reviews/m-lab/etl/173#-KnpmoniMUBtISGJyWPf:-Knpp-BXrlyspMJMuxKv:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/ecd84d870247b1a764285a214ff5b1f62ebb9b3b/parser/ndt_meta_test.go#L53)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest `t.Logf` rather than `log.Printf` in tests.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/173)*

**Comment by gfr10598** [comment]
PTAL.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/173#-:-Knpp1HPUirxtVQbOxnG:b-83330m)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[parser/ndt_meta.go, line 83 at r2](https://reviewable.io:443/reviews/m-lab/etl/173#-KnppXxcQWOWNAlJwqYf:-KnppXxcQWOWNAlJwqYg:bjlrpaq) ([raw file](https://github.com/m-lab/etl/blob/6143576bd029c55d1c94d6a3046ce76b833323e6/parser/ndt_meta.go#L83)):*
> ```Go
> 	} else {
> 		metrics.WarningCount.WithLabelValues(
> 			"table", "unknown", "missing server_ip").Inc()
> ```

Please change these to "ndt" table also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/173#-:-KnppacoaTEHLx5IClA-:bnfp4nl)*

**Comment by gfr10598** [comment]
Addesses some aspects of #168

**Pull request merged**
