### PR TITLE
A multiqueue implementation without baggage

### PR DESCRIPTION
**Pull request by pboothe**
Obviates #34 , which I will discard as soon as this is submitted.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/60)

### CODE REVIEW

**Comment by gfr10598** [comment]
Reviewed 9 of 10 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[.travis.yml, line 48 at r1](https://reviewable.io:443/reviews/m-lab/etl/60#-KjEgIqae9CUW9v4hDGI:-KjEgIqae9CUW9v4hDGJ:by4vtdx) ([raw file](https://github.com/m-lab/etl/blob/a256ab2154a60fc2587dfb89e9f60f9b04ebe73a/.travis.yml#L48)):*
> ```YAML
> # SANDBOX: before code review for development code in a specific branch.
> ## Service: etl-disco-parser -- AppEngine Flexible Environment.
> - provider: script
> ```

Please ask Stephen to also take a look at this, since he wrote the original.

---

*[appengine/queue.yaml, line 14 at r1](https://reviewable.io:443/reviews/m-lab/etl/60#-KjEfv2zYhQpaz29Fxvw:-KjEfv3-DHV_R58QIGzK:b-1rb2sv) ([raw file](https://github.com/m-lab/etl/blob/a256ab2154a60fc2587dfb89e9f60f9b04ebe73a/appengine/queue.yaml#L14)):*
> ```YAML
>   bucket_size: 10
>   # Maximum number of concurrent requests.
>   max_concurrent_requests: 50
> ```

Please make this 200

---

*[appengine/queue.yaml, line 25 at r1](https://reviewable.io:443/reviews/m-lab/etl/60#-KjEfqGaal93aLZbM8b3:-KjEfqGbvSoJa9N5p03z:b-1rb2sv) ([raw file](https://github.com/m-lab/etl/blob/a256ab2154a60fc2587dfb89e9f60f9b04ebe73a/appengine/queue.yaml#L25)):*
> ```YAML
>   bucket_size: 10
>   # Maximum number of concurrent requests.
>   max_concurrent_requests: 50
> ```

Please make this 200

---

*[appengine/queue_pusher/queue_pusher.go, line 53 at r1](https://reviewable.io:443/reviews/m-lab/etl/60#-KjEfQL0kGp3CihV7YZw:-KjEfQL1lzXrBDHoR8GB:b7d5hn3) ([raw file](https://github.com/m-lab/etl/blob/a256ab2154a60fc2587dfb89e9f60f9b04ebe73a/appengine/queue_pusher/queue_pusher.go#L53)):*
> ```Go
> 
> 	validQueue := false
> 	for _, queue := range queueForType {
> ```

Please add a TODO to evaluate whether this should be improved.  Should we use the DataType keys to determine whether this is valid?

---

*[cmd/etl_worker/app-sidestream.yaml, line 18 at r1](https://reviewable.io:443/reviews/m-lab/etl/60#-KjEeqliaQ69VahTKMct:-KjEeqliaQ69VahTKMcu:bonvitx) ([raw file](https://github.com/m-lab/etl/blob/a256ab2154a60fc2587dfb89e9f60f9b04ebe73a/cmd/etl_worker/app-sidestream.yaml#L18)):*
> ```YAML
>   disk_size_gb: 10
> 
>   # The tmpfs space is allocated from memory_gb.
> ```

Note: Only need the tmpfs on the NDT instance, but I will tweak these as they come online.

---

*[storage/storage.go, line 156 at r1](https://reviewable.io:443/reviews/m-lab/etl/60#-KjEgzmooOlykJWayB6X:-KjEgzmpMTaB7avoq_M-:byngzlv) ([raw file](https://github.com/m-lab/etl/blob/a256ab2154a60fc2587dfb89e9f60f9b04ebe73a/storage/storage.go#L156)):*
> ```Go
> // Turn the bytes received from the queue into a filename
> // TODO(dev) Add unit test
> func GetFilename(filename string) (string, error) {
> ```

Good - thanks for moving.

---

*[storage/storage.go, line 174 at r1](https://reviewable.io:443/reviews/m-lab/etl/60#-KjEh1Gu8tOWz5cxljee:-KjEh1Gu8tOWz5cxljef:b-ippfpw) ([raw file](https://github.com/m-lab/etl/blob/a256ab2154a60fc2587dfb89e9f60f9b04ebe73a/storage/storage.go#L174)):*
> ```Go
> 
> // Find the type of data stored in a file from its comlete filename
> func GetDataType(fn string) etl.DataType {
> ```

I think this should go in etl/globals.go (aka util).  8-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/60)*

**Comment by gfr10598** [comment]
Reviewed 1 of 10 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[appengine/queue_pusher/queue_pusher.go, line 20 at r1](https://reviewable.io:443/reviews/m-lab/etl/60#-KjEhVoTJXPk6TVxT4c7:-KjEhVoTJXPk6TVxT4c8:b4jfdw9) ([raw file](https://github.com/m-lab/etl/blob/a256ab2154a60fc2587dfb89e9f60f9b04ebe73a/appengine/queue_pusher/queue_pusher.go#L20)):*
> ```Go
> 
> // Requests can only add tasks to one of these whitelisted queue names.
> var queueForType = map[etl.DataType]string {
> ```

I had thought this should go in globals.go, but on more thought I think it is fine here.  However, a comment in that file pointing to this one would be useful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/60)*

**Comment by stephen-soltesz** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[.travis.yml, line 48 at r1](https://reviewable.io:443/reviews/m-lab/etl/60#-KjEgIqae9CUW9v4hDGI:-KjJOSwjmYa4eAdQ3nrs:b-kylabm) ([raw file](https://github.com/m-lab/etl/blob/a256ab2154a60fc2587dfb89e9f60f9b04ebe73a/.travis.yml#L48)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please ask Stephen to also take a look at this, since he wrote the original.
</blockquote></details>

.travis.yml LGTM as-is. If you'd like, we could wrap up the multiple calls to `deploy_app.sh` into another script. All the conditions look the same. I can't think of an advantage to one over the other from travis's perspective. A small wrapper script would be more maintainable for us I think.

---

*[.travis.yml, line 61 at r1](https://reviewable.io:443/reviews/m-lab/etl/60#-KjJOY0BXsbDuG1ZIoim:-KjJOY0BXsbDuG1ZIoin:b-gwvfvi) ([raw file](https://github.com/m-lab/etl/blob/a256ab2154a60fc2587dfb89e9f60f9b04ebe73a/.travis.yml#L61)):*
> ```YAML
>     # Sandbox branches will be deployed to personalized service names.
>     # Integration branch will not use decorated service names.
>     condition: $TRAVIS_BRANCH == sandbox-* || $TRAVIS_BRANCH == integration
> ```

gfr asked me to remove the `|| $TRAVIS_BRANCH == integration` so we can do this manually for now. Probably remove this again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/60)*

**Comment by pboothe** [comment]
Review status: 5 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[.travis.yml, line 61 at r1](https://reviewable.io:443/reviews/m-lab/etl/60#-KjJOY0BXsbDuG1ZIoim:-KjJRg1vU5OOPWxZ-IYu:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a256ab2154a60fc2587dfb89e9f60f9b04ebe73a/.travis.yml#L61)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

gfr asked me to remove the `|| $TRAVIS_BRANCH == integration` so we can do this manually for now. Probably remove this again.
</blockquote></details>

Done.

---

*[appengine/queue.yaml, line 14 at r1](https://reviewable.io:443/reviews/m-lab/etl/60#-KjEfv2zYhQpaz29Fxvw:-KjJ3NJaAnkhIeY_weWe:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a256ab2154a60fc2587dfb89e9f60f9b04ebe73a/appengine/queue.yaml#L14)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please make this 200
</blockquote></details>

Done.

---

*[appengine/queue.yaml, line 25 at r1](https://reviewable.io:443/reviews/m-lab/etl/60#-KjEfqGaal93aLZbM8b3:-KjJ3Lrm9KVj98lifpqB:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a256ab2154a60fc2587dfb89e9f60f9b04ebe73a/appengine/queue.yaml#L25)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please make this 200
</blockquote></details>

Done.

---

*[appengine/queue_pusher/queue_pusher.go, line 20 at r1](https://reviewable.io:443/reviews/m-lab/etl/60#-KjEhVoTJXPk6TVxT4c7:-KjJNBBztx_2fz3rSdLz:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a256ab2154a60fc2587dfb89e9f60f9b04ebe73a/appengine/queue_pusher/queue_pusher.go#L20)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I had thought this should go in globals.go, but on more thought I think it is fine here.  However, a comment in that file pointing to this one would be useful.
</blockquote></details>

Done.

---

*[appengine/queue_pusher/queue_pusher.go, line 53 at r1](https://reviewable.io:443/reviews/m-lab/etl/60#-KjEfQL0kGp3CihV7YZw:-KjJNXD_m2HLhjFVVX3H:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a256ab2154a60fc2587dfb89e9f60f9b04ebe73a/appengine/queue_pusher/queue_pusher.go#L53)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please add a TODO to evaluate whether this should be improved.  Should we use the DataType keys to determine whether this is valid?
</blockquote></details>

Done.

---

*[storage/storage.go, line 174 at r1](https://reviewable.io:443/reviews/m-lab/etl/60#-KjEh1Gu8tOWz5cxljee:-KjJRKhsYL-h_0FHDi04:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a256ab2154a60fc2587dfb89e9f60f9b04ebe73a/storage/storage.go#L174)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I think this should go in etl/globals.go (aka util).  8-)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/60)*

**Comment by pboothe** [comment]
PTAL

**Comment by stephen-soltesz** [comment]
Review status: 4 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 61 at r1](https://reviewable.io:443/reviews/m-lab/etl/60#-KjJOY0BXsbDuG1ZIoim:-KjJS4-GFo3AF9M8IwEJ:b-8fx2u7) ([raw file](https://github.com/m-lab/etl/blob/a256ab2154a60fc2587dfb89e9f60f9b04ebe73a/.travis.yml#L61)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/60)*

**Comment by gfr10598** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/60#-:-KjJSEoDLJgIarg4N1nZ:bnfp4nl)*

**Pull request merged**
