### PR TITLE
Dedup step 2 - more complex functions.

### PR DESCRIPTION
**Pull request by gfr10598**
This adds:
  checkDetails()
  checkDestOlder()
  WaitForJob()
  SafeCopyPartition()
  CheckAndDedup()
  ProcessTablesMatching()

These collectively provide all the tools we need to run dedupping jobs.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/394)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
This is my main comment -- but I'd like to talk in person b/c I think my mental model is still incomplete.

I'm finding the number of base, extended, details, and meta information for the src and dest tables confusing.

Where possible and practical and positive, I would like to see consistent types provided as parameters, and derived types created in the process of some operation.

For example, I think of `SanityCheckAndCopy` as being a copy operation that takes a srcTable and a destTable.  Or, I could imagine this being a `CopyTo` method on an extended srcTable type, that has a shorter parameter list, e.g. only the dest parameters.

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[dedup/dedup.go, line 221 at r3](https://reviewable.io:443/reviews/m-lab/etl/394#-L47nMly9UOuyY18dNRL:-L47nMly9UOuyY18dNRM:b-zau440) ([raw file](https://github.com/m-lab/etl/blob/6e1dd115723c5b96bf25abdcf8dab3addfd178bb/dedup/dedup.go#L221)):*
> ```Go
> 	// Check that new table contains at least 99% as many tasks as
> 	// old table.
> 	if destDetail.TaskFileCount > int(1.01*float32(srcDetail.TaskFileCount)) {
> ```

I suspect you have a good reason, so this is a genuine question: why do you express these using the inverse ratio? I expect to see "99%" expressed as `0.99*destDetail.TaskFileCount`. They're maybe close enough but the values are not equivalent. Why is that okay?

---

*[dedup/dedup.go, line 273 at r3](https://reviewable.io:443/reviews/m-lab/etl/394#-L47_eSHk8iwNNllAf6T:-L47_eSHk8iwNNllAf6U:b-81b0a0) ([raw file](https://github.com/m-lab/etl/blob/6e1dd115723c5b96bf25abdcf8dab3addfd178bb/dedup/dedup.go#L273)):*
> ```Go
> 			backoff = backoff + tmp
> 		}
> 		time.Sleep(time.Duration(backoff))
> ```

The base unit for duration is nanoseconds. Is this intentional? My suggestion is to make maxbackoff a duration, and start backoff at some specific unit, e.g. 1ms.

---

*[dedup/dedup.go, line 320 at r3](https://reviewable.io:443/reviews/m-lab/etl/394#-L47bWCSDYn1DxmjC_os:-L47bWCSDYn1DxmjC_ot:b-ebg3w8) ([raw file](https://github.com/m-lab/etl/blob/6e1dd115723c5b96bf25abdcf8dab3addfd178bb/dedup/dedup.go#L320)):*
> ```Go
> 
> // CheckAndDedup checks various criteria, and if they all pass,
> // dedups the table.  Returns true if criteria pass, false if they fail.
> ```

why not just error or no-error?

---

*[dedup/dedup.go, line 329 at r3](https://reviewable.io:443/reviews/m-lab/etl/394#-L47bYx_Mf6IIk2Fjmv2:-L47bYx_Mf6IIk2Fjmv3:b-3j5jhj) ([raw file](https://github.com/m-lab/etl/blob/6e1dd115723c5b96bf25abdcf8dab3addfd178bb/dedup/dedup.go#L329)):*
> ```Go
> //   4.  Source reflects at least 99% as many task files as destination.
> //   5.  Source has at least 95% as many tests as destination (including dups)
> //   6.  After deduplication, intermediate table has at least 95% as many tests as destination.
> ```

I don't understand this step. It sounds like dedup is an operation between a source, a dest, and an intermediate table?

---

*[dedup/dedup.go, line 331 at r3](https://reviewable.io:443/reviews/m-lab/etl/394#-L47cRnZNNUKmwC7aIyj:-L47cRnZNNUKmwC7aIyk:bp9cims) ([raw file](https://github.com/m-lab/etl/blob/6e1dd115723c5b96bf25abdcf8dab3addfd178bb/dedup/dedup.go#L331)):*
> ```Go
> //   6.  After deduplication, intermediate table has at least 95% as many tests as destination.
> //
> // dsExt         - bqext.Dataset containing the source (and used for intermediate)
> ```

i thought intermediate was its own dataset?

---

*[dedup/dedup.go, line 348 at r3](https://reviewable.io:443/reviews/m-lab/etl/394#-L47fPtkpmjsrH8q05gi:-L47fPtkpmjsrH8q05gj:bsfsrx8) ([raw file](https://github.com/m-lab/etl/blob/6e1dd115723c5b96bf25abdcf8dab3addfd178bb/dedup/dedup.go#L348)):*
> ```Go
> 	}
> 
> 	if destTable.DatasetID == dsExt.DatasetID {
> ```

please rename `dsExt` to clearly designate it is as a `src*`.

---

*[dedup/dedup.go, line 393 at r3](https://reviewable.io:443/reviews/m-lab/etl/394#-L47orydDFge-Lp5PNGh:-L47orydDFge-Lp5PNGi:birtfsp) ([raw file](https://github.com/m-lab/etl/blob/6e1dd115723c5b96bf25abdcf8dab3addfd178bb/dedup/dedup.go#L393)):*
> ```Go
> 	}
> 
> 	err = checkDetails(srcDetail, destDetail)
> ```

There's something I'm missing -- dest is the new table? how would the dest have at least 99% as many tables initially? Isn't dest initially empty?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/394#-:-L47vinmGFMO2RwBYity:b-p8afxo)*

**Comment by gfr10598** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[dedup/dedup.go, line 273 at r3](https://reviewable.io:443/reviews/m-lab/etl/394#-L47_eSHk8iwNNllAf6T:-L48LL8KGFRYJihJGn9J:b-g7tuu) ([raw file](https://github.com/m-lab/etl/blob/6e1dd115723c5b96bf25abdcf8dab3addfd178bb/dedup/dedup.go#L273)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The base unit for duration is nanoseconds. Is this intentional? My suggestion is to make maxbackoff a duration, and start backoff at some specific unit, e.g. 1ms.
</blockquote></details>

Thanks.  Fixed.

---

*[dedup/dedup.go, line 320 at r3](https://reviewable.io:443/reviews/m-lab/etl/394#-L47bWCSDYn1DxmjC_os:-L48MBE0W-s2VvZ6k1CZ:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/6e1dd115723c5b96bf25abdcf8dab3addfd178bb/dedup/dedup.go#L320)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

why not just error or no-error?
</blockquote></details>

Done.

---

*[dedup/dedup.go, line 329 at r3](https://reviewable.io:443/reviews/m-lab/etl/394#-L47bYx_Mf6IIk2Fjmv2:-L48ND_Dm0o86KcI4nS-:b-f2ztfd) ([raw file](https://github.com/m-lab/etl/blob/6e1dd115723c5b96bf25abdcf8dab3addfd178bb/dedup/dedup.go#L329)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I don't understand this step. It sounds like dedup is an operation between a source, a dest, and an intermediate table?
</blockquote></details>

Clarified a bit.  Bad name choice.

---

*[dedup/dedup.go, line 331 at r3](https://reviewable.io:443/reviews/m-lab/etl/394#-L47cRnZNNUKmwC7aIyj:-L48P3hSmG0KuuXyJJfP:btayny3) ([raw file](https://github.com/m-lab/etl/blob/6e1dd115723c5b96bf25abdcf8dab3addfd178bb/dedup/dedup.go#L331)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

i thought intermediate was its own dataset?
</blockquote></details>

See new comments for clarification.

---

*[dedup/dedup.go, line 348 at r3](https://reviewable.io:443/reviews/m-lab/etl/394#-L47fPtkpmjsrH8q05gi:-L48Poigxb4u2ojOCONm:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/6e1dd115723c5b96bf25abdcf8dab3addfd178bb/dedup/dedup.go#L348)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

please rename `dsExt` to clearly designate it is as a `src*`.
</blockquote></details>

Done.

---

*[dedup/dedup.go, line 393 at r3](https://reviewable.io:443/reviews/m-lab/etl/394#-L47orydDFge-Lp5PNGh:-L48QtscY7qsBlsEyFJ5:b-blrpip) ([raw file](https://github.com/m-lab/etl/blob/6e1dd115723c5b96bf25abdcf8dab3addfd178bb/dedup/dedup.go#L393)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

There's something I'm missing -- dest is the new table? how would the dest have at least 99% as many tables initially? Isn't dest initially empty?
</blockquote></details>

Added better comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/394)*

**Comment by gfr10598** [comment]
I'm working on this and will ask for PTAL when things are better.
Thanks for all the excellent feedback to help get me unstuck.

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[dedup/dedup.go, line 221 at r3](https://reviewable.io:443/reviews/m-lab/etl/394#-L47nMly9UOuyY18dNRL:-L48TwQ8wtRyAABnpojA:b28afxy) ([raw file](https://github.com/m-lab/etl/blob/6e1dd115723c5b96bf25abdcf8dab3addfd178bb/dedup/dedup.go#L221)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suspect you have a good reason, so this is a genuine question: why do you express these using the inverse ratio? I expect to see "99%" expressed as `0.99*destDetail.TaskFileCount`. They're maybe close enough but the values are not equivalent. Why is that okay?
</blockquote></details>

Cleaned up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/394#-:-L48U0te7Up4KlVYHhd_:b-r3yi4n)*

**Comment by gfr10598** [comment]
I've added AnnotatedTables, and Job.  This increases the LOC, but I think encapsulates better and improves readability.

Also eliminated TableInfo, and just using TableMetaData directly instead.

PTAL.

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/394#-:-L4D0vo55diSohbJ9lyh:bqbe4rb)*

**Comment by stephen-soltesz** [comment]
Thank you for the new types and the methods on them. This is a great improvement!

I think the remaining comments just help with readability.

If you're not planning to make any more substantial changes, then :lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[dedup/dedup.go, line 90 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DKFBj5oGPRFrXPpXB:-L4DKFBj5oGPRFrXPpXC:b9xx8z9) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L90)):*
> ```Go
> 	meta, err := at.CachedMeta(ctx)
> 	if err != nil {
> 		return time.Now() // Hack - not sure what to do instead.
> ```

`time.Time{}` is the time zero value. I don't know whether this is a better value for "unknown" or "never".

---

*[dedup/dedup.go, line 293 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DaFPeUv0GI3kBoEY_:-L4DaFPeUv0GI3kBoEYa:b2qyi3) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L293)):*
> ```Go
> 
> // TODO - move these up with other methods after review.
> func (at *AnnotatedTable) checkDetails(ctx context.Context, other *AnnotatedTable) error {
> ```

s/checkDetails/checkAtLeastAsBig/  (or similar) -- this makes usage of checkDetails read a little easier.

---

*[dedup/dedup.go, line 322 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DPm-JAwESRIcsoR2C:-L4DPm-JAwESRIcsoR2D:blbv00g) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L322)):*
> ```Go
> 
> // TODO - should we use the metadata, or the PI?  Are they the same?
> func (at *AnnotatedTable) checkAges(ctx context.Context, other *AnnotatedTable) error {
> ```

s/checkAges/checkModifiedAfter/

---

*[dedup/dedup.go, line 369 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DfWeRLewt5qlRGvv4:-L4DfWeRLewt5qlRGvv5:b7ghjc6) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L369)):*
> ```Go
> // TODO(gfr) Ideally this should be done by a separate process with
> // higher priviledge than the reprocessing and dedupping processes.
> // TODO(gfr) Also support copying from a template instead of partition?
> ```

Do we have workflows that will require template-to-partition copies without dedup first? imo, it's okay to have methods that do one thing well.

---

*[dedup/dedup.go, line 415 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DSaKtaLJ4XO0qCkov:-L4DSaKtaLJ4XO0qCkow:b-9dupxf) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L415)):*
> ```Go
> }
> 
> // NewJob creates a DedupJob struct
> ```

Looks like? s/DedupJob/Job/

---

*[dedup/dedup.go, line 443 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4Deyl__gW35luO66BI:-L4Deyl__gW35luO66BJ:b-xxd1a1) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L443)):*
> ```Go
> 	}
> 
> 	err = SanityCheckAndCopy(ctx, job.Dataset.BqClient, job.dedupTable.Table, job.destTable.DatasetID, destParts.prefix)
> ```

Most parameters are elements of `job`. Would `SanityCheckAndCopy` be a helpful method for the `job` type?

---

*[dedup/dedup.go, line 467 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DW536ieFb8W1fXSaM:-L4DW536ieFb8W1fXSaN:bb6mdej) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L467)):*
> ```Go
> //   3. If destination partition exists then
> //       3a. Source reflects at least as many task files as destination (if dest)
> //       3b. Source has at least 98% as many tests as destination (including dups)
> ```

95%?

---

*[dedup/dedup.go, line 475 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DW9ysRDE4QlhP7NXu:-L4DW9ysRDE4QlhP7NXv:bnsqgdi) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L475)):*
> ```Go
> // options       - dedup options, MinSrcAge, IgnoreDestAge, DryRun, CopyOnly.
> //
> // TODO(gfr) Should we check that intermediate table is NOT a production table?
> ```

This todo sounds like a good idea. If anything breaks, better to leave dangling pieces somewhere outside of prod tables. My understanding based on the conversation today is that the "prod tables" in this case are the "base_tables".

---

*[dedup/dedup.go, line 493 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DdytLBje9x2miTJhs:-L4DdytLBje9x2miTJht:b-oo30od) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L493)):*
> ```Go
> 
> 	// Check if the last update was at least minSrcAge in the past.
> 	if time.Now().Sub(job.srcTable.LastModifiedTime(ctx)) < options.MinSrcAge {
> ```

`time.Since`?

---

*[dedup/dedup.go, line 501 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DY5pB8NR1mT1mL3Mj:-L4DY5pB8NR1mT1mL3Mk:b1w4e93) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L501)):*
> // We do the deduplication into the corresponding partition, derived from the source table template.

Please rephrase. There is something too non-specific about "corresponding partition".

Maybe "We use the source template table to derive the name of the temporary partition table, dedupTable"
Or, "The source is a template table, and the temporary dedupTable is a partition table. The dedup table name and partition are derived from the source."

---

*[dedup/dedup.go, line 529 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DaktbhrEY3nr4Q8tf:-L4DaktbhrEY3nr4Q8tg:b8gmtbx) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L529)):*
> ```Go
> 	}
> 
> 	err = job.srcTable.checkDetails(ctx, job.destTable)
> ```

This is where I imagined `job.srcTable.checkAtLeastAsBig(ctx, job.destTable)` (or similar) might read more easily.

---

*[dedup/dedup.go, line 565 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DdWSFt68c8SnTRB_T:-L4DdWSFt68c8SnTRB_U:bcayo5r) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L565)):*
> ```Go
> // any that are at least the age specified in options, dedups and copies them to
> // corresponding partitions in the destination table.
> func ProcessTablesMatching(dsExt *bqext.Dataset, srcPattern string, destDataset, destBase string, options Options) error {
> ```

Please rename `dsExt` to indicate that it is a `src*` value.

---

*[dedup/dedup.go, line 565 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DddyjJ47VTwyghon_:-L4DddyjJ47VTwyghona:b-5r27qv) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L565)):*
> ```Go
> // any that are at least the age specified in options, dedups and copies them to
> // corresponding partitions in the destination table.
> func ProcessTablesMatching(dsExt *bqext.Dataset, srcPattern string, destDataset, destBase string, options Options) error {
> ```

When will `destBase` differ from the value derivable from `srcPattern`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/394#-:-L4DgjAaovLA7txVUbSX:b-7xewxg)*

**Comment by gfr10598** [comment]
Review status: 0 of 3 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[dedup/dedup.go, line 90 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DKFBj5oGPRFrXPpXB:-L4IPIqesdk85I1UPzdm:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L90)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`time.Time{}` is the time zero value. I don't know whether this is a better value for "unknown" or "never".
</blockquote></details>

Done.

---

*[dedup/dedup.go, line 293 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DaFPeUv0GI3kBoEY_:-L4I8JlNgxFJnGKX5eD7:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L293)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

s/checkDetails/checkAtLeastAsBig/  (or similar) -- this makes usage of checkDetails read a little easier.
</blockquote></details>

Done.

---

*[dedup/dedup.go, line 322 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DPm-JAwESRIcsoR2C:-L4I8tguu8_sMs3XXFzZ:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L322)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

s/checkAges/checkModifiedAfter/
</blockquote></details>

Done.

---

*[dedup/dedup.go, line 369 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DfWeRLewt5qlRGvv4:-L4I8zcAo_gRveVt62ZO:b-hvz6v9) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L369)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Do we have workflows that will require template-to-partition copies without dedup first? imo, it's okay to have methods that do one thing well.
</blockquote></details>

Not sure yet, but I expect it is likely.

---

*[dedup/dedup.go, line 415 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DSaKtaLJ4XO0qCkov:-L4IMCheVtCy9efgRD7p:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L415)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Looks like? s/DedupJob/Job/
</blockquote></details>

Done.

---

*[dedup/dedup.go, line 443 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4Deyl__gW35luO66BI:-L4IOa0hwUG1KXHh8mqg:bwohdx4) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L443)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Most parameters are elements of `job`. Would `SanityCheckAndCopy` be a helpful method for the `job` type?
</blockquote></details>

Tried it but it doesn't seem to add much value.

---

*[dedup/dedup.go, line 467 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DW536ieFb8W1fXSaM:-L4IOfyd-KPW2ZQeMJkt:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L467)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

95%?
</blockquote></details>

Done.

---

*[dedup/dedup.go, line 475 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DW9ysRDE4QlhP7NXu:-L4IB5b7jD3PJrP_77A-:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L475)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This todo sounds like a good idea. If anything breaks, better to leave dangling pieces somewhere outside of prod tables. My understanding based on the conversation today is that the "prod tables" in this case are the "base_tables".
</blockquote></details>

Done.

---

*[dedup/dedup.go, line 493 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DdytLBje9x2miTJhs:-L4IBDojdX4zxtgINWj9:b2nhpkx) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L493)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`time.Since`?
</blockquote></details>

Tx

---

*[dedup/dedup.go, line 501 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DY5pB8NR1mT1mL3Mj:-L4IJbB7pgzmLZ1tkIKb:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L501)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

> // We do the deduplication into the corresponding partition, derived from the source table template.

Please rephrase. There is something too non-specific about "corresponding partition".

Maybe "We use the source template table to derive the name of the temporary partition table, dedupTable"
Or, "The source is a template table, and the temporary dedupTable is a partition table. The dedup table name and partition are derived from the source."
</blockquote></details>

Done.

---

*[dedup/dedup.go, line 529 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DaktbhrEY3nr4Q8tf:-L4IOhOzj9K2dapCiqg0:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L529)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This is where I imagined `job.srcTable.checkAtLeastAsBig(ctx, job.destTable)` (or similar) might read more easily.
</blockquote></details>

Done.

---

*[dedup/dedup.go, line 565 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DdWSFt68c8SnTRB_T:-L4IKW5FWnoj4G11Ne5q:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L565)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please rename `dsExt` to indicate that it is a `src*` value.
</blockquote></details>

Done.

---

*[dedup/dedup.go, line 565 at r5](https://reviewable.io:443/reviews/m-lab/etl/394#-L4DddyjJ47VTwyghon_:-L4IKaS7hRNFZj1Zsf12:bfkj3s7) ([raw file](https://github.com/m-lab/etl/blob/a718a76f6fd1546de9a1954ec327b1c980f30372/dedup/dedup.go#L565)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

When will `destBase` differ from the value derivable from `srcPattern`?
</blockquote></details>

Hmm.  That might be a good simplification.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/394)*

**Pull request merged**
