### PR TITLE
choose dataset based on datatype and batch

### PR DESCRIPTION
**Pull request by gfr10598**
This introduces a bit of code to determine which dataset to use, based on very simple logic.
1. Sidestream:  use "private", because it includes embargoed data
2. Batch: use "batch"
3. Otherwise: use "base_tables" (for the daily pipeline)

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/513)

### CODE REVIEW

**Comment by pboothe** [comment]
Unit tests, please. This code has no dependencies, so it should be trivial.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/513#-:-LEVByvE1JANMgoUT-4o:b-qdrbnz)*

**Comment by gfr10598** [comment]
>  dependencies, so it should be trivial.
Done.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/513#-:-LEVF1wmDp3o9A17ghOS:b7ijhzy)*

**Comment by gfr10598** [comment]
PTAL.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/513#-:-LEVF6tC9d8R3eazNjgR:b-83330m)*

**Comment by pboothe** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl/513#-:-LEW8cge0Z1noq7765fz:bnfp4nl)*

**Pull request merged**
