### PR TITLE
Clean up travis deployments

### PR DESCRIPTION
**Pull request by gfr10598**
1. Make the various deployments more consistent.
  a.  Sandbox all individual, and based on branch *-sandbox-* or sandbox-*
  b.  Staging ONLY when merged with integration.
2.  Add big comment about deployment triggers.
3.  Add staging deployment for views.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl/439)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Added some thoughts.

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 131 at r1](https://reviewable.io:443/reviews/m-lab/etl/439#-L4ritByGMeJXqaI1Rtn:-L4ritByGMeJXqaI1Rto:b-34ry9i) ([raw file](https://github.com/m-lab/etl/blob/74fe48b45e81ced50842dc21e6eca8d31f250a8d/.travis.yml#L131)):*
> ```YAML
> - provider: script
>   script:
>     $TRAVIS_BUILD_DIR/travis/deploy_app.sh mlab-staging
> ```

This list of deploy commands is long enough and formatted oddly as a result of the travis-to-bash concatenation that it might be worth while to create a separate deploy_etl.sh script that takes one parameter, the project name.

---

*[.travis.yml, line 131 at r1](https://reviewable.io:443/reviews/m-lab/etl/439#-L4rkMjbl8O_BXxejeM9:-L4rkMjbl8O_BXxejeMA:b-mptqo4) ([raw file](https://github.com/m-lab/etl/blob/74fe48b45e81ced50842dc21e6eca8d31f250a8d/.travis.yml#L131)):*
> ```YAML
> - provider: script
>   script:
>     $TRAVIS_BUILD_DIR/travis/deploy_app.sh mlab-staging
> ```

I wonder too if a lot of the "condition" complexity and repetition might be easier to express in a separate script and allow us to consolidate the .travis.yml in favor of a more expressive bash script.

For example, sandbox-* implies mlab-sandbox. Branch "integration" implies staging. And the *prod* tags imply production.

---

*[.travis.yml, line 190 at r1](https://reviewable.io:443/reviews/m-lab/etl/439#-L4rkbLGXGNMrWmO5CIp:-L4rkbLGXGNMrWmO5CIq:b-k9f9hy) ([raw file](https://github.com/m-lab/etl/blob/74fe48b45e81ced50842dc21e6eca8d31f250a8d/.travis.yml#L190)):*
> ```YAML
>     repo: m-lab/etl
>     all_branches: true
>     condition: $TRAVIS_BRANCH == gardener-sandbox-* || $TRAVIS_BRANCH == sandbox-*
> ```

Supporting piece-wise sandbox deploys (with the option of all-sandbox) makes sense.

Supporting deploy-all for integration makes sense.

Supporting deploy-all for prod makes sense to me.

I'm not sure about piece-wise prod deploys. One day we would like to "launch-on-green".  I guess we could consider each service separately. 

Maybe all of this is also an argument in favor of consolidating the parsers. Hmm.

---

*[.travis.yml, line 333 at r1](https://reviewable.io:443/reviews/m-lab/etl/439#-L4rjTfhapOFwQR6-2PK:-L4rjTfhapOFwQR6-2PL:b8zbi16) ([raw file](https://github.com/m-lab/etl/blob/74fe48b45e81ced50842dc21e6eca8d31f250a8d/.travis.yml#L333)):*
> ```YAML
>     all_branches: true
>     tag: true
>     condition: $TRAVIS_TAG == qp-prod-*
> ```

`|| $TRAVIS_TAG == prod-*`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/439#-:-L4rlC52bjKHoXorYyBr:bwlocct)*

**Comment by stephen-soltesz** [comment]
Also, just fyi, from reading around about the slow ae flex deployments, there is a hint that re-using the version number may considerably speed up the process. That strategy may have different trade offs, but could be worth considering, especially if we expose it via tags or similar.

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/439#-:-L4rmhXTvbmjMb3eB5hw:b-mr4fxg)*

**Comment by gfr10598** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 131 at r1](https://reviewable.io:443/reviews/m-lab/etl/439#-L4rkMjbl8O_BXxejeM9:-L59oaTgL9llrIwdS3v6:b-7dmhjt) ([raw file](https://github.com/m-lab/etl/blob/74fe48b45e81ced50842dc21e6eca8d31f250a8d/.travis.yml#L131)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I wonder too if a lot of the "condition" complexity and repetition might be easier to express in a separate script and allow us to consolidate the .travis.yml in favor of a more expressive bash script.

For example, sandbox-* implies mlab-sandbox. Branch "integration" implies staging. And the *prod* tags imply production.
</blockquote></details>

I think these are good ideas, and if I weren't so backed up I'd like to try implementing them.  But I'm pretty slow at bash scripting, so I think it would be better to defer it, or for you or Peter to do it?

---

*[.travis.yml, line 190 at r1](https://reviewable.io:443/reviews/m-lab/etl/439#-L4rkbLGXGNMrWmO5CIp:-L59othxo0wlCuEOvzlI:bt55mhq) ([raw file](https://github.com/m-lab/etl/blob/74fe48b45e81ced50842dc21e6eca8d31f250a8d/.travis.yml#L190)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Supporting piece-wise sandbox deploys (with the option of all-sandbox) makes sense.

Supporting deploy-all for integration makes sense.

Supporting deploy-all for prod makes sense to me.

I'm not sure about piece-wise prod deploys. One day we would like to "launch-on-green".  I guess we could consider each service separately. 

Maybe all of this is also an argument in favor of consolidating the parsers. Hmm.
</blockquote></details>

I'd like to limit the number of partial prod deploy targets.  Maybe just NDT and not-NDT?

I'd like to follow this PR with one that reorganizes the whole file so that targets are grouped by project, rather than by binary.  I think that would be a good time to do further clean up regarding which targets we keep and which we drop.

OK with you?

---

*[.travis.yml, line 333 at r1](https://reviewable.io:443/reviews/m-lab/etl/439#-L4rjTfhapOFwQR6-2PK:-L59pJQXpUCdbx28Vzmp:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/74fe48b45e81ced50842dc21e6eca8d31f250a8d/.travis.yml#L333)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`|| $TRAVIS_TAG == prod-*`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/439)*

**Comment by gfr10598** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 131 at r1](https://reviewable.io:443/reviews/m-lab/etl/439#-L4ritByGMeJXqaI1Rtn:-L59pLw2aM6x5Eom1UAc:b-wzmbyk) ([raw file](https://github.com/m-lab/etl/blob/74fe48b45e81ced50842dc21e6eca8d31f250a8d/.travis.yml#L131)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This list of deploy commands is long enough and formatted oddly as a result of the travis-to-bash concatenation that it might be worth while to create a separate deploy_etl.sh script that takes one parameter, the project name.
</blockquote></details>

ack.  See below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/439)*

**Comment by gfr10598** [comment]
I'm not at all sure what this comment (about tags) means.  Can you elaborate?

PTAL.

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/439#-:-L59pd5btWA3UeQ12KZr:b-3hqyss)*

**Comment by stephen-soltesz** [comment]
The comment about tags was a brain-storm quality idea that we might be able to work toward.

* tag etl with tags in a pre-defined form, e.g. prod-v1.0.3
* deploy scripts extract the version and only use, say, the major version, "v1" as the AE version.
* because we're re-using the version, the AE deploy is (predicted to be) faster.

It sounds like you're done with this round and will defer future improvements to future PRs -- :lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 131 at r1](https://reviewable.io:443/reviews/m-lab/etl/439#-L4rkMjbl8O_BXxejeM9:-L59r1B1DGds3sy-KJ4s:b-cmi3u3) ([raw file](https://github.com/m-lab/etl/blob/74fe48b45e81ced50842dc21e6eca8d31f250a8d/.travis.yml#L131)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I think these are good ideas, and if I weren't so backed up I'd like to try implementing them.  But I'm pretty slow at bash scripting, so I think it would be better to defer it, or for you or Peter to do it?
</blockquote></details>

Sure, just add a TODO, if we agree that the system would be improved by a stand alone deploy script.

---

*[.travis.yml, line 190 at r1](https://reviewable.io:443/reviews/m-lab/etl/439#-L4rkbLGXGNMrWmO5CIp:-L59rEUtMP83vLCtoP0u:bu3o6s4) ([raw file](https://github.com/m-lab/etl/blob/74fe48b45e81ced50842dc21e6eca8d31f250a8d/.travis.yml#L190)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I'd like to limit the number of partial prod deploy targets.  Maybe just NDT and not-NDT?

I'd like to follow this PR with one that reorganizes the whole file so that targets are grouped by project, rather than by binary.  I think that would be a good time to do further clean up regarding which targets we keep and which we drop.

OK with you?
</blockquote></details>

Yeah, NDT & non-NDT could work.

---

*[.travis.yml, line 333 at r1](https://reviewable.io:443/reviews/m-lab/etl/439#-L4rjTfhapOFwQR6-2PK:-L59rLmTKFBh8K2mWvmW:b-vl7368) ([raw file](https://github.com/m-lab/etl/blob/74fe48b45e81ced50842dc21e6eca8d31f250a8d/.travis.yml#L333)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This question was short hand for "should the generic `prod-*` tag also deploy the queue pusher?" This could be part of the "non-ndt" prod deployment set.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/439#-:-L59rbQ81ScDgHXGg5u1:bge7ptc)*

**Comment by stephen-soltesz** [comment]
Citations requested for the "slow ae deploy mitigation"

AEflex being slow to deploy is a common experience:
https://groups.google.com/forum/#!topic/google-appengine/hZMEkmmObDU
https://groups.google.com/forum/#!topic/google-appengine/JTUfl-Kl_B0

The original answer that seemed plausible:
https://stackoverflow.com/questions/40205222/why-does-google-appengine-deployment-take-several-minutes-to-update-service

Subsequent answers to are anecdotal support:
https://stackoverflow.com/questions/37683120/gcloud-preview-app-deploy-process-takes-8-minutes-is-this-normal

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl/439#-:-L59zPxNHWDVkD4JI4dU:b-9hklmd)*

**Pull request merged**
